/**
 * EveryStudent — Russian (mirstudentov.com, "Мир студентов" / "World of
 * students"). The Russian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, plus first-person student testimonies,
 * written for Russian-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ar`, `everystudent-fr`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). mirstudentov.com is its own domain, so it gets its own
 * key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ⓘ **`ru` will not stay single-source.** A Central-Asian Russian EveryStudent
 * sibling exists at `studentstan.com` and, if registered, will also carry `ru`.
 * Recorded here as an observation for the orchestrator — this entry does not
 * try to solve it, and nothing below assumes `ru` is unique to this domain.
 *
 * ## NOT walled — plain HTTP, unlike the three walled EveryStudent banners
 *
 * Verified 2026-07-28: **26 plain-HTTP GETs** with a plain browser UA
 * (robots.txt, /sitemap.xml, 14 articles, all 7 `/m/` indexes, /vopros.html,
 * /sitemap.html, and the homepage) — **every one returned HTTP 200 with real
 * HTML**, and not one carried a Cloudflare block-page signature (no `Attention
 * Required`, no `Just a moment`, no `cf-error-details`). The `server:
 * cloudflare` header is present, but this host serves rather than challenges.
 * So `fetchStrategy` is intentionally OMITTED: plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012). This is the notable difference from
 * everystudent.com / everyarabstudent.com / questions2vie.com, all three of
 * which 403 to plain HTTP.
 *
 * Consequence: discovery is free here, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, and the non-walled sibling `everystudent-de`.
 *
 * ## robots.txt — no rules at all
 *
 * Verified 2026-07-28: HTTP 200, **13 bytes**, Last-Modified 2018-03-28. The
 * entire file is the single line `User-agent: *` — there is no `Allow` line and
 * no `Disallow` line, so the file grants a wildcard agent an empty rule set.
 * That is even barer than everyarabstudent.com / questions2vie.com (`User-agent:
 * * Allow: /`) and unlike everystudent.com, which carries a real disallow list.
 * **Nothing on this domain is disallowed**, so no URL is dropped on robots
 * grounds — every exclusion below is a content-quality call, not a policy one.
 *
 * ## Sitemap — 105 entries, all distinct
 *
 * Verified 2026-07-28: `https://www.mirstudentov.com/sitemap.xml` → HTTP 200,
 * 7,692 bytes, `application/xml`, generated by xml-sitemaps.com. It holds 105
 * `<loc>` elements and **105 distinct URLs** — no duplicates (unlike the German
 * sibling). This matches the ~105 from prior recon exactly.
 *
 * The bare host 301-redirects to `www` (measured on /sitemap.xml), so
 * `www.mirstudentov.com` is the canonical host and the one every `<loc>` uses.
 *
 * The 105 URLs break down as:
 *   - **95 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **7 `/m/<slug>.html`** — section indexes (`sush`, `poznavaya`,
 *     `otnosheniya`, `zhizni`, `vid`, `forum`, `ob`). BLOCKED, below.
 *   - **`/vopros.html`** — the contact form. BLOCKED, below.
 *   - **`/sitemap.html`** — the site-plan page. BLOCKED, below.
 *   - **`/`** — the homepage. BLOCKED, below.
 *
 * So `articleHints` is exactly `/a/<slug>.html`, and the expected yield is 95
 * documents.
 *
 * **All 95 `/a/` URLs are live.** Verified 2026-07-28 by a HEAD sweep of the
 * full article set: 95/95 returned HTTP 200 with no redirect. There are no dead
 * seeds and no extension twins to de-duplicate — every slug is `[A-Za-z0-9-]`
 * and `.html`, with no `.php` counterparts of the kind the French entry had to
 * drop. (One slug is mixed-case, `/a/pomoshch-ot-Boga.html`, so the hint regex
 * must stay case-sensitive-safe; `[^/]+` handles it.)
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes all of these (nothing outside `/a/` can
 * match). The `block` list is deliberately redundant: it records *why* each
 * group is out, so a later widening of the hints cannot silently readmit them.
 * Same defensive posture as `thelife-fr` and `everystudent-de`.
 *
 *   - **`/m/*` — navigation, not content.** Verified 2026-07-28: all 7 fetched
 *     and extracted at **756–1,750 chars**, and every one is a list of headline
 *     + teaser pairs linking to `/a/` pages. They are the five section indexes
 *     (Существование Бога, Познавая Бога, Отношения, Вопросы о жизни, and the
 *     "В и О Форум" Q&A index) plus `/m/vid.html` (the "Видео комната" video
 *     index) and `/m/ob.html` ("Об этом сайте" — about + privacy policy). They
 *     all clear the 250-char floor, so the floor could not catch them. These are
 *     the Russian twins of the `/menu/*` indexes the German entry drops and the
 *     `/m/*` indexes the French entry drops.
 *   - **`/sitemap.html` — the site-plan page.** Verified 2026-07-28: extracts
 *     **3,262 chars** of pure link list ("Карта сайта / Главная / Видео комната
 *     / …"). It clears the floor by an order of magnitude — length is not
 *     aboutness. It is also the page carrying the "Другие языки" (other
 *     languages) links out to the sibling language domains, which is the same
 *     reason the English entry drops `/menus/intl.html` and the French entry
 *     drops `/m/intl.html`. Russian twin of the French `/plan.html`.
 *   - **`/vopros.html` — the contact form.** Verified 2026-07-28: extracts
 *     **85 chars** — "Есть вопрос? Напиши нам" plus the JS fallback line "Enable
 *     javascript in your browser if this form does not load." It would fail
 *     `minContentLength` anyway; blocking skips the fetch.
 *   - **`/`** — the homepage. Verified 2026-07-28: it has **no `.content4` at
 *     all**, so it would extract nothing. Blocked so it is never fetched.
 *
 * ## Near-twin slugs checked, and deliberately KEPT
 *
 * Two slug pairs looked like transliteration or part-1/part-2 duplicates and
 * were checked rather than assumed. Verified 2026-07-28, both are genuinely
 * distinct articles and both are kept:
 *   - `/a/gdebog.html` (12,350 ch, "Где Бог, когда приходит несчастье?") vs
 *     `/a/gdyebog.html` (3,571 ch, "Где Бог?") — **0.3%** 12-word shingle
 *     overlap.
 *   - `/a/nebesnom.html` (3,214 ch) vs `/a/nebesnom2.html` (2,570 ch) — **0.0%**
 *     12-word shingle overlap.
 * Unlike the German sibling's `/audio/*` transcript twins, this host has no
 * duplicate-content group to exclude.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * **The shared `.content4` template does NOT bind here.** Re-verified 2026-07-29
 * by running the repo's own `extractContent` against live pages — the only check
 * that proves anything, because these tokens are also declared in the page's
 * inline `<style>` block and a grep false-positives on every one of them:
 *   - `.contentpadding` — **1 instance, the whole article**: kicker, title,
 *     subhead, byline and body. `/a/estli.html` → 17,787 chars raw, **17,541
 *     after stripping**; `/a/ktoeto.html` → 3,980 raw / 3,835 stripped.
 *   - `.content4` — **1 instance, an empty spacer div: 0 characters.**
 *   - `.content4b` — **0 instances.** Absent from this host entirely.
 *   - `.articletitle` — an `<h1>`, 12–14 chars. A title, not a body.
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text, so listing `.content4` ahead of `.contentpadding`
 * bound the empty spacer and extracted **0 chars on every page** — every article
 * skipped as `too-thin` on a 200 status, with no error anywhere. That is how
 * this entry first shipped. `contentSelectors` is now the one measured
 * container and nothing else.
 *
 * ⚠️ `.contentpadding` also binds on `/m/`, `/vopros.html` and `/sitemap.html` —
 * it does **not** discriminate content from nav. The URL filters above are what
 * keep the corpus clean; the selector list must not be relied on to do it.
 *
 * ## Chrome stripped — re-counted 2026-07-29 INSIDE the real scope
 *
 * The earlier figures on this entry were taken against a container that
 * extracted nothing, so they are superseded. Instances and char removals below
 * are measured within `.contentpadding` on `/a/estli.html` and `/a/ktoeto.html`:
 *
 *   - **`sitelevel_noindex`** is a **custom ELEMENT tag**, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **2 instances inside
 *     `.contentpadding`, 83 chars** on both pages. Hence the bare tag-name
 *     selector with no leading `.` — matching the sibling entries, whose form is
 *     correct rather than a typo.
 *   - **`.fctable` (1) and `.fccell` (4–6)** — the "FEATURE CLOSE" call-to-action
 *     table appended to every article ("► Как начать взаимоотношения с Богом… ►
 *     У меня есть вопрос…"). Measured removal: **163 chars** on `estli`, **62**
 *     on `ktoeto`; the two selectors remove the same block (the cells nest in
 *     the table). `.fctable` is included because stripping only the cells would
 *     leave the table shell.
 *   - **`.hr2` (2) and `.articledivider` (1)** — empty divs drawing the rules
 *     that bracket that CTA block. **0 chars**, confirmed.
 *   - **`.shareiconsmenupg` (1 per article) — a site-specific addition, and the
 *     one selector this host genuinely needs.** It wraps the "ПОДЕЛИТЬСЯ:"
 *     ("SHARE:") AddToAny widget, **13 chars**. It must be named explicitly
 *     because the `<sitelevel_noindex>` that nominally contains it is
 *     **malformed** — it opens inside `.contentpadding` and closes only after
 *     `.contentpadding` has closed, so the parser pops it early and it never
 *     encloses the share row (#128). Identical finding to the German sibling.
 *   - **`.relatedbottom`** has **no element instance** on any page measured — a
 *     no-op on this host. Retained for parity with the sibling entries; do not
 *     read its presence here as evidence it binds.
 *
 * ## Language: `["ru"]` — read, not inferred
 *
 * Verified 2026-07-28 by reading the extracted text myself. The pages serve
 * genuine Russian prose, not untranslated English. `/a/estli.html` opens "Есть
 * ли Бог? Шесть прямых обоснований существования Бога" and presses the reader
 * "Разве вы не хотите, чтобы хотя бы раз вам кто-то просто привел доказательства
 * существования Бога?"; `/a/molitvi.html` asks "Отвечает ли Бог на наши
 * молитвы?" and narrates "Когда я была атеисткой, у меня была подруга, которая
 * часто молилась"; `/a/stradaniy.html` is titled "Разве существование зла и
 * страданий не доказывают, что Богу все равно?"; `/a/troitsu.html` is "Не могли
 * бы вы объяснить Троицу?". Scripture citations use Russian book names
 * throughout (Иоанна, Откровение, Римлянам, Псалтирь, Иеремия, 1 Петра,
 * Филиппийцам, Матфея, Луки, Еккл.).
 *
 * The only English on these pages is bibliographic: footnotes citing
 * English-language books (e.g. "Josh McDowell, More Than A Carpenter (Wheaton,
 * IL: Tyndale House, 1977)"), which is normal citation apparatus in a translated
 * article, not an untranslated body.
 *
 * ⓘ Source-side typo worth knowing about: the site's own nav labels the
 * relationships section "Oтношения" with a **Latin** capital O rather than
 * Cyrillic О. It appears in the kicker line of every `/a/` page in that section,
 * so it will land in extracted text. Harmless, but it is why a naive
 * Cyrillic-only check on that token would fail.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: 26 sequential plain-HTTP GETs and a 95-request HEAD sweep drew no
 * 429 and no throttling, and at 95 pages the whole crawl is ~2 minutes of wall
 * clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentRu: SourceEntry = {
  key: "everystudent-ru",
  name: "EveryStudent — Russian (Мир студентов)",
  domain: "www.mirstudentov.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ru"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ru"],
  defaultCategory: "article",
  rights:
    "© MirStudentov.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.mirstudentov.com",
    // No `fetchStrategy`: verified 2026-07-28 that plain HTTP serves every page
    // on this host (unlike the three walled EveryStudent siblings). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.mirstudentov\\.com/"],
    // The whole article corpus and nothing else: 95 of the 105 sitemap URLs.
    // Case-sensitive-safe — /a/pomoshch-ot-Boga.html carries an uppercase B.
    articleHints: ["^https://www\\.mirstudentov\\.com/a/[^/]+\\.html$"],
    block: [
      // The 7 section indexes (sush, poznavaya, otnosheniya, zhizni, vid,
      // forum, ob) — headline+teaser link lists, 756-1,750 chars, so they
      // clear minContentLength and the floor can NOT catch them. /m/ob.html is
      // the about + privacy page; /m/vid.html the video index.
      "^https://www\\.mirstudentov\\.com/m/",
      // The site-plan page: 3,262 chars of pure link list, and the page that
      // links out to the sibling language domains ("Другие языки"). Russian
      // twin of the French /plan.html.
      "^https://www\\.mirstudentov\\.com/sitemap\\.html$",
      // The contact form: 85 chars, would fail minContentLength anyway.
      "^https://www\\.mirstudentov\\.com/vopros\\.html$",
      // The homepage — no article container, so it extracts nothing.
      "^https://www\\.mirstudentov\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article. `.content4` is deliberately ABSENT: it is
    // an empty spacer div (0 chars) and, because extractContent scopes to the
    // first selector that MATCHES rather than the first that yields text,
    // listing it here made every page skip as `too-thin`. `.content4b` does not
    // exist on this host.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag (4 pairs/page): cookie bar, nav, share, utility bar, footer
      ".shareiconsmenupg", // the "ПОДЕЛИТЬСЯ:" AddToAny widget — its sitelevel_noindex nesting is malformed
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells: "► Как начать взаимоотношения с Богом…"
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".relatedbottom", // CSS-only on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 150, // 105 sitemap entries (95 articles) + headroom
    minContentLength: 250,
  },
};
