/**
 * EveryStudent — Serbian (studentskikutak.com, "Studentski kutak" / "Students'
 * corner"). The Serbian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles plus first-person student testimonies,
 * written for Serbian-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ru`, `everystudent-pt`, `everystudent-hu`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). studentskikutak.com is its own domain, so it gets its
 * own key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ⚠️ **Do not confuse with the neighbouring-language siblings.** `hr`
 * (vrlovazno.com) and `mk` (studentskiodgovori.com) are separate EveryStudent
 * domains and separate registry entries. The content here was checked to be
 * Serbian rather than either of those — see "Language" below.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: **~110 plain-HTTP requests** with a full browser UA
 * (robots.txt, /sitemap.xml, all 77 live articles, all 8 `/m/` pages,
 * /mapa.html, /kontakt.html, /ranac.html, /index.html and the homepage) — every
 * one returned HTTP 200 with real HTML, served by **Apache over HTTP/2**. No
 * Cloudflare anywhere: no `server: cloudflare` header, no `Attention Required`,
 * no `Just a moment`, no `cf-error-details`. So `fetchStrategy` is intentionally
 * OMITTED — plain HTTP is the default and nothing here needs Firecrawl
 * (ADR-0012). Consequence: discovery is free, so this is a **discovery crawl**.
 * Precedent for the shape: `thelife-fr`, `everystudent-ru`, `everystudent-pt`.
 *
 * The bare host **301-redirects to `www`** (measured on /robots.txt), so
 * `www.studentskikutak.com` is canonical and the host every `<loc>` uses.
 *
 * ⓘ **Local-network caveat, not a property of this source.** Recon from the
 * authoring machine initially failed with `SSL certificate problem` on every
 * request. Cause: the local UniFi gateway DNS-hijacks this specific domain to
 * `203.0.113.250` (TEST-NET-3, RFC 5737 — a filtering blackhole) and MITMs TLS
 * with a `UniFi SSL Certificate Authority` cert. Public DNS-over-HTTPS
 * (dns.google, cloudflare-dns.com) resolves the real address, `50.28.103.165`,
 * and all measurements below were taken against it with a pinned resolve. The
 * sibling domains are not filtered. If an acquisition run from this network
 * reports TLS failures for this host alone, that is the cause — the site is
 * healthy.
 *
 * ## robots.txt — nothing disallowed
 *
 * Verified 2026-07-29: `https://www.studentskikutak.com/robots.txt` → HTTP 200,
 * **22 bytes**, the single line `User-agent: * Allow: /` (confirmed by hexdump —
 * it is one line, not two). There is no `Disallow` directive at all, so
 * **nothing on this domain is disallowed** and no URL below is dropped on robots
 * grounds. Every exclusion here is a content-quality call, not a policy one.
 * Same as everyarabstudent.com / questions2vie.com.
 *
 * ## Sitemap — 84 entries, all distinct, and 5.5 years STALE
 *
 * Verified 2026-07-29: `/sitemap.xml` → HTTP 200, 11,144 bytes,
 * `application/xml`, generated by xml-sitemaps.com. 84 `<loc>` elements, **84
 * distinct URLs**, matching the ~84 from prior recon exactly. Every `<lastmod>`
 * reads 2020-11-13 and the file's own `Last-Modified` is **2020-11-25** — a
 * one-off run never regenerated. The 84 break down as:
 *   - **74 `/a/<slug>.html`** — the article directory, but only 69 are live.
 *   - **6 `/m/<slug>.html`** — section indexes. BLOCKED, below.
 *   - **`/mapa.html`** (site plan), **`/kontakt.html`** (contact). BLOCKED.
 *   - **`/` and `/index.html`** — the homepage, listed TWICE. Verified
 *     byte-identical (33,793 bytes each). Both BLOCKED.
 *
 * ## The stale sitemap is wrong in BOTH directions — cross-checked against /mapa.html
 *
 * The site's own HTML site map lists **77 `/a/` articles** against the XML's 74.
 * Verified 2026-07-29 by a HEAD/GET sweep of the union (82 distinct `/a/` URLs):
 *
 * **5 sitemap URLs are dead and are explicitly BLOCKED.** All 5 are exactly the
 * URLs `/mapa.html` does *not* link, so the HTML map is the accurate inventory:
 *   - `/a/glinpos111.html`, `/a/mutnevode112.html`, `/a/zivot114.html` — all
 *     three **301 → `/m/postanje100.html`**, the section index. Left unblocked
 *     they would stage **3 byte-identical copies of a 1,031-char nav page**.
 *     They match `articleHints`, so only a URL block stops them.
 *   - `/a/pravedanrat216.html`, `/a/ranac.html` — both **404**.
 *
 * **8 live articles are missing from the XML sitemap** — a **10.4% blind spot**.
 * 7 are pinned in `seedPaths` (acquire.ts unions seeds with discovered URLs);
 * the 8th is dropped, see the video stub below. Each pinned seed was fetched and
 * measured: heroina 11,181 ch, judaizam 6,281, kontradikcija 2,539, sest 4,468,
 * sledbenicima 2,813, zajednicko 3,421, zajednistvo 9,756.
 *
 * So the expected yield is **76 documents** = 69 discovered + 7 pinned.
 *
 * ## Script: LATIN ONLY — no Cyrillic tree, no duplicate-content trap
 *
 * Serbian is digraphic, so this was checked rather than assumed. Verified
 * 2026-07-29 by scanning every fetched page for codepoints in U+0400–U+04FF:
 * across all 77 articles and 13 nav pages there are exactly **two** Cyrillic
 * occurrences, both incidental — the word "видео" on `/a/tanjiri.html` (the
 * video stub, dropped anyway) and a single stray "је" in a sentence otherwise
 * set in Latin on `/m/osajtu803.html`. Everything else is Serbian Latin
 * (gajica: š, đ, č, ć, ž). The pages declare `<html lang="sr">` and
 * `charset=utf-8`, and there is **no `hreflang`, no `<link rel="alternate">`,
 * and no `/cir/`-style parallel URL tree** anywhere in the sitemap or in the
 * link inventory of any page. **There is no second script variant to
 * de-duplicate**, so no script tree needed blocking.
 *
 * ## Extraction — measured across ALL 77 live articles, not sampled
 *
 * Verified 2026-07-29 by running the repo's own `extractContent` over every live
 * article. This is the only check that proves anything: all of these tokens are
 * also declared in each page's inline `<style>` block, so grepping for the class
 * name false-positives on every page.
 *   - **`.contentpadding` — matches 76/77, ZERO of them empty**, 33–23,205 ch,
 *     median 6,281. The whole article: kicker, title, subhead, byline, body.
 *   - **`.content4` — matches 76/77 and extracts 0 characters on all 76.** An
 *     empty spacer div. This is the trap that broke 5 pilot entries.
 *   - **`.content4b` — matches 1/77 and extracts 0 characters.**
 *   - **`.articletitle` — matches 77/77, 2–67 ch.** A title, not a body.
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text, so listing `.content4` (or `.content4b`) ahead of
 * `.contentpadding` would bind an empty div and extract **0 chars on every
 * page** — every article skipped as `too-thin` on an HTTP 200, silently.
 * `contentSelectors` is therefore the ONE measured container and nothing else.
 *
 * ⚠️ `.contentpadding` also binds on `/mapa.html`, `/kontakt.html`,
 * `/ranac.html` and 3 of the `/m/` pages — it does **not** discriminate content
 * from nav. The URL filters are what keep the corpus clean.
 *
 * ⓘ **One article intentionally uses the implicit root fallback.**
 * `/a/zajednistvo.html` is served with malformed markup: it has no
 * `.contentpadding` wrapper (its only container is an empty `.content4b`), and
 * node-html-parser builds no `<body>` element for it either, so `extractContent`
 * falls through to the document root. Measured: **9,756 ch of clean article
 * prose** that ends correctly on the article's own footnotes — the
 * `sitelevel_noindex` strip removes the surrounding nav, and the only artifacts
 * are a leading `<!DOCTYPE html>` token and one stray `</sup`. Kept as a seed on
 * that evidence. Adding `.content4b` as a fallback would make this page extract
 * **0** and be dropped, which is why it is absent. Same pattern the Hungarian
 * sibling documents for its 3 broken articles.
 *
 * ## Chrome stripped — measured INSIDE `.contentpadding`
 *
 * Instances and char removals measured on `/a/imaliboga101.html`,
 * `/a/trojstvo709.html` and `/a/molitve306.html`:
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class: **2
 *     instances, 102 ch** on all three. Hence the bare tag-name selector with no
 *     leading `.` — matching the siblings, whose form is correct, not a typo.
 *   - **`.fctable` (1) and `.fccell` (4–6)** — the "FEATURE CLOSE" CTA table
 *     appended to every article. **202 ch** on imaliboga, **55** on the other
 *     two; the two selectors remove the same block (the cells nest in the
 *     table), and `.fctable` is kept so the shell does not survive alone.
 *   - **`.shareiconsmenupg` (1) — 9 ch, and REQUIRED.** It must be named
 *     explicitly because the `<sitelevel_noindex>` that nominally contains the
 *     share widget is malformed — it opens inside `.contentpadding` and closes
 *     only after it, so the parser pops it early (#128).
 *   - **`.sidebar` (2 instances, 93 ch) — site-specific, and NOT in the sibling
 *     entries.** Audited across all 77 articles: it holds exactly two blocks of
 *     pure nav chrome and never any article text — "Imate pitanje? / Paket
 *     duhovne avanture / Podeli sa drugima" and "► Mapa sajta / ► Pošalji
 *     stranicu", identical on 76/76 pages, max 93 ch removed on any page.
 *   - **`.hr2` (2) and `.articledivider` (1)** — empty divs drawing the rules
 *     bracketing the CTA block. **0 chars**, confirmed.
 *   - **`.relatedbottom`** — **0 element instances** on every page measured. A
 *     no-op here; retained only for sibling parity. Do not read its presence as
 *     evidence it binds.
 *
 * ## What is blocked, and the evidence for each
 *
 * Every nav page on this host clears `minContentLength` — several only via the
 * `<body>` fallback, which returns the whole nav page rather than nothing. The
 * floor can NOT catch any of them; only a URL block can. All measured 2026-07-29
 * under this entry's exact shipped config:
 *   - **`/m/*` — navigation, not content.** All 8 measured at **12–2,823 ch**:
 *     postanje100 1,031, forum700 1,094, iskustvo300 1,060, pitanja500 987,
 *     zagonetke600 1,187 (these five are headline+teaser link lists reached via
 *     the `<body>` fallback), osajtu803 2,823 (about + privacy), autoru 1,654
 *     (author bio), intl 12 (the "Drugi jezici" page linking out to the sibling
 *     language domains — the same reason the English entry drops
 *     `/menus/intl.html`). `/m/autoru.html` and `/m/intl.html` are not even in
 *     the sitemap; the prefix block covers them regardless.
 *   - **`/mapa.html` — the site plan.** **2,712 ch** of pure link list. Clears
 *     the floor by 10×: length is not aboutness. Serbian twin of the French
 *     `/plan.html` and the Portuguese `/mapa.html`.
 *   - **`/kontakt.html` — the contact form.** **373 ch**, which is *over* the
 *     250 floor, so blocking is what excludes it.
 *   - **`/ranac.html` — the "Paket duhovne avanture" email series.** **1,233
 *     ch**: a signup page for a 7-message email course ("To je serijal od 7
 *     poruka… Poruke će stizati u razmacima od dva dana imejlom"), signed by
 *     Marilyn Adamson. Serbian twin of the French `/aventure.html`, the Arabic
 *     `/pack.html` and the Hungarian `/hatizsak.html`. Clears the floor
 *     comfortably — only a URL block catches it.
 *   - **`/` and `/index.html` — the homepage, twice.** **846 ch each** via the
 *     `<body>` fallback (byte-identical pages). Both blocked, or discovery would
 *     stage the same teaser page twice.
 *   - **the 5 dead `/a/` sitemap URLs** — 3 redirecting to a nav index and 2
 *     404s; see the cross-check section above.
 *   - **`/a/tanjiri.html` — a video stub.** `<title>Video: Padajući
 *     Tanjiri</title>`, and `.contentpadding` extracts **33 ch** ("Poznavanje
 *     Boga / Padajući Tanjiri"). It is the only one of the 77 live articles
 *     under the floor and the only page titled "Video:". Not in the XML sitemap,
 *     so it is excluded simply by not being seeded; blocked as well so a
 *     regenerated sitemap cannot readmit it.
 *
 * ⓘ **No Gospel-of-John signup page exists on this host.** The localized twin of
 * the French `/jean.html` / Hungarian `/janos.html` was searched for and is
 * absent: `/jovan.html`, `/a/jovan.html` and `/jevandjelje.html` all return 404,
 * and no such link appears anywhere in the full internal-link inventory of every
 * page fetched. Nothing to block.
 *
 * ## Language: `["sr"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text. The pages serve genuine
 * Serbian prose, not untranslated English. `/a/imaliboga101.html` opens "Ima li
 * Boga? Da li Bog postoji? Tu su šest iskrenih i nekomplikovanih razloga da
 * verujete da je Bog zaista ovde." and asks "Zar ne biste voleli bar jednom da
 * Vam neko jednostavno pokaže dokaz koji potvrđuje Božije postojanje?";
 * `/a/molitve306.html` is "Da li Bog uslišuje naše molitve?";
 * `/a/trojstvo709.html` is "Možete li objasniti Trojstvo?"; `/a/isus.html` is
 * "Ko je bio Isus?". Scripture citations use Serbian book names throughout
 * (Jovan, Otkrivenje, Matej, Luka, Psalam, 2.Korinćanima).
 *
 * **Serbian, not Croatian.** The corpus is uniformly **Ekavian**, the Serbian
 * standard, where the Croatian sibling (vrlovazno.com) would be Ijekavian.
 * Counted across all 77 articles 2026-07-29: čovek 102 / čovjek 0, verovati 56 /
 * vjerovati 1, hleb 26 / kruh 0, posle 148 / poslije 0, ovde 51 / ovdje 1, vera
 * 38 / vjera 0, and the interrogative "ko" 201 / "tko" 0. **Not Macedonian**
 * either — that sibling (studentskiodgovori.com) is written in Cyrillic, and
 * this host has effectively none (see Script above).
 *
 * The only English on these pages is bibliographic: footnotes citing
 * English-language works and translators' glosses of author names (e.g.
 * "Napisala Merilin Adamson (Marilyn Adamson)"). That is normal apparatus in a
 * translated article, not an untranslated body.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: ~110 sequential plain-HTTP requests drew no 429 and no throttling.
 */
import type { SourceEntry } from "./types.js";

export const everystudentSr: SourceEntry = {
  key: "everystudent-sr",
  name: "EveryStudent — Serbian (Studentski kutak)",
  domain: "www.studentskikutak.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["sr"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:sr"],
  defaultCategory: "article",
  rights:
    "© StudentskiKutak.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.studentskikutak.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP (Apache/HTTP2, no
    // Cloudflare) serves every page on this host. See header.
    sitemaps: ["/sitemap.xml"],
    // The 7 live `/a/` articles the stale 2020-11-25 sitemap omits, recovered
    // from the site's own /mapa.html and each verified HTTP 200 with real
    // extracted text on 2026-07-29. acquire.ts unions these with the discovered
    // set, so the effective corpus is 69 + 7 = 76. The 8th missing URL,
    // /a/tanjiri.html, is a 33-char video stub and is blocked instead.
    seedPaths: [
      "/a/heroina.html",
      "/a/judaizam.html",
      "/a/kontradikcija.html",
      "/a/sest.html",
      "/a/sledbenicima.html",
      "/a/zajednicko.html",
      "/a/zajednistvo.html",
    ],
    allow: ["^https://www\\.studentskikutak\\.com/"],
    // Articles live in one flat /a/ directory; nothing else on the host is one.
    // `[^/]+` keeps it safe for the one mixed-case slug, /a/Bibliji215.html.
    articleHints: ["^https://www\\.studentskikutak\\.com/a/[^/]+\\.html$"],
    block: [
      // The 8 /m/ pages — 12-2,823 ch of navigation, several reached only via
      // the <body> fallback, so ALL clear minContentLength and the floor can
      // NOT catch them. Covers the 6 section indexes plus /m/osajtu803.html
      // (about + privacy), /m/autoru.html (author bio) and /m/intl.html, the
      // "Drugi jezici" page linking out to the sibling language domains.
      "^https://www\\.studentskikutak\\.com/m/",
      // mapa = "Mapa sajta", the site plan (2,712 ch of pure link list);
      // kontakt = the contact form (373 ch, ABOVE the floor);
      // ranac = "Paket duhovne avanture", the 7-message email-series signup
      // (1,233 ch) — the twin of the French /aventure.html and Arabic
      // /pack.html. All three clear the floor; only a URL block excludes them.
      "^https://www\\.studentskikutak\\.com/(mapa|kontakt|ranac)\\.html$",
      // The homepage, which the sitemap lists TWICE as / and /index.html
      // (byte-identical, 846 ch each via the <body> fallback).
      "^https://www\\.studentskikutak\\.com/(index\\.html)?$",
      // DEAD sitemap URLs. These match articleHints, so ONLY a block stops
      // them. glinpos111 / mutnevode112 / zivot114 all 301 to the section index
      // /m/postanje100.html — unblocked they would stage 3 byte-identical
      // copies of a 1,031-char nav page. pravedanrat216 and ranac are 404.
      "^https://www\\.studentskikutak\\.com/a/(glinpos111|mutnevode112|zivot114|pravedanrat216|ranac)\\.html$",
      // A video stub: <title>Video: Padajući Tanjiri</title>, 33 ch extracted.
      // Absent from the sitemap today; blocked so a regenerated one cannot
      // readmit it.
      "^https://www\\.studentskikutak\\.com/a/tanjiri\\.html$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 across all 77 live articles
    // as the sole element on this host that extracts the article (76/77 match,
    // none empty, 33-23,205 ch). `.content4` is deliberately ABSENT: it matches
    // 76/77 pages and extracts 0 chars on every one of them, and because
    // extractContent scopes to the first selector that MATCHES rather than the
    // first that yields text, listing it here would make every article skip as
    // `too-thin` on an HTTP 200. `.content4b` matches 1 page and is also empty;
    // adding it would drop /a/zajednistvo.html, which the implicit root
    // fallback extracts correctly at 9,756 ch. See header.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome — all counted in THIS host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 instances / 102 ch; nesting is malformed
      ".shareiconsmenupg", // the share widget, 9 ch — sitelevel_noindex does NOT contain it (#128)
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells, 55-202 ch (nested in the table above)
      ".sidebar", // 2 per page / 93 ch: "Imate pitanje?…" + "► Mapa sajta…" nav chrome
      ".hr2", // empty divs drawing the rules bracketing the CTA block, 0 ch
      ".articledivider", // 0 ch
      ".relatedbottom", // 0 instances on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 130, // 84 sitemap entries + 7 pinned seeds -> 76 documents, + headroom
    minContentLength: 250,
  },
};
