/**
 * EveryStudent — Indonesian (mahasiswakeren.com, "MahasiswaKeren.com" /
 * "Cool Student"). The Indonesian banner of Cru's seeker-facing Q&A ministry:
 * short apologetics and life-issue articles, forum answers, video transcripts
 * and first-person testimonies written for Indonesian-speaking students who are
 * not believers. A sibling of `everystudent` (en), `everystudent-pl`,
 * `everystudent-sq`, `everystudent-ru`, `everystudent-de`, `everystudent-ko`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). mahasiswakeren.com is its own domain, so it gets its
 * own key, the same way `everystudent-pl` (kazdystudent.pl), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP throughout, despite Cloudflare being present
 *
 * Verified 2026-07-29: **~85 plain-HTTP GETs** with a full desktop-Chrome UA
 * (robots.txt, /sitemap.xml, all 67 sitemap URLs, /isi/sitemap.html,
 * /artikel/402mengenal.html and 9 probe paths). **Every sitemap URL returned
 * HTTP/2 200 with real HTML**, and **0 of the 67 fetched pages carry a
 * Cloudflare block-page signature** (grepped for "Attention Required",
 * "cf-browser-verification", "Cloudflare" — zero hits).
 *
 * ⚠️ Cloudflare IS in front of this host — responses carry `server: cloudflare`
 * and a `cf-nel` report-to header — but it is passing traffic through, not
 * challenging it. The wall test is the **block-page signature**, not the
 * presence of Cloudflare; keying off the latter false-positives (#114, and the
 * `everystudent-fr` header records the same correction). So `fetchStrategy` is
 * intentionally OMITTED: plain HTTP is the default and nothing here needs
 * Firecrawl (ADR-0012).
 *
 * Consequence: discovery is free, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-pl`, `everystudent-sq`.
 *
 * The bare host **301-redirects to `www`** (measured on /robots.txt), so
 * `www.mahasiswakeren.com` is the canonical host and the one every `<loc>` uses.
 * Every regex below is pinned to `www.` because filters match the absolute URL.
 *
 * ## robots.txt — nothing is disallowed
 *
 * Verified 2026-07-29: HTTP 200, **22 bytes**, the entire file being
 * `User-agent: * Allow: /`. Identical to `everystudent-fr` and
 * everyarabstudent.com. **No path on this domain is disallowed**, so nothing
 * below is blocked on robots grounds — every exclusion is a content-quality
 * call. (The acquire path does not enforce robots.txt today, so a Disallow
 * would have had to be mirrored into `block` by hand; there is none to mirror.)
 *
 * ## Sitemap — 67 entries, all distinct, 57 articles
 *
 * Verified 2026-07-29: `https://www.mahasiswakeren.com/sitemap.xml` → HTTP 200,
 * **11,108 bytes**, `application/xml`, Last-Modified 2025-12-11, a single flat
 * `<urlset>` (no `<sitemapindex>`, so no recursion), generated by
 * xml-sitemaps.com. It holds 67 `<loc>` elements and **67 distinct URLs** — no
 * duplicates. This matches the ~67 from prior recon exactly. The breakdown:
 *   - **57 `/artikel/<slug>.html`** — the article corpus. This is the keep set.
 *   - **8 `/isi/<slug>.html`** — section indexes (`forum`, `intl`, `isu`,
 *     `keberadaan`, `kebingungan`, `pengalaman`, `sitemap`, `tentang`). BLOCKED.
 *   - **`/hubungi.html`** — the contact page. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 * Note this banner uses `/artikel/` + `/isi/` where the siblings use `/a/` +
 * `/m/`; the path vocabulary is localized, so the sibling regexes do not carry
 * over unchanged.
 *
 * **All 67 sitemap URLs are live.** Verified 2026-07-29 by a full sequential
 * sweep: **67/67 returned HTTP 200 with an empty redirect_url** — no 301, no
 * 302, and in particular **no sitemap URL redirects to the homepage**. There is
 * no dead-URL cohort of the kind `everystudent-ro` shipped 25 of, so no
 * redirect-blocking entries are needed and none are present.
 *
 * ⚠️ **Mixed-case slugs are real on this host, and that was checked rather than
 * assumed.** **Eleven** of the 57 article slugs carry an uppercase letter:
 * `/artikel/109Tuhan.html`, `/artikel/200Islam.html` and its five sequels
 * `200Islam2`–`200Islam6`, `/artikel/202Yesus.html`, `/artikel/206Yesus.html`,
 * `/artikel/mengenal-Allah.html`, `/artikel/pertolongan-Tuhan.html`. A
 * lowercase-only `[a-z0-9-]+` hint would have silently dropped all of them, so
 * the hint uses `[^/]+`. All 67 `<loc>` values were also scanned for non-ASCII
 * bytes and `%XX` percent-encoding: **zero hits** — Indonesian orthography is
 * plain ASCII, so no encoding hazard here.
 *
 * ## HTML-map cross-check — the XML sitemap is the SUPERSET here
 *
 * These generated sitemaps are known to be stale (one sibling's was 17% short,
 * another listed 25 dead URLs), so the site's own HTML map was fetched and
 * diffed. Verified 2026-07-29: `/isi/sitemap.html` ("Peta situs") links **52
 * `/artikel/` URLs, and all 52 are already in the XML sitemap**. The delta runs
 * the other way — the XML holds **5 articles the HTML map omits**
 * (`/artikel/200Islam2.html` … `/artikel/200Islam6.html`, the six-part Islam
 * series whose map entry links only part 1). So discovery is the wider net and
 * **`seedPaths` is deliberately absent: there is nothing to pin.**
 *
 * As a second net, every `href` on all 67 fetched pages was harvested — 147
 * distinct values. Their union yields **58 distinct `/artikel/` URLs**, i.e.
 * exactly one beyond the sitemap: **`/artikel/402mengenal.html`**, and it is a
 * signup/referral page, not an article (see below). No genuine article is
 * missing from discovery.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` already excludes everything outside `/artikel/`. The `block`
 * list is deliberately redundant for those, recording *why* each group is out so
 * a later widening of the hints cannot silently readmit them — same defensive
 * posture as `thelife-fr` / `everystudent-pl` / `everystudent-sq`. **One entry
 * is not redundant**: `/artikel/402mengenal.html` sits under `/artikel/` and
 * matches `articleHints`, so `block` is the only thing keeping it out.
 *
 * All char counts are post-strip, measured 2026-07-29 with the repo's own
 * `extractContent`. ⚠️ **Every page listed here except `/isi/intl.html` clears
 * `minContentLength: 250`**, so the floor could not have excluded them — they
 * need URL blocks, and "minContentLength will drop it" would have been wrong.
 *
 *   - **`/artikel/402mengenal.html` — 369 chars, and it MATCHES `articleHints`.**
 *     "Memulai Bersama Allah — Seri Pertumbuhan Rohani": the post-decision
 *     spiritual-growth referral ("Kami telah membuat situs lain,
 *     MemulaiBersamaAllah.com…"), linked from the closing paragraph of five
 *     articles. This is the Indonesian twin of the French `/aventure.html`,
 *     German `/abenteuerreise.html`, Arabic `/pack.html` and Polish
 *     `/a/nowezycie.html` email series. It is **absent from today's sitemap**,
 *     so discovery would not reach it; the block is what makes that safe rather
 *     than lucky.
 *     ⓘ **There is no Gospel-of-John signup page on this host.** The Indonesian
 *     twins of `/john` · `/jean` · `/juan` were probed directly —
 *     `/yohanes.html`, `/yoh.html`, `/john.html`, `/injil.html` — and all four
 *     **404**. So do the "adventure/pack" twins `/petualangan.html` and
 *     `/paket.html`. This banner delegates that funnel to the separate domain
 *     memulaibersamaallah.com, which is out of this source's scope entirely.
 *   - **`/isi/*` — the 8 section indexes.** Verified 2026-07-29: 5 of the 8 have
 *     **no `.contentpadding` at all**, so `extractContent` falls back and returns
 *     **674 – 1,071 chars** of headline + teaser link list (`/isi/keberadaan.html`
 *     = "Keberadaan Tuhan", `/isi/pengalaman.html` = "Mengenal Tuhan", …).
 *     Navigation, not content. The 3 that DO have `.contentpadding`:
 *     `/isi/sitemap.html` (**2,254 ch**, the site plan — Indonesian twin of the
 *     French `/plan.html` and Polish `/mapa.html`), `/isi/tentang.html`
 *     (**719 ch**, the about page) and `/isi/intl.html` (**14 ch**, "Bahasa
 *     lainnya" — the page linking out to the sibling language domains, and the
 *     only excluded page the 250 floor would have caught on its own).
 *   - **`/hubungi.html` — 381 chars.** "Pertanyaan?", the contact/email page.
 *     Indonesian twin of the Polish `/pytanie.html` (401 ch) and Albanian
 *     `/kontaktoni1.html` (395 ch). It clears 250, so only a URL block excludes it.
 *   - **`/` — 803 chars.** The homepage. It does NOT extract to 0: it has no
 *     `.contentpadding`, so the fallback returns its full teaser list ("Apakah
 *     Tujuan Hidup Saya? / Apakah Tuhan itu ada? …"). Only a URL block excludes it.
 *
 * ## ⓘ NO full-Scripture page on this host — checked, not assumed
 *
 * The estate-wide scripture policy (decided 2026-07-29; `everystudent-sq` blocks
 * `/a/gjoni.html` at 98,887 chars, `everystudent-es` blocks
 * `/articulos/biblia_juan.html` at 100,409) has **nothing to bite on here**. The
 * longest article is `/artikel/215alkitab.html` at **30,537 chars**, and it was
 * read: it is "Mengapa Saudara dapat mempercayai Alkitab?" — an apologetics
 * essay *about* the Bible's historical reliability (Ebla tablets, F.F. Bruce,
 * Josh McDowell), not Bible text. The second longest, `/artikel/201buta.html`
 * (24,138 ch), is Paul E. Little's "Melampaui Iman yang Buta". This banner links
 * **out** to YouVersion for scripture — 4 articles carry
 * `https://www.bible.com/id/bible/306/JHN.1.TB` style links — rather than
 * hosting it, so no third-party Bible-society text is served from this domain
 * and no scripture block is required.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Verified 2026-07-29 by running the repo's own `extractContent`
 * (node-html-parser 7.1.0, exactly as `src/acquisition/extract.ts` uses it) over
 * **all 57 article pages** — not grepped, because every one of these tokens is
 * also declared in the page's inline `<style>` block and a grep false-positives
 * on all of them. Raw (pre-strip) figures, per candidate:
 *
 *   | selector              | pages matched | 0-char pages | min    | max    | mean   |
 *   |-----------------------|---------------|--------------|--------|--------|--------|
 *   | `.contentpadding`     | **56/57**     | **0**        | 1,545  | 30,713 | 9,730  |
 *   | `html`                | 57/57         | 0            | 21,429 | 50,629 | 29,754 |
 *   | `.content4`           | 56/57         | **56**       | 0      | 0      | 0      |
 *   | `.content4b`          | 1/57          | 1            | 0      | 0      | 0      |
 *   | `.articletitle`       | 57/57         | 0            | 5      | 101    | 36     |
 *   | `.cb-entry-content`   | 0/57          | —            | —      | —      | —      |
 *   | `.entry-content`      | 0/57          | —            | —      | —      | —      |
 *   | `.contentleftpadding` | 0/57          | —            | —      | —      | —      |
 *   | `.article-content`    | 0/57          | —            | —      | —      | —      |
 *   | `.articlebody`        | 0/57          | —            | —      | —      | —      |
 *   | `.content`            | 0/57          | —            | —      | —      | —      |
 *   | `article` / `main`    | 0/57          | —            | —      | —      | —      |
 *   | `body`                | **0/57**      | —            | —      | —      | —      |
 *
 * ⚠️ **`.content4` matches 56 of 57 pages and extracts 0 characters on every one
 * of them** — an empty spacer div. `contentSelectors` is **NOT a fallback
 * chain**: `extractContent` scopes to the FIRST selector that MATCHES AN
 * ELEMENT, not the first that yields text. Listing `.content4` ahead of
 * `.contentpadding` would bind the spacer and skip all 56 pages as `too-thin` on
 * an HTTP 200 — silent, and invisible to the unit tests. That is the batch-1
 * failure (#128). So `contentSelectors` here is the single measured container
 * and nothing else.
 *
 * ⚠️ **`<body>` matches 0 of 57 article pages.** The parse tree on this host is
 * already flattened: on a normal page (`/artikel/723katolik.html`)
 * `div.content4` and `div.contentpadding` are both **direct children of
 * `<html>`** and siblings of each other, rather than nested — which is exactly
 * why `.content4` holds no text while `.contentpadding` holds the whole article.
 * So the `extractContent` fallback is `body ?? root` → **`root`**, i.e. the whole
 * document with a literal `<!DOCTYPE html>` text node at the front. That is far
 * above the 250 floor, which is why every unwanted page above is blocked by URL
 * rather than left to `minContentLength`.
 *
 * With `.contentpadding` + the strip list below, across all 57 articles:
 * **1,369 – 30,537 chars, median 6,712, and 0 pages below the 250 floor.** Each
 * document opens on the section kicker + title and closes on its own "Catatan
 * kaki:" ("Footnotes:") scripture-reference line.
 *
 * ## ⓘ `/artikel/coronavirus.html` — the one page that falls back, and it is KEPT
 *
 * This is a call the orchestrator may want to reverse, so the evidence is here
 * rather than the decision being buried. It is the **only** article of the 57
 * where `querySelector(".contentpadding")` returns **null** (`.content4` is null
 * too, and `.content4b` matches with 0 chars) — its div stack collapses one level
 * differently from its 56 siblings, leaving the article as bare `<p>`/`<h2>`
 * children of `<html>`. `extractContent` therefore falls back to `root`.
 *
 * Unlike the Polish sibling's `/a/biblia.html` — which was BLOCKED because its
 * root fallback folded in the cookie bar, top nav, both menus, the sidebar and
 * the footer — **this fallback is clean**. Measured under the exact shipped
 * policy: **13,356 chars in 75 blocks**, of which **74 are genuine article
 * prose** ("Coronavirus (COVID-19) - Bagaimana Mengatasi Kecemasan" by Marilyn
 * Adamson), ending correctly on its own "Catatan kaki:" line. The nav does not
 * leak because on this host it lives inside `<sitelevel_noindex>`, which the
 * strip list removes. A targeted scan for 11 known nav strings ("Peta situs",
 * "Tentang situs ini", "BAGIKAN", "Bahasa lainnya", …) found **zero hits**.
 *
 * The entire defect is **block [0]: the literal string `"<!DOCTYPE html>"`** —
 * 15 characters, 0.1% of the document. (`head` is in the strip list, which
 * removes the duplicated `<title>` that would otherwise share that block; see
 * below.) Blocking would forfeit a 13.3k-char pastoral article on anxiety to fix
 * a 15-char cosmetic artefact, so it is KEPT. If the call goes the other way it
 * is one line:
 * `"^https://www\\.mahasiswakeren\\.com/artikel/coronavirus\\.html$"`.
 *
 * ## Chrome stripped — every selector counted on this host, 2026-07-29
 *
 * Two figures are given because they differ and both matter: **standalone** =
 * chars removed by that selector alone on top of the generic list;
 * **marginal** = chars it still removes once the selectors before it in the
 * shipped list have run. Measured across the 56 pages where `.contentpadding`
 * binds. Together the site-specific list removes **176 – 526 chars per page,
 * mean 214.**
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. The bare tag name with no
 *     leading `.` is correct, not a typo. **112 instances (2 on every one of the
 *     56 pages); standalone 100 chars, marginal 74 — on all 56, invariantly.**
 *     Instance [0] is the share-row label "BAGIKAN DENGAN YANG LAIN" ("SHARE
 *     WITH OTHERS"); instance [1] is the related/footer block "Pertanyaan? /
 *     Bagikan dengan yang lain / ► Peta situs / ► Tentang situs ini". It also
 *     wraps the top nav outside `.contentpadding`, which is why the one
 *     root-fallback page above stays clean.
 *   - **`.shareiconsmenupg` — standalone 26 chars on 56/56 pages, marginal 0.**
 *     ⓘ **On THIS host `sitelevel_noindex` is WELL-FORMED and already contains
 *     it**, so once that is stripped first this selector matches nothing — a
 *     genuine **0-char no-op in list order**. This is the batch-2 correction:
 *     it is NOT "required because the markup is malformed" (that is the `-de`/
 *     `-ru` finding, and no malformation was measured here). Kept purely as a
 *     cheap drift guard — the day `sitelevel_noindex` moves, "BAGIKAN DENGAN
 *     YANG LAIN" would otherwise trail all 56 extractions.
 *   - **`.fctable` — 57 instances on 55/56 pages; standalone 0–426 chars, mean
 *     112.** The "FEATURE CLOSE" call-to-action table appended to every article.
 *   - **`.fccell` — 264 instances on 56/56 pages; standalone 76–426 chars, mean
 *     114; marginal 0 on 55 pages and 107 on the one page that has cells but no
 *     `.fctable`.** The cells nest inside the table, so whichever runs first does
 *     the work — both are listed because stripping only the cells would leave the
 *     table shell, and stripping only the table misses that one page. Content:
 *     "► Bagaimana memulai sebuah hubungan dengan Tuhan ► Saya ada pertanyaan…".
 *   - **`.a2a_kit` — 112 instances on 56/56 pages, 0 chars.** The AddToAny share
 *     row, and the share widget this host actually uses. It removes nothing today
 *     because the buttons are `<img>` and `structuredText` does not read `alt`.
 *     Stripped anyway so a markup change adding text labels cannot leak them into
 *     every article. **Say it plainly: this is a 0-char guard, not a strip.**
 *   - **`.hr2` (120 instances) and `.articledivider` (54)** — present on nearly
 *     every page, but empty presentational divs drawing the rules that bracket
 *     the CTA block. **0 chars, confirmed.**
 *   - **`.relatedbottom` — 0 instances on this host.** Dead config, as on every
 *     sibling measured so far. Retained only as a parity no-op; do not read its
 *     presence here as evidence it binds.
 *   - **`head` — 0 chars on all 56 pages where `.contentpadding` binds**, because
 *     `head` is not inside that container. It earns its place on the single
 *     root-fallback page (`/artikel/coronavirus.html`), where it removes the
 *     duplicated `<title>`: **13,356 → 13,301 chars**, reducing the leading block
 *     to a bare `"<!DOCTYPE html>"`. Safe **only because `extract.ts` captures the
 *     title from `root` BEFORE the strip loop runs** — a future edit that reorders
 *     those two steps would lose the title on that page. Keep them in that order.
 *
 * ## Language: `["id"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Indonesian prose, not untranslated English — this is not the cru.org
 * `/mx/es/` failure mode where a localized URL served an English body.
 * `/artikel/101apakah.html` asks "Apakah Tuhan itu ada? Apakah ada bukti tentang
 * Tuhan?" and opens "Tidakkah saudara mau seseorang menunjukkan kepada saudara
 * bukti bahwa Tuhan itu ada? Tanpa paksaan. Tanpa pernyataan, 'Percaya
 * sajalah.'"; `/artikel/306menjawabdoa.html` is "Apakah Tuhan Menjawab Doa-Doa
 * Kita?" and narrates "Ketika saya masih seorang atheis, Saya mempunyai seorang
 * teman yang sangat sering berdoa"; `/artikel/723katolik.html` asks "Apakah ada
 * Perbedaan antara Orang Katolik dengan Kristen?"; `/artikel/coronavirus.html`
 * counsels "Bagi banyak orang, Coronavirus (COVID-19) telah meningkat menjadi
 * masalah yang mengkhawatirkan". Scripture citations use Indonesian book names
 * throughout (Yohanes, Mazmur, Matius, Yeremia, Lukas, Wahyu, 1 Petrus, Roma,
 * Yesaya, Filipi) under the native "Catatan kaki:" ("Footnotes:") heading. All
 * 57 pages declare `<html lang="id">`.
 *
 * The only English on these pages is bibliographic — footnotes citing
 * English-language books (e.g. "Francis S. Collins, … The Language of God, (Free
 * Press, New York, NY), 2006") — normal citation apparatus in a translated
 * article, not an untranslated body.
 *
 * ⚠️ ⓘ **One genuine oddity, reported not fixed: `/artikel/401mengenal.html`
 * ("Mengenal Tuhan Secara Pribadi") has an Indonesian body but VIETNAMESE
 * scripture references in its footnote list** — "Giăng 3:16", "Êsai 53:6",
 * "Rôma 6:23", "1 Côrinhtô 15:3-6", "Khải huyền 3:20". Copy-paste leakage from
 * the Vietnamese sibling, corroborated by this host hotlinking two share images
 * from everyvietstudent.com. It affects the closing ~200 chars of one article of
 * 57; the body is fully Indonesian, so the page is KEPT. Flagged because a
 * per-document language detector may score that article oddly at ingest.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * ## ⓘ Two video-transcript articles are KEPT, unlike the Polish sibling's
 *
 * `/artikel/pertolongan-Tuhan.html` (6,410 ch) and `/artikel/mengenal-Allah.html`
 * (6,945 ch) both open "Transkrip video:". `everystudent-pl` BLOCKED its
 * equivalent `/wideo.html` because the transcript extracted as ~60 one-line
 * blocks that chunk poorly against paragraph boundaries (invariant 4). That does
 * not apply here: measured 2026-07-29, these extract as **31 and 34 blocks
 * averaging 207 and 204 chars** — full prose paragraphs, statistically
 * indistinguishable from a normal article on this host (`/artikel/306menjawabdoa`
 * = 31 blocks, 383 chars/block). They are genuine seeker content in article
 * shape, live under `/artikel/`, and are kept.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~85 sequential
 * plain-HTTP requests at 0.6–1s spacing drew **zero 429s and no throttling**, so
 * the sibling default is kept rather than raised. At 57 pages the whole crawl is
 * ~60 seconds of wall clock.
 *
 * **Expected yield: 57 documents** — every `/artikel/` URL in the sitemap.
 */
import type { SourceEntry } from "./types.js";

export const everystudentId: SourceEntry = {
  key: "everystudent-id",
  name: "EveryStudent — Indonesian (MahasiswaKeren.com)",
  domain: "www.mahasiswakeren.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["id"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:id"],
  defaultCategory: "article",
  rights:
    "© MahasiswaKeren.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.mahasiswakeren.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host. Cloudflare fronts it (`server: cloudflare`) but passes
    // traffic through — 0 of 67 pages carried a block-page signature. The wall
    // test is the signature, not Cloudflare's presence (#114). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.mahasiswakeren\\.com/"],
    // The whole article corpus: 57 of the 67 sitemap URLs. `[^/]+` rather than a
    // lowercase class — 11 slugs carry uppercase letters (/artikel/109Tuhan.html,
    // /artikel/200Islam.html, /artikel/202Yesus.html, /artikel/206Yesus.html,
    // /artikel/mengenal-Allah.html, /artikel/pertolongan-Tuhan.html …), and a
    // [a-z0-9-]+ hint would have silently dropped every one of them. Slugs are
    // plain ASCII: 0 non-ASCII bytes and 0 %XX escapes across all 67 <loc>s.
    articleHints: ["^https://www\\.mahasiswakeren\\.com/artikel/[^/]+\\.html$"],
    block: [
      // ── This one MATCHES articleHints; `block` is the ONLY thing excluding it.
      // "Memulai Bersama Allah — Seri Pertumbuhan Rohani", 369 ch: the
      // post-decision referral to the separate site MemulaiBersamaAllah.com.
      // Indonesian twin of the French /aventure.html, Arabic /pack.html and
      // Polish /a/nowezycie.html. Absent from today's sitemap but linked from the
      // closing paragraph of 5 articles, so the block is what makes that safe.
      // (There is no Gospel-of-John signup page here — /yohanes.html, /yoh.html,
      // /john.html and /injil.html were all probed and all 404.)
      "^https://www\\.mahasiswakeren\\.com/artikel/402mengenal\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 8 section indexes. 5 of the 8 have no .contentpadding, so the
      // fallback returns 674-1,071 ch of headline+teaser link list — well clear
      // of the 250 floor. /isi/sitemap.html is the site plan (2,254 ch),
      // /isi/tentang.html the about page (719 ch), and /isi/intl.html the page
      // linking out to the sibling language domains (14 ch).
      "^https://www\\.mahasiswakeren\\.com/isi/",
      // The contact page: 381 ch, so like the Polish /pytanie.html it CLEARS
      // minContentLength and the floor cannot catch it.
      "^https://www\\.mahasiswakeren\\.com/hubungi\\.html$",
      // The homepage. It does NOT extract to 0 — it has no .contentpadding, so
      // the fallback returns its full 803-ch teaser list. Only a URL block
      // excludes it. (No redirect blocks are needed: all 67 sitemap URLs were
      // swept 2026-07-29 and returned 200 with no redirect at all.)
      "^https://www\\.mahasiswakeren\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 with the repo's own
    // extractContent as the sole element on this host that extracts the article
    // (1,545-30,713 ch raw across 56 of 57 pages, 0 of them empty).
    // `.content4` is deliberately ABSENT: it MATCHES on 56/57 pages and extracts
    // 0 chars on every one, and because extractContent scopes to the first
    // selector that MATCHES rather than the first that yields text, listing it
    // here would shadow this one and skip every page as `too-thin` (#128).
    // `.content4b` matches 1 page at 0 chars; `.cb-entry-content`,
    // `.entry-content`, `.contentleftpadding`, `.article-content`, `.articlebody`,
    // `.content`, `article`, `main` and even `body` match 0/57. No fallback is
    // listed on purpose — see the coronavirus note in the header.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // 0 chars on the 56 pages where .contentpadding binds (head is outside it).
      // Earns its place on /artikel/coronavirus.html, the one page that falls
      // back to `root`, where it drops the duplicated <title>: 13,356 -> 13,301.
      // Safe ONLY because extract.ts reads the title from `root` BEFORE the strip
      // loop — keep those two steps in that order.
      "head",
      // Site-specific chrome — all counted on this host 2026-07-29 (see header).
      // Together: 176-526 chars per page, mean 214.
      "sitelevel_noindex", // custom ELEMENT tag, 2/page on 56/56: "BAGIKAN DENGAN YANG LAIN" share row + the related/footer block. 100 ch standalone, 74 ch marginal.
      ".fctable", // the "FEATURE CLOSE" CTA table — 57 inst on 55/56 pages, 0-426 ch (mean 112)
      ".fccell", // its cells: "► Bagaimana memulai sebuah hubungan dengan Tuhan…" — 264 inst, 76-426 ch standalone
      ".shareiconsmenupg", // 0-CHAR NO-OP here: sitelevel_noindex is well-formed on this host and already contains it (26 ch standalone, 0 marginal). Kept as a drift guard, NOT because the markup is malformed.
      ".a2a_kit", // AddToAny share row — 112 inst, 0 chars (image-only buttons). A guard against labels being added, not a strip.
      ".hr2", // 120 inst, 0 chars — empty divs drawing the rules bracketing the CTA
      ".articledivider", // 54 inst, 0 chars
      ".relatedbottom", // 0 instances on this host; parity no-op, does not bind
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 100, // 67 sitemap URLs (57 kept after filtering) + headroom
    minContentLength: 250,
  },
};
