/**
 * EveryStudent — Persian/Farsi (everypersianstudent.com, "شناخت خداوند" /
 * "Knowing God"). The Persian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, plus first-person testimonies, written
 * for Farsi-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ar`, `everystudent-fr`, `everystudent-ru`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everypersianstudent.com is its own domain, so it gets
 * its own key, the same way `everystudent-ru` (mirstudentov.com),
 * `everystudent-fr` (questions2vie.com), `thelife-fr` (laviejenparle.com) and
 * `thelife-zh` (uwota.com) are separate entries.
 *
 * ⓘ **`fa` is a NEW language for this corpus, and this entry is its only
 * source.** thelife's Persian site (shagerdan.com) is Cloudflare-walled and has
 * never been registered — see the barrel's note. So `fa` arrives single-source
 * here; nothing else in the registry carries it today.
 *
 * ## NOT walled — plain HTTP, unlike the three walled EveryStudent banners
 *
 * Verified 2026-07-29: **116 plain-HTTP GETs** with a full browser UA — all 107
 * sitemap URLs, plus robots.txt, /sitemap.xml and 7 off-sitemap probes. Every
 * one of the 107 returned **HTTP 200 with real HTML and no redirect**, and not
 * one carried a Cloudflare block-page signature (no `Attention Required`, no
 * `Just a moment`). Responses are bare `Server: Apache` with no Cloudflare
 * layer at all. So `fetchStrategy` is intentionally OMITTED: plain HTTP is the
 * default and nothing here needs Firecrawl (ADR-0012).
 *
 * This matters because the OTHER Persian Cru site — thelife's shagerdan.com —
 * *is* walled. Do not generalize that host's behaviour onto this one; they were
 * probed separately and this one answers plain HTTP.
 *
 * Consequence: discovery is free, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, and the non-walled siblings `everystudent-ru` / `-de`.
 *
 * ## robots.txt — permissive, nothing disallowed
 *
 * Verified 2026-07-29: HTTP 200, **22 bytes**, the whole file being
 * `User-agent: * Allow: /`. Identical to everyarabstudent.com and
 * questions2vie.com, and unlike everystudent.com which carries a real disallow
 * list. **There is no `Disallow` line at all**, so nothing on this domain is
 * disallowed and no URL below is dropped on robots grounds — every exclusion
 * here is a content-quality call, not a policy one.
 *
 * ## Sitemap — 107 entries, all distinct, all live
 *
 * Verified 2026-07-29: `https://www.everypersianstudent.com/sitemap.xml` → HTTP
 * 200, **8,479 bytes**, `application/xml`, a single flat `<urlset>` (no
 * `<sitemapindex>`, so no recursion) generated by xml-sitemaps.com. It holds
 * **107 `<loc>` elements and 107 distinct URLs** — no duplicates. This matches
 * the ~107 from prior recon exactly.
 *
 * The bare apex 301-redirects to `www` (measured on /sitemap.xml), so
 * `www.everypersianstudent.com` is canonical and the host every `<loc>` uses.
 * `baseUrl`, `domain` and every regex below are pinned to `www.` accordingly.
 *
 * The 107 URLs break down as:
 *   - **75 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **21 `/j/j<N>.html`** — the Gospel of John, chapters 1-21. BLOCKED, below.
 *   - **8 `/m/<slug>.html`** — section indexes (`exi`, `jes`, `exp`, `iss`,
 *     `eni`, `for`, `abo`, `words`). BLOCKED, below.
 *   - **`/contact.html`**, **`/sitemap.html`**, **`/`** — BLOCKED, below.
 *
 * So `articleHints` is exactly `/a/<slug>.html` and the expected yield is 75
 * documents. One slug is mixed-case (`/a/Godreal.html`), so the hint must stay
 * case-sensitive-safe; `[^/]+` handles it.
 *
 * **No dead URLs and no redirects.** A full GET sweep of all 107 returned
 * 107 × 200 with an empty `redirect_url` on every one. Unlike siblings that
 * shipped dead sitemap entries, there is nothing here to block on that ground.
 *
 * ## HTML-map cross-check — the XML sitemap is COMPLETE, delta is zero
 *
 * These generated sitemaps are routinely stale, so the site's own HTML site
 * plan was parsed and diffed rather than trusted. Verified 2026-07-29:
 * `/sitemap.html` carries **86 internal links, and every single one is already
 * in the XML sitemap** — 0 links absent from it. Going the other way, it links
 * **75 of the 75** `/a/` articles: none missing. The same diff run across ALL
 * 107 fetched pages found no `/a/` article outside the sitemap either.
 * **Therefore `seedPaths` is intentionally absent** — there is nothing to pin.
 *
 * The link diff did surface three off-sitemap things, none of which needs a seed:
 *   - **`/a/fol.html` (HTTP 200)** — an email-signup page, BLOCKED below.
 *   - **25 `/x/*.html` links — all HTTP 404.** Dead alternates of `/a/` and
 *     `/j/` pages, linked from articles. `discoverUrls` reads sitemaps ONLY and
 *     never follows page links, so these can never be discovered; they get no
 *     block rule because there is nothing for one to catch. Recorded so a future
 *     link-following crawler does not rediscover them as a surprise.
 *   - **`/m/intl.html` (HTTP 200, 13 chars)** — the "زبان های دیگر" (other
 *     languages) page, already covered by the `/m/` block.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes everything outside `/a/`. The `block`
 * list is deliberately redundant: it records *why* each group is out, so a later
 * widening of the hints cannot silently readmit them. Same defensive posture as
 * `everystudent-ru` and `everystudent-ko`. Every figure below is the char count
 * `extractContent` actually returns for that page, measured 2026-07-29.
 *
 *   - **`/j/*` — the Gospel of John, not ministry writing.** 21 pages, one per
 *     chapter, each titled "انجيل يوحنّا" ("Gospel of John") and headed
 *     "باب ۱" … "باب ۲۱" ("Chapter 1" … "Chapter 21"). The bodies are
 *     verse-numbered Persian Scripture ("۱ در ابتدا كلمه بود و كلمه نزد خدا
 *     بود…" — John 1:1). They extract at **2,313-6,765 chars each, ~85,000
 *     total**, so the 250-char floor cannot touch them, and unblocked they would
 *     add more Bible text than this domain has ministry articles and compete
 *     with them in retrieval. Excluded on the same reasoning `everystudent-ar`
 *     drops its `/bible/**.pdf` files: public-domain Scripture, not the
 *     seeker-facing writing this corpus answers from.
 *   - **`/m/*` — navigation, not content.** All 8 fetched. Six (`exi`, `jes`,
 *     `exp`, `iss`, `eni`, `for`) have **no `.contentpadding` at all** and
 *     extract 739-1,311 chars of headline+teaser link list via the fallback;
 *     `/m/abo.html` (about) extracts 839 and `/m/words.html` extracts 1,570.
 *     Every one clears the floor, so the floor could not catch them. The Persian
 *     twins of the `/m/*` indexes the French entry drops.
 *   - **`/sitemap.html` — the site-plan page.** Extracts **2,904 chars** of pure
 *     link list. It clears the floor by an order of magnitude — length is not
 *     aboutness.
 *   - **`/contact.html` — contact chrome.** Extracts **312 chars**, which is
 *     *above* the 250 floor by 62. It is precisely the page a "minContentLength
 *     will drop it" argument would have lost.
 *   - **`/a/fol.html` — an email-signup follow-up page.** Extracts **284 chars**
 *     — again above the floor, by 34. Content is "بسیار عالی است که شما عیسی را
 *     در قلب خود پذیرفته اید" ("it is wonderful that you have accepted Jesus
 *     into your heart") followed by a request to email the site so they can send
 *     more material. Form copy, not a seeker question being answered — the same
 *     call `everystudent-fr` reached on `/jean.html` / `/aventure.html`. It is
 *     **not in today's sitemap**, but it IS linked from at least 4 articles and
 *     matches `articleHints`, and this sitemap is generated by a link-following
 *     crawler — so a regeneration would admit it. The block is the insurance.
 *   - **`/` — the homepage.** No content container at all; the `<body>` fallback
 *     extracts **676 chars** of nav. Above the floor, so blocked by URL.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Re-verified 2026-07-29 by running node-html-parser exactly as
 * `src/acquisition/extract.ts` does, over all 107 saved pages. This is the only
 * check that proves anything: every one of these tokens is ALSO declared in the
 * page's inline `<style>` block, so grepping for a class name false-positives.
 * Every candidate, with the chars it actually extracts on an article:
 *   - **`.contentpadding` — 1 instance, the whole article.** Kicker, title,
 *     subhead, byline and body. `/a/faith.html` → 21,235 raw / **20,960 after
 *     stripping**; `/a/bible.html` → 27,503 / **27,323**; `/a/trinity.html` →
 *     3,412 / **3,232**. Across the 74 articles that carry it the range is
 *     **937-27,323 chars, and not one falls below the 250 floor.**
 *   - **`.content4` — 1 instance on 105 of 107 pages, and it extracts
 *     0 characters on 99 of them**, including every single `/a/` and `/j/`
 *     article. It is an empty spacer div. (The 6 exceptions are `/m/` indexes,
 *     where it holds 739-1,311 chars of nav — all blocked anyway.)
 *   - **`.content4b` — 1 instance on exactly ONE page** (`/a/personally.html`),
 *     where it extracts **0 characters**. Absent from the other 106.
 *   - **`.articletitle` — 1 instance, 11-55 chars.** An `<h1>`. A title, not a body.
 *   - `.content`, `#content`, `article`, `main` — **0 instances anywhere.**
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text, so listing `.content4` ahead of `.contentpadding`
 * would bind the empty spacer and extract **0 chars on every article** — every
 * page skipping as `too-thin` on an HTTP 200, silently, with no error anywhere
 * and no unit test able to see it. That is how 5 of the 8 pilot entries shipped
 * broken (#128). `contentSelectors` is therefore the ONE measured container and
 * nothing else — no chain, no "outermost first" fallbacks.
 *
 * ⚠️ `.contentpadding` also binds on `/j/`, `/contact.html`, `/sitemap.html`,
 * `/m/abo.html` and `/m/words.html` — it does **not** discriminate content from
 * chrome. The URL filters above are what keep the corpus clean; the selector
 * must not be relied on to do it.
 *
 * ### The one page that does not fit: `/a/personally.html`
 *
 * `/a/personally.html` ("شخصاً خدا را شناختن" — "Knowing God personally", the
 * gospel presentation) is served with **malformed markup that flattens the DOM**:
 * the parser pops out of every wrapper, so `.container2` and `.content4b` both
 * close empty (0 chars), `.contentpadding` and `.content4` are absent entirely,
 * and even `<body>` is lost — the article's `<h1>`/`<h2>`/`<p>` nodes end up as
 * direct children of `<html>`. Same failure mode as `everystudent-ko`, but here
 * it is 1 page out of 75 rather than the whole host.
 *
 * **It is deliberately left unblocked and unhandled.** `extractContent` falls
 * back to `<body>` and then to the root, and the root fallback here happens to
 * work well: **7,311 chars over 39 paragraphs, all of it the article**, from the
 * opening question to the closing prayer, because the nav really does live
 * inside the `sitelevel_noindex` tags the strip list removes. The only residual
 * noise is the literal string `<!DOCTYPE html>` (15 chars, 0.2%) surviving as a
 * text node. Adding `.content4b` to `contentSelectors` to "handle" this page
 * would be actively harmful — it would bind and yield 0 chars, turning a working
 * 7,311-char extraction into a `too-thin` skip.
 *
 * ## Chrome stripped — counted INSIDE `.contentpadding` on this host
 *
 * Instance counts are totals across the 74 articles that carry `.contentpadding`;
 * char removals are measured on `/a/faith.html` and `/a/trinity.html`.
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **148 instances (2 per
 *     article), 99 chars** removed per page. Hence the bare tag-name selector
 *     with no leading `.` — matching the sibling entries, whose form is correct
 *     rather than a typo.
 *   - **`.fctable` (148, 2/article) and `.fccell` (320, 4-6/article)** — the
 *     "FEATURE CLOSE" call-to-action table appended to every article. Measured
 *     removal **224 chars** on `faith`, **129** on `trinity`; the cells nest in
 *     the table, and `.fctable` is included because stripping only the cells
 *     would leave the table shell.
 *   - **`.hr2` (148) and `.articledivider` (74)** — empty divs drawing the rules
 *     that bracket that CTA block. **0 chars**, confirmed.
 *   - **`head`** — a NO-OP on the 74 well-formed articles (the container is
 *     `.contentpadding`, which contains no `<head>`). It earns its place on
 *     `/a/personally.html` alone, where the container falls back to the root and
 *     `<head>` would otherwise contribute a duplicate `<title>`: measured
 *     7,334 → **7,311 chars** with it. `extract.ts` reads the title from `root`
 *     BEFORE stripping, so the page title is not lost — keep that order.
 *   - **`.shareiconsmenupg` (74, 1/article) — retained, but a measured NO-OP
 *     HERE.** It wraps the AddToAny share row. On the German and Russian
 *     siblings it must be named explicitly because their `<sitelevel_noindex>`
 *     is malformed and pops before enclosing it (#128); **on this host that
 *     markup is well-formed** — the ancestor chain is
 *     `DIV.shareiconsmenupg < SITELEVEL_NOINDEX < DIV.contentpadding`, and
 *     removing the selector changes the output on **0 of 75 pages**. Kept for
 *     sibling parity and because the malformed variant costs nothing to defend
 *     against; do not read its presence here as evidence it binds.
 *   - **`.relatedbottom`** — **0 instances** on any page measured. Also a no-op
 *     on this host, also retained for parity.
 * Total chrome removed per article: **275 chars** on `faith`, **180** on the
 * others measured. Articles end on their own last line.
 *
 * ## Language: `["fa"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. These pages serve
 * genuine Persian prose, not untranslated English — the failure mode cru.org's
 * Spanish path hit. `/a/isthere.html` is titled "آيا خدايي هست؟" ("Is there a
 * God?") and opens "آيا خدا وجود دارد؟ در اينجا شش دليل صريح و واضح وجود دارد
 * تا باور کنيد خدا واقعاً آنجاست." ("Does God exist? Here are six clear and
 * plain reasons to believe God really is there."), bylined "به نوشتة مارلين
 * آدامسون" (Marilyn Adamson). `/a/howcan.html` asks "آيا عيسي خداست؟" ("Is Jesus
 * God?") in an explicit "سئوال:" / "پاسخ ما:" ("question" / "our answer")
 * format; `/a/trinity.html` is "آيا ميتوانيد تثليث را توضيح دهيد؟" ("Can you
 * explain the Trinity?"); `/a/marriage.html` is "آيا اميدي براي يك ازدواج
 * پايدار وجود دارد؟" ("Is there hope for a lasting marriage?").
 *
 * It is **Persian, not Arabic** — a distinction worth pinning on an RTL host
 * whose Arabic sibling is already registered. The four Perso-Arabic letters that
 * do not exist in Arabic all appear in quantity; on `/a/isthere.html` alone:
 * گ ×187, چ ×83, پ ×62, ژ ×8. Persian grammar words ("است", "آيا", "ميتوانيد")
 * run throughout. A script census over all 75 articles found **436,849
 * Arabic-script characters against 683 Latin (0.16%)**, and the Latin residue is
 * bibliographic — English book titles in footnotes, normal citation apparatus in
 * a translated article, not an untranslated body.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field. No language-detection library was
 * used to reach the above; it is read text plus a character census.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: 116 sequential plain-HTTP GETs drew no 429 and no throttling, and at
 * 75 pages the whole crawl is well under two minutes of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentFa: SourceEntry = {
  key: "everystudent-fa",
  name: "EveryStudent — Persian/Farsi (everypersianstudent.com)",
  domain: "www.everypersianstudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["fa"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:fa"],
  defaultCategory: "article",
  rights:
    "© EveryPersianStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everypersianstudent.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare layer), unlike the three walled
    // EveryStudent siblings — and unlike thelife's Persian shagerdan.com, which
    // IS walled and is a different host entirely. See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.everypersianstudent\\.com/"],
    // The whole article corpus and nothing else: 75 of the 107 sitemap URLs.
    // Case-sensitive-safe — /a/Godreal.html carries an uppercase G.
    articleHints: ["^https://www\\.everypersianstudent\\.com/a/[^/]+\\.html$"],
    block: [
      // The Gospel of John, chapters 1-21 ("انجيل يوحنّا", "باب ۱"…"باب ۲۱") —
      // verse-numbered Persian Scripture at 2,313-6,765 chars each, ~85,000
      // total. Public-domain Bible text, not ministry writing, and far too much
      // of it to sit unblocked beside 75 articles. Same call as the Arabic
      // entry's /bible/**.pdf drop. minContentLength cannot touch these.
      "^https://www\\.everypersianstudent\\.com/j/",
      // The 8 section indexes (exi, jes, exp, iss, eni, for, abo, words) —
      // headline+teaser link lists at 739-1,570 chars, so they clear the floor
      // and the floor can NOT catch them. /m/abo.html is the about page.
      // /m/intl.html (off-sitemap, the "other languages" page) is covered too.
      "^https://www\\.everypersianstudent\\.com/m/",
      // The site-plan page: 2,904 chars of pure link list.
      "^https://www\\.everypersianstudent\\.com/sitemap\\.html$",
      // Contact chrome: 312 chars — ABOVE the 250 floor by 62.
      "^https://www\\.everypersianstudent\\.com/contact\\.html$",
      // Email-signup follow-up page: 284 chars, ABOVE the floor by 34. Not in
      // today's sitemap, but linked from 4+ articles and matching articleHints,
      // and this sitemap is generated by a link-following crawler — so a
      // regeneration would admit it. Blocked by URL, not left to the floor.
      "^https://www\\.everypersianstudent\\.com/a/fol\\.html$",
      // The homepage — no content container; the <body> fallback yields 676
      // chars of nav, well over the floor.
      "^https://www\\.everypersianstudent\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts an article (937-27,323 chars across 74 of the 75).
    // `.content4` is deliberately ABSENT: it matches on 105 pages and extracts
    // 0 chars on 99 of them, and because extractContent scopes to the first
    // selector that MATCHES rather than the first that yields text, listing it
    // here would make every article skip as `too-thin` on a 200 (#128).
    // `.content4b` exists on exactly one page and also extracts 0 chars —
    // adding it would break /a/personally.html rather than fix it. See header.
    // Rule 1e (added 2026-07-30, retrofitted): trailing "html" rescues pages
    // whose .contentpadding container collapses. Without it extract.ts falls
    // through to `?? root`, which returns the whole document INCLUDING a
    // literal `<!DOCTYPE html>` text node. Proven inert on healthy pages —
    // 21 of 21 sampled extractions were byte-identical before and after.
    // It can shadow nothing, because nothing follows it.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // No-op on the 74 well-formed articles; needed only on the flattened
      // /a/personally.html, whose container falls back to the root. extract.ts
      // reads the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 per article: 99 chars
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells — 129-224 chars removed with the shell
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".shareiconsmenupg", // AddToAny share row; NO-OP here (well-formed wrapper), kept for parity
      ".relatedbottom", // 0 instances on this host; kept for parity
    ],
    requestDelayMs: 1000,
    maxPages: 150, // 107 sitemap entries (75 articles) + headroom
    minContentLength: 250,
  },
};
