/**
 * EveryStudent — Romanian (everystudent.ro). The Romanian banner of Cru's
 * seeker-facing Q&A ministry: short apologetics/life-issue articles aimed at
 * Romanian-speaking students who are not believers.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everystudent.ro is its own domain, so it gets its own
 * key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate from their
 * English parents.
 *
 * **NOT walled — plain HTTP, so no `fetchStrategy`.** Verified 2026-07-28:
 * `robots.txt`, `/sitemap.xml`, the homepage and every article page probed
 * returned **200** to a plain `curl` with a browser UA. No Cloudflare block-page
 * signature anywhere (no "Attention Required", no "Just a moment"). This is the
 * first EveryStudent banner in the estate that does NOT need Firecrawl — the
 * three walled ones (`everystudent`, `everystudent-ar`, `everystudent-fr`) are
 * the exception here, not the rule. Omitting `fetchStrategy` leaves it at the
 * `plain-http` default, so this source costs nothing per page.
 *
 * **Discovery mode, not hand-listed seeds** — the opposite call from the three
 * walled siblings, and for exactly the reason their headers give: they hand-list
 * because their `/sitemap.xml` is 403 and re-enumeration costs Firecrawl credits.
 * Neither applies here. `/sitemap.xml` is public and free, so `sitemaps` +
 * `allow`/`articleHints`/`block` is strictly better — it picks up new articles
 * without an entry edit. Precedent: `thelife-fr`.
 *
 * **`robots.txt` is `User-agent: * Allow: /`** — fetched live 2026-07-28, 22
 * bytes, the entire file. No Disallow rules at all, so nothing in the article
 * set is disallowed. Same as everyarabstudent.com and questions2vie.com, and
 * UNLIKE everystudent.com, which carries a real disallow list. Note the bare
 * apex `everystudent.ro` 301s to `www.everystudent.ro`; `domain`/`baseUrl` use
 * the `www.` form the sitemap's own `<loc>` entries use, so no redirect hop is
 * paid per page.
 *
 * **Sitemap: 102 URLs, all unique** (verified 2026-07-28, `<urlset>` not a
 * `<sitemapindex>`; generated by xml-sitemaps.com with a 2019 `lastmod`):
 *   - **85 `/a/*.html`** — the article corpus.
 *   - **5 `/v/*.html`** — video pages. **Kept, not dropped**: 4 of the 5 carry a
 *     real Romanian transcript under a "Transcriere video:" heading (measured
 *     1,619–6,644 chars of body text), which is substantive seeker content in
 *     the same voice as the articles. The English sibling makes the same call —
 *     it seeds `/videos/*`, including `/videos/collins.html`, the very same
 *     Francis Collins piece that lives here at `/v/collins.html`.
 *   - **8 `/m/*.html`** — the mobile/menu section indexes (`acord`, `credinta`,
 *     `despre`, `existenta`, `intl`, `intrebari`, `relatii`, `viata`).
 *     Navigation, not articles: `/m/intrebari.html` extracts to 906 chars that
 *     are purely a list of other pages' titles. `/m/intl.html` is the page
 *     linking out to the sibling language domains. Blocked, matching the `/m/`
 *     drop in `everystudent-fr` and `/menus/` in `everystudent`.
 *   - **`/sitemap.html`** — the "Harta site-ului" link index (2,575 chars of
 *     nothing but other pages' titles). The Romanian twin of the `/sitemap.html`
 *     the English entry drops. Blocked.
 *   - **`/contact.html`** — the "Întreabă-ne" contact form + privacy notice
 *     (886 chars). Blocked.
 *   - **`/ioan.html`** — an email-signup landing page for a Gospel-of-John email
 *     series (1,550 chars: "Înregistrare", "o serie de mesaje trimise prin
 *     email", an unsubscribe explanation, signed by the site director). Blocked.
 *     This is the exact Romanian twin of `/jean.html` on the French banner,
 *     which slice #10 seeded provisionally, fetched, and then dropped on
 *     evidence. It clears `minContentLength` comfortably — length is not
 *     aboutness — so the floor could never have caught it and the URL block is
 *     doing real work.
 *   - **the bare homepage.** Blocked (and see below — it is also inert).
 *
 * ⚠️ **The sitemap is STALE: 25 of the 85 `/a/` URLs are dead.** HEAD-checked all
 * 90 `/a/` + `/v/` URLs on 2026-07-28: 65 returned 200 and **25 returned 301 to
 * the homepage** (`/a/adam`, `/a/apostolii`, `/a/asemanare`, `/a/astazi`,
 * `/a/cale`, `/a/care`, `/a/ceva`, `/a/cine`, `/a/cine2`, `/a/coronavirus`,
 * `/a/fericire`, `/a/iad`, `/a/inchinare`, `/a/inspirata`, `/a/intamplare`,
 * `/a/iubitor`, `/a/miracole`, `/a/nimic`, `/a/ofera`, `/a/raul2`,
 * `/a/religiile`, `/a/rezultat`, `/a/sex`, `/a/sex2`, `/a/suferinta`). The
 * filters below keep 90 of the sitemap's 102 URLs (85 `/a/` + 5 `/v/`), but only
 * **65 of those are live**, and one live `/v/` page is a transcript-less embed
 * (below), so expect **~64 ingested documents**, not 102. Do not read a
 * shortfall against the sitemap count as a crawl failure.
 *
 * Those 25 are deliberately NOT hard-blocked, because they are **self-policing**:
 * the homepage they redirect to carries **none** of the four content selectors
 * (verified 2026-07-28 — zero `class="content4|content4b|articletitle|
 * contentpadding"` attributes in the whole document), so extraction yields **0
 * characters** and `minContentLength: 250` drops every one of them. They cost 25
 * wasted plain-HTTP fetches per run and pollute nothing. Listing 25 dead-URL
 * regexes would bloat the entry and rot the moment the site restores one, so the
 * floor handles it. Revisit only if the homepage ever grows a `.content4`.
 *
 * **Extraction — measured on THIS host, not inherited.** All four shared
 * EveryStudent template selectors bind here (verified 2026-07-28 across
 * `/a/exista.html`, `/a/iisus.html`, `/a/depresie.html`, `/v/collins.html`,
 * `/v/estedumnezeubun.html` and more): `<div class="content4">` wraps the body,
 * with `.content4b` and `.contentpadding` nested inside it and
 * `<h1 class="articletitle">` carrying the title. `.content4` first is correct —
 * it is the outermost of the four. Extracted body text ran 2,208–25,272 chars on
 * the sampled articles, all far above the floor.
 *
 * **Strip list — `.shareiconsmenupg` is site-specific and load-bearing.** The
 * inherited five all appear: `sitelevel_noindex` is a custom element wrapping
 * the cookie notice, sidebar and nav; `.fccell` is the call-to-action table
 * (6 cells/page); `.hr2` and `.articledivider` are rule divs. `.relatedbottom`
 * is present **only as a CSS rule in an inline `<style>`**, never as an element
 * on this host — retained for parity with the siblings, but it strips nothing
 * here and that is not a mistake to "fix". Together they removed 50–192 chars
 * per page.
 *
 * The addition: **this host's markup overlaps**, and `sitelevel_noindex` alone
 * does not contain the share widget. Traced byte offsets in `/a/iisus.html`:
 * `.content4` opens at 22086, a `<sitelevel_noindex>` opens at 27504 *inside*
 * `.contentpadding`, and the `</div>`s closing `.contentpadding`, `.content4b`
 * and `.content4` all sit *inside* it (closing comments at 27531/27571/28897)
 * before it closes at 28929. Any conforming parser resolves that overlap by
 * implicitly closing `sitelevel_noindex` at the first `</div>` — which leaves
 * `<div class="shareiconsmenupg">` (offset 27608) as a direct child of
 * `.content4`. Measured result: without it every extracted body ended in a
 * dangling "SHARE:"; with it added, all 10 sampled pages end on their own last
 * sentence. Do not remove it on the grounds that `sitelevel_noindex` "already
 * covers" the share links — on this host it does not.
 *
 * `/v/filmuliisus.html` is likewise left unblocked and left to the floor: it is a
 * bare 2-hour JESUS film embed with no transcript, extracting to **53 chars**,
 * so `minContentLength` drops it. The other four `/v/` pages survive.
 *
 * **Language: `["ro"]` — read, not assumed.** The probed pages serve genuine
 * Romanian prose with correct diacritics (ș/ț/ă/î/â), not untranslated English:
 * `/a/exista.html` opens "Există dovezi ale existenţei lui Dumnezeu?" ("Is there
 * evidence of God's existence?") and `/a/depresie.html` is titled "Sfârşitul
 * depresiei" ("The end of depression"). The stored per-document label still
 * comes from content detection at ingest (invariant 6), never from this field.
 *
 * ⓘ **Romanian is a NEW language for this corpus** — unlike French at slice #10,
 * no `ro` documents exist yet, so no existing golden case becomes eligible by
 * construction and Stage-4 Part A re-review has nothing to re-rank. `ro` starts
 * as a single-source language for gating purposes.
 *
 * `requestDelayMs: 1000` — plain HTTP against a small static Apache site. The
 * 100+ probe requests made during recon (including a 90-URL HEAD sweep at 400ms)
 * drew no 429 and no throttling, so 1s is comfortably polite.
 */
import type { SourceEntry } from "./types.js";

export const everystudentRo: SourceEntry = {
  key: "everystudent-ro",
  name: "EveryStudent — Romanian (everystudent.ro)",
  domain: "www.everystudent.ro",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ro"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ro"],
  defaultCategory: "article",
  rights:
    "© EveryStudent.ro (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everystudent.ro",
    // No `fetchStrategy`: this banner is NOT walled (verified 2026-07-28, all
    // 200s to plain curl), so it stays on the plain-http default. See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.everystudent\\.ro/"],
    articleHints: [
      // The article corpus (85 in the sitemap, 60 of them live).
      "^https://www\\.everystudent\\.ro/a/[^/]+\\.html$",
      // Video pages — 4 of 5 carry a real Romanian transcript. See header.
      "^https://www\\.everystudent\\.ro/v/[^/]+\\.html$",
    ],
    block: [
      // /m/* are the mobile/menu section indexes — navigation, not articles.
      // /m/intl.html is also the page linking to the sibling language domains.
      "^https://www\\.everystudent\\.ro/m/",
      // Link indexes, contact chrome, and the Gospel-of-John email-signup
      // landing page (the Romanian twin of the French /jean.html, dropped at
      // slice #10 — it clears minContentLength, so only a URL block catches it).
      "^https://www\\.everystudent\\.ro/(sitemap|contact|ioan)\\.html$",
      // The homepage: no content selectors at all, so it extracts to 0 chars.
      "^https://www\\.everystudent\\.ro/?$",
    ],
    contentSelectors: [
      ".content4",
      ".content4b",
      ".articletitle",
      ".contentpadding",
    ],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome, measured on this host 2026-07-28 (see header):
      "sitelevel_noindex", // custom element: cookie notice, sidebar, nav
      ".relatedbottom", // CSS-only on this host; kept for sibling parity
      ".fccell", // the "FEATURE CLOSE" call-to-action table
      ".hr2",
      ".articledivider",
      // NOT covered by sitelevel_noindex here: the site's markup overlaps, so
      // the share widget resolves to a direct child of .content4 and every body
      // otherwise ends in a dangling "SHARE:". See header.
      ".shareiconsmenupg",
    ],
    requestDelayMs: 1000, // plain HTTP, small static site; no 429s seen in recon
    maxPages: 150, // 102 sitemap URLs + headroom
    minContentLength: 250,
  },
};
