/**
 * EveryStudent — Albanian (pyetjetejetes.com, "Pyetjet e Jetës" / "Life's
 * Questions"). The Albanian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, plus first-person student testimonies,
 * written for Albanian-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ru`, `everystudent-de`, `everystudent-ko`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). pyetjetejetes.com is its own domain, so it gets its own
 * key, the same way `everystudent-ru` (mirstudentov.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-29: robots.txt, /sitemap.xml, **all 78 `/a/` articles**, all 8
 * `/m/` indexes, the homepage, /gjonit.html, /aventures.html and
 * /kontaktoni1.html were fetched with a plain `curl` carrying a browser UA —
 * **every one returned HTTP/2 200 with real HTML**. Responses are `server:
 * Apache` with no Cloudflare layer at all, so this host is further from the three
 * walled banners (everystudent.com, everyarabstudent.com, questions2vie.com) than
 * even the Russian one. The only redirect seen anywhere is the intentional
 * apex→`www` 301 (measured on /robots.txt), which is why `domain`, `baseUrl` and
 * every regex below are pinned to `www.` — the sitemap emits `www` absolute URLs
 * and the filters match the full absolute URL.
 *
 * So `fetchStrategy` is intentionally OMITTED: plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012). Discovery is therefore free, making
 * this a **discovery crawl** rather than the hand-listed seed set the walled
 * banners were forced into. Precedent: `thelife-fr`, `everystudent-ru`.
 *
 * ## robots.txt — one real Disallow, and it names an article path
 *
 * Verified 2026-07-29: HTTP 200, 42 bytes, Last-Modified 2019-11-12. The whole
 * file is:
 *
 *     User-agent: *
 *     Disallow: /a/ungjillin2.html
 *
 * Unlike the Russian/German siblings (which disallow nothing), this host carries
 * a rule that **points into the `/a/` article namespace** — so it had to be
 * honoured rather than noted. `/a/ungjillin2.html` returns 200 and extracts 2,523
 * chars ("Të fillosh me Perëndinë" — a "getting started with God" follow-up
 * page), so neither the 250 floor nor the article-hint regex would have excluded
 * it. It is **absent from /sitemap.xml**, so discovery would not reach it today;
 * it is blocked below anyway so the rule is enforced explicitly and a later
 * widening of the hints cannot silently readmit it. Nothing else on the domain is
 * disallowed.
 *
 * ## Sitemap — 131 entries, all distinct
 *
 * Verified 2026-07-29: `https://www.pyetjetejetes.com/sitemap.xml` → HTTP 200,
 * 11,698 bytes, `application/xml`, Last-Modified 2022-12-21, a single flat
 * `<urlset>` (no `<sitemapindex>`, so no recursion), generated by
 * xml-sitemaps.com. It holds 131 `<loc>` elements and **131 distinct URLs** — no
 * duplicates. This matches the ~131 from prior recon exactly.
 *
 * The 131 break down as:
 *   - **78 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **41 `/pdf/<slug>.pdf`** — print twins of the articles. BLOCKED: this
 *     source is `html-scrape` and cannot read a PDF.
 *   - **8 `/m/<slug>.html`** — section indexes (`ekzistenca`, `pyetjet`,
 *     `seksualiteti`, `njohesh`, `forum`, `video`, `sitemap`, `faqe`). BLOCKED.
 *   - **3 root pages** — `/gjonit.html`, `/aventures.html`, `/kontaktoni1.html`.
 *     BLOCKED, individually, on measured evidence below.
 *   - **`/`** — the homepage. BLOCKED.
 * So `articleHints` is exactly `/a/<slug>.html` and the expected yield is **78
 * documents**.
 *
 * **All 78 `/a/` URLs are live.** Verified 2026-07-29 by a sweep of the full
 * article set: **78/78 returned HTTP 200 with no redirect**. There are no dead
 * URLs to block (contrast `everystudent-ro`, which had 25 redirecting to its
 * homepage) and no `.php` extension twins of the kind the French entry dropped.
 * One slug is mixed-case, `/a/Zoti-vertete.html`, so the hint regex must stay
 * case-sensitive-safe; `[^/]+` handles it.
 *
 * ## HTML-map cross-check — the XML sitemap is the SUPERSET here
 *
 * These sitemaps are known to be stale, so `/m/sitemap.html` ("Harta e faqes")
 * was fetched and diffed against the XML. Verified 2026-07-29: the HTML map lists
 * **72 `/a/` links, and all 72 are already in the XML sitemap** — the delta runs
 * the other way, with 6 articles in the XML that the HTML map omits
 * (`/a/grave.html`, `/a/heather.html`, `/a/paris.html`, `/a/paterice.html`,
 * `/a/pavaresia.html`, `/a/studentore.html`). All 6 were fetched and are genuine
 * articles (3,623 – 8,484 chars: "Të drejtat e Grave", "A ka paqe pas Parisit?",
 * "Ëndrra Studentore në Universitet", …), so discovery already covers them and
 * **no `seedPaths` are needed** — `seedPaths` is deliberately absent.
 *
 * The hrefs of all 8 `/m/` indexes and the homepage were harvested too, as a
 * second net. Their union adds exactly **one** `/a/` URL the XML sitemap lacks —
 * `/a/erdhi.html`, linked from `/m/video.html` — and it is **dead**: verified
 * 2026-07-29, it **301-redirects to `/m/ekzistenca.html`**, a section index. It
 * is not seeded, and it is blocked below so that a later hand-added seed or a
 * regenerated sitemap cannot quietly stage a copy of that nav page.
 *
 * ## ⚠️ EXTRACTION: the shared EveryStudent template DOES NOT BIND on this host
 *
 * This is the one decision on this entry that would silently destroy the source
 * if undone, so it is measured rather than inherited. Every candidate below was
 * run through the repo's own parser (`node-html-parser`, exactly as
 * `src/acquisition/extract.ts` uses it) over **all 78 article pages** on
 * 2026-07-29 — not grepped, because every one of these tokens is also declared in
 * the page's inline `<style>` block and a grep false-positives on all of them:
 *
 *   - **`.content4` — matches on 78/78 pages and extracts 0 characters on every
 *     one of them.** An empty spacer div.
 *   - **`.contentpadding` — matches on only 52/78 pages, and extracts 0
 *     characters on all 52.** Absent from the other 26 entirely.
 *   - **`.content4b` — 0 matches.** Absent from this host.
 *   - **`.articletitle` — 1 match, 20–46 chars.** The `<h1>` headline, not a body.
 *   - **`.articlebody`, `.content`, `<article>`, `<main>` — 0 matches each.**
 *   - **`<body>` is itself absent from the parsed tree** on all 78 pages.
 *   - **`<html>` — the ONLY element that contains the article** (24,442 – 41,539
 *     chars unstripped on the pages sampled).
 *
 * Root cause, same shape as `everystudent-ko`: the FreeFind markers **interleave
 * with** rather than nest inside the content divs. In `/a/jezusi.html`,
 * `<sitelevel_noindex>` opens at line 157, `<div class="container2">` at 160,
 * `<div id="content4">` at 163, `<div class="content4">` at 169 and
 * `<div class="contentpadding">` at 170 — then a stray `</sitelevel_noindex>` at
 * line 172 closes that whole div stack early, and a second unmatched
 * `</sitelevel_noindex>` at line 378 disposes of `<body>`. The article (title at
 * line 180, prose onward) is left as **flat direct children of `<html>`**. No
 * wrapper element survives to select.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text — so
 * listing `.content4` or `.contentpadding` "outermost first as fallbacks" would
 * bind an empty div, extract 0 chars, and skip every article as `too-thin` on an
 * HTTP 200: silent, and invisible to the unit tests. That is how five of the
 * eight pilot entries first shipped. `contentSelectors` here is therefore the
 * single measured container and nothing else.
 *
 * `["html"]` is also deliberately explicit rather than left to `extractContent`'s
 * `body ?? root` fallback: with no selector matching, the fallback lands on
 * `root`, whose doctype node leaks the literal string `<!DOCTYPE html>` into the
 * head of every extracted document (measured: 6,291 chars vs 6,274 on
 * `/a/jezusi.html`).
 *
 * **Measured with `["html"]` plus the strip list below, across all 78 articles:
 * 1,241 – 98,887 chars, median 6,855, and 0 pages below the 250 floor.** Output
 * opens on the article title and closes on the article's own last line (usually
 * its scripture-reference list), with no nav, cookie bar, share widget, related
 * links, CTA or footer left.
 *
 * ⓘ **`/a/gjoni.html` is the outlier at 98,887 chars — a call for the
 * orchestrator, not blocked here.** It is titled "Lexoje Fjalën e Perëndisë vetë"
 * ("Read God's Word yourself") and is the **complete text of the Gospel of John,
 * all 21 chapters**, fronted by a chapter index and a Bible-search widget
 * ("Librat e Biblës / Pasazh specifik / Kërkim fjalësh"). It is ~14× the median
 * article and is raw scripture rather than the seeker Q&A prose this source
 * exists for, so it will chunk into a large block of Bible text. It is genuine
 * `/a/` content and no sibling entry has an equivalent page to set precedent, so
 * it is KEPT and flagged rather than dropped on my own judgement. Blocking it is
 * a one-line addition if that is the call.
 *
 * ## Chrome stripped — measured across all 78 articles, 2026-07-29
 *
 * Per-selector figures are the marginal characters each removes, measured by
 * re-running the full extraction with that one selector withheld:
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **2 instances on 78/78 pages,
 *     removing exactly 905 chars on every single page** — by far the largest
 *     contributor. It carries the cookie-consent bar and top nav ("Kjo faqe përdor
 *     cookie vetëm për analitikë…", 396 ch) and the bottom share + related-links +
 *     footer block ("TREGOJUA MIQVE:" — "TELL YOUR FRIENDS", 458 ch). Hence the
 *     bare tag-name selector with no leading `.`; the siblings' form is correct
 *     rather than a typo.
 *   - **`head`** — 1 instance, 6–134 chars. Needed **only because the container is
 *     `<html>`**: without it every document opens with a duplicate of its own
 *     `<title>`. Safe because `extract.ts` captures the title from `root` BEFORE
 *     the strip loop runs — a future edit that reorders those two steps would lose
 *     the title, so keep them in that order.
 *   - **`.fccell`** — 354 instances across 78 pages, removing 79–196 chars: the
 *     "FEATURE CLOSE" call-to-action cells appended to every article ("► Si të
 *     fillosh një marrëdhënie personale me Perëndinë ► Kam një pyetje…").
 *     ⓘ `.fctable` is **0 instances on this host** — the CTA `<table>` carries no
 *     class here, only its cells do, and the emptied shell contributes 0 chars —
 *     so it is not in the list. Do not add it expecting it to bind.
 *   - **`.a2a_kit`** — the AddToAny share-button row, and the share widget this
 *     host actually uses (the Korean sibling's `.likesharediv` is **0 instances**
 *     here). 2 instances on 78/78 pages, **0 chars**: the buttons are images and
 *     `structuredText` does not read `alt`. Stripped anyway so a future markup
 *     change that adds text labels cannot leak them into every article.
 *   - **`.hr2` (200 instances) and `.articledivider` (75)** — empty divs drawing
 *     the rules that bracket the CTA block. **0 chars**, confirmed.
 *   - **`.shareiconsmenupg`** — checked because the Russian and German siblings
 *     need it: **0 instances on this host**. Retained as a documented no-op for
 *     sibling parity; do not read its presence here as evidence it binds.
 *   - **`.relatedbottom`** — likewise **0 instances**. Same parity no-op.
 *
 * ## ⚠️ minContentLength cannot be relied on to catch the non-articles
 *
 * Every page blocked below was fetched and extracted, and **every single one
 * clears the 250-char floor** — so the floor could not have excluded any of them
 * and the `block` list is doing real work, not decorating. Verified 2026-07-29:
 *   - the 8 `/m/` section indexes: **333 – 3,305 chars** of headline+teaser link
 *     lists. `/m/sitemap.html` ("Harta e faqes", 3,305 ch) is the site-plan page
 *     and also the one linking out to sibling language domains — the Albanian twin
 *     of the French `/plan.html`; `/m/faqe.html` ("Për këtë faqe", 1,067 ch) is
 *     about + privacy; `/m/video.html` (333 ch) is the video index.
 *   - **`/gjonit.html` — 1,756 chars.** "Studim mbi Ungjillin e Gjonit", the
 *     Gospel-of-John email-study signup landing page. Albanian twin of the French
 *     `/jean.html`, Romanian `/ioan.html`, Portuguese `/joao.html`.
 *   - **`/aventures.html` — 1,241 chars.** "Kutia e Aventurës Shpirtërore" ("The
 *     Spiritual Adventure Box"), the 7-email series signup. Albanian twin of the
 *     French `/aventure.html`, German `/abenteuerreise.html`, Arabic `/pack.html`.
 *   - **`/kontaktoni1.html` — 395 chars.** "Keni pyetje?", the contact form.
 *   - **`/` — 778 chars.** The homepage. It does NOT extract to 0: `html` matches
 *     on it as readily as on an article, so it yields its full teaser list. It
 *     must be blocked by URL.
 *
 * ## Language: `["sq"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Albanian prose, not untranslated English. `/a/trinine.html` asks "A mund
 * ta shpjegoni Trininë?" ("Can you explain the Trinity?") and answers "Përgjigjia
 * jonë: 'Trini' është një term që nuk gjendet në Bibël por një fjalë e përdorur
 * për të përshkruar atë që del qartë për Perëndinë në Shkrimin e Shenjtë";
 * `/a/ekziston.html` opens "A ekziston Perëndia? … Vetëm një herë të vetme a nuk
 * do të doje që dikush të të tregonte faktet për ekzistencën e Perëndisë?";
 * `/a/lutjeve.html` is "A u përgjigjet Perëndia lutjeve tona?" and narrates "Kur
 * isha ateist, kisha një shoqe të mirë e cila lutej shpesh"; `/a/heather.html` is
 * a Stanford student's testimony, "Sfida ime më e madhe në Stanford University".
 * Scripture citations use Albanian book names throughout (Gjoni, Zbulesa,
 * Romakëve, Psalmi, Jeremia, 1 Pjetrit, Filipianëve, Isaia). The site declares
 * `<html lang="sq">` and `charset=utf-8`, both consistent with what was read.
 *
 * The only English on these pages is bibliographic: footnotes citing
 * English-language books (e.g. "…of God, (Free Press, New York, NY), 2006"),
 * which is normal citation apparatus in a translated article, not an untranslated
 * body. No sampled page was untranslated English.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. Two full sequential
 * sweeps of all 78 articles at ~1s spacing, plus ~25 other probes, drew **zero
 * 429s and no throttling**, so the sibling default is kept rather than raised.
 */
import type { SourceEntry } from "./types.js";

export const everystudentSq: SourceEntry = {
  key: "everystudent-sq",
  name: "EveryStudent — Albanian (Pyetjet e Jetës)",
  domain: "www.pyetjetejetes.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["sq"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:sq"],
  defaultCategory: "article",
  rights:
    "© PyetjeteJetes.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.pyetjetejetes.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.pyetjetejetes\\.com/"],
    // The whole article corpus and nothing else: 78 of the 131 sitemap URLs.
    // Case-sensitive-safe — /a/Zoti-vertete.html carries an uppercase Z.
    articleHints: ["^https://www\\.pyetjetejetes\\.com/a/[^/]+\\.html$"],
    block: [
      // The estate's "Who was Jesus?" page (22,089 chars) — curated highlights
      // from the Gospel of John carrying the family's own formula: excerpts
      // taken straight from the Bible with NO COMMENTARY ADDED. Because it is
      // predominantly Bible-translation text, it stays quarantined until its
      // translation, rights holder, reuse terms, and required attribution are
      // known and representable. The same temporary rule covers the full
      // Gospel-of-John pages and `everystudent-ar` Bible-PDF pages. This is the
      // ~20-26k curated version of the same thing; all 13
      // instances across the estate go together (campaign #111 §0.13).
      // NOT inert — sibling copies took ranks 7 and 8 on a cross question,
      // consuming top-10 slots a real answer would hold.
      // It matches the article shape, so only a URL block catches it.
      "^https://www\\.pyetjetejetes\\.com/a/ishte\\.html$",
      // robots.txt Disallow, fetched live 2026-07-29 — the ONE rule on this
      // host, and it names an /a/ path. The page returns 200 and extracts 2,523
      // chars, so nothing else would have excluded it. Absent from the sitemap
      // today; blocked so the rule is enforced, not merely noted.
      "^https://www\\.pyetjetejetes\\.com/a/ungjillin2\\.html$",
      // /a/gjoni.html is the COMPLETE Gospel of John, all 21 chapters
      // (98,887 chars measured 2026-07-29) — verbatim Scripture, not ministry
      // writing. Blocked 2026-07-29 under the estate-wide scripture policy that
      // `everystudent-ar` set for its /bible/**.pdf files: "outside what this
      // corpus answers from". Siblings -et, -mn and -fa block their equivalents.
      // It matches /a/*.html, so only a URL block catches it.
      "^https://www\\.pyetjetejetes\\.com/a/gjoni\\.html$",
      // 41 sitemap entries are /pdf/ print twins of the articles. This source is
      // html-scrape and cannot read a PDF.
      "^https://www\\.pyetjetejetes\\.com/pdf/",
      "\\.pdf($|\\?)",
      // The 8 section indexes (ekzistenca, pyetjet, seksualiteti, njohesh,
      // forum, video, sitemap, faqe) — headline+teaser link lists, 333-3,305
      // chars, so they clear minContentLength and the floor can NOT catch them.
      // /m/sitemap.html is the site plan and the page linking out to the sibling
      // language domains; /m/faqe.html is about + privacy.
      "^https://www\\.pyetjetejetes\\.com/m/",
      // Email-signup landing pages, both measured well above the floor:
      // gjonit = the Gospel-of-John study (1,756 ch), aventures = the "Kutia e
      // Aventurës Shpirtërore" 7-email series (1,241 ch). kontaktoni1 = the
      // contact form (395 ch).
      "^https://www\\.pyetjetejetes\\.com/(gjonit|aventures|kontaktoni1)\\.html$",
      // Dead: 301s to /m/ekzistenca.html. Linked from /m/video.html but absent
      // from the sitemap, so discovery cannot reach it today — blocked so a
      // regenerated sitemap cannot stage a copy of that nav page.
      "^https://www\\.pyetjetejetes\\.com/a/erdhi\\.html$",
      // The homepage. It does NOT extract to 0 — `html` matches on it too, so it
      // yields its 778-char teaser list. Only a URL block excludes it.
      "^https://www\\.pyetjetejetes\\.com/?$",
    ],
    // ⚠️ NOT the shared EveryStudent template. Measured 2026-07-29 over all 78
    // articles: `.content4` matches on 78/78 and extracts 0 chars,
    // `.contentpadding` matches on 52/78 and extracts 0 chars, `.content4b` does
    // not match at all, and even <body> is lost — stray </sitelevel_noindex> end
    // tags close the content divs early and flatten the article into <html>'s
    // direct children. `<html>` is the only element that still contains it.
    // Do NOT add `.content4` or `.contentpadding` here: extractContent binds the
    // first selector that MATCHES, so either would win and yield "".
    contentSelectors: ["html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Required because the container is <html>: drops the duplicate <title>.
      // extract.ts reads the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-29 (see header):
      "sitelevel_noindex", // custom TAG (2/page): cookie bar + nav, and share + related + footer — 905 chars on all 78
      ".fccell", // "FEATURE CLOSE" CTA cells — 79-196 chars. `.fctable` is 0 instances here.
      ".a2a_kit", // the AddToAny share row — 0 chars today (image-only buttons)
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".shareiconsmenupg", // NO-OP here — 0 instances; kept for sibling parity
      ".relatedbottom", // NO-OP here — 0 instances; kept for sibling parity
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 170, // 131 sitemap URLs (78 kept after filtering) + headroom
    minContentLength: 250,
  },
};
