/**
 * EveryStudent — Malay (persoalanhidup.com, "Persoalan Hidup" / "Life's
 * Questions"). The Malay banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, plus first-person testimonies, written
 * for Malay-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-pl`, `everystudent-sq`, `everystudent-ru`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). persoalanhidup.com is its own domain, so it gets its
 * own key, the same way `everystudent-pl` (kazdystudent.pl), `everystudent-sq`
 * (pyetjetejetes.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries. In particular it is **distinct from the
 * Indonesian banner** (`everystudent-id`, mahasiswakeren.com) — see the language
 * section below, which was the one real risk on this host.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-29: `/sitemap.xml`, **all 61 sitemap URLs**, `/a/fol.html`
 * and 12 probe paths were fetched with a plain `curl` carrying a browser UA.
 * **All 61 sitemap URLs returned HTTP 200 with no redirect**; responses are
 * `server: Apache` with no Cloudflare layer and no block page anywhere. Median
 * response ~1.4 s.
 *
 * So `fetchStrategy` is intentionally OMITTED: plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012). Discovery is therefore free, making
 * this a **discovery crawl** rather than a hand-listed seed set. Precedent:
 * `thelife-fr`, `everystudent-pl`.
 *
 * The apex 301-redirects to `www` (measured on `/robots.txt`), so `domain`,
 * `baseUrl` and every regex below are pinned to `www.` — the sitemap emits
 * `www` absolute URLs and the filters match the full absolute URL.
 *
 * ## robots.txt — there ISN'T one
 *
 * Verified 2026-07-29: `https://www.persoalanhidup.com/robots.txt` returns
 * **HTTP 404** (the site's own styled "Maaf!" error page, 36,187 bytes of HTML,
 * not a robots file). The apex serves a 301 to the `www` form, which then 404s
 * too. There is **no Disallow list on this host at all**, so nothing needed
 * blocking on robots grounds and no path below is blocked for that reason.
 * Contrast `everystudent-sq`, whose single Disallow named an `/a/` article.
 *
 * ## Sitemap — 61 entries, all distinct, all live
 *
 * Verified 2026-07-29: `https://www.persoalanhidup.com/sitemap.xml` → HTTP 200,
 * 9,543 bytes, `application/xml`, Last-Modified 2024-12-23, a single flat
 * `<urlset>` (no `<sitemapindex>`, so no recursion), generated by
 * xml-sitemaps.com. It holds 61 `<loc>` elements and **61 distinct URLs** — no
 * duplicates. This matches the ~61 from prior recon exactly.
 *
 * The 61 break down as:
 *   - **52 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **7 `/m/<slug>.html`** — section indexes (`hubungan`, `kehidupan`,
 *     `kewujudan`, `mengenal`, `sitemap`, `soaljawab`, `tentang`). BLOCKED.
 *   - **`/hubungi.html`** — the contact form. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 * So `articleHints` is exactly `/a/<slug>.html`, and after the one scripture
 * block the expected yield is **51 discovered + 1 seeded = 52 documents**.
 *
 * **No dead URLs.** All 61 returned 200 with an empty `redirect_url` — there is
 * nothing here like `everystudent-ro`'s 25 homepage redirects. No `.php`
 * extension twins either.
 *
 * Five slugs are **mixed-case** — `/a/109Tuhan.html`, `/a/202Yesus.html`,
 * `/a/206Yesus.html`, `/a/708RohKudus.html`, `/a/mengenali-Tuhan.html` — so a
 * lowercase-only hint would silently drop them. `[^/]+` handles it.
 *
 * ## HTML-map cross-check — the two sitemaps agree exactly, but BOTH miss a page
 *
 * These sitemaps are known to be stale, so `/m/sitemap.html` ("Peta Laman") was
 * fetched and diffed against the XML. Verified 2026-07-29: the HTML map lists
 * **52 `/a/` links and they are the SAME 52 the XML sitemap holds** — zero delta
 * in either direction.
 *
 * A full `<a href>` harvest across all 61 fetched pages (64 distinct on-site
 * links) was run as a second net, and it found **three URLs absent from the XML
 * sitemap**:
 *   - `/a/201buta` — **404**, a broken link missing its `.html` (the real page,
 *     `/a/201buta.html`, is in the sitemap). Not seeded; no block needed, since
 *     it fails `articleHints` anyway and `acquireOne` rejects any status ≥ 400.
 *   - `/a/collins.html` — **404**, a stale link to what is now
 *     `/a/100collins.html`. Same reasoning: not reachable by discovery, and a
 *     404 body never stages.
 *   - **`/a/fol.html` — HTTP 200, a REAL 3,100-char article** titled "Permulaan
 *     dengan Tuhan" ("Beginning with God"), answering "if I asked Jesus into my
 *     life, how do I know He is really there?". It is linked from three articles
 *     (`/a/101wujud.html`, `/a/107sempurna.html`, `/a/201buta.html`) but is
 *     **missing from the XML sitemap AND from `/m/sitemap.html`**, so discovery
 *     cannot reach it. It is therefore **pinned in `seedPaths`** — `acquire.ts`
 *     unions seeds with discovered URLs precisely for this case.
 *
 * ⓘ **`/a/fol.html` is the one page with noticeable Indonesian bleed** — it
 * mixes Malay `bahawa` (×2) with Indonesian `bahwa` (×3) and uses Indonesian
 * `memulai` where every other page uses Malay `memulakan`. It reads as a
 * partially-relocalised import from the Indonesian sibling. It is still genuine
 * ministry prose on an `/a/` URL, so it is kept; the per-document language label
 * comes from content detection at ingest (invariant 6), which will judge it on
 * its own text. Flagged here so the call is visible rather than buried.
 *
 * ## ⚠️ EXTRACTION: `.content4` is an EMPTY SPACER — it must NOT be listed
 *
 * This is the one decision on this entry that would silently destroy the source
 * if undone, so it is measured rather than inherited. Every candidate was run
 * through the repo's own parser (`node-html-parser`, exactly as
 * `src/acquisition/extract.ts` uses it) over **all 52 article pages** on
 * 2026-07-29 — not grepped, because `.content4` is also declared in each page's
 * inline `<style>` block and a grep false-positives on it:
 *
 *   - **`.contentpadding` — matches 52/52, extracts 2,472–28,368 chars, and is
 *     ZERO-CHAR ON NONE of them.** The article container. ✅ SHIPPED.
 *   - **`.content4` — matches 52/52 and extracts 0 characters on every single
 *     one.** An empty spacer div.
 *   - **`html` — matches 52/52, 22,310–48,197 chars**, but drags in the whole
 *     nav/chrome shell. Correct only where `.contentpadding` fails; it does not.
 *   - **`.articletitle` — 1 match, 30–56 chars.** The `<h1>` headline, not a body.
 *   - **`.content4b`, `.cb-entry-content`, `.entry-content`,
 *     `.contentleftpadding`, `.article-content`, `<article>`, `<main>` — 0
 *     matches each.** Absent from this host.
 *   - **`<body>` is itself absent from the parsed tree** on all 52 pages, so the
 *     `body ?? root` fallback in `extractContent` lands on `root` — the whole
 *     document including a literal `<!DOCTYPE html>` text node.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text —
 * so listing `.content4` "outermost first as a fallback" would bind the empty
 * spacer, extract 0 chars, and skip every article as `too-thin` on an HTTP 200:
 * silent, and invisible to the unit tests. That is how five of the eight pilot
 * entries first shipped. `contentSelectors` here is therefore the single
 * measured container and nothing else.
 *
 * **Measured with `[".contentpadding"]` plus the strip list below, across all 52
 * articles: 2,317 – 28,213 chars, median 9,915, and 0 pages below the 250
 * floor.** Output opens on the section breadcrumb + headline + standfirst and
 * closes on the article's own last line (usually its "Nota Kaki" footnote list),
 * with no nav, share widget, CTA or footer left. A scan of all 52 extracted
 * bodies for chrome strings found **zero real leaks**.
 *
 * ## ⚠️ SCRIPTURE: `/a/300siapakah.html` is 16 chapters of John — BLOCKED
 *
 * Verified 2026-07-29. Titled "Siapakah Yesus?" ("Who is Jesus?") and, at 28,213
 * chars, the largest page on the host. Its own standfirst says what it is: "Ini
 * adalah **kutipan langsung dari Injil Yohanes**, dalam Alkitab. **Tanpa
 * tambahan ulasan**" — "these are direct quotations from the Gospel of John, in
 * the Bible. Without added commentary." The body carries 16 standalone chapter
 * headings (Yohanes 1, 3, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
 * and runs to the resurrection appearance to Thomas.
 *
 * Blocked under the **estate-wide scripture policy decided 2026-07-29**:
 * public-domain Scripture text rather than ministry writing — outside what this
 * corpus answers from. Siblings `-es` (`/articulos/biblia_juan.html`, 100,409
 * ch), `-sq` (`/a/gjoni.html`, 98,887 ch), `-et`, `-mn` and `-fa` block their
 * equivalents. It matches `/a/*.html`, so **only a URL block catches it** — it
 * is 113× the 250-char floor.
 *
 * It is an *abridged* John (16 of 21 chapters) rather than a complete book, but
 * it is still verbatim Scripture with no commentary, which is what the policy
 * targets. A sweep of the other 51 articles for standalone chapter headings
 * returned **0 on every one**, so this is the only such page.
 *
 * ⓘ No third-party Bible-society copyright was found. The only "hak cipta"
 * notice on the host is an ordinary book-adaptation credit on `/a/201buta.html`
 * ("Diadaptasi daripada 'Know Why You Believe' oleh Paul E. Little … Digunakan
 * dengan izin"), which is normal citation apparatus.
 *
 * ⓘ **No Gospel-of-John signup page and no "adventure/pack" email series exist
 * on this host.** The Malay twins of `/jean`·`/john`·`/juan` and
 * `/aventure`·`/pack` were probed directly — `/yohanes.html`, `/john.html`,
 * `/a/yohanes.html`, `/pengembaraan.html`, `/pakej.html`, `/petualangan.html`
 * **all return 404** — and the 64-link harvest turned up no signup landing page
 * of any kind. There is nothing to block here; the siblings' blocks have no
 * counterpart on this domain.
 *
 * ## Chrome stripped — measured across all 52 articles, 2026-07-29
 *
 * Figures are each selector's STANDALONE contribution (base strip vs base strip
 * plus that one selector), because several of these nest inside one another and
 * a marginal-only measurement under-reports them. Together the site-specific
 * selectors remove **9,736 chars over the 52 articles (~187/page)**:
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **104 instances (2 per page)
 *     on 52/52 pages, removing exactly 77 chars on every page.** It carries the
 *     "KONGSI HALAMAN INI" ("SHARE THIS PAGE", 18 ch) share header and the
 *     bottom nav block ("Ajukan Soalan! / Kongsi Halaman / ► Peta Laman /
 *     ► Tentang", 55 ch). Hence the bare tag-name selector with no leading `.`;
 *     the siblings' form is correct rather than a typo.
 *     ⓘ On THIS host it is **well-formed** — it does not break the div tree, and
 *     `.contentpadding` survives on 52/52 pages. Do not repeat the older
 *     "REQUIRED because the markup is malformed" claim here; that was measured
 *     on other hosts, not this one.
 *   - **`.fccell`** — 250 instances on 52/52 pages, **78–232 chars per page**:
 *     the "FEATURE CLOSE" call-to-action cells ("► Bagaimana memulai sebuah
 *     hubungan dengan Tuhan", "► Saya mempunyai soalan…"). The single biggest
 *     text contributor at 5,732 chars total.
 *   - **`.fctable`** — 52 instances on 51/52 pages; the `<table>` wrapping those
 *     cells. Standalone it removes the same 0–156 chars per page, but **marginal
 *     0** once `.fccell` is also listed. Kept so the emptied shell cannot survive
 *     if the cell class ever changes.
 *   - **`.shareiconsmenupg`** — 52 instances on 52/52 pages. Standalone it
 *     removes 20 chars/page, but it sits **INSIDE** the well-formed
 *     `sitelevel_noindex` above, so in list order it is a **0-char no-op**. Kept
 *     as a cheap drift guard, exactly as the `-pl` sibling does; it is NOT
 *     claimed to strip anything today.
 *   - **`.a2a_kit`** (104 instances), **`.hr2`** (110), **`.articledivider`**
 *     (51) — the AddToAny share row and the empty divs drawing the rules that
 *     bracket the CTA block. **0 chars each**, confirmed; the share buttons are
 *     images and `structuredText` does not read `alt`. Stripped anyway so a
 *     future markup change adding text labels cannot leak into every article.
 *   - **`.relatedbottom`** — **0 instances on this host**, as on every sibling
 *     measured so far. Retained as a documented parity no-op; do not read its
 *     presence as evidence it binds.
 *   - **`head`** is deliberately NOT in the list: it has **0 instances inside
 *     `.contentpadding`**. `-sq` needs it only because its container is `<html>`.
 *
 * ## ⚠️ minContentLength cannot catch the non-articles
 *
 * Every page blocked below was fetched and extracted, and **every one clears the
 * 250-char floor** — so the floor could not have excluded any of them and the
 * `block` list is doing real work. Verified 2026-07-29:
 *   - the 7 `/m/` section indexes: **459 – 2,022 chars** of headline+teaser link
 *     lists. `/m/sitemap.html` ("Peta Laman", 2,022 ch) is the site-plan page,
 *     the Malay twin of the French `/plan.html` and Polish `/mapa.html`;
 *     `/m/tentang.html` ("Tentang Laman Web", 996 ch) is about + privacy.
 *     ⓘ Five of the seven (`hubungan`, `kehidupan`, `kewujudan`, `mengenal`,
 *     `soaljawab`) have **no `.contentpadding` at all** and use a different
 *     template in which `.content4` is non-empty (947–1,225 ch) — another
 *     reason not to trust `.content4` as a fallback. Only `/m/sitemap.html`
 *     (2,099 ch) and `/m/tentang.html` (1,073 ch) carry `.contentpadding`.
 *   - **`/hubungi.html` — 418 chars.** "Ajukan Soalan!", the contact form.
 *   - **`/` — 720 chars.** The homepage. It has no `.contentpadding`, so
 *     `extractContent` falls through `body` (absent) to `root` and yields the
 *     WHOLE DOCUMENT as its teaser list — it does NOT extract to 0. Only a URL
 *     block excludes it.
 *
 * ## Language: `["ms"]` — MALAY, read and counted, not inferred
 *
 * ⚠️ This host declares **`<html lang="id">`** (Indonesian) on every page. That
 * attribute is WRONG, and it is the reason this was checked rather than assumed:
 * Malay and Indonesian are closely related and a sibling entry
 * (`everystudent-id`, mahasiswakeren.com) covers the Indonesian banner.
 *
 * Read directly 2026-07-29, the prose is unambiguously **Malay**.
 * `/a/709tritunggal.html` ("Bolehkah Anda Terangkan Tritunggal") reads: "Semua
 * objek fizikal mempunyai ketinggian, kelebaran, dan kedalaman yang tertentu …
 * Mereka adalah individu yang **berbeza**" — Malay `fizikal`/`berbeza`, where
 * Indonesian would be `fisik`/`berbeda`. `/a/502perkahwinan.html` ("Adakah
 * Harapan untuk **Perkahwinan** yang Berkekalan?") uses Malay `perkahwinan`,
 * `berkahwin`, `kanak-kanak`, `Amerika Syarikat` and `muka surat` where
 * Indonesian uses `pernikahan`, `menikah`, `anak-anak`, `Amerika Serikat` and
 * `halaman`. Slugs agree: `syurga` not `surga`, `kanser` not `kanker`,
 * `kewujudan` not `keberadaan`, `soaljawab` not `tanyajawab`.
 *
 * Counted over all 52 extracted article bodies across 18 discriminating word
 * pairs: **1,319 Malay forms vs 163 Indonesian forms (8:1)**, with the Malay
 * form ahead on every single pair — `bahawa` 448 / `bahwa` 57, `kerana` 284 /
 * `karena` 26, `mengapa` 112 / `kenapa` 3, `berlaku` 80 / `terjadi` 30,
 * `perkahwinan` 75 / `pernikahan` 1, `cuba` 44 / `coba` 0, `kanser` 21 /
 * `kanker` 0, `pelajar` 17 / `mahasiswa` 0. The residual Indonesian is mostly
 * quoted scripture (the Malay Bible text used shares wording with the
 * Indonesian) plus the one relocalisation gap at `/a/fol.html` noted above. No
 * sampled page was untranslated English.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. A full sequential sweep
 * of all 61 sitemap URLs at ~1 s spacing plus ~20 further probes drew **zero
 * 429s and no throttling**, and responses stayed flat at ~1.4 s, so the sibling
 * default is kept rather than raised.
 */
import type { SourceEntry } from "./types.js";

export const everystudentMs: SourceEntry = {
  key: "everystudent-ms",
  name: "EveryStudent — Malay (PersoalanHidup.com)",
  domain: "www.persoalanhidup.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ms"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ms"],
  defaultCategory: "article",
  rights:
    "© PersoalanHidup.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.persoalanhidup.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.persoalanhidup\\.com/"],
    // The whole article corpus and nothing else: 52 of the 61 sitemap URLs.
    // `[^/]+` rather than a lowercase class — five slugs are mixed-case
    // (/a/109Tuhan.html, /a/202Yesus.html, /a/206Yesus.html,
    // /a/708RohKudus.html, /a/mengenali-Tuhan.html) and a lowercase-only hint
    // would silently drop all five.
    articleHints: ["^https://www\\.persoalanhidup\\.com/a/[^/]+\\.html$"],
    // Live but absent from BOTH the XML sitemap and /m/sitemap.html, so
    // discovery cannot reach it. "Permulaan dengan Tuhan", a real 3,100-char
    // article linked from three others. acquire.ts unions seeds with discovered
    // URLs, which is exactly what this is for. See the header for the
    // Indonesian-bleed caveat on this one page.
    seedPaths: ["/a/fol.html"],
    block: [
      // ── Matches articleHints; `block` is the ONLY thing excluding it.
      // "Siapakah Yesus?" — 28,213 chars, and by its own standfirst "kutipan
      // langsung dari Injil Yohanes … Tanpa tambahan ulasan" (direct quotations
      // from the Gospel of John, no added commentary): 16 chapters of John
      // verbatim. Blocked 2026-07-29 under the estate-wide scripture policy —
      // public-domain Scripture rather than ministry writing, outside what this
      // corpus answers from. Siblings -es, -sq, -et, -mn and -fa block theirs.
      // At 113× the 250-char floor, only a URL block catches it.
      "^https://www\\.persoalanhidup\\.com/a/300siapakah\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 7 section indexes (hubungan, kehidupan, kewujudan, mengenal,
      // sitemap, soaljawab, tentang) — 459-2,022 ch of headline+teaser link
      // lists, so they CLEAR minContentLength and the floor cannot catch them.
      // /m/sitemap.html ("Peta Laman") is the site plan; /m/tentang.html is
      // about + privacy. Five of the seven have no .contentpadding at all.
      "^https://www\\.persoalanhidup\\.com/m/",
      // "Ajukan Soalan!" — the contact form, 418 ch, also above the floor.
      "^https://www\\.persoalanhidup\\.com/hubungi\\.html$",
      // The homepage. It does NOT extract to 0: it has no .contentpadding, so
      // extractContent falls through <body> (absent on this host) to `root` and
      // returns the whole document — 720 ch of teaser list. Only a URL block
      // excludes it.
      "^https://www\\.persoalanhidup\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 with the repo's own
    // extractContent as the sole element on this host that extracts the article
    // (2,472-28,368 ch raw across all 52 pages; 2,317-28,213 ch after stripping,
    // median 9,915, none below the 250 floor).
    // `.content4` is deliberately ABSENT: it matches on 52/52 pages and extracts
    // 0 chars on EVERY one, and extractContent binds the first selector that
    // MATCHES rather than the first that yields text — so listing it would skip
    // every article as `too-thin` on an HTTP 200 (#128). Not a fallback chain:
    // exactly one. `.content4b`, `.entry-content`, `.cb-entry-content`,
    // `.contentleftpadding`, `.article-content`, <article> and <main> are all
    // absent from this host, and even <body> is missing from the parsed tree.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome, all counted on this host 2026-07-29 (see header).
      // Together these remove 9,736 ch across the 52 articles (~187/page).
      "sitelevel_noindex", // custom ELEMENT tag, 104 inst (2/page) on 52/52: "KONGSI HALAMAN INI" + bottom nav — exactly 77 ch every page. Well-formed here; it does NOT break the div tree.
      ".fctable", // the "FEATURE CLOSE" CTA table shell, 52 inst — 0 marginal once .fccell is listed, kept so the emptied shell cannot survive a class rename
      ".fccell", // its cells: "► Bagaimana memulai sebuah hubungan dengan Tuhan" — 78-232 ch/page, 5,732 ch total, the biggest contributor
      ".shareiconsmenupg", // 52 inst, but nested INSIDE the well-formed sitelevel_noindex above, so a 0-char NO-OP in list order. Drift guard only — not claimed to strip.
      ".a2a_kit", // AddToAny share row, 104 inst — 0 chars today (image-only buttons)
      ".hr2", // empty divs drawing the rules bracketing the CTA block, 110 inst — 0 chars
      ".articledivider", // 51 inst — 0 chars
      ".relatedbottom", // 0 instances on this host; documented parity no-op
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 90, // 61 sitemap URLs + 1 pinned seed + headroom
    minContentLength: 250,
  },
};
