/**
 * EveryStudent — Bengali (everybengalistudent.com). The Bengali/Bangla banner of
 * Cru's seeker-facing Q&A ministry: short apologetics and life-issue articles
 * plus first-person testimonies, written for Bengali-speaking students who are
 * not believers. A sibling of `everystudent` (en) and of the non-walled entries
 * `-de` / `-es` / `-pl` / `-ru` / `-sq` / `-ko` and the rest of the estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everybengalistudent.com is its own domain, so it gets
 * its own key, the same way `everystudent-pl` (kazdystudent.pl),
 * `everystudent-sq` (pyetjetejetes.com), `everystudent-fr` (questions2vie.com),
 * `thelife-fr` (laviejenparle.com) and `thelife-zh` (uwota.com) are separate
 * entries rather than extra `languages` on one row.
 *
 * `bn` is a NEW language for this corpus — no other registry entry declares it.
 * Nothing below depends on that, and the stored per-document label still comes
 * from content detection at ingest (invariant 6), never from `languages`.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-29: **~70 plain-HTTP GETs** with a full desktop-Chrome UA —
 * /sitemap.xml, all 57 sitemap URLs (48 articles, 6 `/m/` indexes,
 * /contact.html, /sitemap.html, the homepage), plus /m/intl.html,
 * /a/followup.html and eight probe URLs. **All 57 sitemap URLs returned HTTP/2
 * 200 with real HTML and not one redirect.** Responses are `server: Apache` with
 * no Cloudflare layer and no block-page signature anywhere. So `fetchStrategy`
 * is intentionally OMITTED: plain HTTP is the default and nothing here needs
 * Firecrawl (ADR-0012), unlike everystudent.com / everyarabstudent.com /
 * questions2vie.com which all 403.
 *
 * Discovery is therefore free, making this a **discovery crawl** rather than the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-pl`, `everystudent-sq`.
 *
 * The bare apex **301-redirects to `www`** (measured on /robots.txt and on
 * /a/isthere.html), so `www.everybengalistudent.com` is the canonical host and
 * the one every `<loc>` uses. `domain`, `baseUrl` and every regex below are
 * pinned to `www.` because the filters match the full absolute URL.
 *
 * ## robots.txt — there is none
 *
 * Verified 2026-07-29: `https://www.everybengalistudent.com/robots.txt` returns
 * **HTTP 404** (a 35 KB Bengali soft-404 page titled "দুঃখিত! 404 Error", not a
 * robots file). The apex 301s to `www` first, and the `www` URL is the 404. With
 * no robots.txt there are **no Disallow rules at all**, so **nothing below is
 * blocked on robots grounds** — every exclusion here is a content-quality call.
 * Contrast `everystudent-sq`, whose single Disallow named a live `/a/` article
 * and had to be honoured by hand (the acquire path does not enforce robots.txt).
 *
 * ## Sitemap — 57 entries, all distinct, all live
 *
 * Verified 2026-07-29: `/sitemap.xml` → HTTP 200, **9,373 bytes**,
 * `application/xml`, a single flat `<urlset>` (no `<sitemapindex>`, so no
 * recursion), generated by xml-sitemaps.com, `lastmod` values from 2020. It
 * holds 57 `<loc>` elements and **57 distinct URLs** — no duplicates. This
 * matches the ~57 from prior recon exactly. The breakdown:
 *   - **48 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **6 `/m/<slug>.html`** — section indexes (`about`, `existence`, `forum`,
 *     `knowing`, `questions`, `relationships`). BLOCKED.
 *   - **`/contact.html`** (question form), **`/sitemap.html`** (the HTML site
 *     map) and **`/`** (homepage). All BLOCKED, on measured evidence below.
 * So `articleHints` is exactly `/a/<slug>.html`.
 *
 * **No dead URLs.** A full sweep of all 57 returned **57 × HTTP 200 with zero
 * redirects** — there is no cohort of sitemap entries 301ing to the homepage of
 * the kind `everystudent-ro` shipped 25 of, and no `.php` extension twins of the
 * kind the French entry dropped.
 *
 * ⓘ **Slugs are pure lowercase ASCII English words** (`/a/isthere.html`,
 * `/a/gay-lesbian.html`) even though the content is Bengali — the site
 * transliterates nothing into the URL. Checked, not assumed: all 57 `<loc>`
 * values were scanned for non-ASCII bytes, for `%XX` percent-encoding and for
 * uppercase letters — **zero hits on all three**. So the mixed-case hazard that
 * bit `-es` / `-pl` does not arise here and neither does a Bengali-script slug;
 * `[^/]+` is used anyway so a future uppercase or encoded slug cannot be
 * silently dropped.
 *
 * ## HTML-map cross-check — the XML sitemap is the SUPERSET here
 *
 * These sitemaps are known to be stale, so `/sitemap.html` ("মানচিত্র" — "Map")
 * was fetched and diffed against the XML. Verified 2026-07-29: the HTML map
 * links **47 `/a/` URLs, and all 47 are already in the XML sitemap**. The delta
 * runs the other way — the XML holds one article the HTML map omits,
 * `/a/personally.html`, which is a genuine 7,000-char article that discovery
 * already covers. **No article is missing from discovery, so `seedPaths` is
 * deliberately absent** — there is nothing to pin.
 *
 * As a wider net, every internal `href` on all 57 pages was harvested. Their
 * union adds exactly **five** paths the sitemap lacks, and **not one of them is
 * a live article that belongs in the corpus**:
 *   - **`/a/connecting.html` — HTTP 404.** A dead link in the site's own nav.
 *   - **`/pack.html` — HTTP 404** and **`/personally.html` — HTTP 404.** Dead
 *     links in the per-article call-to-action. See the signup-page note below.
 *   - **`/m/intl.html` — HTTP 200**, the "অন্যান্য ভাষাগুলি" ("Other languages")
 *     page linking out to the sibling language domains. Extracts **17 chars**.
 *     Covered by the `/m/` block.
 *   - **`/a/followup.html` — HTTP 200, and the one real judgement call.** See
 *     below.
 *
 * ## ⚠️ There is NO Gospel-of-John signup page and NO adventure/pack page here
 *
 * The estate-wide rule is to block the localized Gospel-of-John email study
 * (`/john` · `/jean` · `/juan` · `/jan` · `/gjonit`) and the "spiritual
 * adventure" email series (`/aventure` · `/aventura` · `/pack` ·
 * `/abenteuerreise`). On this host **both are absent**: verified 2026-07-29,
 * `/john.html`, `/a/john.html`, `/adventure.html`, `/plan.html`, `/a/bible.html`
 * and `/a/biblejohn.html` **all return HTTP 404**, and `/pack.html` — which every
 * article's CTA still links to — **also returns 404**. The Bengali banner links
 * to signup pages it no longer serves. `/pack.html` and `/personally.html` are
 * blocked anyway so that a future restore of those pages cannot quietly stage a
 * signup form into the corpus.
 *
 * ## ⚠️ SCRIPTURE: `/a/whowas.html` is the complete Gospel of John — BLOCKED
 *
 * Verified 2026-07-29. Titled "যীশু কে ছিলেন?" ("Who was Jesus?"), it extracts
 * **22,236 chars** and its own standfirst says it plainly: "এগুলো হল যোহনলিখিত
 * সুসমাচারের থেকে সরাসরি উদ্ধৃত বাক্যসমূহ। এখানে কোন মন্তব্য দেয়া হয় নি"
 * ("These are direct quotations from the Gospel of John. No commentary is given
 * here"). Walking the extracted text confirms it: it runs chapter by chapter
 * through John — the prologue, John 7, the raising of Lazarus, John 14, the high
 * priestly prayer, the crucifixion, and Mary at the empty tomb.
 *
 * It is blocked under the **estate-wide scripture policy decided 2026-07-29**
 * (set by `everystudent-ar` for its `/bible/**.pdf`, applied by `-es`, `-sq`,
 * `-et`, `-mn` and `-fa`): public-domain Scripture text rather than ministry
 * writing — outside what this corpus answers from.
 *
 * **It is also the only third-party-copyright page on the domain.** A scan of
 * all 48 articles for copyright markers found "টিন্ডলে" (Tyndale), "নিউ লিভিং"
 * (New Living Translation), "কপিরাইট ©" and "সর্বস্বত্ব সংরক্ষিত" ("all rights
 * reserved") on **1 page — this one**, whose footer credits "পবিত্র বাইবেল …
 * নিউ লিভিং ট্রান্সলেশন, কপিরাইট © ১৯৯৬,২০০৪,২০০৭ টিন্ডলে হাউস ফাউন্ডেশন".
 * That is a Bible-society licence on text Cru redistributes by permission, not
 * a licence this corpus holds. Two independent reasons to block, and it matches
 * `articleHints`, so **only a URL block catches it**.
 *
 * ## ⚠️ EXTRACTION: `.contentpadding`, and `.content4` would destroy the source
 *
 * This is the decision that would silently kill the crawl if undone, so it is
 * measured rather than inherited. Every candidate was run through the repo's own
 * parser (`node-html-parser`, exactly as `src/acquisition/extract.ts` uses it)
 * over **all 57 fetched pages** on 2026-07-29 — not grepped, because every one
 * of these tokens is also declared in the page's inline `<style>` block and a
 * grep false-positives on all of them. Char counts are post-`tidy`, first match:
 *
 *   | selector              | pages matched | extracted chars        |
 *   |-----------------------|---------------|------------------------|
 *   | `.contentpadding`     | **50 / 57**   | **354 – 24,007**, 0 empty |
 *   | `.content4`           | 55 / 57       | **0 chars on 50 of them** |
 *   | `.content4b`          | 1 / 57        | 0 chars                |
 *   | `.articletitle`       | 51 / 57       | 8 – 63 (a headline)    |
 *   | `body`                | 6 / 57        | 9,898 – 10,403         |
 *   | `html`                | 57 / 57       | 19,690 – 42,846 (whole page) |
 *   | `.contentleftpadding` | **0 / 57**    | absent                 |
 *   | `.cb-entry-content`   | **0 / 57**    | absent                 |
 *   | `.entry-content`      | **0 / 57**    | absent                 |
 *   | `.article-content`    | **0 / 57**    | absent                 |
 *   | `.articlebody`, `.content`, `article`, `main` | **0 / 57** | absent |
 *
 * **`.content4` matched, 0 chars** — on all 47 kept articles it is an empty
 * spacer div. It matches on 55 of 57 pages and yields text on only the 5 `/m/`
 * indexes we do not want. ⚠️ `contentSelectors` is **NOT a fallback chain**:
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text. Listing `.content4` ahead of `.contentpadding` would
 * bind the spacer on every article, extract "", and skip the entire corpus as
 * `too-thin` on an HTTP 200 — silent, and invisible to unit tests. That is how
 * five of the eight pilot entries first shipped (#128). It is therefore
 * deliberately ABSENT, and so is `.content4b`.
 *
 * **`<body>` is absent from the parsed tree on 51 of 57 pages**, so the
 * `body ?? root` fallback in `extract.ts` lands on the document root and leaks
 * the literal string `<!DOCTYPE html>` into the head of the extraction. That is
 * exactly why the pages below are excluded by URL and not left to
 * `minContentLength`.
 *
 * **Measured with `[".contentpadding"]` plus the strip list, across the 47 kept
 * articles: 2,186 – 23,853 chars, median 7,963, and 0 pages below the 250
 * floor.** Output opens on the section kicker + headline + standfirst + byline
 * and closes on the article's own "পাদটিকা:" ("Footnotes:") scripture-reference
 * line, with no nav, cookie bar, share widget, related links, CTA or footer.
 *
 * ⚠️ `.contentpadding` does **not** discriminate article from chrome — it also
 * binds on `/contact.html`, `/sitemap.html`, `/m/about.html` and `/m/intl.html`.
 * The URL filters are what keep the corpus clean; the selector must not be
 * relied on to do it.
 *
 * ## ⓘ `/a/jesusislam.html` — malformed markup, KEPT on measured evidence
 *
 * One article carries the `-pl` `/a/biblia.html` defect: its source has **76
 * `<a>` openers against 69 closers**, which pops node-html-parser's element
 * stack and collapses the div tree, so `.contentpadding` is null, `.content4` is
 * null and `<body>` is gone. `extractContent` falls through to the document root.
 *
 * **It is kept anyway, unlike the `-pl` case, because the damage was measured
 * and is trivial here.** With the strip list applied the root extraction is
 * **22,768 chars that are the article and almost nothing else**: checked
 * explicitly for the site nav ("প্রথম পাতা"), the language index ("অন্যান্য
 * ভাষাগুলি"), the about text, the contact link, the section menu and the cookie
 * bar — **all six are absent**, because `sitelevel_noindex` (which removes 814
 * chars on this page, the largest of any) still catches the whole chrome block
 * even after the tree collapses. The only contamination left is the leading
 * literal `<!DOCTYPE html>`, ~15 chars in a 22,768-char document. Contrast `-pl`,
 * whose equivalent blob folded in the cookie bar, nav, both menus, sidebar and
 * footer — that one had to go.
 *
 * The article is "যীশু এবং ইসলাম - যীশুর সম্পর্কে মুসলিমদের ৬ টি প্রশ্ন" ("Jesus
 * and Islam — six questions Muslims ask about Jesus"), which is high-value for
 * this specific audience. Trading it away to avoid 15 junk characters is the
 * wrong trade. ⓘ If a reviewer disagrees, blocking it is a one-line addition.
 *
 * ## ⓘ `/a/followup.html` — a real page, BLOCKED, and reversible
 *
 * HTTP 200, **3,335 chars**, genuine post-decision discipleship Q&A ("যদি আমি
 * যীশুকে আমার জীবনে আসার জন্য অনুরোধ করতে চাই, তাহলে কীভাবে আমি জানব যে তিনি
 * সত্যিই আছেন?" — "If I ask Jesus into my life, how do I know he is really
 * there?"). It is **absent from both the XML sitemap and the HTML site map**, so
 * discovery cannot reach it today; it surfaced only in the link harvest. It also
 * has **no `.contentpadding` and no `<body>`**, so it too extracts as a
 * DOCTYPE-leaking root blob. It is blocked rather than pinned as a seed, so that
 * a regenerated sitemap cannot quietly stage a degraded extraction. ⓘ If the
 * orchestrator wants the document, add it to `seedPaths` and drop the block —
 * the content itself is sound.
 *
 * ## Chrome stripped — measured on this host, 2026-07-29
 *
 * Each figure is what that selector removes **on its own** (base strip + it,
 * against base strip alone), across all 48 articles:
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **98 instances (2/page),
 *     removes on 48/48 pages, 70 – 814 chars** (median 70) — the only selector
 *     doing large work. It carries the top nav + cookie bar and the bottom
 *     share + related-links block. Hence the bare tag name with no leading `.`;
 *     the siblings' form is correct rather than a typo.
 *   - **`.shareiconsmenupg` — 48 instances, 25 chars each in isolation, but a
 *     0-char NO-OP in list order.** On THIS host the enclosing
 *     `<sitelevel_noindex>` is **well-formed and already contains it**, so once
 *     that is stripped first this selector matches nothing. Same finding as
 *     `-pl` and 6 of the 11 batch-2 hosts, and the OPPOSITE of `-de`/`-ru`,
 *     where the wrapper is malformed and the share row survives. **No
 *     malformation was measured here**, so it is kept as a cheap drift guard,
 *     not because it strips anything today.
 *   - **`.fctable` (47 instances, 84 – 212 chars in isolation) and `.fccell`
 *     (218 instances, same 84 – 212 chars)** — the "FEATURE CLOSE"
 *     call-to-action table appended to every article. Both are listed so that
 *     stripping only the cells cannot leave the table shell. In list order they
 *     too are ~0-char no-ops (only 1 of 48 pages has a `.fccell` outside
 *     `sitelevel_noindex`, worth 197 chars there) — kept for the same
 *     drift-guard reason.
 *   - **`.hr2` (100 instances) and `.articledivider` (48)** — they bind, but are
 *     empty presentational divs drawing the rules bracketing the CTA block.
 *     **0 chars**, confirmed on 0/48 pages affected.
 *   - **`.relatedbottom` — 0 instances.** Dead config on this host, as on every
 *     host measured so far. Retained only for sibling parity; do not read its
 *     presence here as evidence it binds.
 *   - **`head` — 1 instance across all 48 articles**, and only on
 *     `/a/jesusislam.html`, where the container is the document root. Removes
 *     **54 chars** (that page's duplicated `<title>`) and changes **0** of the
 *     other 47. Safe because `extract.ts` captures the title from `root` BEFORE
 *     the strip loop runs — a future edit that reorders those two steps would
 *     lose every title, so keep them in that order.
 *
 * After the full list, all 48 articles were re-scanned for leftovers: "শেয়ার"
 * (share), the about-page boilerplate, "কুকিজ" (cookies) and the "►" CTA bullet
 * survive on **0/48**.
 *
 * ## ⚠️ minContentLength cannot catch the non-articles
 *
 * Every excluded page was fetched and extracted, and **every one clears the
 * 250-char floor** except `/m/intl.html`. Verified 2026-07-29:
 *   - **`/` — 745 chars.** The homepage does NOT extract to 0: it has no
 *     `.contentpadding`, so the fallback yields its full Bengali teaser list.
 *   - **the 6 `/m/` indexes — 468 – 1,635 chars** of headline + teaser link
 *     lists (`/m/about.html` 1,635, `/m/knowing.html` 973, `/m/questions.html`
 *     810, `/m/relationships.html` 749, `/m/existence.html` 601,
 *     `/m/forum.html` 468). Navigation, not content.
 *   - **`/sitemap.html` — 1,649 chars** of pure link list ("মানচিত্র / প্রথম
 *     পাতা / …"), the Bengali twin of the French `/plan.html` and Polish
 *     `/mapa.html`. It is also the page linking out to the sibling language
 *     domains.
 *   - **`/contact.html` — 309 chars.** "একটি প্রশ্ন করুন!" ("Ask a question!"),
 *     the contact form plus a privacy notice. It clears 250, so the floor could
 *     not have caught it.
 *
 * ## Encoding — checked, because a Bengali-script host makes it load-bearing
 *
 * Verified 2026-07-29. The response header is **`content-type: text/html` with
 * NO charset parameter** — the same gap as `studentinjapan.com` and
 * `everykoreanstudent.com`. The bytes are nonetheless UTF-8 and the HTML says so
 * in-document: every one of the 57 pages carries
 * `<meta http-equiv="content-type" content="text/html; charset=utf-8">` and
 * `<html lang="bn">`. **All 57 fetched files pass a strict UTF-8 decode** with
 * zero errors, and the Bengali read back clean — no mojibake, no replacement
 * characters, conjuncts and vowel signs intact (e.g. "ঈশ্বর", "যীশু খ্রীষ্ট",
 * "প্রার্থনা"). Nothing here needs a charset override.
 *
 * ## Language: `["bn"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Bengali (Bangla script) prose, not untranslated English.
 * `/a/isthere.html` is "ঈশ্বর কি আছেন?" ("Is there a God?") and offers "ঈশ্বর যে
 * সত্যিই আছেন তা বিশ্বাস করার ছয়টি মৌলিক কারণ" ("six basic reasons to believe
 * God really exists"); `/a/prayers.html` is "ঈশ্বর কি আমাদের প্রার্থনার উত্তর
 * দেন?" ("Does God answer our prayers?") and narrates "যখন আমি একজন নাস্তিক
 * ছিলাম" ("when I was an atheist"); `/a/blues.html` is a testimony of "আবেগজনিত
 * কষ্ট, আত্নহত্যার চিন্তা" ("emotional pain, suicidal thoughts"). Bylines are
 * Bengali too ("মেরিলিয়ান এডামসন এর লেখা" — "written by Marilyn Adamson").
 * Scripture citations use Bengali book names and Bengali digits throughout —
 * যোহন (John), মথি (Matthew), রোমীয় (Romans), গীতসংহিতা (Psalms), যিশাইয়
 * (Isaiah), প্রকাশিত বাক্য (Revelation), e.g. "১ম যোহন ৫:১৪".
 *
 * Quantified as a cross-check: the Bengali-script share of the extracted text is
 * **93.6 % – 100 % on all 48 articles** (lowest: `/a/historical.html` 93.6 %).
 * The residual Latin is bibliographic — English author names in footnotes — and
 * even those are often transliterated ("দ্যা ল্যাংগুয়েজ অব গড", "ফ্রি প্রেস,
 * নিউইয়র্ক"). **No page showed the cru.org `/mx/es/` failure mode of a localized
 * URL serving an English body.** No language-detection library was used; the
 * stored per-document label still comes from content detection at ingest
 * (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~70 sequential
 * plain-HTTP requests drew **zero 429s and no throttling**, so the sibling
 * default is kept rather than raised.
 *
 * **Expected yield: 47 documents** — 48 sitemap articles minus the blocked
 * Gospel-of-John page.
 */
import type { SourceEntry } from "./types.js";

export const everystudentBn: SourceEntry = {
  key: "everystudent-bn",
  name: "EveryStudent — Bengali (EveryBengaliStudent.com)",
  domain: "www.everybengalistudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["bn"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:bn"],
  defaultCategory: "article",
  rights:
    "© EveryBengaliStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everybengalistudent.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare). See header.
    sitemaps: ["/sitemap.xml"],
    // The one article both sitemaps omit. `acquire.ts` unions seeds with
    // discovered URLs, so this is the only way to reach it. Genuine 3,335-char
    // post-decision Q&A; see the note in `block`. Orchestrator call, 2026-07-29.
    seedPaths: ["/a/followup.html"],
    allow: ["^https://www\\.everybengalistudent\\.com/"],
    // The whole article corpus: 48 of the 57 sitemap URLs. `[^/]+` rather than a
    // lowercase class — slugs today are pure lowercase ASCII (verified: zero
    // non-ASCII bytes, zero %XX escapes and zero uppercase across all 57 <loc>
    // values), but a future mixed-case slug must not be silently dropped the way
    // -es and -pl nearly were.
    articleHints: ["^https://www\\.everybengalistudent\\.com/a/[^/]+\\.html$"],
    block: [
      // ── These three sit under /a/ and MATCH articleHints; `block` is the ONLY
      // thing excluding them.
      //
      // The COMPLETE Gospel of John, 22,236 chars measured 2026-07-29. Its own
      // standfirst says "direct quotations from the Gospel of John, no
      // commentary". Blocked under the estate-wide scripture policy set by
      // everystudent-ar and applied by -es/-sq/-et/-mn/-fa: verbatim Scripture
      // rather than ministry writing, outside what this corpus answers from.
      // It is ALSO the only page on the domain carrying a third-party licence —
      // "নিউ লিভিং ট্রান্সলেশন, কপিরাইট © ১৯৯৬,২০০৪,২০০৭ টিন্ডলে হাউস ফাউন্ডেশন"
      // (New Living Translation, © Tyndale House Foundation).
      "^https://www\\.everybengalistudent\\.com/a/whowas\\.html$",
      // NOTE `/a/followup.html` was blocked here when this entry was first
      // written, then moved to `seedPaths` by the orchestrator on 2026-07-29.
      // It is a genuine 3,335-char post-decision Q&A that both sitemaps omit.
      // The original block cited its DOCTYPE-leaking root extraction — but this
      // entry KEEPS `/a/jesusislam.html`, which has exactly the same defect, so
      // the two calls contradicted each other. The `"html"` fallback in
      // contentSelectors plus `head` in the strip list fixes both.
      // A dead link in the site's own navigation: HTTP 404, verified 2026-07-29.
      // Not in the sitemap today; blocked so a regenerated sitemap cannot admit
      // a soft-404 page that would extract well over the 250 floor.
      "^https://www\\.everybengalistudent\\.com/a/connecting\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 6 section indexes (about, existence, forum, knowing, questions,
      // relationships) plus /m/intl.html, the "other languages" page that links
      // out to the sibling domains. 17-1,635 ch of headline+teaser link list, so
      // all but one CLEAR the 250 floor — the floor cannot catch them.
      "^https://www\\.everybengalistudent\\.com/m/",
      // The HTML site map: 1,649 ch of pure link list ("মানচিত্র"). Bengali twin
      // of the French /plan.html and the Polish /mapa.html.
      "^https://www\\.everybengalistudent\\.com/sitemap\\.html$",
      // The question form ("একটি প্রশ্ন করুন!") + privacy notice: 309 ch, which
      // clears minContentLength, so only a URL block excludes it.
      "^https://www\\.everybengalistudent\\.com/contact\\.html$",
      // Both HTTP 404 today (verified 2026-07-29) but still linked from every
      // article's call-to-action: /pack.html is the estate's "spiritual
      // adventure" email series and /personally.html a root-level signup twin.
      // Blocked so restoring them cannot quietly stage a signup form.
      "^https://www\\.everybengalistudent\\.com/(pack|personally)\\.html$",
      // The homepage. It does NOT extract to 0 — it has no .contentpadding, so
      // the fallback returns its 745-char Bengali teaser list.
      "^https://www\\.everybengalistudent\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article (2,186-23,853 ch across the 47 kept pages,
    // median 7,963, none below the floor). `.content4` is deliberately ABSENT:
    // it matches on 55/57 pages and extracts 0 chars on all 50 that are not /m/
    // indexes, and because extractContent scopes to the first selector that
    // MATCHES rather than the first that yields text, listing it would make
    // every article skip as `too-thin` on an HTTP 200. `.content4b` (1/57, 0 ch),
    // `.contentleftpadding`, `.cb-entry-content`, `.entry-content` and
    // `.article-content` are all absent or empty on this host.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Binds on exactly 1 of 48 articles — /a/jesusislam.html, whose collapsed
      // markup makes the container the document root — and removes that page's
      // duplicated <title> (54 ch). extract.ts reads the title from `root`
      // BEFORE stripping; keep those two steps in that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-29 (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 98 inst (2/page): nav + cookie bar, share + related links — 70-814 ch on 48/48
      ".shareiconsmenupg", // 48 inst, 25 ch alone, but 0-char NO-OP in list order: sitelevel_noindex is WELL-FORMED here and already contains it. Kept as a drift guard.
      ".fctable", // the "FEATURE CLOSE" CTA table shell — 47 inst, 84-212 ch alone
      ".fccell", // its cells — 218 inst, same block; both listed so stripping only the cells cannot leave the shell
      ".hr2", // 100 inst, 0 chars: empty divs drawing the rules bracketing the CTA
      ".articledivider", // 48 inst, 0 chars
      ".relatedbottom", // 0 instances on this host; kept for sibling parity only
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 90, // 57 sitemap URLs (48 articles, 47 kept) + headroom
    minContentLength: 250,
  },
};
