/**
 * EveryStudent — Swahili (lipotumaini.com, "LipoTumaini.com" / "There is Hope").
 * The Swahili banner of Cru's seeker-facing Q&A ministry: short apologetics and
 * life-issue articles written for Swahili-speaking students who are not
 * believers. A sibling of `everystudent` (en), `everystudent-am`,
 * `everystudent-pl`, `everystudent-sq` and the rest of the estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). lipotumaini.com is its own domain, so it gets its own
 * key, the same way `everystudent-am` (habeshastudent.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * **This is one of the smallest hosts on the estate: 13 articles.** Every
 * per-page call below therefore moves a larger share of the corpus than it would
 * on a 78-article sibling — a single wrongly-blocked page costs ~8% of the source.
 *
 * ## Canonical host — checked BOTH ways
 *
 * Verified 2026-07-30: `http://lipotumaini.com/` and `https://lipotumaini.com/`
 * both **301 to `https://www.lipotumaini.com/`**, which answers 200. So the
 * `www.` host is canonical (the usual estate direction, NOT the reversed
 * `everystudent.sk` case), and `domain`, `baseUrl` and every regex below are
 * pinned to `www.` — the same form every sitemap `<loc>` uses.
 *
 * ## NOT walled — plain HTTP, bare Apache
 *
 * Verified 2026-07-30: the homepage, `/sitemap.xml`, `/sitemap.html`, all four
 * `/m/` indexes, `/kuhusu.html`, `/wasiliana.html` and **all 14 live `/a/`
 * pages** were fetched with a plain `curl` carrying a full desktop-Chrome UA.
 * **Every one returned HTTP/2 200 with real HTML.** Responses are `server:
 * Apache` with **no Cloudflare layer at all** — no `cf-ray`, and no block-page
 * signature anywhere. So `fetchStrategy` is intentionally OMITTED: plain HTTP is
 * the default and nothing here needs Firecrawl (ADR-0012). Discovery is free,
 * which is why this is a **discovery crawl** rather than the hand-listed seed set
 * the three walled banners were forced into. Precedent: `thelife-fr`,
 * `everystudent-am`, `everystudent-sq`.
 *
 * ## robots.txt — there ISN'T one
 *
 * Verified 2026-07-30: `https://www.lipotumaini.com/robots.txt` returns **HTTP
 * 404**, `content-type: text/html`, 32,092 bytes — it is the site's own styled
 * HTML 404 page, not a robots file. There is no robots.txt on this host, so
 * **nothing is disallowed** and no URL below is blocked on robots grounds; every
 * exclusion here is a content-quality call. (Contrast `everystudent-sq`, whose
 * robots.txt names an `/a/` path that had to be honoured by hand because the
 * acquire path does not enforce robots.txt.)
 *
 * ## Sitemap — 21 entries, matching recon exactly, but NOT the whole site
 *
 * Verified 2026-07-30: `https://www.lipotumaini.com/sitemap.xml` → HTTP 200,
 * **3,551 bytes**, `application/xml`, a single flat `<urlset>` (**0
 * `<sitemapindex>` elements**, so no recursion) generated by xml-sitemaps.com.
 * It holds **21 `<loc>` elements, all distinct** — matching the "~21" from prior
 * recon exactly, with **no delta in either direction**.
 *
 * ⚠️ The `everystudent.sk` fossil trap was checked for and did **not** apply:
 * `/sitemap_index.xml` returns **404** (the same HTML 404 page), so
 * `/sitemap.xml` is the only sitemap and is the live one. Its every `<lastmod>`
 * is the single stamp **2022-04-04T19:54:55+00:00**, i.e. it is a 2022
 * generation — old, but confirmed complete against the site's own HTML map below.
 *
 * ⚠️ **Scheme: every `<loc>` is `https://`** (0 of 21 are `http://`), so the
 * filters below pin `^https://`. This host is NOT the `everystudent.gr` case.
 * ⓘ The `<urlset>` declares its xmlns as `https://www.sitemaps.org/…` rather
 * than the conventional `http://…`. Harmless here: `discover.ts` parses with
 * node-html-parser and selects `url loc` by tag name, ignoring namespaces —
 * verified by running that exact query over the fetched bytes (21 locs found).
 *
 * The 21 break down as:
 *   - **13 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **4 `/m/<slug>.html`** — section indexes (`kuwepo`, `maisha`,
 *     `kuunganishwa`, `intl`). BLOCKED, below.
 *   - **`/sitemap.html`** (the HTML site plan), **`/kuhusu.html`** (about),
 *     **`/wasiliana.html`** (contact) and **`/`** (homepage). BLOCKED, below.
 *
 * **No sitemap URL redirects anywhere.** Verified 2026-07-30 by requesting all
 * 21 without following redirects: **21/21 returned HTTP 200 with an empty
 * `redirect_url`**. There is no dead-URL cohort of the kind a sibling shipped 25
 * of, and nothing needs blocking for redirecting to the homepage.
 *
 * ## HTML-map cross-check — and the one page in NEITHER map
 *
 * These sitemaps are known to run stale, so `/sitemap.html` ("Ramani ya Tovuti")
 * was fetched and diffed. Verified 2026-07-30: it links **13 `/a/` URLs, exactly
 * the same 13 the XML sitemap lists** — 0 in the HTML map the XML lacks, 0 the
 * other way. On a 13-article host that agreement is worth having measured.
 *
 * Then, as a wider net, every internal `href` on all 13 articles, all 4 `/m/`
 * indexes, `/sitemap.html`, `/kuhusu.html`, `/wasiliana.html` and the homepage
 * was harvested. The union adds exactly **two** URLs that appear in neither map:
 *   - **`/a/fol.html` — live (HTTP 200), and BLOCKED on content grounds.** See
 *     the block list; it is this host's post-decision hand-off page.
 *   - **`/john.html` — does not exist: HTTP 404.**
 * No live article is missing from discovery, so **`seedPaths` is deliberately
 * absent**: there is nothing to pin.
 *
 * ## The Gospel-of-John and "adventure/pack" pages — a MEASURED absence
 *
 * The estate rule is to block the localized Gospel-of-John email-study signup
 * and the "spiritual adventure / starter pack" email series, because both clear
 * `minContentLength` and only a URL block catches them. **On this host neither
 * exists.** Verified 2026-07-30 by direct request: `/john.html`, `/pack.html`,
 * `/adventure.html`, `/4laws.html`, `/a/4laws.html` and `/plan.html` **all
 * return HTTP 404**. This is a measured absence, not an omission — no block is
 * written for a URL that is not there, and `articleHints` confines discovery to
 * `/a/` anyway, so a root-level signup page could not be admitted even if one
 * were added later.
 *
 * ## No Scripture on this host — and how the Bible article was told apart
 *
 * Checked under the estate-wide full-Scripture policy (2026-07-29). **No page
 * here carries Bible text**: the largest extraction on the whole domain is
 * **23,390 chars**, nowhere near the 98k–100k band the sibling scripture pages
 * sit in, and there is no chapter index or Bible-search widget anywhere.
 *
 * `/a/biblia.html` is the page that had to be judged, and it is **KEPT**. Read
 * on 2026-07-30, it is titled "Kwa Nini Unaweza Kuamini Biblia" ("Why You Can
 * Believe the Bible") and is an apologetics essay *about* the Bible — its
 * authorship ("Biblia iliandikwa kwa muda wa miaka 1500 na waandishi 40"), its
 * archaeological corroboration (the five porticoes at the Pool of Bethesda), and
 * why the reader might trust it. That is ministry writing, not Scripture: the
 * test applied was whether the body is *quoted Bible text* or *argument about*
 * it, and this is continuous prose making a case, with only short cited verses.
 *
 * The only copyright on these pages is the site's **own** — `© LipoTumaini.com`,
 * plus an author credit for `Dkt. Richard Purnell`. **No third-party
 * Bible-society copyright** (no Eesti Piibliselts, no Tyndale House) appears
 * anywhere, so the `rights` line below misattributes nothing.
 *
 * ## ⚠️ EXTRACTION — every candidate measured on THIS host
 *
 * This is the decision that would silently destroy the source if undone, so it
 * was measured rather than inherited. Every candidate below was run through the
 * repo's own parser (node-html-parser, exactly as `src/acquisition/extract.ts`
 * uses it) over **all 14 live `/a/` pages** on 2026-07-30 — not grepped, because
 * this host declares `.content4`, `.contentpadding`, `.shareiconsmenupg` and the
 * rest inside its inline `<style>` block, so a grep false-positives on all of
 * them. Raw (pre-strip) character counts:
 *
 *   - **`.contentpadding` — matches on 11/14 pages, and extracts 3,452–23,512
 *     chars. ZERO matched-but-empty pages.** The whole article: section kicker,
 *     title, subhead, body and footnotes. **Shipped FIRST.**
 *   - **`.content4` — matches on 11/14 pages and extracts 0 chars on every one
 *     of them.** An empty spacer div. Listing it ahead of `.contentpadding`
 *     would bind the spacer and skip all 13 articles as `too-thin` on an HTTP
 *     200 — the batch-1 failure (#128). It must never appear here.
 *   - **`.content4b` — matches on 3/14 pages and extracts 0 chars on all 3.**
 *     Worse than useless: the 3 pages it matches are exactly the 3 where
 *     `.contentpadding` misses, so listing it as a "fallback" would convert the
 *     `html` recovery below into three silent `too-thin` skips.
 *   - **`.articletitle` — matches 13/14, 14–42 chars.** A title, not a body.
 *   - **`#content4`** (the ID form some siblings need), **`.content4c`,
 *     `.cb-entry-content`, `.entry-content`, `.post-content`,
 *     `.contentleftpadding`, `.article-content`, `.content` — 0 matches each**,
 *     absent from this host.
 *   - **`<body>` — 0 matches on all 14 pages.** This host emits no `<body>` the
 *     parser recognises, so `extractContent`'s implicit fallback is the document
 *     ROOT, i.e. the whole page including the literal `<!DOCTYPE html>` text
 *     node. That is precisely why the explicit `"html"` entry exists.
 *   - **`html` — matches 14/14, 20,058–42,860 chars.** Never empty.
 *
 * ### Why `"html"` is appended, and why it is safe
 *
 * `.contentpadding` has **no matched-but-empty page on this host**, so it can
 * never shadow the fallback — the fallback fires only where the primary truly
 * misses. `"html"` is last, so it can shadow nothing itself, and it beats the
 * implicit `?? root` because `<html>` is a real element carrying no doctype text
 * node.
 *
 * ### ⚠️ The 3 misses are BROKEN MARKUP on real articles — not junk pages
 *
 * `.contentpadding` misses on `/a/kumjua.html`, `/a/utatu-mtakatifu.html` and
 * `/a/fol.html`. All three **do** contain `class="contentpadding"` in their raw
 * bytes; the element does not survive parsing because each page has one
 * unbalanced tag that pops the open-element stack and collapses the div tree:
 *   - `/a/kumjua.html` — **23 `<span>` openers against 22 closers**;
 *   - `/a/utatu-mtakatifu.html` — **16 `<sup>` openers against 15 closers**;
 *   - `/a/fol.html` — an `<h1>` opened and closed by `</h2>`.
 * Two of those are substantial, genuine articles — "Jinsi ya Kumjua Mungu
 * Binafsi" (How to Know God Personally) and "Je, Unaweza Kufafanua Utatu
 * Mtakatifu?" (Can You Explain the Trinity?) — and the `"html"` fallback
 * recovers them cleanly at **6,436 and 5,194 chars post-strip**. They are
 * therefore NOT blocked; batch 3 nearly lost three articles to exactly this
 * reasoning. `/a/fol.html` is blocked, but on content grounds, not markup ones.
 *
 * ⚠️ `.contentpadding` does **not** discriminate article from chrome — it also
 * binds on `/kuhusu.html`, `/wasiliana.html`, `/sitemap.html` and `/m/intl.html`.
 * And the homepage and 3 of the 4 `/m/` indexes have no `.contentpadding` at all,
 * so they fall to `html` and yield their full teaser text (345–711 chars) rather
 * than nothing. The URL filters are what keep the corpus clean; the selector
 * list must never be relied on to do it.
 *
 * **Final measured yield over the 13 kept articles: 3,330 – 23,390 chars,
 * median 12,145, and 0 pages below the 250 floor.**
 *
 * ## Chrome stripped — marginal chars, measured in list order
 *
 * Totals are across all 14 pages, each selector measured as the characters it
 * removes *after* the ones before it have already run:
 *   - **`head` — 88 marginal.** 0 chars whenever `.contentpadding` binds (it is
 *     outside the container); fires only on the `html` fallback, where it drops
 *     the duplicated `<title>`. Safe because extract.ts reads the title from
 *     `root` at line 43, BEFORE the strip loop at line 52 — keep that order.
 *   - **`script` 27,201 and `style` 28,880.** Large only because the 3
 *     `html`-fallback pages pull in the whole document; 0 on the other 11.
 *   - **`sitelevel_noindex` — 2,774 marginal, 2 instances on 14/14 pages.** A
 *     custom ELEMENT tag, not a class, hence no leading dot. The largest
 *     site-specific contributor: the share row and the related-links/footer
 *     block. ⓘ It is **well-formed on this host** — measured, not assumed — so
 *     it genuinely encloses what it should.
 *   - **`.fccell` — 1,612 marginal, 13/14 pages.** The "FEATURE CLOSE"
 *     call-to-action cells appended to every article.
 *   - **`.fctable` — 0 marginal, but 1,453 chars when measured on its own.** It
 *     is the shell around those cells; `.fccell` (listed first) already empties
 *     it. Kept because dropping `.fccell` alone would leave the table.
 *   - **`.shareiconsmenupg` — 0 marginal, 260 chars on its own, 13/14 pages.**
 *     A **no-op in list order** precisely because `sitelevel_noindex` is
 *     well-formed here and already contains it. Kept as a drift guard only; do
 *     NOT read its presence as evidence it strips anything today, and do not
 *     repeat the `-de`/`-ru` "required, the markup is malformed" note — that was
 *     measured to be FALSE on this host.
 *   - **`.a2a_kit` — 0 chars, 13/14 pages.** The AddToAny share row binds but is
 *     image-only, so `structuredText` reads nothing. Stripped anyway so a future
 *     markup change adding text labels cannot leak into every article.
 *   - **`.hr2` (13/14) and `.articledivider` (13/14) — 0 chars both.** Empty
 *     presentational divs drawing the rules that bracket the CTA. They bind, so
 *     they are not dead config; they simply carry no text.
 *   - **`.relatedbottom` — 0 instances on this host. OMITTED**, not carried as a
 *     parity no-op: it cannot bind, so it can only mislead a later reader.
 *   - `noscript`, `svg`, `nav`, `header`, `footer` — 0 each; this host uses none
 *     of those elements. Retained as the estate baseline for the `html` path.
 *   - `form` — 9 chars, the site search box, reachable only on the `html` path.
 *
 * ## Language: `["sw"]` — read, not inferred
 *
 * Verified 2026-07-30 by reading the extracted text myself. The pages serve
 * genuine Swahili prose, not untranslated English. `/a/kumjua.html` states the
 * first principle as "Mungu anakupenda na anakupa mpango mzuri sana wa maisha
 * yako" ("God loves you and offers you a wonderful plan for your life") and the
 * second as "Sisi sote tunatenda dhambi na dhambi zetu zimetutenganisha na
 * Mungu"; `/a/fol.html` opens "Ongera kwa uamuzi wako wa kumuomba Yesu Kristo
 * aje kwenye maisha yako"; titles include "Je kuna Mungu?", "Kwa Nini Yesu
 * Alikufa?", "Mungu yuko wapi katika nyakati ngumu?" and "Je, Mungu Hujibu Sala
 * Zetu?".
 *
 * That is Swahili on the grammar, not merely on the vocabulary: the `ni`
 * copula ("Matokeo ya dhambi maishani mwetu **ni** kifo"), the negative `si`,
 * the `ki-`/`vi-` noun-class pair ("kila **ki**tu" / "**vi**tu vingi"), the
 * `m-`/`wa-` class ("**M**wanawe" / "**wa**andishi 40"), and the verbal
 * infinitive `ku-` running through every title ("**Ku**anza", "**Ku**mjua",
 * "**Ku**unganishwa"). Swahili is Latin-script, so the mojibake risk that
 * dominates the Cyrillic and Indic siblings does not arise here; the pages
 * declare `charset=utf-8` and render clean. No page showed the cru.org `/mx/es/`
 * failure mode of a localized URL serving an English body.
 *
 * ⓘ `<html lang="sw">` is declared and happens to be correct, but the call above
 * rests on the prose, not the attribute — `persoalanhidup.com` declares
 * `lang="id"` and serves Malay. The stored per-document language label still
 * comes from content detection at ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. We pay this host's bandwidth
 * directly rather than proxying through Firecrawl, so it is real; ~50 sequential
 * plain-HTTP requests drew zero 429s and no throttling, and at 13 pages the whole
 * crawl is under 30 seconds of wall clock. Nothing argued for the 2000 a slow PHP
 * sibling needed.
 *
 * **Expected yield: 13 documents** — the 13 `/a/` sitemap articles, with
 * `/a/fol.html` (not in the sitemap) blocked.
 */
import type { SourceEntry } from "./types.js";

export const everystudentSw: SourceEntry = {
  key: "everystudent-sw",
  name: "EveryStudent — Swahili (LipoTumaini.com)",
  domain: "www.lipotumaini.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["sw"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:sw"],
  defaultCategory: "article",
  rights:
    "© LipoTumaini.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    // Apex 301s to www (measured both schemes, 2026-07-30); www serves 200.
    baseUrl: "https://www.lipotumaini.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, zero Cloudflare markers). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.lipotumaini\\.com/"],
    // The whole article corpus: 13 of the 21 sitemap URLs. `^https://` because
    // every <loc> is https (0 of 21 are http). `[^/]+` rather than a lowercase
    // class — this host's slugs are all lowercase ASCII today, but a
    // `[a-z0-9-]+` hint would silently drop a future mixed-case or
    // percent-encoded slug, as /a/pomoshch-ot-Boga.html elsewhere on the estate
    // already proves.
    articleHints: ["^https://www\\.lipotumaini\\.com/a/[^/]+\\.html$"],
    block: [
      // ── This one MATCHES articleHints; `block` is the ONLY thing excluding it.
      // "Kuanza na Mungu" ("Starting with God") — the post-decision follow-up
      // page, 678 ch, whose entire purpose is to hand the reader off to the
      // off-domain KutembeaNaYesu.com ("Tumetengeza tovuti nyingine … Tafadhali
      // nenda hapo sasa"). Same slug, same shape and same call as the Amharic
      // sibling's blocked /a/fol.html; this host's twin of the French
      // /aventure.html and Arabic /pack.html, of which it has neither. It is in
      // NEITHER the XML nor the HTML sitemap, so discovery cannot reach it
      // today — the block makes that safe rather than lucky. NB its markup is
      // also broken, but that is NOT why it is blocked: the `html` fallback
      // extracts it fine.
      "^https://www\\.lipotumaini\\.com/a/fol\\.html$",
      // ── Below here articleHints already excludes them; these record WHY, so a
      // later widening of the hints cannot silently readmit them.
      // The 4 section indexes (kuwepo, maisha, kuunganishwa, intl). Three have
      // no .contentpadding, so they fall to the `html` container and yield
      // 345-481 ch of headline+teaser links — well clear of the 250 floor.
      // /m/intl.html is the page linking out to the sibling language domains and
      // is the ONE excluded page the floor would have caught (14 ch); it is
      // blocked anyway so the exclusion does not depend on a threshold.
      "^https://www\\.lipotumaini\\.com/m/",
      // "Ramani ya Tovuti" — the HTML site plan, 526 ch of pure link list.
      // Swahili twin of the French /plan.html and the Polish /mapa.html.
      "^https://www\\.lipotumaini\\.com/sitemap\\.html$",
      // "Kuhusu tovuti hii" (about, 883 ch) and "Uliza Swali!" (the contact
      // form, 307 ch). BOTH clear minContentLength, so the floor cannot catch
      // either — unlike the Russian sibling's 85-char /vopros.html.
      "^https://www\\.lipotumaini\\.com/(kuhusu|wasiliana)\\.html$",
      // The homepage. It has no .contentpadding, so it does NOT extract to 0 —
      // the `html` container returns its full 711-char teaser list. Only a URL
      // block excludes it; minContentLength never could.
      "^https://www\\.lipotumaini\\.com/?$",
    ],
    // Measured 2026-07-30 across all 14 live /a/ pages. `.contentpadding` is the
    // sole element that holds the article (11/14 pages, 3,452-23,512 ch, and
    // ZERO matched-but-empty). `.content4` is deliberately ABSENT: it matches
    // 11/14 and extracts 0 chars on every one, and extractContent binds the
    // first selector that MATCHES rather than the first that yields text, so
    // listing it would skip all 13 articles as `too-thin` on an HTTP 200.
    // `.content4b` is absent for the same reason — it matches only the 3 pages
    // where `.contentpadding` misses, and extracts 0 chars on all 3.
    // "html" is a deliberate LAST entry: because `.contentpadding` never matches
    // empty here, it fires only on those 3 broken-markup pages, where it
    // recovers two genuine articles at 6,436 and 5,194 ch. It cannot shadow
    // anything (nothing follows it) and beats the implicit `?? root` because
    // <html> carries no literal "<!DOCTYPE html>" text node.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      // 0 chars whenever `.contentpadding` binds (it is not inside the div);
      // fires only on the `html` fallback, where it drops the duplicated
      // <title>. Safe because extract.ts reads the title from `root` BEFORE
      // this strip loop runs (extract.ts:43 vs :52).
      "head",
      "script", // 27,201 ch, all of it on the 3 `html`-fallback pages
      "style", // 28,880 ch, likewise
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form", // 9 ch — the site search box, reachable only via the `html` path
      // Site-specific chrome — every count measured on this host across all 14
      // pages (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 inst on 14/14: share row + related/footer — 2,774 ch
      ".fccell", // "FEATURE CLOSE" CTA cells, 13/14 pages — 1,612 ch
      ".fctable", // the shell around them: 0 MARGINAL (.fccell empties it first)
      // but 1,453 ch on its own, so it is what stops the table surviving alone.
      ".shareiconsmenupg", // 0 MARGINAL — sitelevel_noindex is well-formed on THIS
      // host and already contains it (260 ch on its own). A drift guard, NOT
      // evidence it strips anything today.
      ".a2a_kit", // AddToAny share row, 13/14 pages — 0 ch (image-only buttons)
      ".hr2", // empty divs drawing the rules bracketing the CTA — 0 ch
      ".articledivider", // 0 ch
      // `.relatedbottom` is deliberately NOT listed: 0 instances on this host.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 x 429 observed
    maxPages: 60, // 21 sitemap URLs (13 kept after filtering) + headroom
    minContentLength: 250,
  },
};
