/**
 * EveryStudent — German (duentscheidest.com, "Du entscheidest" / "You decide").
 * The German banner of Cru's seeker-facing Q&A ministry: short apologetics and
 * life-issue articles written for German-speaking students who are not
 * believers. A sibling of `everystudent` (en), `everystudent-ar`,
 * `everystudent-fr`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). duentscheidest.com is its own domain, so it gets its
 * own key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP, unlike all three sibling EveryStudent banners
 *
 * Verified 2026-07-28: 11 pages fetched with a plain browser UA (robots.txt,
 * /sitemap.xml, 6 articles, an /audio/ page, /p_andy.html, /abenteuerreise.html,
 * /menu/Gott.html) — **every one returned HTTP 200 with real content**, and none
 * carried a Cloudflare block-page signature (no `Attention Required`, no
 * `Just a moment`). The `server: cloudflare` header is present, but this host
 * serves rather than challenges. So `fetchStrategy` is intentionally OMITTED:
 * plain HTTP is the default and nothing here needs Firecrawl (ADR-0012). This
 * is the notable difference from everystudent.com / everyarabstudent.com /
 * questions2vie.com, all three of which 403 to plain HTTP.
 *
 * Consequence: discovery is free here, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`.
 *
 * ## robots.txt
 *
 * Verified 2026-07-28: the entire file is `User-agent: * Allow: /` (HTTP 200,
 * Last-Modified 2018-07-20). Identical to everyarabstudent.com and
 * questions2vie.com, and UNLIKE everystudent.com, which carries a real disallow
 * list. **Nothing on this domain is disallowed**, so no URL is dropped on robots
 * grounds — every exclusion below is a content-quality call, not a policy one.
 *
 * ## Sitemap — 72 entries, 70 distinct
 *
 * Verified 2026-07-28: `https://www.duentscheidest.com/sitemap.xml` → HTTP 200,
 * 6,054 bytes, generated by xml-sitemaps.com. It holds 72 `<loc>` elements but
 * only **70 distinct URLs** — `/artikel/Gottes-Hilfe-video.html` and
 * `/artikel/Gott-personlich-kennenlernen-video.html` are each listed twice.
 * (This matches the ~72 from prior recon; the duplication is the discrepancy.)
 *
 * The bare host 301-redirects to `www`, so `www.duentscheidest.com` is the
 * canonical host and the one every `<loc>` uses.
 *
 * The 70 distinct URLs break down as:
 *   - **45 `/artikel/<slug>.html`** — the article corpus. This is the keep set.
 *   - **12 `/audio/*`** — 11 audio pages + the `/audio/` index. BLOCKED, below.
 *   - **9 `/menu/<slug>.html`** — section indexes. BLOCKED, below.
 *   - **4 root-level** — `/`, `/abenteuerreise.html`, `/p_andy.html`,
 *     `/p_hans.html`. All BLOCKED, below.
 *
 * So `articleHints` is exactly `/artikel/<slug>.html`, and the expected yield is
 * 45 documents.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes all of these (nothing outside
 * `/artikel/` can match). The `block` list is deliberately redundant: it records
 * *why* each group is out, so a later widening of the hints cannot silently
 * readmit them. Same defensive posture as `thelife-fr`.
 *
 *   - **`/audio/*` — near-duplicates of the `/artikel/` twins.** Verified
 *     2026-07-28: all 11 audio slugs have an exact `/artikel/` slug twin
 *     (connectmitGott, dreieinigkeit, echtesleben, gebete, gibtes, glaube,
 *     himmel, hochsten, leid, suche, universum). These are audio-player pages
 *     that reprint the whole article as a "Video-Transkription":
 *     `/audio/gibtes.html` extracts 18,944 chars against `/artikel/gibtes.html`'s
 *     19,120, sharing **73.3% of its 12-word shingles** (Jaccard 56.9%) — the
 *     wording is reflowed for speech, which is the only reason it is not higher.
 *     The document-level content hash cannot collapse duplicates sitting at
 *     different URLs, so ingesting both would double-count 11 articles. This is
 *     the same call the English entry made on its podcast/article overlap.
 *   - **`/menu/*` — navigation, not content.** Verified 2026-07-28:
 *     `/menu/Gott.html` extracts 732 chars and is entirely headline + teaser
 *     pairs linking to `/artikel/` pages. The 9 include `/menu/sitemap.html`,
 *     `/menu/impressum.html` and `/menu/uber.html` (site plan, legal imprint,
 *     about) — the German twins of the `/plan.html` + `/contact1.html` chrome the
 *     French entry drops and the `/menus/*` indexes the English entry drops.
 *   - **`/p_andy.html`, `/p_hans.html` — contact stubs.** Verified 2026-07-28:
 *     they extract **14 characters each** ("Kontakt - Andy", "Kontakt - Hans").
 *     They would fail `minContentLength` anyway; blocking skips the fetch.
 *   - **`/abenteuerreise.html` — an email-signup landing page.** Verified
 *     2026-07-28: it is the sign-up form for a free 7-email series, "Die
 *     geistliche Abenteuerreise" ("Sie ist völlig kostenlos und du kannst dich
 *     dafür gerne anmelden"). It is the German twin of the French
 *     `/aventure.html` and the Arabic `/pack.html`. It extracts **1,539 chars**,
 *     so it CLEARS the 250-char floor comfortably — which is exactly why the
 *     floor cannot decide this. Slice #10 learned that lesson the expensive way
 *     (length is not aboutness); this entry applies it up front instead of
 *     seeding it provisionally and deleting the rows afterwards.
 *   - **`/`** — the homepage.
 *
 * ## What is deliberately KEPT
 *
 * The two `/artikel/*-video.html` pages, despite being the ones the sitemap
 * lists twice. Verified 2026-07-28: they carry unique standalone German
 * transcripts (5,979 and 6,697 chars) and share a slug with no other
 * `/artikel/` page, so — unlike `/audio/*` — they duplicate nothing. The
 * duplicate `<loc>` is a sitemap-generator artefact, and discovery dedupes URLs.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * The prior probe reported the shared EveryStudent template selectors "present".
 * The tokens are — but they are also all defined in the page's inline `<style>`
 * block, so mere presence proves nothing, and **`.content4` does not actually
 * hold the article here.** Re-verified 2026-07-28 by running the repo's own
 * `extractContent` against live pages:
 *   - `.contentpadding` — **1 instance, the whole article**.
 *     `/artikel/gibtes.html` → 19,471 chars raw, **19,160 after stripping**;
 *     `/artikel/ichkann.html` → 3,771 raw / 3,609 stripped.
 *   - `.content4` — **1 instance, an empty spacer div: 0 characters.**
 *   - `.content4b` — **0 instances.** Absent from this host entirely.
 *   - `.articletitle` — an `<h1>`, 19–44 chars. A title, not a body.
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text, so listing `.content4` ahead of `.contentpadding`
 * bound the empty spacer and extracted **0 chars on every page** — every article
 * skipped as `too-thin` on a 200 status, with no error anywhere. That is how
 * this entry first shipped.
 *
 * ⚠️ `.contentpadding` also binds on `/menu/`, `/audio/` and `/p_*` pages — it
 * does **not** discriminate content from nav. The URL filters above are what keep
 * the corpus clean; the selector list must not be relied on to do it.
 *
 * ## Chrome stripped — re-counted 2026-07-28 INSIDE the real scope
 *
 * The earlier figures were taken against a container that extracted nothing and
 * are superseded. Counts below are within `.contentpadding` on
 * `/artikel/gibtes.html` and `/artikel/ichkann.html`:
 *
 *   - **`sitelevel_noindex`** is a **custom ELEMENT tag**, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **2 instances inside
 *     `.contentpadding`, 109 chars** on both pages. Hence the bare tag-name
 *     selector with no leading `.` — matching the sibling entries, whose form
 *     is correct rather than a typo.
 *   - **`.fccell` (4–6) and `.fctable` (1)** — the "FEATURE CLOSE" call-to-action
 *     table of links to other articles, appended to every article. Measured
 *     **204 chars** on `gibtes`, **54** on `ichkann`; the two selectors remove
 *     the same block (the cells nest in the table). `.fctable` is included
 *     because stripping only the cells would leave the table shell behind.
 *   - **`.hr2` (2) and `.articledivider` (1)** — the rules bracketing that CTA
 *     block. **0 chars**, confirmed.
 *   - **`.shareiconsmenupg` (1 per article) — a site-specific addition and the
 *     only selector that removes the share row.** It wraps the "TEILEN:"
 *     AddToAny widget, **9 chars**. The `<sitelevel_noindex>` that nominally
 *     contains it opens inside `.contentpadding` and closes only after
 *     `.contentpadding` does, so the parser pops it early and it never encloses
 *     the widget (#128). Without this selector, "TEILEN:" trails the extraction.
 *   - **`.relatedbottom`** has **no element instance** on any page measured — a
 *     no-op on this host. Retained for parity with the sibling entries; do not
 *     read its presence here as evidence it binds.
 *
 * Together the strip list removes 60–384 chars of pure chrome per article
 * (measured across the six sampled), leaving each article ending on its own
 * last line.
 *
 * ## Language: `["de"]` — read, not inferred
 *
 * Verified 2026-07-28 by reading the extracted text. The pages serve genuine
 * German prose, not untranslated English: `/artikel/gibtes.html` opens "Gibt es
 * einen Gott? Gibt es Beweise dafür?" and argues "Würdest du gerne wissen, wie
 * das nun ist mit Gott, ob es ihn jetzt gibt oder nicht?"; `/artikel/leid.html`
 * asks "Wo ist Gott bei all dem Leid?"; `/artikel/bibel.html` is titled "Kann
 * man der Bibel vertrauen?". Scripture citations use German book names
 * throughout (Johannes, Offenbarung, Römer, Hebräer, Matthäus). Register is
 * mixed across the corpus — `gibtes` addresses the reader as informal "du",
 * `bibel` as formal "Sie" — which is a house-style inconsistency, not a
 * translation gap.
 *
 * German is a NEW language for this corpus as far as this entry is concerned;
 * the stored per-document label still comes from content detection at ingest
 * (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: 11 sequential plain-HTTP fetches drew no 429 and no throttling, and
 * at 45 pages the whole crawl is under a minute of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentDe: SourceEntry = {
  key: "everystudent-de",
  name: "EveryStudent — German (Du entscheidest)",
  domain: "www.duentscheidest.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["de"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:de"],
  defaultCategory: "article",
  rights:
    "© DuEntscheidest.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.duentscheidest.com",
    // No `fetchStrategy`: verified 2026-07-28 that plain HTTP serves every page
    // on this host (unlike all three walled EveryStudent siblings). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.duentscheidest\\.com/"],
    // The whole article corpus and nothing else: 45 of the 70 distinct sitemap URLs.
    articleHints: ["^https://www\\.duentscheidest\\.com/artikel/[^/]+\\.html$"],
    block: [
      // The estate's "Who was Jesus?" page (26,343 chars) — curated highlights
      // from the Gospel of John carrying the family's own formula: excerpts
      // taken straight from the Bible with NO COMMENTARY ADDED. Verbatim
      // Scripture, not ministry writing, so it is excluded 2026-08-06 under the
      // same estate-wide policy that blocked the FULL Gospel of John
      // (`sq /a/gjoni.html` 98.9k, `es /articulos/biblia_juan.html` 100.4k) and
      // `everystudent-ar`'s /bible/**.pdf: "outside what this corpus answers
      // from". This is the ~20-26k curated version of the same thing; all 13
      // instances across the estate go together (campaign #111 §0.13).
      // NOT inert — sibling copies took ranks 7 and 8 on a cross question,
      // consuming top-10 slots a real answer would hold.
      // It matches the article shape, so only a URL block catches it.
      "^https://www\\.duentscheidest\\.com/artikel/werwar\\.html$",
      // Audio-player pages reprinting the article as a transcript — all 11 slugs
      // have an /artikel/ twin; /audio/gibtes.html shares 73.3% of its 12-word
      // shingles with /artikel/gibtes.html. Ingesting both double-counts.
      "^https://www\\.duentscheidest\\.com/audio/",
      // Section indexes (teaser link lists), incl. sitemap/impressum/uber.
      "^https://www\\.duentscheidest\\.com/menu/",
      // The free 7-email "Die geistliche Abenteuerreise" signup landing page —
      // 1,539 chars, so minContentLength can NOT catch it. German twin of the
      // French /aventure.html and Arabic /pack.html.
      "^https://www\\.duentscheidest\\.com/abenteuerreise\\.html$",
      // Contact stubs: 14 chars each ("Kontakt - Andy" / "Kontakt - Hans").
      "^https://www\\.duentscheidest\\.com/p_[^/]+\\.html$",
      // The homepage.
      "^https://www\\.duentscheidest\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-28 as the sole element on this
    // host that extracts the article. `.content4` is deliberately ABSENT: it is
    // an empty spacer div (0 chars) and, because extractContent scopes to the
    // first selector that MATCHES rather than the first that yields text,
    // listing it here made every page skip as `too-thin`. `.content4b` does not
    // exist on this host.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag (4 pairs/page): cookie bar, nav, share, sidebar, footer
      ".shareiconsmenupg", // the "TEILEN:" AddToAny share widget — site-specific addition
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells: links to other articles
      ".hr2", // rules bracketing the CTA block
      ".articledivider",
      ".relatedbottom", // CSS-only on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 120, // 72 sitemap entries (70 distinct, 45 articles) + headroom
    minContentLength: 250,
  },
};
