/**
 * EveryStudent — Urdu (zindagikaysawalat.com, "زندگی کے سوالات" / "Questions of
 * Life"). The Urdu banner of Cru's seeker-facing Q&A ministry: short apologetics
 * and life-issue articles plus first-person testimonies, written for
 * Urdu-speaking students who are not believers. A sibling of `everystudent`
 * (en), `everystudent-ar`, `everystudent-fa`, `everystudent-fr`,
 * `everystudent-pl`, `everystudent-sq`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). zindagikaysawalat.com is its own domain, so it gets its
 * own key, the same way `everystudent-ru` (mirstudentov.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: **~60 plain-HTTP GETs** with a full desktop-Chrome UA —
 * all 42 sitemap URLs, /sitemap.xml, /robots.txt (both apex and www),
 * /m/sitemap.html and 15 off-sitemap probes. Every live page returned **HTTP/2
 * 200 with real HTML**, responses are bare `server: Apache`, and a grep for
 * Cloudflare block-page signatures ("Attention Required", "Just a moment",
 * `cf-browser-verification`) across every fetched page found **0**. So
 * `fetchStrategy` is intentionally OMITTED: plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012). Discovery is therefore free, making
 * this a **discovery crawl** rather than the hand-listed seed set the three
 * walled banners were forced into. Precedent: `thelife-fr`, `everystudent-fa`.
 *
 * The bare apex **301-redirects to `www`** (measured on /robots.txt and
 * /sitemap.xml), so `www.zindagikaysawalat.com` is canonical and the host every
 * `<loc>` uses. `domain`, `baseUrl` and every regex below are pinned to `www.`.
 *
 * ## robots.txt — there is no robots.txt on this host
 *
 * Verified 2026-07-29: `https://zindagikaysawalat.com/robots.txt` 301s to the
 * `www` host, and `https://www.zindagikaysawalat.com/robots.txt` returns **HTTP
 * 404** — the site's own Urdu error page ("معاف کریں!" / "Sorry!"), not a robots
 * file. **There are no `User-agent` or `Disallow` directives anywhere on this
 * domain**, so nothing below is dropped or hand-blocked on robots grounds; every
 * exclusion here is a content-quality call. (The acquire path does not enforce
 * robots.txt anyway — known gap — so a real Disallow would have needed a manual
 * URL block. There is none to mirror.)
 *
 * ## Sitemap — 42 entries, all distinct
 *
 * Verified 2026-07-29: `https://www.zindagikaysawalat.com/sitemap.xml` → HTTP
 * 200, **3,490 bytes**, `content-type: application/xml`, Last-Modified
 * 2021-07-13, a single flat `<urlset>` (no `<sitemapindex>`, so no recursion)
 * generated by xml-sitemaps.com. It holds **42 `<loc>` elements and 42 distinct
 * URLs** — no duplicates. This matches the ~42 from prior recon exactly.
 *
 * The 42 break down as:
 *   - **33 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **7 `/m/<slug>.html`** — section indexes (`exi`, `jes`, `life`, `know`,
 *     `iss`, `forum`, `about`). BLOCKED, below.
 *   - **`/contact.html`** — the contact form. BLOCKED, below.
 *   - **`/`** — the homepage. BLOCKED, below.
 * So `articleHints` is exactly `/a/<slug>.html` and the **expected yield is 33
 * documents**.
 *
 * A full GET sweep of all 42 returned **41 × 200 and 1 × 301**. The single
 * redirect is **`/m/forum.html` → the homepage** (followed with `-L`: final 200
 * at `https://www.zindagikaysawalat.com/`, 34,087 bytes) — a dead sitemap entry
 * of exactly the kind a sibling shipped 25 of. It is caught by the `/m/` block
 * below rather than left to `minContentLength`. **No `/a/` URL redirects at
 * all**, so there is no dead-article cohort.
 *
 * ⓘ **Slugs are pure lowercase ASCII — checked, not assumed.** All 42 `<loc>`
 * values were scanned for uppercase letters inside `/a/`, for non-ASCII bytes,
 * and for `%XX` percent-encoding: **zero hits on all three**. Unlike the Spanish
 * and Bulgarian siblings there is no mixed-case slug here, and unlike the risk an
 * Arabic-script host raises, no slug carries Urdu script. `[^/]+` is kept anyway
 * so a future mixed-case or percent-encoded slug cannot be silently dropped.
 *
 * ## HTML-map cross-check — delta is ZERO in both directions
 *
 * These generated sitemaps are routinely stale, so the site's own HTML site plan
 * was fetched and diffed rather than trusted. Verified 2026-07-29:
 * **`/m/sitemap.html` ("سائٹ کا نقشہ" / "Site map") returns 200 (32,034 bytes)
 * and is itself ABSENT from the XML sitemap.** It links exactly **33 `/a/` URLs,
 * and the two sets are identical** — 0 articles in the HTML map that the XML
 * lacks, 0 the other way.
 *
 * As a wider net, every internal `href` on all 42 fetched pages plus the HTML map
 * was harvested: **34 distinct `/a/` URLs**, i.e. exactly one beyond the sitemap
 * — `/a/fol.html`, which is a post-decision signup page, not an article (see
 * below). **Therefore `seedPaths` is intentionally absent: there is nothing to
 * pin.** No article is missing from discovery.
 *
 * ## What is blocked, and the measured evidence for each
 *
 * All char counts below are what `extractContent` actually returns for that page
 * under the exact `contentSelectors` + `stripSelectors` shipped here, measured
 * 2026-07-29. **Every single one clears the 250-char floor**, so
 * `minContentLength` could not have excluded any of them — the `block` list is
 * doing real work, not decorating.
 *
 *   - **`/a/fol.html` — 604 chars, and it MATCHES `articleHints`.** "خُدا کے
 *     ساتھ آغاز" ("Starting with God"), the post-decision follow-up page:
 *     "یسوع مسیح کا اپنی زندگی میں انتخاب کرنے کیلئے آپکو مُبارکباد۔"
 *     ("Congratulations on choosing Jesus Christ for your life.") followed by a
 *     hand-off to Cru's separate Urdu follow-up site khudakaysathagaaz.com. Form
 *     copy, not a seeker question being answered — the same call
 *     `everystudent-fa` reached on its `/a/fol.html` and `everystudent-pl` on
 *     `/a/nowezycie.html`. It is **not in today's sitemap**, but it IS linked
 *     from articles and this sitemap is generated by a link-following crawler, so
 *     a regeneration would admit it. **Only a URL block catches this one.**
 *   - **`/m/*` — 7 navigation pages, 47–1,195 chars.** `/m/exi.html` 783,
 *     `/m/jes.html` 938, `/m/life.html` 973, `/m/know.html` 724, `/m/iss.html`
 *     448 — none of these has a `.contentpadding` at all, so `extractContent`
 *     falls back to `<body>` and returns a headline+teaser link list.
 *     `/m/about.html` (641) does bind `.contentpadding` and is the about page.
 *     `/m/forum.html` is the 301-to-homepage dead entry above. The block also
 *     covers **`/m/sitemap.html` (1,195 chars of pure link list)**, which is
 *     off-sitemap but linked from every page footer.
 *   - **`/contact.html` — 354 chars**, which is *above* the 250 floor by 104.
 *     "ہم سے رابطہ کریں" ("Contact us") plus a privacy statement. Precisely the
 *     page a "minContentLength will drop it" argument would have lost.
 *   - **`/` — the homepage, 818 chars.** It does NOT extract to 0: with no
 *     `.contentpadding` present, `extractContent` falls back to `<body>` and
 *     yields the full teaser list. Only a URL block excludes it.
 *
 * ⓘ **No Scripture to block on this host, and that was checked.** The
 * estate-wide policy (2026-07-29) drops complete Bible books served on article
 * URLs — `everystudent-es` `/articulos/biblia_juan.html`, `everystudent-sq`
 * `/a/gjoni.html`, `everystudent-fa` `/j/j1`–`/j/j21` — on the reasoning
 * `everystudent-ar` set for its `/bible/**.pdf`: public-domain Scripture rather
 * than ministry writing, outside what this corpus answers from. **This host
 * serves none.** `/j/j1.html`, `/a/yuhanna.html`, `/a/john.html`, `/a/injil.html`,
 * `/yuhanna.html`, `/john.html` and `/injil.html` all return **404**, and the one
 * plausible candidate, `/a/bible.html`, is an apologetics article — "آپ کیوں
 * بائبل پر ایمان رکھ سکتے ہیں؟" ("Why can you believe the Bible?"), arguing from
 * Tacitus, archaeology and manuscript transmission — not Bible text. There is
 * likewise **no Gospel-of-John email course and no "adventure/pack" email
 * series** on this domain: `/pack.html` and `/adventure.html` are 404 too, and
 * `/a/fol.html` above is the only signup-shaped page that exists.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Verified 2026-07-29 by running node-html-parser 7.1.0 exactly as
 * `src/acquisition/extract.ts` does, over **all 33 article pages**. This is the
 * only check that proves anything: every one of these class names is ALSO
 * declared in the page's inline `<style>` block, so grepping for one
 * false-positives on every page. Char counts are post-strip:
 *
 *   - **`.contentpadding` — 1 instance on 32 of 33 pages, 1,520–21,041 chars,
 *     and it extracts 0 chars on NONE of them.** Section kicker, title, subhead,
 *     byline and body. Median 5,312. This is the article.
 *   - **`.content4` — 1 instance on 32 of 33 pages, and it extracts 0 characters
 *     on all 32.** An empty spacer div.
 *   - **`.content4b` — 1 instance on exactly ONE page** (`/a/bible.html`), where
 *     it extracts **0 chars**. Absent from the other 32.
 *   - **`.container2` — 1 instance on the same one page, also 0 chars.** Absent
 *     from the other 32.
 *   - **`.articletitle` — 1 instance on 33/33, 12–60 chars.** An `<h1>`. A title,
 *     not a body.
 *   - **`.content4c`, `.contentleftpadding`, `.cb-entry-content`,
 *     `.entry-content`, `.article-content`, `.content`, `#content`, `article`,
 *     `main` — 0 instances on all 33 pages.** All seven page-generator variants
 *     seen elsewhere on this estate were tried; none of the other six exists here.
 *   - **`<body>` — 0 instances on all 33 articles.** The parser loses it on every
 *     article page (it survives only on the homepage and the `/m/` indexes), so
 *     the real fallback container on an article is the document ROOT.
 *   - **`html` — 33/33, 1,520–21,041 chars**, identical to `.contentpadding`
 *     wherever that binds, because the strip list removes the surrounding chrome.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain.** `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text — so
 * listing `.content4` "as a fallback" would bind the empty spacer, extract 0
 * chars, and skip **every article as `too-thin` on an HTTP 200**: silent, with no
 * error anywhere and invisible to these unit tests. That is how five of the eight
 * pilot entries shipped broken (#128). `contentSelectors` here is therefore the
 * ONE measured container and nothing else.
 *
 * ⚠️ `.contentpadding` also binds on `/contact.html`, `/m/about.html`,
 * `/m/sitemap.html` and `/a/fol.html` — it does **not** discriminate article from
 * chrome. The URL filters above are what keep the corpus clean; the selector must
 * not be relied on to do it.
 *
 * ### The one page that does not fit: `/a/bible.html`
 *
 * Its `<h2 class="subhead">` is closed with **`</em></h1>`** — a stray `</em>`
 * plus an `<h1>` end tag closing an `<h2>`. node-html-parser pops its
 * open-element stack on the mismatch, dissolving the surrounding div stack:
 * `.contentpadding` and `.content4` never form as elements (`querySelector`
 * returns null for both), and `.content4b` / `.container2` are left as empty
 * shells. Every other page on the host has balanced tags.
 *
 * **It is deliberately left unblocked and unhandled**, unlike the Polish
 * sibling's `/a/biblia.html`, because here the root fallback WORKS: it yields
 * **19,159 chars, all of it the article**, from the section kicker to the closing
 * paragraph, with no cookie bar, nav, sidebar, share row, CTA or footer — because
 * that chrome genuinely lives inside the `sitelevel_noindex` tags the strip list
 * removes (verified: the sidebar, share-row and CTA marker strings are all
 * PRESENT before the site-specific strips and ABSENT after). The only residual
 * noise is the literal string `<!DOCTYPE html>` surviving as a text node — 15
 * chars, 0.08% of the document. Same disposition as `everystudent-fa`'s
 * `/a/personally.html`. Adding `.content4b` to `contentSelectors` to "handle" it
 * would be actively harmful: it would bind and yield 0 chars, turning a working
 * 19,159-char extraction into a silent `too-thin` skip.
 *
 * ## Chrome stripped — every selector measured, zeros included
 *
 * Two figures per selector, both across all 33 articles: **solo** = characters
 * removed when that selector alone is added to the generic strips; **marginal** =
 * characters lost if it is withheld from the full shipped list (several selectors
 * cover overlapping regions, so marginals are smaller than solos). Total chrome
 * removed per article: **241–965 chars**.
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **68 instances (2 per article,
 *     4 on `/a/bible.html`); solo 129–816 chars on 33/33; marginal 97–784 on
 *     33/33** — by far the largest contributor and the only one that is
 *     load-bearing on every page. It carries the cookie bar, the top/bottom nav,
 *     the sidebar ("کیا آپ کے پاس کوئی سوال ہے؟" / "سائٹ کا نقشہ") and the
 *     footer. Hence the bare tag name with no leading `.`; the siblings' form is
 *     correct, not a typo.
 *   - **`.fccell` — 164 instances; solo 112–246 chars on 33/33; marginal 112 on
 *     1/33.** The "FEATURE CLOSE" call-to-action cells appended to every article
 *     ("◄ میں ایک سوال پوچھنا یا اظہارِخیال کرنا چاہتا ہوں۔۔۔"). The marginal is
 *     0 on 32 pages only because their CTA table sits inside a
 *     `<sitelevel_noindex>` that is stripped first; on `/a/fourlaws.html` it does
 *     not, and there this selector is the only thing removing those 112 chars.
 *   - **`.fctable` — 36 instances; solo 0–246 chars on 32/33; marginal 0 on
 *     33/33.** The CTA table shell holding those cells. Listed because stripping
 *     only the cells would leave the shell; honestly, it removes nothing extra
 *     once `.fccell` has run.
 *   - **`.hr2` (78 instances) and `.articledivider` (29) — 0 chars, both solo and
 *     marginal, on all 33 pages.** Empty presentational divs drawing the rules
 *     that bracket the CTA block. They bind; they remove nothing.
 *   - **`.shareiconsmenupg` — 33 instances; solo 32 chars on 33/33; marginal 0 on
 *     33/33.** It wraps "اس صفحہ کو دوسروں تک پہنچائیں۔" ("Pass this page on to
 *     others."). On THIS host the enclosing `<sitelevel_noindex>` is
 *     **well-formed** — the ancestor chain is
 *     `DIV.shareiconsmenupg < SITELEVEL_NOINDEX < DIV.contentpadding` — so once
 *     that is stripped first this selector matches nothing: a measured **0-char
 *     no-op in list order**, same as `everystudent-fa` and `everystudent-pl`, and
 *     the opposite of the malformed `-de`/`-ru` case (#128). Kept as a cheap
 *     drift guard, NOT because it strips anything today.
 *   - **`.a2a_kit` — 66 instances, of which 33 SURVIVE the rest of the list, and
 *     they remove 0 chars.** The AddToAny share/print button row; the buttons are
 *     images and `structuredText` does not read `alt`. It is the one share
 *     element that outlives `sitelevel_noindex` here, so it is stripped anyway —
 *     a markup change that adds text labels would otherwise leak them into all 33
 *     articles. Today its contribution is exactly **0**.
 *   - **`.relatedbottom` — 0 instances on this host**, as on every sibling
 *     measured so far. A parity no-op; do not read its presence as evidence it
 *     binds.
 *   - **`head` — 1 instance across all 33 articles, on `/a/bible.html` alone,
 *     removing 37 chars.** A no-op on the 32 pages whose container is
 *     `.contentpadding` (which holds no `<head>`); it earns its place only where
 *     the container falls back to the root and `<head>` would contribute a
 *     duplicate `<title>`. `extract.ts` reads the title from `root` BEFORE the
 *     strip loop, so the page title is not lost — keep those two steps in that
 *     order.
 *
 * ## Encoding — the charset header is missing, the bytes are fine
 *
 * Verified 2026-07-29 on four separate pages: the response header is a bare
 * **`content-type: text/html` with NO charset parameter**, the same gap
 * `studentinjapan.com` and `everykoreanstudent.com` have. The HTML itself
 * declares UTF-8 in the XHTML form — **`<meta http-equiv="content-type"
 * content="text/html; charset=utf-8" />`** on 41 of 41 live pages (there is no
 * short `<meta charset>` tag). The bytes really are UTF-8 and the Urdu is **not
 * mojibake**: across every fetched page there are **0 U+FFFD replacement
 * characters, 0 Latin-1 garble bigrams, and 247,227 Arabic-block characters**,
 * and the extracted prose reads as clean connected Urdu.
 *
 * ⓘ **No `dir="rtl"` attribute exists anywhere on this host** — `<html
 * lang="ur">` carries no `dir`, and right-to-left rendering is applied instead
 * through ~15 inline `style="direction:rtl"` declarations per page. This is
 * informational only: `extractContent` reads `structuredText` and does not
 * consult direction, so RTL costs this pipeline nothing.
 *
 * ## Language: `["ur"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. These pages serve
 * genuine Urdu prose, not untranslated English. `/a/isthere.html` is titled
 * "کیا خداموجود ہے ؟" ("Does God exist?") and opens "کیا آپ صرف ایک دفعہ کسی ایک
 * شخص کو خدا کا وجود ثابت کرنے کی اجازت نہ دیں گے ؟" ("Would you not, just once,
 * let someone prove God's existence to you?"), bylined "از میر لن ایڈم سن"
 * (Marilyn Adamson). `/a/trinity.html` asks "کیا آپ تثلیث کی وضاحت کر سکتے ہیں؟"
 * ("Can you explain the Trinity?") in an explicit "سوال:" / "ہمارا جواب:"
 * ("question" / "our answer") format; `/a/why.html` is "زندگی اتنی مشکل کیوں
 * ہے؟" ("Why is life so hard?"); `/a/prayers.html` is "کیا خدا ہماری دُعاؤں کا
 * جواب دیتا ہے ؟" ("Does God answer our prayers?").
 *
 * It is **Urdu — not Arabic, and not Persian**, a distinction worth pinning on an
 * Arabic-script host whose Arabic (`everystudent-ar`) and Persian
 * (`everystudent-fa`) siblings are already registered. A character census over
 * all 33 extracted articles found the Urdu-only letters in quantity: **ے (bari
 * ye) ×10,955, ں (noon ghunna) ×5,567, ھ (do-chashmi he) ×3,522, ٹ ×646, ڑ ×419,
 * ڈ ×197** — none of these exist in Arabic, and ٹ/ڈ/ڑ/ے do not exist in Persian
 * either. Meanwhile the Arabic-only forms are entirely absent (**ي ×0, ك ×0**)
 * and Persian ژ appears **once** in 266,175 characters. Urdu grammar words
 * ("ہے", "ہیں", "کیا", "سکتے ہیں") run throughout. Of those 266,175 characters
 * only **139 are Latin (0.05%)** — proper nouns and citations, not an
 * untranslated body. No language-detection library was used: this is read text
 * plus a character census.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: ~60 sequential plain-HTTP GETs drew no 429 and no throttling, and at
 * 33 pages the whole crawl is well under a minute of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentUr: SourceEntry = {
  key: "everystudent-ur",
  name: "EveryStudent — Urdu (ZindagiKaySawalat.com)",
  domain: "www.zindagikaysawalat.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ur"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ur"],
  defaultCategory: "article",
  rights:
    "© ZindagiKaySawalat.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.zindagikaysawalat.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare layer), unlike the three walled
    // EveryStudent banners. See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.zindagikaysawalat\\.com/"],
    // The whole article corpus and nothing else: 33 of the 42 sitemap URLs.
    // `[^/]+` rather than a lowercase class — today every slug is lowercase
    // ASCII (verified: 0 uppercase, 0 non-ASCII, 0 %XX across all 42 <loc>
    // values), but siblings carry mixed-case slugs and a `[a-z0-9-]+` hint
    // would silently drop them if one ever appears here.
    articleHints: ["^https://www\\.zindagikaysawalat\\.com/a/[^/]+\\.html$"],
    block: [
      // ── This one MATCHES articleHints; `block` is the ONLY thing excluding it.
      // "خُدا کے ساتھ آغاز" ("Starting with God") — the post-decision follow-up
      // page, 604 chars, which hands off to Cru's separate Urdu site
      // khudakaysathagaaz.com. Absent from today's sitemap but linked from
      // articles, and this sitemap is crawler-generated, so a regeneration would
      // admit it. Same call as everystudent-fa's /a/fol.html.
      "^https://www\\.zindagikaysawalat\\.com/a/fol\\.html$",
      // ── Below here articleHints already excludes them; these record WHY, so a
      // later widening of the hints cannot silently readmit them.
      // The 7 section indexes (exi, jes, life, know, iss, forum, about) plus the
      // off-sitemap /m/sitemap.html site plan. Five have no .contentpadding, so
      // the <body> fallback returns 448-973 chars of headline+teaser link list;
      // /m/about.html is 641 and /m/sitemap.html 1,195. All clear the 250 floor,
      // so the floor can NOT catch them. /m/forum.html is also the one dead
      // sitemap entry — it 301s to the homepage.
      "^https://www\\.zindagikaysawalat\\.com/m/",
      // Contact chrome: 354 chars — ABOVE the 250 floor by 104.
      "^https://www\\.zindagikaysawalat\\.com/contact\\.html$",
      // The homepage. It does NOT extract to 0: with no .contentpadding present,
      // the <body> fallback yields its 818-char teaser list. Only a URL block
      // excludes it.
      "^https://www\\.zindagikaysawalat\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 with the repo's own
    // extractContent over all 33 articles as the sole element on this host that
    // extracts an article (1,520-21,041 chars, median 5,312, across 32 of the
    // 33). `.content4` is deliberately ABSENT: it matches on those same 32 pages
    // and extracts 0 chars on every one, and because extractContent scopes to
    // the first selector that MATCHES rather than the first that yields text,
    // listing it here would make every article skip as `too-thin` on an HTTP 200
    // (#128). `.content4b` and `.container2` exist on exactly one page
    // (/a/bible.html) and also extract 0 chars — adding either would break that
    // page's working 19,159-char root fallback rather than fix it. See header.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // No-op on the 32 well-formed articles; needed only on /a/bible.html,
      // whose container falls back to the document root (37 chars there).
      // extract.ts reads the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 68 inst: cookie bar, nav, sidebar, footer — 97-784 ch on 33/33
      ".fctable", // the "FEATURE CLOSE" CTA table shell — 0 ch once .fccell has run
      ".fccell", // its cells, 164 inst — 112 ch on /a/fourlaws.html, where nothing else catches them
      ".hr2", // 78 inst, 0 chars — empty divs drawing the rules bracketing the CTA
      ".articledivider", // 29 inst, 0 chars — likewise
      ".shareiconsmenupg", // 33 inst; 0 ch in list order (well-formed sitelevel_noindex already holds it). Drift guard.
      ".a2a_kit", // AddToAny share/print row, 33 inst SURVIVE the list; 0 ch today (image-only buttons)
      ".relatedbottom", // 0 instances on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 70, // 42 sitemap entries (33 articles) + headroom
    minContentLength: 250,
  },
};
