/**
 * EveryStudent — Kazakh (shakirtter.com, "Шәкірттер" / "Students"). The Kazakh
 * banner of Cru's seeker-facing Q&A ministry: short apologetics and life-issue
 * articles, FAQ answers and one video transcript, written for Kazakh-speaking
 * students who are not believers. A sibling of `everystudent` (en),
 * `everystudent-ru`, `everystudent-mk`, `everystudent-sq` and the rest of the
 * estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). shakirtter.com is its own domain, so it gets its own
 * key, the same way `everystudent-ru` (mirstudentov.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP, bare Apache
 *
 * Verified 2026-07-30: ~80 plain-HTTP GETs with a full desktop-Chrome UA
 * (`/robots.txt`, `/sitemap.xml`, `/sitemap_index.xml`, a status sweep of all 25
 * sitemap URLs, a full body fetch of all 25, plus `/a/fol.html` and ~22 negative
 * probes). Every response carried `server: Apache` and **no `cf-ray`, no
 * `cf-cache-status`, no Cloudflare layer at all** — so the wall question is
 * settled on the response itself, not on a CDN header. Not one request 403'd, not
 * one carried a block-page signature, and not one 429'd.
 *
 * So `fetchStrategy` is intentionally OMITTED: plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012), unlike everystudent.com /
 * everyarabstudent.com / questions2vie.com which all 403. Discovery is therefore
 * free, making this a **discovery crawl** rather than the hand-listed seed set
 * the walled banners were forced into. Precedent: `thelife-fr`,
 * `everystudent-ru`, `everystudent-mk`.
 *
 * The bare apex **301-redirects to `www`** (measured on `/`, `/robots.txt` and
 * `/sitemap.xml` — `location: https://www.shakirtter.com/…`), so
 * `www.shakirtter.com` is canonical and the host every `<loc>` uses. Every regex
 * below is pinned to it. ⓘ This is the usual direction for the estate, NOT the
 * reverse `everystudent.sk` case.
 *
 * Responses arrive as a bare `content-type: text/html` with **no charset
 * parameter**, which is the estate-wide hazard. Checked rather than assumed: all
 * 25 fetched bodies decode as **valid UTF-8** with zero decode errors, the pages
 * declare `<meta http-equiv="content-type" content="text/html; charset=utf-8">`,
 * and the extracted text is clean Kazakh Cyrillic — no mojibake.
 *
 * ## robots.txt — ONE real Disallow, and it names an article path
 *
 * Verified 2026-07-30: HTTP 200, 35 bytes, `text/plain`. The whole file is:
 *
 *     User-agent: *
 *     Disallow: /a/fol.html
 *
 * There is no `Sitemap:` directive. ⚠️ **The acquire path does not enforce
 * robots.txt**, so this rule is honoured BY HAND as the first `block` entry.
 * It matters: `/a/fol.html` returns **HTTP 200 and extracts 3,001 chars**
 * ("Құдаймен бастау" — "Starting with God", the follow-up page for someone who
 * has just prayed), so neither the 250 floor nor the article-hint regex would
 * have excluded it. It is **absent from /sitemap.xml**, so discovery would not
 * reach it today, but it is linked from **7** of the fetched pages — one
 * regenerated sitemap and it would be in scope. Blocked so the rule is enforced,
 * not merely noted. Nothing else on the domain is disallowed. Same shape as
 * `everystudent-sq`, whose robots.txt disallows `/a/ungjillin2.html`.
 *
 * ## Sitemap — 25 entries, all distinct, all live, all https
 *
 * Verified 2026-07-30: `https://www.shakirtter.com/sitemap.xml` → HTTP 200,
 * **4,092 bytes**, `application/xml`, `Last-Modified: 2020-03-02`, a single flat
 * `<urlset>` (no `<sitemapindex>`, so no recursion), generated by
 * xml-sitemaps.com. 25 `<loc>` elements, **25 distinct URLs**, matching the "~25"
 * from prior recon exactly — **no delta**. `/sitemap_index.xml` returns **404**
 * (checked because of the `everystudent.sk` fossil-sitemap incident), and so does
 * `/sitemap.html`, so `/sitemap.xml` is the only machine map on this host.
 *
 * ⚠️ **`<lastmod>` is worthless here and must not be read as a freshness signal:
 * every one of the 25 entries carries the identical stamp
 * `2018-11-14T20:51:09+00:00`**, yet the set includes `/a/koronavirus.html`
 * (COVID-19), which cannot predate 2020. The file's own `Last-Modified` header
 * (2020-03-02) is the real date. The file is six years old — but see the
 * cross-check below: the site is frozen and both maps agree exactly, so this is
 * an old sitemap of a static site, not a fossil hiding a live corpus.
 *
 * **All 25 `<loc>` values use the `https://` scheme** (0 × `http://`), so the
 * `^https://` pin in `allow` / `articleHints` / `block` is correct here.
 * `discover.ts` filters the RAW `<loc>` string without normalising, so this had
 * to be checked — `everystudent.gr` publishes `http://` and an `^https://` pin
 * would discover zero there.
 *
 * The 25 break down as:
 *   - **17 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **6 `/m/<slug>.html`** — section indexes (`ekendigi`, `suraqtari`, `tanw`,
 *     `smenj`, `kartasi`, `twrali`). BLOCKED.
 *   - **`/baylanis.html`** — the contact page. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 * So `articleHints` is exactly `/a/<slug>.html` and the **expected yield is 17
 * documents**.
 *
 * **A status sweep of all 25 returned 25 × HTTP 200 with ZERO redirects.** There
 * is no dead-redirect cohort of the kind `everystudent-ro` shipped 25 of, and no
 * `.php` extension twins of the kind the French entry dropped.
 *
 * ⓘ **Slugs are lowercase Latin ASCII transliterations of Kazakh words**
 * (`/a/barma.html` for "бар ма", `/a/minajattarimizga.html` for
 * "мінажаттарымызға"), NOT Cyrillic and NOT percent-encoded — checked, not
 * assumed: all 25 `<loc>` values were scanned for non-ASCII bytes (**0 hits**),
 * for `%XX` escapes (**0 hits**) and for uppercase letters (**0 hits**). So the
 * Cyrillic / percent-encoding hazard that would break an ASCII-only hint regex
 * does not exist on this host. `[^/]+` is used regardless, so a future
 * mixed-case or Cyrillic slug cannot be silently dropped.
 *
 * ## HTML-map cross-check — ZERO delta, so no seedPaths
 *
 * These sitemaps are known to be stale, so the site's own map was fetched and
 * diffed, then every internal `href` on all 25 pages was harvested as a wider
 * net. Verified 2026-07-30:
 *   - **`/m/kartasi.html` ("Сайттың картасы" — "Site map") lists exactly the
 *     same 17 `/a/` articles the XML sitemap does.** The delta is **zero in both
 *     directions**. Unusually for this estate, the two maps agree completely.
 *   - The full href harvest across all 25 pages surfaced only **3 paths absent
 *     from the XML sitemap**, and **none of them is an acquirable article**:
 *     - **`/a/fol.html`** — live, 3,001 chars, but **robots-disallowed**. See above.
 *     - **`/a/kim.html`** and **`/a/sinayiomir.html`** — both **HTTP 404**. Dead
 *       links inside the site's own prose. Blocked; see below.
 *   - No other path prefix exists on the whole host: the harvested link set is
 *     exactly `/`, `/baylanis.html`, `/a/*` and `/m/*`.
 *
 * So **`seedPaths` is deliberately absent** — there is no orphan article to pin.
 * (Contrast `everystudent-mk`, which had to pin `/a/zapoznaj402.html`.)
 *
 * ## ⚠️ EXTRACTION: the shared EveryStudent template DOES NOT BIND on this host
 *
 * This is the one decision on this entry that would silently destroy the source
 * if undone, so it is measured rather than inherited. Every candidate below was
 * run through the repo's own parser (`node-html-parser` 7.1.0, exactly as
 * `src/acquisition/extract.ts` uses it) over **all 25 fetched pages** on
 * 2026-07-30 — not grepped, because every one of these class names is also
 * declared in the page's inline `<style>` block and a grep false-positives on all
 * of them. Counts are post-base-strip. **Article pages are the 17 that matter;
 * both figures are given where they differ:**
 *
 *   - **`.content4` — matched 20/25 pages and extracted 0 characters on 17 of
 *     them, which is EVERY SINGLE ARTICLE (17/17 articles, 0 chars).** An empty
 *     spacer div. The only 3 that yield text (411–790 ch) are `/baylanis.html`,
 *     `/m/kartasi.html` and `/m/twrali.html`, all blocked. **This is the shadow
 *     selector on this host** — see the warning below.
 *   - **`.contentpadding` — matched only 3/25, and 0/17 articles.** The estate's
 *     most common container is simply not present on any article here. Where it
 *     does match (the same 3 non-article pages) it yields 411–790 ch.
 *   - **`#content4` (the ID, not the class) — matched 4/25, and 0/17 articles**
 *     (283–615 ch on 4 `/m/` indexes only).
 *   - **`.container2` — matched 21/25 and extracted 0 chars on 20 of them,
 *     including 17/17 articles.** A second shadow selector.
 *   - **`.articletitle` — matched 15/17 articles, 13–66 chars.** A headline, not
 *     a body; and 2 articles do not have one at all.
 *   - **`.post-content` — 1 match, 55 chars** (the homepage teaser block only).
 *   - **`.content4b`, `.content4c`, `.contentpadding2`, `.contentleftpadding`,
 *     `.cb-entry-content`, `.entry-content`, `.article-content`, `.content`,
 *     `<article>`, `<main>` — 0 matches each**, absent from this host.
 *   - **`<body>` — matched 1/25 (the homepage only), and 0/17 articles.**
 *   - **`<html>` — 25/25, and on the 17 articles 3,015–26,869 chars.** The ONLY
 *     element that contains an article on this host.
 *
 * Root cause, same shape as `everystudent-sq` and `everystudent-ko`: the FreeFind
 * markers **interleave with** rather than nest inside the content divs. On
 * `/a/barma.html` the second `<sitelevel_noindex>` opens at line 162,
 * `<div class="container2">` at 165, `<div id="content4">` at 168,
 * `<div class="content4">` at 174 and `<div class="contentpadding">` at 175 —
 * then `</sitelevel_noindex>` at line 188 pops that whole div stack early. On top
 * of that every page carries **one more `</div>` than `<div>`** (84 vs 85 on
 * `/a/barma.html`, 90 vs 91 on `/a/kieli.html`), and that stray close tag
 * disposes of `<body>`. The article survives as **flat direct children of
 * `<html>`** — confirmed by dumping the tree: `head | a | sitelevel_noindex |
 * div.container2 | div.content4 | div.likesharediv | div | h1.articletitle |
 * h1.subhead | div.articledivider | p | p | p | …`. No wrapper element survives
 * to select.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text — so
 * listing `.content4`, `.container2` or `.contentpadding` "outermost first as
 * fallbacks" would bind an empty div, extract 0 chars, and skip every article as
 * `too-thin` on an HTTP 200: silent, and invisible to the unit tests. That is how
 * five of the eight pilot entries first shipped.
 *
 * ⓘ **`"html"` is shipped OUTRIGHT, not appended as a last-resort fallback.**
 * The append trick only works when the primary selector never matches-at-zero;
 * here `.content4` matches at 0 chars on 17/17 articles, so anything listed after
 * it would never fire. `["html"]` is therefore the whole list. It is also
 * deliberately explicit rather than left to `extractContent`'s `body ?? root`
 * fallback: `<body>` is absent, so the fallback would land on `root`, whose
 * doctype node leaks the literal string `<!DOCTYPE html>` into the head of every
 * document (measured: `root.childNodes` is `#text "<!DOCTYPE html>" | html`).
 *
 * **Measured with `["html"]` plus the strip list below, across all 17 articles:
 * 1,513 – 25,427 chars, median 15,082, and 0 pages below the 250 floor.** Spot
 * checks confirm the output opens on the article title ("Құдай бар ма?") and
 * closes on the article's own last line — its numbered scripture-reference list
 * ("(20) Жохан жазған Ізгі хабар 10:27-29") — with no nav, cookie bar, share
 * widget, related links, CTA or footer left.
 *
 * ## Chrome stripped — every selector counted on THIS host, 2026-07-30
 *
 * Marginal contribution, measured by re-running the full extraction with that one
 * selector withheld, across all 17 articles. Zeros are reported as zeros:
 *   - **`head` — 17 instances, 616 chars total (15–70 per page).** Needed **only
 *     because the container is `<html>`**: without it every document opens with a
 *     duplicate of its own `<title>`. Safe because `extract.ts` captures the
 *     title from `root` at line 43, BEFORE the strip loop at line 52 — a future
 *     edit that reorders those two steps would lose the title, so keep them in
 *     that order.
 *   - **`sitelevel_noindex` — 34 instances (2 per page) on 17/17 pages, removing
 *     exactly 1,313 chars on EVERY page, 22,321 total.** By far the largest
 *     contributor. It is a custom ELEMENT tag, not a class, so the missing
 *     leading `.` is correct rather than a typo. It carries the cookie bar and
 *     top nav ("Бұл сайт cookie файлдарын тек талдау үшін пайдаланады…
 *     МАЗМҰНЫ / Іздеу / Құдайдың бар екендігі / Өмір сұрақтары / …") and the
 *     bottom share + related + footer block.
 *   - **`.fccell` — 84 instances on 17/17 pages, 2,062 chars (72–195 per page).**
 *     The "FEATURE CLOSE" call-to-action cells appended to every article
 *     ("► Мен жай ғана Исаны өз өміріме шақырдым… ► Менің сұрағым бар…").
 *   - **`.likesharediv` — 34 instances on 17/17, 22 chars in ISOLATION but a
 *     0-CHAR NO-OP in list order.** The instance carrying the text
 *     ("Басқалармен бөлісу:" — "Share with others:") sits INSIDE the second
 *     `<sitelevel_noindex>`, which is stripped first; the other instance is
 *     empty. Kept because it is the one no-op here that would carry REAL TEXT if
 *     the enclosing markup ever changed.
 *   - **`.a2a_kit` — 34 instances on 17/17, 0 chars.** The AddToAny share row;
 *     its buttons are images and `structuredText` does not read `alt`. Stripped
 *     so a future markup change that adds text labels cannot leak "WhatsApp
 *     Share / Facebook Share / …" into every article.
 *   - **`.hr2` (54 instances, 17/17 pages) and `.articledivider` (14 instances,
 *     14/17) — 0 chars each.** Empty presentational divs bracketing the CTA.
 *   - **`.fctable` — 0 INSTANCES on this host.** The CTA `<table>` carries no
 *     class here, only its cells do — same as `everystudent-sq`. OMITTED from
 *     the list; do not add it expecting it to bind.
 *   - **`.shareiconsmenupg` — 0 INSTANCES on this host.** OMITTED. ⚠️ Do NOT
 *     repeat the `-ru` / `-de` note that it is "required because the markup is
 *     malformed" — that was measured FALSE here: the selector does not exist on
 *     this host at all, so it could not bind under any markup.
 *   - **`.relatedbottom` — 0 INSTANCES.** OMITTED, as dead config; it has never
 *     bound on any host measured so far.
 *
 * ## No Gospel-of-John signup, no e-mail series, no scripture page — all MEASURED
 *
 * Most siblings carry a localized Gospel-of-John study signup and an
 * "adventure/pack" e-mail series that clear the floor and need URL blocks.
 * **This banner has neither**, and that is an absence I measured rather than
 * assumed. Verified 2026-07-30: `/jokan.html`, `/a/jokan.html`, `/jahan.html`,
 * `/injil.html`, `/a/injil.html`, `/kielikitap.html`, `/a/kielikitap.html`,
 * `/sayahat.html`, `/a/sayahat.html`, `/pack.html`, `/a/pack.html`,
 * `/adventure.html` and `/pdf/` **all return HTTP 404**, and the href harvest
 * across all 25 pages found no root-level page other than `/baylanis.html`.
 *
 * **No full Scripture either**, checked under the estate-wide policy of
 * 2026-07-29 (siblings carry 98k–100k-char complete Bible books on `/a/` URLs).
 * The longest page on this domain is **25,427 chars** (`/a/kieli.html`), only
 * ~1.7× the 15,082 median — nowhere near the ~14× outlier that flags a Bible
 * book. How the two were told apart: `/a/kieli.html` is titled "Сіз неге Киелі
 * Кітапқа сене аласыз" ("Why you can believe the Bible") and reads as an
 * apologetics ESSAY *about* the Bible ("Киелі кітап 1500 жыл бойы, 40 жазушы
 * арқылы жазылған" — "The Bible was written over 1,500 years by 40 writers"),
 * closing on 12 numbered footnotes citing F. F. Bruce, Josh McDowell and Tacitus.
 * That is ministry writing with citation apparatus, not verbatim scripture, so it
 * is KEPT. Every article on the host has the same footnoted-essay shape.
 * **There is also no third-party Bible-society copyright anywhere in the fetched
 * HTML** — a grep for `©` across all 25 pages returns **zero matches** — so the
 * `rights` line below cannot misattribute someone else's translation.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` already excludes everything outside `/a/`. The `block` list is
 * deliberately redundant for those, recording *why* each group is out so a later
 * widening of the hints cannot silently readmit them. Three entries are **not**
 * redundant — `/a/fol.html`, `/a/kim.html` and `/a/sinayiomir.html` sit under
 * `/a/` and match `articleHints`, so `block` is the only filter keeping them out.
 *
 * All char counts are post-strip. ⚠️ **Every single one clears
 * `minContentLength: 250`**, so the floor could not have excluded any of them —
 * the URL blocks are doing real work, not decorating. And the usual "the floor
 * will catch it" argument is doubly wrong here: with `contentSelectors: ["html"]`
 * the container matches on EVERY page, article or not, so a non-article extracts
 * its full teaser list rather than nothing:
 *   - **`/a/fol.html` — 3,001 chars, robots-disallowed.** The only entry blocked
 *     for a reason other than content quality.
 *   - **`/a/kim.html` and `/a/sinayiomir.html` — HTTP 404, whose error body
 *     extracts 505 chars.** "Кешіріңіз" ("Sorry") plus a list of the site's
 *     most popular articles. `acquire.ts` drops `status >= 400` as
 *     `fetch-failed`, so they would not stage today, and they are absent from
 *     the sitemap so discovery cannot reach them — but at 505 chars the floor
 *     would NOT save us if either URL were ever "fixed" or hand-seeded.
 *   - **`/m/*` — 262–790 chars.** The 6 section indexes: `ekendigi`
 *     ("Құдайдың бар екендігі"), `suraqtari` ("Өмір сұрақтары"), `tanw`
 *     ("Құдайды тану"), `smenj` ("Сұрақтар мен Жауаптар"), `twrali`
 *     ("Біз туралы" — about + privacy) and `kartasi` ("Сайттың картасы" — the
 *     site plan). Headline + teaser link lists. Navigation, not content.
 *   - **`/baylanis.html` — 411 chars.** "Бізбен байланысыңыз" — the contact
 *     page. ⚠️ Note the near-collision: `/a/baylanis.html` is a REAL article
 *     ("Құдаймен байланыс", 17,294 ch) and must not be caught by this block,
 *     which is why the regex is anchored at the host root rather than matching
 *     the bare filename.
 *   - **`/` — 1,379 chars.** The homepage. It does NOT extract to 0: `html`
 *     matches on it as readily as on an article, so it yields its full teaser
 *     list. Only a URL block excludes it.
 *
 * ⓘ **One video transcript is KEPT.** `/a/jaqsi.html` ("Құдай жақсы ма?", 1,513
 * ch) is the transcript of a 1:45 film, marked in its own body as "Бейне
 * транскрипті:". `everystudent-pl` blocks its equivalent `/wideo.html` on the
 * grounds that a transcript "extracts as ~60 one-line blocks that chunk poorly
 * against paragraph boundaries" (invariant 4). **That reason was measured and
 * does NOT hold here**: it extracts as 13 normal multi-sentence paragraphs, it
 * sits under `/a/`, and the site's own `/m/kartasi.html` lists it as an article.
 * Same call as `everystudent-mk` made on its three transcripts.
 *
 * ## Language: `["kk"]`, and the script is CYRILLIC — read and counted
 *
 * ⚠️ Kazakhstan is mid-transition between Cyrillic and Latin, so the script was
 * checked, not assumed. **This host serves CYRILLIC Kazakh.** Verified
 * 2026-07-30 across all 17 extracted articles (232,135 chars): **189,052 Cyrillic
 * letters against 178 Latin — 99.91% Cyrillic**, and the Latin-Kazakh diacritics
 * that a Latin edition would need (ä, ğ, ñ, ö, ū, ü, ş) score **0 each**. There is
 * no parallel Latin tree: the only path prefixes on the entire host are `/a/` and
 * `/m/`, harvested from every internal href on all 25 pages.
 *
 * ⚠️ **It is Kazakh, NOT Russian** — checked deliberately, because `ru`
 * (mirstudentov.com) is already in the registry and `ru-ca` (studentstan.com) is
 * coming, and a naive reading of Cyrillic would confuse them. The proof is the
 * alphabet: the nine letters that exist in Kazakh Cyrillic and **do not exist in
 * the Russian alphabet at all** are present in bulk —
 * **і ×13,546, қ ×6,079, ң ×3,156, ғ ×2,818, ұ ×2,203, ө ×2,142, ә ×1,896,
 * ү ×1,579, һ ×16 — 33,435 occurrences in total.**
 *
 * ⓘ **An honest caveat on the reverse test.** The Kazakh Cyrillic alphabet is the
 * Russian alphabet PLUS those nine letters, so ы / э / ъ are *not* Russian-only
 * discriminators the way Serbian ђ/ћ are against Macedonian — ы ×13,004 here is
 * ordinary Kazakh, not evidence of Russian, and it is reported rather than spun.
 * The discriminating counts run the other way and are word-bounded with
 * `(?<!\p{L})…(?!\p{L})` (naive substring counts gave the OPPOSITE answer on
 * Croatian vs Serbian in batch 3): the common Russian function words
 * **что, это, как, для, они, был, есть, бог score 0 EACH**, while the Kazakh ones
 * score **мен ×412, Құдай ×349, және ×343, деп ×235, үшін ×202, бұл ×181,
 * бар ×180, емес ×125, болып ×89**. Word-bounded English scores **the ×1, and ×1,
 * that ×0, with ×0, which ×0, have ×0** across 232k chars, so these are not
 * untranslated English bodies either (the cru.org failure mode).
 *
 * What I read: `/a/barma.html` is titled "Құдай бар ма?" ("Is there a God?");
 * `/a/usbirlikti.html` asks „Үшбірлікті түсіндіріп бере аласыз ба?" ("Can you
 * explain the Trinity?"); `/a/jaqsi.html` argues „Құдай роботтарды қалаған жоқ.
 * Ол шынайы адамдарды қалады" ("God did not want robots. He wanted real
 * people"); the site's own tagline is "Өмір және Құдай жайлы сұрақтарды зерттеуге
 * болатын қауіпсіз орын" ("A safe place to explore questions about Life and
 * God"). Scripture citations use Kazakh book names throughout (Жохан жазған Ізгі
 * хабар, Ишая, Римдіктерге хат, Аян, Забур, Еремия, Матай).
 *
 * The site declares `<html lang="kk">`, which agrees with what was read — but the
 * declaration was NOT relied on (`persoalanhidup.com` declares `lang="id"` and
 * serves Malay). The stored per-document language label still comes from content
 * detection at ingest (invariant 6), never from this field.
 *
 * ⚠️ **Kazakh is a NEW language for this corpus** — no `kk` documents exist
 * today, so there is no existing golden case this source becomes eligible for by
 * construction, and Stage-4 gating treats `kk` as single-source.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~80 sequential requests
 * drew **zero 429s and no throttling**, so the sibling default is kept rather
 * than raised; at 17 pages the whole crawl is a few seconds.
 */
import type { SourceEntry } from "./types.js";

export const everystudentKk: SourceEntry = {
  key: "everystudent-kk",
  name: "EveryStudent — Kazakh (Shakirtter.com)",
  domain: "www.shakirtter.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["kk"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:kk"],
  defaultCategory: "article",
  rights:
    "© Shakirtter.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.shakirtter.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare header, no 403). See header.
    sitemaps: ["/sitemap.xml"],
    // No `seedPaths`: the XML sitemap and the site's own /m/kartasi.html list
    // the SAME 17 articles (zero delta both ways), and the href harvest across
    // all 25 pages found no orphan article to pin. See header.
    allow: ["^https://www\\.shakirtter\\.com/"],
    // The whole article corpus and nothing else: 17 of the 25 sitemap URLs.
    // All 25 <loc> use https:// (0 × http://), so the ^https:// pin is correct.
    // `[^/]+` rather than a lowercase class — slugs are all-lowercase Latin
    // ASCII today (0 non-ASCII bytes, 0 %XX escapes, 0 uppercase across all 25
    // <loc>), but a Cyrillic or mixed-case slug added later must not be dropped.
    articleHints: ["^https://www\\.shakirtter\\.com/a/[^/]+\\.html$"],
    block: [
      // ── The three below match articleHints; `block` is the ONLY filter
      //    excluding them.
      // robots.txt Disallow, fetched live 2026-07-30 — the ONE rule on this
      // host, and it names an /a/ path. The acquire path does NOT enforce
      // robots.txt, so it is honoured by hand here. The page returns 200 and
      // extracts 3,001 chars ("Құдаймен бастау" — a "starting with God"
      // follow-up), so nothing else would have excluded it. Absent from the
      // sitemap but linked from 7 pages; blocked so the rule is enforced.
      "^https://www\\.shakirtter\\.com/a/fol\\.html$",
      // Dead links inside the site's own prose: both HTTP 404, and the 404 body
      // extracts 505 chars — over the 250 floor. Absent from the sitemap, so
      // discovery cannot reach them today; blocked so a regenerated sitemap or
      // a hand-added seed cannot stage an error page as an article.
      "^https://www\\.shakirtter\\.com/a/(kim|sinayiomir)\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 6 section indexes, 262-790 ch: ekendigi, suraqtari, tanw, smenj,
      // twrali (about + privacy) and kartasi (the site plan). With
      // contentSelectors ["html"] the container matches on these too, so each
      // yields its full teaser link list rather than nothing.
      "^https://www\\.shakirtter\\.com/m/",
      // "Бізбен байланысыңыз" — the contact page, 411 ch. Anchored at the host
      // root on purpose: /a/baylanis.html is a REAL 17,294-char article
      // ("Құдаймен байланыс") and must not be caught by this.
      "^https://www\\.shakirtter\\.com/baylanis\\.html$",
      // The homepage — `html` matches on it as readily as on an article, so it
      // yields 1,379 ch of teaser headlines. Only a URL block excludes it.
      "^https://www\\.shakirtter\\.com/?$",
    ],
    // ⚠️ NOT the shared EveryStudent template. Measured 2026-07-30 over all 25
    // fetched pages with node-html-parser: `.content4` matches on 17/17 ARTICLES
    // and extracts 0 chars on every one, `.container2` likewise, `.contentpadding`
    // matches 0/17 articles, `#content4` 0/17, and even <body> is lost — a stray
    // </sitelevel_noindex> closes the content divs early and one extra </div> per
    // page disposes of <body>, flattening the article into <html>'s direct
    // children. `<html>` is the only element that still contains it (3,015-26,869
    // ch). Do NOT add `.content4`, `.container2` or `.contentpadding` here:
    // extractContent binds the first selector that MATCHES, so any of them would
    // win and yield "" — every article would skip as `too-thin` on an HTTP 200.
    contentSelectors: ["html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Required because the container is <html>: drops the duplicate <title>.
      // 616 ch over 17 pages. extract.ts reads the title from `root` (line 43)
      // BEFORE the strip loop (line 52) — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-30 (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2/page: cookie bar + nav, and share + related + footer — exactly 1,313 ch on all 17
      ".fccell", // "FEATURE CLOSE" CTA cells, 84 inst — 2,062 ch (72-195/page)
      ".a2a_kit", // AddToAny share row, 34 inst — 0 chars today (image-only buttons)
      ".likesharediv", // "Басқалармен бөлісу:" — 22 ch isolated, 0 marginal (nested inside sitelevel_noindex). The one no-op here that carries real TEXT if that markup drifts.
      ".hr2", // 54 inst, 0 chars — empty presentational divs
      ".articledivider", // 14 inst, 0 chars
      // `.fctable`, `.shareiconsmenupg` and `.relatedbottom` are deliberately
      // ABSENT: measured 0 INSTANCES each on this host, so they can never bind.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 over ~80 requests
    maxPages: 60, // 25 sitemap URLs (17 kept after filtering) + headroom
    minContentLength: 250,
  },
};
