/**
 * EveryStudent — Tamil (ungalthervuenna.com, "UngalThervuEnna.com" / "உங்கள்
 * தேர்வு என்ன?" — "What is your choice?"). The Tamil banner of Cru's
 * seeker-facing Q&A ministry: short apologetics and life-issue articles, FAQ
 * answers and first-person testimonies written for Tamil-speaking students who
 * are not believers. A sibling of `everystudent` (en), `everystudent-sq`,
 * `everystudent-pl`, `everystudent-ru`, `everystudent-de`, `everystudent-ko`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). ungalthervuenna.com is its own domain, so it gets its
 * own key, the same way `everystudent-sq` (pyetjetejetes.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-30: ~90 plain-HTTP GETs with a full desktop-Chrome UA —
 * robots.txt, /sitemap.xml, all 31 `/a/` articles, all 7 `/m/` indexes,
 * /m/intl.html, /contact.html, the homepage, plus a 40-URL sweep of the whole
 * sitemap and 17 probes for pages that turned out not to exist. **Every live
 * page returned HTTP/2 200 with real HTML.** Responses are `server: Apache`
 * with `strict-transport-security` and `x-content-type-options: nosniff` and
 * **no Cloudflare layer at all** — no `cf-ray`, no challenge script, and not one
 * block-page signature anywhere. So `fetchStrategy` is intentionally OMITTED:
 * plain HTTP is the default and nothing here needs Firecrawl (ADR-0012). Same
 * as `everystudent-sq` / `-pl`; unlike everystudent.com, everyarabstudent.com
 * and questions2vie.com, which all 403.
 *
 * Discovery is therefore free, making this a **discovery crawl** rather than the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-sq`, `everystudent-pl`.
 *
 * **Canonicalisation was checked BOTH ways.** Verified 2026-07-30: the bare apex
 * 301s to `https://www.ungalthervuenna.com/` over both http and https, and `www`
 * over http 301s to `www` over https. Nothing redirects toward the apex — this
 * host is the normal direction, not the `everystudent.sk` reverse. So
 * `www.ungalthervuenna.com` is canonical and `domain`, `baseUrl` and every regex
 * below are pinned to it, which is also what every `<loc>` in the sitemap emits.
 *
 * ## robots.txt — permissive, and it is 22 bytes long
 *
 * Verified 2026-07-30: HTTP 200, `Last-Modified: 2019-07-17`, **22 bytes**, and
 * the entire file is the single line `User-agent: * Allow: /` with no trailing
 * newline (both directives on ONE line — sloppy, but there is nothing in it to
 * misread). **Zero `Disallow` rules of any kind**, so no URL is disallowed and
 * **nothing below is blocked on robots grounds** — every exclusion in `block` is
 * a content-quality call. This matters because the acquire path does not enforce
 * robots.txt; had there been a rule, it would have had to be mirrored into
 * `block` by hand, as `everystudent-sq` does for its one `/a/` Disallow.
 *
 * ## Sitemap — 40 entries, exactly as recon predicted, and NOT a fossil
 *
 * Verified 2026-07-30: `https://www.ungalthervuenna.com/sitemap.xml` → HTTP 200,
 * **3,298 bytes**, `application/xml`, a single flat `<urlset>` (no
 * `<sitemapindex>`, so no recursion), generated by xml-sitemaps.com. It holds
 * **40 `<loc>` elements and 40 distinct URLs** — no duplicates. Prior recon said
 * "~40 URLs"; the measured count is 40, **delta zero**.
 *
 * `/sitemap_index.xml` was tried too and is a **404** — there is no Yoast index
 * hiding a larger live inventory behind a stale flat file, which is the trap
 * `everystudent.sk` fell into. The file's own `Last-Modified` is **2017-10-06**,
 * which does look fossil-ish, so it was not taken on trust: all 40 URLs were
 * swept and the site's own HTML map was diffed against it (both below). The 2017
 * stamp is simply when the generator last ran; the inventory it describes is
 * still live and still complete.
 *
 * **Every `<loc>` is `https://www.` — the scheme is https, not http.** Checked
 * because `everystudent.gr` publishes `http://` URLs and `discover.ts` filters
 * the RAW `<loc>` string without normalising it, so an `^https://` pin there
 * discovers zero. Here `^https://` is correct and is what `allow` uses.
 *
 * The 40 break down as:
 *   - **31 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **7 `/m/<slug>.html`** — section indexes (`existence`, `questions`,
 *     `relationships`, `knowing`, `forum`, `map`, `about`). BLOCKED, below.
 *   - **`/contact.html`** — the contact page. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 * So `articleHints` is exactly `/a/<slug>.html` and the **expected yield is 31
 * documents**.
 *
 * **All 40 sitemap URLs are live: a full sweep returned 40 × 200 with an empty
 * redirect target on every one.** There is no dead-URL cohort and nothing
 * redirecting to the homepage — the failure a sibling shipped 25 of.
 *
 * ⚠️ **Tamil slugs are pure ASCII English words — checked, not assumed.** All 40
 * `<loc>` values were scanned for non-ASCII bytes and for `%XX` percent-encoding:
 * **zero hits of either**. The site does not put Tamil script in its URLs at all;
 * the slugs are the English originals (`/a/isthere.html`, `/a/whodoyousay.html`,
 * `/a/hspirit.html`). One slug is **mixed-case** — `/a/Godreal.html` — so the
 * hint regex must not be lowercase-only; `[^/]+` covers it and a `[a-z0-9-]+`
 * hint would have silently dropped that article.
 *
 * ## Cross-checked against the site's own HTML map — 3 extras, and all 3 are dead
 *
 * These sitemaps are known to run stale, so `/m/map.html` ("தளத்தின்
 * வரைப்படம்" — "site map") was fetched and diffed, and then every `href` on all
 * 7 `/m/` indexes, the homepage and /contact.html was harvested as a wider net.
 * Verified 2026-07-30: the union links **34 distinct `/a/` URLs — 3 more than the
 * XML sitemap's 31**: `/a/addiction.html`, `/a/created.html` and
 * `/a/gaylesbian.html`.
 *
 * **All three return HTTP 404.** They are dead links left in the navigation, not
 * articles the sitemap forgot. So `seedPaths` is deliberately ABSENT — there is
 * nothing to pin, and pinning them would have staged three 404 bodies. (This is
 * why the cross-check is a fetch, not a diff: on a `<body>`-less host like this
 * one an unfetched "missing article" is indistinguishable from a dead one.)
 *
 * The harvest also turned up **`/m/intl.html`** — live (200) but absent from the
 * sitemap. It is the page linking out to the sibling language domains; it
 * extracts **14 chars** ("மற்ற மொழிகளில்" — "in other languages") so the floor
 * would catch it anyway, and the `/m/` block covers it regardless.
 *
 * ## ⚠️ EXTRACTION: the shared EveryStudent template DOES NOT BIND on this host
 *
 * This is the one decision that would silently destroy the source if undone, so
 * every candidate was run through the repo's own parser (`node-html-parser`,
 * exactly as `src/acquisition/extract.ts` uses it) over **all 31 article pages**
 * on 2026-07-30 — not grepped, because `contentpadding` and `content4` are both
 * declared in each page's inline `<style>` block and a grep hits 31/31 on both.
 *
 *   - **`.content4` — MATCHES on 31/31 pages and extracts 0 characters on every
 *     single one.** An empty spacer div. This is the shadow.
 *   - **`.contentpadding` — 0 matches.** Present in the raw bytes on 31/31, but
 *     the parser never forms the element. **There is no safe default here.**
 *   - **`#content4` (the ID) — 0 matches.** Also present in the raw bytes.
 *   - **`.content4b`, `.contentleftpadding`, `.cb-entry-content`,
 *     `.entry-content`, `.post-content`, `.article-content`, `.content`,
 *     `<article>`, `<main>` — 0 matches each.**
 *   - **`.articletitle` — 1 match on 31/31, 4-61 chars.** The `<h1>` headline,
 *     not a body.
 *   - **`<body>` — 0 matches**, despite `<body>` being in the raw bytes on 31/31.
 *   - **`<html>` — the ONLY element that contains the article**, 8,307-36,376
 *     chars unstripped across the 31.
 *
 * Root cause, the same shape as `everystudent-sq` and `everystudent-ko`, and
 * uniform on all 31 pages: the FreeFind markers **interleave with** rather than
 * nest inside the content divs. `<sitelevel_noindex>` opens, then
 * `<div class="container2">`, `<div id="content4">`, `<div class="content4">`,
 * `<div class="contentpadding">`, `<div class="likesharediv">` — and then a
 * stray `</sitelevel_noindex>` fires immediately after the
 * `<!-- end likesharediv -->` comment, closing that entire div stack **and**
 * `<body>` in one pop. Byte-for-byte identical placement on every article. The
 * title and prose that follow are left as **flat direct children of `<html>`**.
 * No wrapper element survives to select. Note the tag counts are *balanced*
 * (`<div>` opens = closes on every page), so a naive balance check finds nothing
 * — it is the ORDER that is wrong, not the count.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text. So
 * listing `.contentpadding` first "because the siblings use it" would fall
 * through to `.content4`, bind the empty spacer, extract 0 chars, and skip every
 * article as `too-thin` on an HTTP 200 — silent, and invisible to the unit tests.
 * That is how five of the eight pilot entries first shipped.
 *
 * **`["html"]` is shipped ALONE, and appending it as a trailing fallback would
 * not have worked here.** The trailing-`"html"` pattern only helps when the
 * primary selector cannot match-at-zero; `.content4` matches at 0 chars on
 * 31/31, so any list containing it never reaches a fallback. `["html"]` is also
 * deliberately explicit rather than left to `extractContent`'s `body ?? root`
 * chain: `<body>` does not parse here, so the implicit fallback would land on
 * `root`, whose doctype node leaks the literal `<!DOCTYPE html>` string into the
 * head of every extracted document.
 *
 * **Measured with `["html"]` plus the strip list below, across all 31 articles:
 * 3,023 - 30,920 chars, median 11,172, and 0 pages below the 250 floor.** Output
 * opens on the article title and closes on the article's own Tamil
 * scripture-footnote list (e.g. `/a/devil.html` ends "…(11) 1கொரிந்தியர் 10:13
 * (12) யோவான் 8:12"). A leftover scan across all 31 found no `<!DOCTYPE`, no
 * cookie text, no "►" CTA marker, no AddToAny label and no FreeFind marker.
 *
 * ## Chrome stripped — every selector measured on THIS host, 2026-07-30
 *
 * Standalone contribution (each selector measured on its own against the
 * unstripped `<html>`), averaged per page over all 31 articles:
 *
 *   - **`sitelevel_noindex` — 62 instances (2/page), 2,063 chars/page.** By far
 *     the largest contributor, and the whole reason the extraction is usable. It
 *     is a custom ELEMENT tag, not a class — `<sitelevel_noindex> …
 *     </sitelevel_noindex>` — so the missing leading `.` is correct, not a typo.
 *     The two instances carry the cookie bar + top nav, and the bottom
 *     share/sidebar/most-popular/footer block. Nested inside them (and therefore
 *     0 additional chars once this is stripped) are `#cookie-notice` (179
 *     ch/page), `.sidebar` (336 ch/page) and `#footer` (116 ch/page) — measured,
 *     which is why none of those three is listed separately.
 *     ⚠️ On THIS host the wrapper is **malformed**, and that was measured here
 *     rather than inherited: it is the stray `</sitelevel_noindex>` above that
 *     collapses the container tree. That is a statement about this host only.
 *   - **`head` — 1 instance/page.** Load-bearing ONLY because the container is
 *     `<html>`. On its own it is worth 1,517 chars/page, but `script` and `style`
 *     live inside it and are stripped first, so in list order it removes the
 *     remaining **31 chars/page — the page's own `<title>`, which would
 *     otherwise be duplicated at the head of every document.** Safe because
 *     `extract.ts` reads the title from `root` at line 43, BEFORE the strip loop
 *     at line 52; a future edit that reorders those two steps would lose every
 *     title, so keep them in that order.
 *   - **`script` — 218 instances, 1,948 chars/page**, and **`style` — 156
 *     instances, 1,140 chars/page.** Unusually large because the container is
 *     `<html>`: these are the repo-standard entries doing real work here.
 *   - **`.fccell` — 146 instances (4-6/page), 123 chars/page.** The "FEATURE
 *     CLOSE" call-to-action cells appended to every article.
 *     ⓘ **`.fctable` is 0 instances on this host** — the CTA `<table>` carries
 *     no class, only its cells do — so it is deliberately NOT in the list. Do not
 *     add it expecting it to bind.
 *   - **`.likesharediv` — 62 instances (2/page).** 351 chars/page measured on its
 *     own, but **0 chars in list order**: all of that text is the Facebook
 *     `document.write` payload inside a `<script>`, already gone by then.
 *     Stripped anyway as a drift guard on the share row.
 *   - **`.a2a_kit` — 62 instances (2/page), 0 chars.** The AddToAny share-button
 *     row; the buttons are images and `structuredText` does not read `alt`.
 *     Stripped so a markup change that adds text labels cannot leak them.
 *   - **`.hr2` (87 instances), `.articledivider` (27, on 27 pages) and
 *     `.articledividerforum` (4, on 4 pages) — 0 chars each.** Empty
 *     presentational divs drawing the rules that bracket the CTA block.
 *   - **`form` — 93 instances, 0 chars** (the FreeFind search boxes).
 *   - **`noscript`, `svg`, `nav`, `header`, `footer` — 0 instances each.** Kept
 *     because they are the repo-wide baseline every sibling carries, not as
 *     host-specific parity.
 *   - **`.shareiconsmenupg` and `.relatedbottom` — 0 instances each, MEASURED,
 *     and therefore OMITTED.** They cannot ever bind on this host: the share row
 *     is `.likesharediv`/`.a2a_kit` here, and there is no related-articles block
 *     at all. Carrying them would be decoration, not a guard.
 *
 * ## ⚠️ minContentLength cannot be relied on to catch the non-articles
 *
 * Every page blocked below was fetched and extracted, and **every one of the 9
 * clears the 250-char floor** — so the floor could not have excluded a single
 * one and `block` is doing real work. Verified 2026-07-30 (this host has no
 * `<body>`, so an unmatched selector falls all the way back to the whole
 * document; here `<html>` matches on chrome pages exactly as readily as on
 * articles, which is the same thing by another route):
 *   - **`/` — 1,162 chars.** The homepage teaser list.
 *   - **`/m/map.html` — 1,176 chars.** The site plan, a pure link list. The Tamil
 *     twin of the French `/plan.html` and the Polish `/mapa.html`.
 *   - **`/m/about.html` — 851**, **`/m/knowing.html` — 808**,
 *     **`/m/questions.html` — 733**, **`/m/existence.html` — 488**,
 *     **`/m/forum.html` — 307**, **`/m/relationships.html` — 265.** Headline +
 *     teaser link lists. Navigation, not content.
 *   - **`/contact.html` — 340 chars.** "எங்களைத் தொடர்புக் கொள்ளுங்கள்"
 *     ("Contact us") — contact chrome.
 *
 * ## No email-signup pages exist here — an absence that was MEASURED
 *
 * The siblings all carry a localized Gospel-of-John study signup and a
 * 7-or-8-email "adventure/pack" series, and both are normally blocked. **This
 * host has neither.** Verified 2026-07-30 by direct probe: `/john.html`,
 * `/jean.html`, `/yohan.html`, `/a/john.html`, `/gospel.html`, `/pack.html`,
 * `/adventure.html`, `/a/newlife.html`, `/a/knowgod.html` and `/4laws.html` **all
 * return HTTP 404**, as do `/sitemap.html`, `/map.html`, `/privacy.html` and
 * `/video.html`. Nothing of that shape is linked from any page either. So there
 * is no such block below, and its absence is a finding rather than an omission.
 *
 * ## No full Scripture on this host — also measured
 *
 * The estate-wide 2026-07-29 policy blocks complete or abridged Bible books
 * served on article URLs (`everystudent-sq` blocks a 98,887-char Gospel of John).
 * **Nothing here qualifies.** All 31 articles were scanned for `chapter:verse`
 * density: the highest is **3.95 refs per 1,000 chars** (`/a/hspirit.html`,
 * 4,308 chars, 17 refs) and every one of those is a numbered footnote citation,
 * not running Bible text. The longest page is **`/a/bible.html` at 30,920 chars
 * — and it is apologetics ABOUT the Bible, not the Bible.** It is titled
 * "நீங்கள் ஏன் பைபிளை நம்பலாம்?" ("Why can you trust the Bible?"), it argues from
 * authorship, manuscript transmission and archaeology, and it closes on 13
 * numbered footnotes citing McDowell, Strobel, Geisler, Bruce and Tacitus. That
 * is the test used to tell the two apart: **running verse text with chapter
 * headings would be Scripture; an argument whose verse references are numbered
 * endnotes is ministry writing.** It is KEPT.
 *
 * ⓘ Copyright was checked for the third-party-Bible-society hazard that would
 * make the `rights` line below a misattribution. Sitewide it is
 * `© UngalThervuEnna.com` on all 40 pages; the only other notices are
 * per-quotation credits inside three articles (`© Worldwide Challenge` on
 * `/a/sawyer.html`, `© Richard Purnell` on `/a/intimacy.html`, and a Tamil
 * `© 1988, எச்.பி. பப்லிகேஷன்ஸ், இங்க்., வீடன், ஐ.எல். 60187` on
 * `/a/faith.html`). **No Bible-society copyright anywhere**, so the `rights`
 * line is accurate.
 *
 * ## Language: `["ta"]` — Tamil, read and counted, not inferred
 *
 * Verified 2026-07-30 by reading the extracted text myself. **The script is
 * Tamil, Unicode block U+0B80-U+0BFF** — counted, not eyeballed: Tamil
 * codepoints are **82.0%-87.5% of every article's extracted characters** (31/31
 * pages), with **zero Telugu (U+0C00-U+0C7F)** anywhere. That distinction was
 * checked explicitly because sibling banners in Telugu and Devanagari were being
 * catalogued at the same time and the blocks are easy to confuse: Tamil அ ஆ இ க
 * ங ச versus Telugu అ ఆ ఇ క ఖ గ.
 *
 * The prose is genuine Tamil, not untranslated English — the cru.org `/mx/es/`
 * failure mode does not occur here. `/a/devil.html` is "சாத்தான் யார்?" ("Who is
 * Satan?") and opens "கேலிசித்திரம் அல்லது நகைச்சுவை சித்திரத்தில் சாத்தான்
 * அழகானவனாகவும், தீங்கற்ற சோதனை காரணாகவும்… இருக்கிறான்" ("in cartoons or comic
 * strips Satan appears handsome, a harmless tempter…"). `/a/whyworship.html`
 * uses the native "கே:" / "எங்களின் பதில்:" ("Q:" / "Our answer:") pair.
 * `/a/trinity.html` is "திரித்துவத்தை நீங்கள் விளக்க முடியுமா?" ("Can you
 * explain the Trinity?"), `/a/whowas.html` is "இயேசு யார்?" ("Who is Jesus?"),
 * `/a/greatest.html` is "என் வாழ்வின் நோக்கம் என்ன?" ("What is the purpose of my
 * life?"). Scripture citations use Tamil book names throughout — ஆதியாகமம்
 * (Genesis), யோவான் (John), 1பேதுரு (1 Peter), ஏரேமியா (Jeremiah),
 * 1கொரிந்தியர் (1 Corinthians).
 *
 * The pages do declare `<html lang="ta">`, but that was NOT what decided this —
 * `persoalanhidup.com` declares `lang="id"` and serves Malay. The reading and
 * the codepoint census are the evidence.
 *
 * ⓘ **One 24-character Hindi fragment exists**, on `/a/prayers.html`: the
 * Devanagari string "सारांश प्रार्थना कैसे की जाए?" ("Summary: how should one
 * pray?"), a stray cross-link label from the Hindi banner. It is 0.2% of that
 * 11,172-char page and appears nowhere else. Not enough to affect anything; noted
 * so it is not mistaken later for a mixed-language source.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * ## Encoding — the missing charset parameter, and why it is harmless here
 *
 * ⚠️ Verified 2026-07-30: this host serves articles with a bare
 * `content-type: text/html` and **NO charset parameter** — the hazard several
 * hosts on this estate share. The bytes are nonetheless UTF-8: all 31 pages
 * declare `<meta http-equiv="content-type" content="text/html; charset=utf-8">`,
 * and **all 31 decode cleanly under a STRICT UTF-8 decoder** (0 files raised, 0
 * U+FFFD replacement characters anywhere). The only non-Tamil high codepoints in
 * the whole corpus are the typographic quotes and ellipsis. **There is no
 * mojibake.** ⓘ A `<meta charset>` sniff would be needed only if a fetcher
 * defaulted to Latin-1 on a charset-less `text/html`; defaulting to UTF-8 is
 * correct for this host.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. Roughly 90 sequential
 * plain-HTTP requests at ~1s spacing drew **zero 429s and no throttling**, so the
 * sibling default is kept rather than raised; at 31 articles the whole crawl is
 * well under a minute of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentTa: SourceEntry = {
  key: "everystudent-ta",
  name: "EveryStudent — Tamil (UngalThervuEnna.com)",
  domain: "www.ungalthervuenna.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ta"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ta"],
  defaultCategory: "article",
  rights:
    "© UngalThervuEnna.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.ungalthervuenna.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare anywhere). See header.
    sitemaps: ["/sitemap.xml"],
    // Every <loc> in the sitemap is `https://www.` — checked, because discover.ts
    // filters the RAW <loc> string and an http-publishing host would match none.
    allow: ["^https://www\\.ungalthervuenna\\.com/"],
    // The whole article corpus and nothing else: 31 of the 40 sitemap URLs.
    // `[^/]+` rather than a lowercase class — /a/Godreal.html carries an
    // uppercase G. Slugs are pure ASCII English words: verified zero non-ASCII
    // bytes and zero %XX escapes across all 40 <loc> values, so no Tamil script
    // appears in any URL.
    articleHints: ["^https://www\\.ungalthervuenna\\.com/a/[^/]+\\.html$"],
    block: [
      // The estate's "Who was Jesus?" page (25,957 chars) — curated highlights
      // from the Gospel of John carrying the family's own formula: excerpts
      // taken straight from the Bible with NO COMMENTARY ADDED. Because it is
      // predominantly Bible-translation text, it stays quarantined until its
      // translation, rights holder, reuse terms, and required attribution are
      // known and representable. The same temporary rule covers the full
      // Gospel-of-John pages and `everystudent-ar` Bible-PDF pages. This is the
      // ~20-26k curated version of the same thing; all 13
      // instances across the estate go together (campaign #111 §0.13).
      // NOT inert — sibling copies took ranks 7 and 8 on a cross question,
      // consuming top-10 slots a real answer would hold.
      // It matches the article shape, so only a URL block catches it.
      "^https://www\\.ungalthervuenna\\.com/a/whowas\\.html$",
      // The 7 section indexes (existence, questions, relationships, knowing,
      // forum, map, about) — headline+teaser link lists extracting 265-1,176
      // chars, so they CLEAR the 250 floor and only a URL block excludes them.
      // /m/map.html is the site plan (1,176 ch), the Tamil twin of the French
      // /plan.html. Also covers /m/intl.html, the language-index page, which is
      // live but absent from the sitemap.
      "^https://www\\.ungalthervuenna\\.com/m/",
      // The contact page: 340 chars ("எங்களைத் தொடர்புக் கொள்ளுங்கள்").
      "^https://www\\.ungalthervuenna\\.com/contact\\.html$",
      // The homepage. It does NOT extract to 0 — `html` matches on it exactly as
      // on an article, so it yields its full 1,162-char teaser list.
      "^https://www\\.ungalthervuenna\\.com/?$",
      // Dead nav links: 404 as of 2026-07-30. They are absent from the sitemap so
      // discovery cannot reach them today, but they ARE linked from the /m/
      // indexes, so a regenerated sitemap could quietly admit three 404 bodies.
      "^https://www\\.ungalthervuenna\\.com/a/(addiction|created|gaylesbian)\\.html$",
      // NOTE: no Gospel-of-John or "adventure/pack" signup block, and no full-
      // Scripture block. Both absences were MEASURED, not assumed — see header.
    ],
    // ⚠️ NOT the shared EveryStudent template. Measured 2026-07-30 over all 31
    // articles: `.content4` MATCHES on 31/31 and extracts 0 chars, while
    // `.contentpadding`, `#content4`, `.content4b` and even <body> do not match
    // at all — a stray </sitelevel_noindex> closes the content div stack early
    // and flattens the article into <html>'s direct children. `<html>` is the
    // only element that still contains it.
    // Do NOT add `.contentpadding` or `.content4` here, in any position: the
    // first selector that MATCHES wins regardless of the text it yields, so
    // `.content4` would bind the empty spacer and return "" — every article
    // skipping `too-thin` on an HTTP 200. For the same reason a TRAILING "html"
    // fallback would never fire; it has to be the sole entry.
    contentSelectors: ["html"],
    stripSelectors: [
      // These four carry real weight here BECAUSE the container is <html>:
      // script 1,948 ch/page, style 1,140 ch/page.
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form", // 93 instances (FreeFind search boxes), 0 chars
      // Required because the container is <html>: drops the duplicate <title>
      // (31 ch/page once script+style are already gone). extract.ts reads the
      // title from `root` BEFORE the strip loop — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-30 (see header):
      "sitelevel_noindex", // custom TAG, 2/page, 2,063 ch/page: cookie bar + nav, and share + sidebar + footer
      ".likesharediv", // 2/page share row; 0 ch in list order (its text is <script> payload)
      ".a2a_kit", // AddToAny buttons, 2/page, 0 ch (image-only)
      ".fccell", // "FEATURE CLOSE" CTA cells — 146 instances, 123 ch/page
      ".hr2", // 87 empty presentational divs, 0 ch
      ".articledivider", // 27 instances, 0 ch
      ".articledividerforum", // 4 instances (4 pages), 0 ch
      // Deliberately ABSENT: `.fctable`, `.shareiconsmenupg` and `.relatedbottom`
      // are each 0 instances on this host (measured). They cannot bind, so they
      // are omitted rather than carried as sibling parity.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 60, // 40 sitemap URLs (31 kept after filtering) + headroom
    minContentLength: 250,
  },
};
