/**
 * EveryStudent — Nepali (nepalistudent.net, "NepaliStudent.net"). The Nepali
 * banner of Cru's seeker-facing Q&A ministry: short apologetics and life-issue
 * articles plus first-person testimonies, written for Nepali-speaking students
 * who are not believers. A sibling of `everystudent` (en), `everystudent-pl`,
 * `everystudent-sq`, `everystudent-ur`, `everystudent-bn`, `everystudent-te`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). nepalistudent.net is its own domain, so it gets its own
 * key, the same way `everystudent-pl` (kazdystudent.pl), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ⚠️ **The TLD is `.net`, not `.com`.** Every regex, `domain` and `baseUrl`
 * below is pinned to `www.nepalistudent.net`; a `.com` pin would match nothing.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-30: ~70 plain-HTTP GETs with a full desktop-Chrome UA
 * (/robots.txt, /sitemap.xml, /sitemap_index.xml, all 28 sitemap URLs, the four
 * extra `/a/` paths found by link harvest, plus a 28-URL HEAD sweep and ~13
 * probes for signup pages). **Every response is `server: Apache` with no
 * Cloudflare layer at all** — no `cf-ray`, no `cf-cache-status`, and no
 * block-page signature anywhere. So `fetchStrategy` is intentionally OMITTED:
 * plain HTTP is the default and nothing here needs Firecrawl (ADR-0012).
 * Discovery is therefore free, making this a **discovery crawl** rather than the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-pl`, `everystudent-sq`.
 *
 * The bare apex **301-redirects to `www`** (measured on `/`, `/robots.txt` and
 * `/sitemap.xml` — all three), so `www.nepalistudent.net` is the canonical host
 * and the one every `<loc>` uses. Checked in both directions: `www.` serves 200
 * directly and never redirects to the apex. This host is therefore the NORMAL
 * way round, not the `everystudent.sk` reversal.
 *
 * ## robots.txt — there isn't one
 *
 * Verified 2026-07-30: `https://www.nepalistudent.net/robots.txt` returns **HTTP
 * 404** (`content-type: text/html`), serving the site's ordinary Nepali "क्षमा
 * प्रार्थी छौ" ("we're sorry") not-found page rather than any rules. There is no
 * `Disallow` anywhere on this domain, so **no path below is blocked on robots
 * grounds** — every exclusion in `block` is a content-quality call I can defend
 * on measured evidence. Nothing needed hand-blocking to honour a rule that does
 * not exist.
 *
 * ## Sitemap — 28 entries, exactly as recon said, and `https://` scheme
 *
 * Verified 2026-07-30: `https://www.nepalistudent.net/sitemap.xml` → HTTP 200,
 * **4,670 bytes**, `application/xml`, a single flat `<urlset>` (no
 * `<sitemapindex>`, so no recursion), generated by xml-sitemaps.com. It holds
 * **28 `<loc>` elements, all distinct — zero delta from the brief's "~28"**.
 * `/sitemap_index.xml` was also tried and returns **404**, so there is no live
 * Yoast index hiding a larger set the way `everystudent.sk` had. `<lastmod>`
 * values run 2024-02-15 → 2024-04-12, so this is a 2024 file, not a fossil.
 *
 * ⚠️ **Every `<loc>` uses the `https://` scheme** (checked on all 28), so the
 * `^https://` pin below discovers all of them. This is NOT the `everystudent.gr`
 * situation where the sitemap publishes `http://` and `discover.ts` — which
 * filters the RAW `<loc>` string without normalising — would match zero.
 *
 * The 28 break down as:
 *   - **18 `/a/<slug>.html`** — the article corpus in the sitemap.
 *   - **8 `/m/<slug>.html`** — section indexes (`existence`, `life`,
 *     `relationships`, `knowing`, `faq`, `intl`, `sitemap`, `about`). BLOCKED.
 *   - **`/contact.html`** — the contact form. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 *
 * A HEAD sweep of all 28 on 2026-07-30 returned **26 × 200 and 2 × 404**
 * (`/m/relationships.html`, `/m/faq.html`) — and **zero redirects of any kind**.
 * There is no dead-URL cohort redirecting to the homepage of the sort a sibling
 * shipped 25 of, so nothing is blocked on that ground. All **18 `/a/` URLs are
 * live 200s.** The two 404s are `/m/` pages already excluded twice over (by
 * `articleHints` and by the `/m/` block), and `acquire.ts` drops any status ≥ 400
 * before extraction anyway.
 *
 * ✅ **Slugs are pure ASCII English, despite the Devanagari body text.** All 28
 * `<loc>` values were scanned for non-ASCII bytes and for `%XX` percent-encoding:
 * **zero hits of either**. The site keeps English slugs (`/a/why-did-jesus-die.html`)
 * and puts Nepali only in the page text, so the ASCII-safe hint below drops
 * nothing. One slug is **mixed-case — `/a/know-God.html`** — so the hint uses
 * `[^/]+` rather than `[a-z0-9-]+`; a lowercase-only class would silently lose
 * that article.
 *
 * ## Cross-checks — the XML sitemap is SHORT by 2 live articles, both pinned
 *
 * These generated sitemaps are known to lag, so two wider nets were cast.
 *
 * **1. The site's own HTML map, `/m/sitemap.html` ("नक्शा" / "map").** Verified
 * 2026-07-30: it links **19 `/a/` URLs — one more than the XML sitemap**. The
 * extra is **`/a/prayer.html`**, and it is a genuine, substantial article:
 * "के परमेश्वरले हाम्रो प्रार्थनाको उत्तर दिनुहुन्छ?" ("Does God answer our
 * prayers?") by Marilyn Adamson, **10,885 chars extracted**, closing on its own
 * 16-item scripture-footnote list. Nothing in the XML sitemap contains it, so
 * **discovery alone would lose it** — it is pinned in `seedPaths`.
 *
 * **2. Every internal `href` on all 28 fetched pages** (30 distinct internal
 * URLs). That adds four `/a/` paths the XML sitemap lacks; two are live and two
 * are dead:
 *   - **`/a/fol.html` — LIVE, 2,806 chars, pinned.** "परमेश्वर को साथ सुरुवात"
 *     ("Starting with God"), linked from three articles. Read in full: it is a
 *     post-decision follow-up ARTICLE, not a signup form — it answers "यदि मैले
 *     उहाँलाई यसमा आमन्त्रित गरें भने येशू साँच्चै मेरो जीवनमा हुनुहुन्छ भनेर कसरी थाहा
 *     पाउने?" ("How do I know Jesus is really in my life if I invited him in?")
 *     from 1 John 5:14, Rev 3:20, John 6:37, John 10:27-28, 1 Peter 3:18 and
 *     Phil 4:6-7, then gives guidance on growing in the relationship. It carries
 *     no subscription pitch and no form copy — the closest it comes is a closing
 *     "email us with your questions". Pinned. ⓘ Its Albanian twin
 *     `/a/ungjillin2.html` is blocked in `everystudent-sq`, but only because
 *     robots.txt there named that exact path; this host has no robots.txt at all,
 *     so that reason does not carry over. A reviewer could reasonably drop it; it
 *     costs one document either way.
 *   - **`/a/faith.html` and `/a/real-life.html` — DEAD (HTTP 404).** Broken links
 *     out of `/a/is-there-a-god.html` and `/a/purpose-in-life.html`. Their 404
 *     body still extracts **488 / 492 chars** of "क्षमा प्रार्थी छौ" plus a
 *     popular-articles list, i.e. **well clear of the 250 floor** — but they are
 *     absent from the sitemap, are not seeded, and `acquire.ts` rejects a 404
 *     before extraction, so no URL block is needed. Recorded here because a
 *     regenerated sitemap that picked them up would stage two near-identical
 *     copies of the site's not-found page.
 *
 * So the expected yield is **20 documents** — the 18 sitemap articles plus the 2
 * pinned seeds. `acquire.ts` unions seeds with discovered URLs, so the 2 pins do
 * not disturb discovery.
 *
 * ## ⚠️ minContentLength cannot be relied on to catch the non-articles
 *
 * Every page in `block` was fetched and extracted with the repo's own
 * `extractContent`. Verified 2026-07-30:
 *   - **`/` — 697 chars.** The homepage has **no `.contentpadding` and no
 *     `<body>` in the parsed tree**, so extraction falls to the `html` container
 *     and returns the whole teaser list, NOT nothing. This is exactly the trap:
 *     a missing content selector yields the page, not an empty string.
 *   - **`/m/existence.html` 666, `/m/knowing.html` 617, `/m/life.html` 819
 *     chars.** Same shape as the homepage: no `.contentpadding`, so the `html`
 *     container returns a headline+teaser link list.
 *   - **`/m/about.html` — 842 chars** of about + cookie/privacy boilerplate.
 *   - **`/m/sitemap.html` — 728 chars** of pure link list (the site plan).
 *   - **`/m/intl.html` — 12 chars** ("अन्य भाषाहरू", "Other languages") — the page
 *     linking out to the sibling language domains.
 *   - **`/contact.html` — 221 chars** ("कुनै प्रश्न छ ?", "Have a question?").
 *     The one page here the 250 floor WOULD have caught; blocked anyway so the
 *     decision does not depend on it staying 29 chars short.
 * Five of those seven clear the floor comfortably, so the `block` list is doing
 * real work rather than decorating.
 *
 * ## No Gospel-of-John signup, no email series, and no full Scripture
 *
 * All three absences were **measured, not assumed**.
 *   - **No email-signup landing pages exist on this host.** Probed 2026-07-30:
 *     `/john.html`, `/jean.html`, `/pack.html`, `/adventure.html`,
 *     `/yohanna.html`, `/yuhanna.html`, `/a/john.html`, `/4laws.html`,
 *     `/yeshu.html`, `/video.html`, `/m/video.html` — **all 404**. The Nepali
 *     banner has no twin of the French `/jean.html` or the Albanian
 *     `/aventures.html`, so there is nothing of that kind to block.
 *   - **No page carries verbatim Scripture.** All 20 articles were scanned for
 *     verse-reference density (Devanagari-digit `chapter:verse` patterns). The
 *     maximum is **3.9 refs per 1,000 chars**, and the longest article on the
 *     whole host is 22,357 chars — nothing remotely like the 98,887-char complete
 *     Gospel of John that `everystudent-sq` had to block.
 *   - **`/a/bible.html` is an apologetics essay ABOUT the Bible and is KEPT.**
 *     "के तपाईं बाइबलमा भरोसा गर्न सक्नुहुन्छ?" ("Can you trust the Bible?"),
 *     22,357 chars, 72 verse references. Told apart from Scripture on structure,
 *     not on length: its verse citations are scattered footnote markers inside
 *     argumentative prose about authorship, archaeology and manuscript
 *     transmission, and it ends on a **secondary-source bibliography** (Strobel,
 *     Geisler, McDowell, F.F. Bruce, Tacitus). Verbatim Scripture would instead
 *     run sequential chapter-and-verse with no argument and no bibliography.
 *   - **No third-party Bible-society copyright.** The only `©` in the whole
 *     corpus is an author byline, "© डा. रिचर्ड पुर्नेल" (Dr. Richard Purnell). The
 *     one "Tyndale" string is a book citation ("Tyndale Press, 1946"), not a
 *     Tyndale House Foundation text licence. The `rights` line below does not
 *     misattribute anyone.
 *
 * ## Extraction — measured on THIS host, every candidate, including the zeros
 *
 * Verified 2026-07-30 by running the repo's own `extractContent`
 * (node-html-parser, exactly as `src/acquisition/extract.ts` does) over all 20
 * article pages — not grepped, because every one of these class names is also
 * declared in the page's inline `<style>` block and a grep false-positives on all
 * of them. Character counts are the extracted text of the FIRST matching element:
 *
 *   - **`.contentpadding` — 1 instance on 20/20 articles, 2,806-22,512 chars.**
 *     The whole article: section kicker, title, subhead, byline, body and
 *     footnote list. **This is the container, and it ships first.**
 *   - **`.content4` — 1 instance on 20/20 articles, and it extracts 0 chars on
 *     every single one.** An empty spacer div. Listing it ahead of
 *     `.contentpadding` would bind the spacer and skip every article as
 *     `too-thin` on an HTTP 200 — the batch-1 failure. It is deliberately absent.
 *   - **`#content4` (the ID form) — 0 matches.** Absent from this host.
 *   - **`.content4b` — 0 matches.**
 *   - **`.cb-entry-content`, `.entry-content`, `.contentleftpadding`,
 *     `.article-content`, `.content` — 0 matches each.**
 *   - **`.post-content` — 0 matches on articles** (1 match, 83 chars, on the
 *     homepage only).
 *   - **`.articletitle` — 1 instance, 18-47 chars.** A headline, not a body.
 *   - **`.articlebody`, `<article>`, `<main>` — 0 matches each.**
 *   - **`<body>` — absent from the parsed tree on all 20 articles.** So without
 *     an explicit container the fallback would be the document ROOT, not `<body>`.
 *   - **`html` — matches everywhere, 21,923-40,885 chars unstripped.**
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**: `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text.
 * That is why `.content4` must never appear in this list.
 *
 * ✅ **`"html"` is appended as the LAST entry and is safe here.** `.contentpadding`
 * matched with NON-ZERO text on 20 of 20 articles — there is no matched-but-empty
 * page for it to be shadowed by, so the fallback can only fire if the primary
 * genuinely misses (e.g. a future page whose div tree collapses on malformed
 * markup, the way `everystudent-pl`'s `/a/biblia.html` did). Nothing follows it,
 * so it cannot shadow anything, and it beats `extractContent`'s implicit `?? root`
 * because `<html>` is a real element and carries no literal `<!DOCTYPE html>`
 * text node. It is paired with `"head"` in `stripSelectors` (see below).
 *
 * **Measured with the shipped config across all 20 articles: 2,806 - 22,357
 * chars, median 12,690, and 0 pages below the 250 floor.**
 *
 * ⓘ Two articles share the title "येशू किन मर्नुभयो?" ("Why did Jesus die?") —
 * `/a/relationship-with-god.html` and `/a/why-did-jesus-die.html`. They are NOT
 * duplicates: measured 2026-07-30, their 12-word shingle overlap is **0.3%**
 * (10,470 vs 9,639 chars). One is Marilyn Adamson's treatment, the other opens on
 * crucifixion as a punishment reserved for the worst criminals. Both are kept.
 *
 * ## Chrome stripped — what each selector actually removed, in chars
 *
 * Measured 2026-07-30 inside the bound `.contentpadding` scope across all 20
 * articles. "Isolated" = the chars that selector removes on its own; several
 * overlap, so isolated figures do not sum to the total.
 *
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **40 instances (2 per page),
 *     1,679 chars / ~84 per page** — the "अरूलार्इ पठाउनुहोस्" ("send to others")
 *     share row and the "कुनै प्रश्न छ ? / ► नक्शा / ► सरवरको बारेमा" related-links
 *     block. The missing leading `.` is correct, not a typo. Biggest share-side
 *     contributor.
 *   - **`.shareiconsmenupg` — 19 instances, 399 chars isolated (~20/page), but
 *     0 chars MARGINAL.** ⓘ On THIS host the enclosing `<sitelevel_noindex>` is
 *     **well-formed and already contains it**, so once that is stripped first this
 *     selector matches nothing. It is a **no-op kept purely as a drift guard** —
 *     NOT "required because the markup is malformed", which was not measured here
 *     and is not true here.
 *   - **`.fctable` — 18 instances, 2,404 chars isolated (~120/page)** — the
 *     "FEATURE CLOSE" call-to-action table appended to every article.
 *   - **`.fccell` — 98 instances, 2,575 chars isolated (~129/page)** — its cells
 *     ("► भर्खरै मात्र मैले येशुलाई मेरो जीवनमा बोलाएँ…", "I just invited Jesus into
 *     my life…"). **Both are listed and both are needed**: together they remove
 *     2,505 chars, and `.fctable` is absent on 2 of the 20 pages (e.g.
 *     `/a/know-God.html`) where `.fccell` alone catches the block.
 *   - **`.a2a_kit` — 38 instances, 0 chars.** The AddToAny share row; its buttons
 *     are images and `structuredText` does not read `alt`. Stripped anyway so a
 *     markup change adding text labels cannot leak them into every article.
 *   - **`.hr2` (42 instances) and `.articledivider` (20) — 0 chars each.** Empty
 *     presentational divs drawing the rules bracketing the CTA block.
 *   - **`head` — 0 instances inside `.contentpadding`, 0 chars on every healthy
 *     page.** It exists only to serve the `"html"` fallback path, where it drops
 *     the duplicated `<title>`. Safe because `extract.ts` reads the title from
 *     `root` at line 43, BEFORE the strip loop at line 52 — an edit that reorders
 *     those two steps would lose the title, so keep them in that order.
 *   - **`.relatedbottom` — 0 instances. OMITTED**, not carried as a parity no-op:
 *     it cannot bind on this host, and every earlier sibling measured it at 0 too.
 *
 * After the full strip list, all 20 articles were re-scanned for leftovers: no
 * "अरूलार्इ पठाउनुहोस्", no "कुनै प्रश्न छ ?", no "► नक्शा", no "► सरवरको बारेमा",
 * and no CTA line survives anywhere.
 *
 * ## Language: `["ne"]` — READ, and separated from Hindi by counting
 *
 * Verified 2026-07-30 by reading the extracted text myself. The pages serve
 * genuine Nepali prose, not untranslated English and not Hindi.
 * `/a/is-there-a-god.html` is titled "के परमेश्वर हुनुहुन्छ?" ("Is there a God?");
 * `/a/purpose-in-life.html` is "मेरो जीवनको उद्देश्य के?" ("What is the purpose of
 * my life?"); `/a/prayer.html` narrates "जतिबेला म नास्तिक थिएँ, मेरो एक जना मिल्ने
 * साथी थिइन्" ("When I was an atheist, I had a close friend…");
 * `/a/tragedy.html` is "विपत्तिको बीचमा परमेश्वर कहाँ छन्?" ("Where is God in the
 * midst of disaster?"). Scripture citations use Nepali book names throughout
 * (यूहन्ना = John, भजनसंग्रह = Psalms, यर्मिया = Jeremiah, रोमी = Romans,
 * फिलिप्पी = Philippians, प्रकाश = Revelation) and verse numbers are written in
 * **Devanagari digits (०-९)**, not Arabic ones.
 *
 * ⚠️ **Nepali and Hindi share the Devanagari script, so "it's Devanagari" proves
 * nothing** — and the Hindi banner (everystudent.in) is being catalogued in the
 * same batch. They were separated on counted evidence over the 212,624-char
 * extracted corpus, with a **mark-aware** word boundary,
 * `(?<![\p{L}\p{M}])…(?![\p{L}\p{M}])`. (A naive `\p{L}`-only boundary is WRONG
 * for Devanagari: matras such as ा and ै are `\p{Mn}`, not letters, so it matched
 * है inside थाहै and था inside अवस्था and reported false Hindi hits. That is the
 * same class of error that flipped the Croatian/Serbian call in batch 3.)
 * Head-to-head, on the same corpus:
 *
 *   | meaning           | Nepali form | hits | Hindi form | hits |
 *   |-------------------|-------------|-----:|------------|-----:|
 *   | "is"              | छ           |  325 | है         |    0 |
 *   | "are"             | छन्          |  111 | हैं        |    0 |
 *   | "was"             | थियो        |  170 | था         |    0 |
 *   | "becomes"         | हुन्छ        |   85 | होता       |    0 |
 *   | "in" (locative)   | मा          |   11 | में        |    0 |
 *   | polite imperative | गर्नुहोस्     |   28 | कीजिए      |    0 |
 *
 * Plus **200 × हो** (Nepali equative "is"), **254 × हामी**, **77 × तपाईं**, and
 * **0 combined hits** for the Hindi-exclusive vocabulary नहीं / और / किया / में /
 * है / हैं. The verdict is not close: **hundreds of Nepali copulas, zero Hindi
 * ones.** (ⓘ Two caveats worth recording. First, मा and लाई score low as free
 * words because Nepali writes them as bound postpositions — संसारमा, परमेश्वरलाई —
 * so a word-boundary count under-reads them; that is expected, not contrary
 * evidence. Second, the 183 hits for के are **Nepali "what?"**, the interrogative,
 * not the Hindi oblique genitive — every title on this Q&A site that asks a
 * question uses it, e.g. "मेरो जीवनको उद्देश्य के?")
 *
 * ⚠️ **`<html lang>` was NOT trusted, and it is a good thing.** This host declares
 * `lang="np"`, which is not a valid ISO 639-1 code at all (Nepali is `ne`; `np`
 * is the ISO 3166 country code for Nepal). The `["ne"]` above comes from the text
 * I read and counted, not from that attribute.
 *
 * **Encoding, checked because the script is non-Latin.** The response header is a
 * bare `content-type: text/html` with **no charset parameter**; the charset is
 * declared only in-page as `<meta http-equiv="content-type"
 * content="text/html; charset=utf-8">`. The bytes are genuine UTF-8 Devanagari
 * and extract as readable text with no mojibake — verified by reading the output,
 * quoted throughout this docstring.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. We pay this host's bandwidth
 * directly rather than proxying through Firecrawl, so it is real politeness, but
 * nothing in the probes argued for more: ~70 sequential plain-HTTP requests drew
 * zero 429s and no throttling, and at 20 pages the whole crawl is ~20 seconds.
 */
import type { SourceEntry } from "./types.js";

export const everystudentNe: SourceEntry = {
  key: "everystudent-ne",
  name: "EveryStudent — Nepali (NepaliStudent.net)",
  domain: "www.nepalistudent.net",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ne"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ne"],
  defaultCategory: "article",
  rights:
    "© NepaliStudent.net (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.nepalistudent.net",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare of any kind). See header.
    sitemaps: ["/sitemap.xml"],
    // NOTE the .net TLD. Scheme is ^https:// because all 28 <loc> values are
    // https (checked) — discover.ts filters the raw <loc> without normalising.
    allow: ["^https://www\\.nepalistudent\\.net/"],
    // The article corpus: 18 of the 28 sitemap URLs. `[^/]+` rather than a
    // lowercase class — /a/know-God.html carries an uppercase G. Slugs are pure
    // ASCII English (verified: zero non-ASCII bytes, zero %XX escapes across all
    // 28 <loc> values), so an ASCII-safe hint loses nothing despite the
    // Devanagari body text.
    articleHints: ["^https://www\\.nepalistudent\\.net/a/[^/]+\\.html$"],
    // Two live articles the XML sitemap OMITS. acquire.ts unions seeds with
    // discovered URLs, so pinning them costs nothing and discovery is unaffected.
    //  - /a/prayer.html: "Does God answer our prayers?" (Marilyn Adamson),
    //    10,885 ch — listed on the site's own HTML map /m/sitemap.html but NOT
    //    in /sitemap.xml. Discovery alone would lose it.
    //  - /a/fol.html: "Starting with God", 2,806 ch — in neither map; found by
    //    harvesting hrefs across all 28 fetched pages. A real follow-up article
    //    answered from 1 John 5:14 / Rev 3:20 / John 6:37, not a signup form.
    seedPaths: ["/a/prayer.html", "/a/fol.html"],
    block: [
      // The 8 section indexes (existence, life, relationships, knowing, faq,
      // intl, sitemap, about). /m/existence, /m/knowing and /m/life have NO
      // .contentpadding, so the `html` container returns 617-819 ch of
      // headline+teaser link list — well clear of the 250 floor, which therefore
      // could not catch them. /m/sitemap.html is the site plan (728 ch);
      // /m/about.html is about + cookie boilerplate (842 ch); /m/intl.html is the
      // page linking out to the sibling language domains (12 ch).
      "^https://www\\.nepalistudent\\.net/m/",
      // The contact form, "कुनै प्रश्न छ ?" — 221 ch. The one page here the floor
      // would also have caught; blocked so the decision does not depend on it.
      "^https://www\\.nepalistudent\\.net/contact\\.html$",
      // The homepage. It does NOT extract to 0: it has no .contentpadding and no
      // <body>, so the `html` container yields its full 697-ch teaser list.
      // Only a URL block excludes it.
      "^https://www\\.nepalistudent\\.net/?$",
    ],
    // ONLY `.contentpadding` first — measured 2026-07-30 as the sole element that
    // extracts the article (2,806-22,512 ch on 20/20 pages). `.content4` is
    // deliberately ABSENT: it matches on 20/20 and extracts 0 chars, and because
    // extractContent scopes to the first selector that MATCHES rather than the
    // first that yields text, listing it would make every page skip `too-thin`.
    // `#content4`, `.content4b`, `.entry-content`, `.article-content`, `.content`
    // and `<body>` do not exist on this host at all.
    // `"html"` is a genuine LAST-resort fallback: the primary never matches empty
    // here, so it can only fire if a page's div tree collapses on broken markup
    // (the everystudent-pl /a/biblia.html failure). Nothing follows it, so it
    // cannot shadow anything.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // 0 chars on every healthy page (0 instances inside .contentpadding); it
      // exists for the `html` fallback path, where it drops the duplicate
      // <title>. Safe only because extract.ts reads the title from `root` BEFORE
      // the strip loop — keep that order.
      "head",
      // Site-specific chrome — all counted on this host 2026-07-30 (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 40 inst / 1,679 ch: share row + related links
      ".shareiconsmenupg", // 19 inst / 399 ch isolated, but 0 MARGINAL — the
      // enclosing <sitelevel_noindex> is well-formed HERE and already contains
      // it. A pure drift guard, not a malformed-markup workaround.
      ".fctable", // "FEATURE CLOSE" CTA table — 18 inst / 2,404 ch isolated
      ".fccell", // its cells — 98 inst / 2,575 ch isolated. BOTH are needed:
      // .fctable is absent on 2 of 20 pages, where .fccell alone catches the CTA.
      ".a2a_kit", // AddToAny share row — 38 inst, 0 ch (image-only buttons today)
      ".hr2", // 42 inst, 0 ch — empty rules bracketing the CTA block
      ".articledivider", // 20 inst, 0 ch
      // `.relatedbottom` is deliberately OMITTED: 0 instances here, and it has
      // never bound on any sibling. Not carried as a parity no-op.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 60, // 28 sitemap URLs + 2 pinned seeds (20 kept) + headroom
    minContentLength: 250,
  },
};
