/**
 * EveryStudent — Georgian (kovelistudenti.com, "KoveliStudenti.com" / "Every
 * Student"). The Georgian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles plus first-person testimonies, written for
 * Georgian-speaking students who are not believers. The site's own about page
 * names its publisher outright — "ეს საიტი შექმილია საერთაშორისო ქრისტიანული
 * ორგანიზაციის: Campus Crusade for Christ, International– მიერ" ("this site was
 * created by the international Christian organisation Campus Crusade for Christ,
 * International").
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain = one
 * source (ADR-0006). kovelistudenti.com is its own domain, so it gets its own
 * key, exactly as `everystudent-sq` (pyetjetejetes.com), `everystudent-it`
 * (ognistudente.com), `everystudent-fr` (questions2vie.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## 🔴 THE #111 "NO SHARED-TEMPLATE SELECTORS" FLAG WAS A FALSE ALARM
 *
 * This host was the last one in the estate carrying that warning, and the
 * campaign expected a tenth distinct generator. It is not one. Verified
 * 2026-07-30: this is the **hand-built EveryStudent "esintl2013" static
 * template** — no `<meta name="generator">` at all, no CMS, plain Apache serving
 * flat `.html` files, styled by `/css/lessframework2013.css` +
 * `/css/esintl2013.css`, with its favicon pulled from the estate's shared asset
 * host `https://1.everystudent.com/2013/img/favicon.png`. The `/a/` (articles)
 * and `/m/` (menu/section indexes) namespaces are the familiar sibling layout.
 *
 * **#111 missed it for one character.** The template's outer content column is
 * `id="content4"` — an ID, NOT a class — so a scan for `.content4` finds
 * nothing. This is the exact hazard `everystudent-el` hit. Measured here:
 * `.content4` matches **0 of 24** fetched pages while `#content4` matches
 * **18 of 24**. Nothing was wrong with the host; the probe was looking for the
 * wrong selector form. **No tenth generator exists.**
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-30: robots.txt, `/sitemap.xml`, `/m/sitemap.html`, all 25
 * sitemap URLs and 14 extra slug probes were fetched with plain `curl` carrying
 * a desktop-Chrome UA. **All 25 sitemap URLs returned HTTP/2 200 with real HTML
 * and an empty redirect_url.** Every response is `server: Apache`; there is no
 * `cf-ray` header on any of the 26 responses and no page carries a block-page
 * signature (grepped for "Attention Required", "cf-error-details", "Just a
 * moment", "cf-browser-verification": 0 hits). So `fetchStrategy` is
 * intentionally OMITTED — plain HTTP is the default (ADR-0012) — and discovery
 * is free, making this a discovery crawl rather than a hand-listed seed set.
 * Precedent: `thelife-fr`, `everystudent-sq`, `everystudent-it`.
 *
 * The bare apex **301-redirects to `www`** (measured on `/`: apex → 301 →
 * `https://www.kovelistudenti.com/`), so `www.` is canonical, it is what every
 * `<loc>` emits, and it is what `domain`, `baseUrl` and every regex are pinned
 * to. (`everystudent.sk` redirects the other way; this one does not.)
 *
 * ## robots.txt — one Disallow, and it names an `/a/` page
 *
 * Verified 2026-07-30, HTTP 200. The whole file is:
 *
 *     User-agent: *
 *     Disallow: a/fol.html
 *
 * Note the missing leading slash — malformed per the robots spec, but the intent
 * is unmistakable. ⚠️ **The acquire path does not enforce robots.txt (known
 * gap), so this is honoured BY HAND in `block` below.** `/a/fol.html` returns
 * 200 and extracts **381 chars** ("ახლა ვთხოვე იესოს შემოვიდეს ჩემ ცხოვრებაში" —
 * the post-decision follow-up contact form), so it clears the 250 floor and
 * matches `articleHints`; neither would have excluded it. It is absent from
 * `/sitemap.xml`, so discovery cannot reach it today — blocked anyway so the
 * rule is enforced rather than merely observed. Nothing else is disallowed.
 *
 * ## Sitemap — 25 entries, all live, and the recon count is EXACT
 *
 * Verified 2026-07-30: `https://www.kovelistudenti.com/sitemap.xml` → HTTP 200,
 * 2,262 bytes, `application/xml`, a single flat `<urlset>` (no `<sitemapindex>`,
 * so no recursion), generated by xml-sitemaps.com. 25 `<loc>` elements, **25
 * distinct URLs**, zero duplicates — matching the brief's "~25" with no delta.
 * `/sitemap_index.xml` is **404**, so there is no Yoast-style index hiding a
 * larger set. The breakdown:
 *   - **16 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **6 `/m/<slug>.html`** — the section indexes (arseboba100, daieso200,
 *     gamocdileba300, movelenebi500, gamocanebi600, shesaxeb803). Navigation.
 *   - **`/` and `/index.html`** — the homepage, listed twice.
 *   - **`/kontakt801.html`** — the contact form.
 *
 * ⚠️ **The sitemap's `Last-Modified` is 2017-10-03 — it is an 8-year-old
 * fossil**, the same shape of hazard that made `everystudent.sk`'s "44 URLs"
 * wrong. Here the fossil turned out to be ACCURATE, and that was measured, not
 * assumed: `/m/sitemap.html` (the site's own HTML map, itself absent from the
 * XML) lists exactly the same 16 `/a/` articles, and harvesting every internal
 * `href` across all 25 fetched pages plus the HTML map turned up only **two**
 * on-site `/a/` URLs the XML lacks, neither of them a live article:
 *
 *   | URL found on-site  | What it is                                       |
 *   |--------------------|--------------------------------------------------|
 *   | `/a/fol.html`      | 200, 381 ch — robots-disallowed follow-up form    |
 *   | `/a/omi216.html`   | **301 → the homepage** (linked from /m/daieso200) |
 *
 * So **`seedPaths` is deliberately absent: there is nothing to pin.** No article
 * is missing from the XML sitemap.
 *
 * `<loc>` **scheme is `https://` on all 25** (checked — `everystudent.gr` emits
 * `http://` and would need `^https?://`; this host does not). `allow` and
 * `articleHints` are pinned to `^https://` accordingly.
 *
 * ## Slugs are Latin-transliterated Georgian, and TWO carry uppercase
 *
 * The pages are Georgian but the URLs are not: all 25 `<loc>` values are pure
 * ASCII — **0 non-ASCII bytes, 0 `%XX` percent-escapes** (both checked, not
 * assumed), because the slugs are romanised (`shevicnoth401`, `khangrdzlivi502`,
 * `pasukhobs309`). But `/a/Ghmerti101.html` and `/a/Ghmerti109.html` carry a
 * capital G, so **an `[a-z0-9-]+` article hint would silently drop 2 of the 16
 * articles.** `[^/]+` is used, which also keeps the door open if a future slug
 * arrives in Mkhedruli script or percent-encoded.
 *
 * ## ⚠️ EXTRACTION — `.contentpadding`, measured, with `html` as a real fallback
 *
 * Every candidate in the estate's catalogue was run through the repo's own
 * parser (`node-html-parser`, exactly as `src/acquisition/extract.ts` uses it)
 * over all 24 fetched HTML pages on 2026-07-30 — measured, not grepped:
 *
 *   | Candidate             | Matched pages | Extracted chars      |
 *   |-----------------------|---------------|----------------------|
 *   | `.contentpadding`     | 18/24         | **346 – 29,305**     |
 *   | `#content4` (ID)      | 18/24         | 346 – 29,305         |
 *   | `html`                | 24/24         | 3,490 – 32,549       |
 *   | `body`                | 24/24         | 2,034 – 31,072       |
 *   | `#contentwrapper`     | 24/24         | 356 – 29,394         |
 *   | `.articletitle`       | 18/24         | **5 – 62** ⚠️        |
 *   | `.content4` (class)   | **0/24**      | never matches        |
 *   | `.cb-entry-content`   | **0/24**      | never matches        |
 *   | `.entry-content`      | **0/24**      | never matches        |
 *   | `.post-content`       | **0/24**      | never matches        |
 *   | `.contentleftpadding` | **0/24**      | never matches        |
 *   | `.article-content`    | **0/24**      | never matches        |
 *   | `.content`            | **0/24**      | never matches        |
 *   | `.content4b`          | **0/24**      | never matches        |
 *   | `article`, `main`     | **0/24**      | never matches        |
 *
 * **Zero matched-but-empty pages for `.contentpadding`** — the `everystudent-sq`
 * failure mode (matched on 52/78 pages and extracted 0 chars) does NOT occur
 * here. The 6 pages it misses are the homepage (twice) and 5 of the 6 `/m/`
 * indexes, all of which are excluded by `articleHints` and blocked below.
 *
 * `#content4` and `.contentpadding` measure IDENTICALLY because the DOM is
 * `#contentwrapper > #content4 > .contentpadding`, and `#content4` has exactly
 * one element child. The tighter inner `.contentpadding` ships, so a future
 * template change that adds a related-articles block between the two cannot leak
 * it into every article.
 *
 * ⚠️ **`.articletitle` is the shadow trap on this host.** It matches 18/24 and
 * yields 5–62 characters — the `<h1>` alone. It sits THIRD in the sibling
 * selector list copied across the walled banners (`.content4`, `.content4b`,
 * `.articletitle`, `.contentpadding`). Since `.content4` and `.content4b` both
 * miss here, pasting that list onto this host would bind `.articletitle` and
 * stage 16 documents of ~20 characters each. `contentSelectors` is NOT a
 * fallback chain: `extractContent` binds the first selector that MATCHES AN
 * ELEMENT, not the first that yields text. Do not add `.articletitle`.
 *
 * **`html` IS appended, as a genuine last resort.** It is safe here precisely
 * because `.contentpadding` has zero matched-but-empty pages: it can only fire
 * when the primary MISSES, nothing follows it so it can shadow nothing, and it
 * beats `extractContent`'s implicit `body ?? root` fallback because `<html>` is
 * a real element carrying no literal `<!DOCTYPE html>` text node. It is paired
 * with `"head"` in `stripSelectors` — measured at 0 chars on every healthy page
 * (there is no `<head>` inside `.contentpadding`) and at 23 chars on the
 * fallback path, where it drops the duplicated `<title>`. Safe because
 * extract.ts reads the title from `root` at line 43, BEFORE the strip loop at
 * line 52.
 *
 * **Measured end state with the shipped policy across the 16 kept articles:
 * 4,042 – 29,243 chars, median 15,285, and 0 pages below the 250 floor.**
 *
 * ## Chrome stripped — measured inside `.contentpadding`, 2026-07-30
 *
 * Marginal characters each selector removes, measured by re-running the full
 * extraction with that one selector withheld, summed over all 16 articles:
 *
 *   - **`.hiddencontact` — 16 instances, 272 chars (17 ch on every article).**
 *     The duplicated "გაქვთ შეკითხვა?" ("Do you have a question?") ask-card that
 *     closes every article body.
 *   - **`.a2a_dd` — 48 instances, 368 chars (23 ch on every article).** The
 *     AddToAny "გადააგზავნე ეს გვერდი" ("share this page") link. The other 32
 *     instances are the image-only share buttons and contribute nothing.
 *   - **`.addthis_toolbox` — 1 instance, 22 chars, on `/a/bibliisa215.html`
 *     only.** A legacy AddThis span wrapping the same share label.
 *   - **`#socialwrapper2` — 16 instances, 0 chars.** The share row at the top of
 *     every content column. Image-only buttons, so `structuredText` reads
 *     nothing from it today; stripped as a guard against a markup change adding
 *     text labels.
 *   - **`.a2a_kit` — 32 instances, 0 chars.** Same reasoning, same widget family.
 *
 * **Measured and DELIBERATELY OMITTED** rather than carried as parity no-ops:
 *   - `sitelevel_noindex`, `.fccell`, `.fctable`, `.relatedbottom`,
 *     `.shareiconsmenupg`, `.sectionlink` — **0 occurrences of the token
 *     anywhere in the raw HTML** of any page. Not "0 chars extracted"; the
 *     markup does not exist. (`.relatedbottom` has now been dead config on every
 *     host measured.)
 *   - `.hr1` (1–14 per page), `.hr2` (6 on one page), `.articledivider` (1 per
 *     page) and `.journeyline` (5 on one page) — these DO exist, but every one
 *     is a literal empty `<div class="…"></div>` drawing a CSS rule. All measured
 *     0 chars. Listing them would be dead config; they cannot ever carry text.
 *
 * ⓘ **One piece of chrome survives, and it cannot be stripped cleanly.** Every
 * article ends with two unclassed call-to-action links — "როგორ დავიწყოთ
 * ურთიერთობა იესოსთან" ("how to begin a relationship with Jesus") and "გაქვთ
 * შეკითხვა?" — sitting in bare `<p><a><em>` tags with no wrapper class of any
 * kind. That is ~50 chars per article. Removing it would need a text-matching
 * hack, not a selector, so it is left in and recorded here.
 *
 * ## ⓘ NO full-Scripture page on this host — checked, not assumed
 *
 * Several siblings carry complete Bible books on article URLs (`sq`
 * `/a/gjoni.html` 98,887 ch; `es` 100,409 ch), blocked under the estate-wide
 * scripture policy of 2026-07-29. **This host has no equivalent.** The one
 * Bible-shaped slug was read in full: **`/a/bibliisa215.html` — 29,243 chars,
 * "რატომ შეგიძლია გწამდეს ბიბლიისა" ("Why you can believe the Bible")** — an
 * apologetics essay on the Bible's historicity and transmission, arguing from
 * archaeology (the Hittite civilisation, Belshazzar as son of Nabonidus, the
 * Chicago dissertation). Ministry writing ABOUT the Bible, not the Bible: it
 * argues a case, cites secondary scholarship, and quotes Scripture only in
 * numbered footnotes. KEPT. It is the longest page at 1.9× the median, nowhere
 * near the ~14× outlier that flagged the real scripture carriers. `/a/gjoni.html`,
 * `/a/ioane.html`, `/a/biblia.html` and `/ioane.html` all **404** (probed).
 *
 * Copyright notices found across the corpus: `© KoveliStudenti.com` (footer),
 * plus per-article attributions `© 1997 რიჩარდ ფურნელი`, `© Laura Krauss
 * Calenberg`, `Copyright 1999 Campus Crusade for Christ` and one `SP
 * Publications, Inc., Wheaton, IL — Used by permission`. **No Bible-society
 * copyright of any kind**, so the `rights` line below does not misattribute.
 *
 * ## ⓘ NO Gospel-of-John signup and NO 7-email "adventure" series exist here
 *
 * Both are blocked on most siblings. Probed 2026-07-30 and **all 404**:
 * `/a/ioane.html`, `/a/john.html`, `/ioane.html`, `/sakhareba.html`,
 * `/a/sakhareba.html`, `/tavgadasavali.html`, `/a/tavgadasavali.html`,
 * `/adventure.html`. This is a measured absence, not an omission. `/m/intl.html`
 * (the sibling-language switcher other banners carry) is also 404. This is not a
 * WordPress host, so there are no `/category/<slug>/` or `/tag/<slug>/` indexes
 * either — both probe 404.
 *
 * ## ⚠️ Everything excluded is excluded BY URL, because the floor cannot do it
 *
 * `articleHints` already restricts the keep set to `/a/<slug>.html`, but the
 * blocks below record WHY each exclusion is a decision. Measured extractions of
 * every excluded page, 2026-07-30 — note that all but one CLEAR the 250 floor,
 * and the six that fall through to the `html` fallback extract the whole page
 * rather than nothing:
 *   - `/` and `/index.html` — **1,077 ch each** via the `html` fallback. Two
 *     sitemap entries for one page; without a block they would stage two
 *     byte-identical homepage copies, the `everystudent-ro` failure exactly.
 *   - the 5 teaser-list section indexes — **825–1,169 ch** via the fallback.
 *   - `/m/shesaxeb803.html` — **1,059 ch**, the about + privacy page.
 *   - `/m/sitemap.html` — **641 ch**, the HTML site map (absent from the XML).
 *   - `/kontakt801.html` — **329 ch**, the contact form.
 *   - `/a/fol.html` — **381 ch**, robots-disallowed (see above).
 *   - `/a/omi216.html` — 301 to the homepage. Not in the XML sitemap today, so
 *     discovery cannot reach it; blocked because it IS linked from
 *     `/m/daieso200.html`, and this sitemap is regenerated by a link-following
 *     crawler, so a regeneration would admit it. Following that 301 would stage
 *     the homepage under an article URL.
 *
 * ## Language: `["ka"]` — read, not inferred
 *
 * Verified 2026-07-30 by reading the extracted text directly. Genuinely Georgian
 * in Mkhedruli script (U+10D0–U+10F0), not untranslated English and not a
 * neighbouring language. `/a/Ghmerti101.html` is titled "არსებობს ღმერთი?"
 * ("Does God exist?") and opens "განა არ გსურთ, რომ ერთხელ მაინც იყოთ საგანი
 * ვინმეს სიყვარულისა…"; `/a/ratom602.html` asks "რატომ უჩნდებათ ადამიანებს
 * სიმსივნე? რატომ ხდება მიწისძვრები…" ("why do people get cancer? why do
 * earthquakes happen…"). Georgian is identifiable by its own alphabet — no
 * capital letters, and the distinctive ღ/ყ/წ/ძ/ჯ letterforms — which no other
 * language uses; the ergative `-მა` and the `-ის` genitive place it as Georgian
 * rather than Mingrelian or Svan. `<html lang="ka">` is declared but was NOT
 * relied on (`persoalanhidup.com` declares `lang="id"` and serves Malay).
 *
 * **Encoding is clean UTF-8, verified.** `<meta charset=utf-8>` is declared, the
 * raw bytes round-trip through `iconv -f UTF-8 -t UTF-8` without error, and the
 * rendered text shows no mojibake — worth stating because the response header is
 * a bare `content-type: text/html` with no charset parameter, and the 301 stub
 * on the apex is served as `iso-8859-1`.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. Two sweeps of all 25
 * sitemap URLs plus ~14 slug probes drew zero 429s and no throttling.
 *
 * **Expected yield: 16 documents.**
 */
import type { SourceEntry } from "./types.js";

export const everystudentKa: SourceEntry = {
  key: "everystudent-ka",
  name: "EveryStudent — Georgian (KoveliStudenti.com)",
  domain: "www.kovelistudenti.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ka"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ka"],
  defaultCategory: "article",
  rights:
    "© KoveliStudenti.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.kovelistudenti.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare header, no block page). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.kovelistudenti\\.com/"],
    // The whole article corpus and nothing else: 16 of the 25 sitemap URLs.
    // `[^/]+` rather than a lowercase class — /a/Ghmerti101.html and
    // /a/Ghmerti109.html carry a capital G, so a lowercase-only hint would
    // silently drop 2 of the 16. Slugs are romanised ASCII today (0 non-ASCII
    // bytes, 0 %XX escapes across all 25 <loc>s, checked), but this hint also
    // survives a future Mkhedruli or percent-encoded slug.
    articleHints: ["^https://www\\.kovelistudenti\\.com/a/[^/]+\\.html$"],
    block: [
      // ── robots.txt, fetched live 2026-07-30. The acquire path does NOT
      // enforce robots.txt, so its one rule is honoured by hand here. Written
      // as `Disallow: a/fol.html` with no leading slash (malformed per spec,
      // intent unmistakable). The page returns 200 and extracts 381 chars — the
      // post-decision follow-up contact form — so it clears the 250 floor AND
      // matches articleHints. Absent from the sitemap today; blocked so the rule
      // is enforced, not merely noted.
      "^https://www\\.kovelistudenti\\.com/a/fol\\.html$",
      // Dead: 301s to the homepage. Absent from the XML sitemap but LINKED from
      // /m/daieso200.html, and this sitemap is regenerated by a link-following
      // crawler (xml-sitemaps.com) — so a regeneration would admit it. Following
      // the redirect would stage the homepage under an article URL, which is how
      // everystudent-ro shipped 25 byte-identical homepage copies.
      "^https://www\\.kovelistudenti\\.com/a/omi216\\.html$",
      // ── Below here articleHints already excludes them; these record WHY, and
      // guard against a later widening of the hint. Every one of these clears
      // minContentLength, and the six with no .contentpadding fall through to
      // the `html` fallback and extract the WHOLE page — the floor cannot catch
      // any of them.
      // The 6 section indexes (arseboba100, daieso200, gamocdileba300,
      // movelenebi500, gamocanebi600 = teaser link lists, 825-1,169 ch;
      // shesaxeb803 = about + privacy, 1,059 ch) and the HTML site map
      // /m/sitemap.html (641 ch, and itself absent from the XML sitemap).
      "^https://www\\.kovelistudenti\\.com/m/",
      // The contact form, 329 ch.
      "^https://www\\.kovelistudenti\\.com/kontakt801\\.html$",
      // The homepage — listed TWICE in the sitemap, as `/` and as
      // `/index.html`. 1,077 ch each via the `html` fallback. Without this block
      // it would stage two byte-identical documents.
      "^https://www\\.kovelistudenti\\.com/(index\\.html)?$",
    ],
    // ⚠️ The hand-built EveryStudent "esintl2013" static template — NOT a tenth
    // generator, and NOT the FreeFind variant. Measured 2026-07-30 over all 24
    // fetched pages with the repo's own extractContent: `.contentpadding`
    // matches 18/24 (all 16 articles) at 346-29,305 ch with ZERO matched-but-
    // empty pages. `#content4` is the identical outer wrapper (same text, one
    // element child); `.content4` as a CLASS matches 0/24 — that single
    // character is why #111 flagged this host as template-less.
    // ⚠️ Do NOT add `.articletitle`: it matches 18/24 and yields 5-62 chars (the
    // <h1> alone), and extractContent binds the first selector that MATCHES, not
    // the first that yields text — it would shadow everything after it.
    // `html` is a genuine last resort, safe only because the primary has no
    // matched-but-empty pages; it fires when .contentpadding misses and can
    // shadow nothing because nothing follows it.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Required by the `html` fallback: drops the duplicated <title>. 0 chars
      // on healthy pages (no <head> inside .contentpadding). extract.ts reads
      // the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome, all counted inside .contentpadding across the 16
      // articles on 2026-07-30:
      ".hiddencontact", // 16 inst / 272 ch: the duplicated "გაქვთ შეკითხვა?" ask card
      ".a2a_dd", // 48 inst / 368 ch: the AddToAny "გადააგზავნე ეს გვერდი" share link
      ".addthis_toolbox", // 1 inst / 22 ch: legacy AddThis span, on /a/bibliisa215.html only
      "#socialwrapper2", // 16 inst / 0 ch: top share row, image-only buttons today
      ".a2a_kit", // 32 inst / 0 ch: same widget family; kept as a guard against text labels
      //
      // ⓘ DELIBERATELY ABSENT — measured, not guessed:
      //   sitelevel_noindex, .fccell, .fctable, .relatedbottom,
      //   .shareiconsmenupg, .sectionlink — ZERO occurrences of the token in
      //   this host's raw HTML. Not zero chars; zero markup.
      //   .hr1, .hr2, .articledivider, .journeyline — these DO exist, but each
      //   is a literal empty div drawing a CSS rule. All measured 0 chars and
      //   they cannot ever carry text, so listing them would be dead config.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 x 429 observed
    maxPages: 60, // 25 sitemap URLs (16 kept after filtering) + headroom
    minContentLength: 250,
  },
};
