/**
 * EveryStudent — Estonian (tudengielu.net, "TudengiElu" / "Student Life"). The
 * Estonian banner of Cru's seeker-facing Q&A ministry, run by Agape Eesti: short
 * apologetics and life-issue articles plus a KKK ("korduma kippuvad küsimused" /
 * FAQ) question-and-answer set, written for Estonian-speaking students who are
 * not believers. A sibling of `everystudent` (en), `everystudent-ru`,
 * `everystudent-de`, `everystudent-fr` and the rest of the #111 estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). tudengielu.net is its own domain, so it gets its own
 * key, the same way `everystudent-ru` (mirstudentov.com), `everystudent-de`
 * (duentscheidest.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries. Note the host carries no "everystudent"
 * string at all — the sibling relationship is editorial, not nominal.
 *
 * ⓘ **`et` is a NEW language for this corpus** as far as this entry knows: no
 * other registered source declares it. Recorded for the orchestrator's
 * Stage-4 gating, which treats single-source languages differently.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-29: **~110 plain-HTTP GETs/HEADs** with a full desktop-Chrome
 * UA (a HEAD sweep of all 77 sitemap URLs, then a full GET of all 77, plus
 * /robots.txt, /m/kaart.html and 17 probe paths) — **every sitemap URL returned
 * HTTP 200 with real HTML**, and not one response carried a Cloudflare
 * block-page signature (no `Attention Required`, no `Just a moment`, no
 * `cf-error-details`). The server header is plain `Apache`; there is no
 * Cloudflare in front of this host at all. So `fetchStrategy` is intentionally
 * OMITTED: plain HTTP is the default and nothing here needs Firecrawl
 * (ADR-0012). Consequence: discovery is free, so this is a **discovery crawl**,
 * not a hand-listed seed set. Precedent for the shape: `thelife-fr`, and the
 * non-walled siblings `everystudent-ru` / `everystudent-de`.
 *
 * The bare host **301-redirects to `www`** (measured on both /robots.txt and
 * /a/olemas.html), so `www.tudengielu.net` is the canonical host and the one
 * every sitemap `<loc>` already uses.
 *
 * ## robots.txt — there ISN'T one
 *
 * Verified 2026-07-29: `https://www.tudengielu.net/robots.txt` → **HTTP 404**,
 * serving the site's own Estonian "Vabandust!" ("Sorry!") error page rather than
 * a rules file. There is no robots.txt on this domain, therefore **no Disallow
 * rule exists and nothing is disallowed** — every exclusion below is a
 * content-quality call, not a policy one. Going the other way, every page on the
 * host carries `<meta name="robots" content="all" />` in its head, an explicit
 * invitation to index. This is barer even than `everystudent-ru`'s 13-byte
 * `User-agent: *`, and unlike everystudent.com, which carries a real disallow
 * list.
 *
 * ⓘ Useful property of that 404: this host returns a **real 404 status** for
 * missing paths, so a 200 genuinely means the page exists. There are no soft-404
 * traps to screen for.
 *
 * ## Sitemap — 77 entries, all distinct, all live
 *
 * Verified 2026-07-29: `https://www.tudengielu.net/sitemap.xml` → HTTP 200,
 * 5,680 bytes, `application/xml`, generated by xml-sitemaps.com,
 * `Last-Modified: 2017-10-11`. It holds 77 `<loc>` elements and **77 distinct
 * URLs** — no duplicates. This matches the ~77 from prior recon exactly.
 *
 * The 77 URLs break down as:
 *   - **46 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **21 `/johannese/j<n>.html`** — Gospel of John, chapters 1-21. BLOCKED, below.
 *   - **8 `/m/<slug>.html`** — section indexes (`eksistents`, `elust`, `jeesus`,
 *     `kaart`, `kkk`, `kogemus`, `moistatused`, `veebilehest`). BLOCKED, below.
 *   - **`/kontakt.html`** — the "Saada küsimus" contact page. BLOCKED, below.
 *   - **`/`** — the homepage. BLOCKED, below.
 *
 * So `articleHints` is exactly `/a/<slug>.html`, and the expected yield is 46
 * documents.
 *
 * **All 77 URLs are live and none redirects.** Verified 2026-07-29 by a HEAD
 * sweep of the complete sitemap: 77/77 returned HTTP 200 with an empty
 * `redirect_url`. Unlike some siblings there are no dead entries and no
 * 301-to-homepage strays to block, and there are no `.php` extension twins of
 * the kind the French entry had to drop.
 *
 * ## HTML site-map cross-check — no delta, so NO `seedPaths`
 *
 * The XML sitemap is nine years stale by its own `Last-Modified`, so it was
 * cross-checked rather than trusted. Verified 2026-07-29: the site's own HTML
 * map `/m/kaart.html` (HTTP 200) links **exactly the same 46 `/a/` articles** —
 * set difference is empty in BOTH directions. Widening the check, every
 * `/a/` and `/johannese/` href on the homepage and on all 8 `/m/` indexes was
 * collected too (47 distinct targets): **not one on-site link points at a URL
 * the XML sitemap lacks.** Nothing needs pinning, so `seedPaths` is absent and
 * discovery alone is complete. (Contrast the siblings whose HTML map exposed
 * articles the XML sitemap had dropped.)
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes all of these (nothing outside `/a/` can
 * match). The `block` list is deliberately redundant — it records *why* each
 * group is out, so a later widening of the hints cannot silently readmit them.
 * Same defensive posture as `thelife-fr`, `everystudent-de` and
 * `everystudent-ru`. Every one of the 31 non-article sitemap URLs is matched by
 * `block` explicitly, not merely missed by the hints.
 *
 *   - **`/johannese/j1…j21` — 21 chapters of VERBATIM BIBLE TEXT, and not Cru's
 *     to license.** Verified 2026-07-29 by reading them: each page is the plain
 *     text of one chapter of the Gospel of John with no commentary, no framing
 *     and no Q&A, headed "Johannese evangeelium" and credited **"© Eesti
 *     Piibliselts"** — the Estonian Bible Society, a **third party**. Two
 *     independent reasons to exclude them:
 *       1. `rights` on this entry asserts Cru partner-ministry content. Ingesting
 *          21 pages owned by a different rights holder would attach a false
 *          attribution to every chunk of scripture in them.
 *       2. They are scripture, not the seeker apologetics corpus this source
 *          exists to supply, and at 2,834-7,691 chars each they would be 21 of
 *          the corpus's larger documents — retrieval noise for questions the
 *          `/a/` articles are written to answer.
 *     They clear `minContentLength` by an order of magnitude, so the floor could
 *     never have caught them. This is the Estonian analogue of the Gospel-of-John
 *     signup page the walled siblings block (`/jean.html`, `/john.html`) — same
 *     material, published here as the full text rather than an email opt-in.
 *     ⓘ **Reversible call, flagged for the orchestrator:** if the estate later
 *     decides third-party scripture text is wanted, it belongs in its own source
 *     entry with its own `rights` line, not folded in under Cru's.
 *   - **`/m/*` — navigation, not content.** Verified 2026-07-29: all 8 fetched
 *     and extracted at **77-2,635 chars**, and every one is a list of headline +
 *     teaser pairs linking to `/a/` pages. **5 of the 8 clear the 250-char floor**
 *     (`elust` 677, `jeesus` 595, `kkk` 1,929, `veebilehest` 1,320, `kaart`
 *     2,635), so the floor demonstrably cannot be relied on here; the other 3
 *     (`eksistents` 199, `kogemus` 234, `moistatused` 77) fall below it by luck,
 *     not by design. `/m/kaart.html` is the site-plan page (Estonian twin of the
 *     French `/plan.html` and the Russian `/sitemap.html`) and `/m/veebilehest.html`
 *     is the about + privacy page.
 *   - **`/kontakt.html` — the contact page.** Verified 2026-07-29: extracts
 *     **285 chars** — "Saada küsimus" plus a privacy blurb and three staff first
 *     names. It **clears the 250 floor by 35 chars**, so blocking by URL is the
 *     only thing that keeps it out.
 *   - **`/`** — the homepage. Verified 2026-07-29: extracts **653 chars** of
 *     welcome copy and six headline+teaser pairs. Also clears the floor.
 *
 * ## Near-twin slugs checked, and deliberately KEPT
 *
 * Three slug pairs looked like part-1/part-2 duplicates and were measured rather
 * than assumed. Verified 2026-07-29 — all three are **0.0% 12-word shingle
 * overlap**, i.e. genuinely unrelated articles, and all are kept:
 *   - `/a/kuidas.html` ("Kuidas leida Jumalat", 15,850 ch) vs `/a/kuidas2.html`
 *     ("Kuidas me saame kindlad olla…", 2,418 ch);
 *   - `/a/seks1.html` (2,987 ch) vs `/a/seks2.html` (4,321 ch);
 *   - `/a/lukka.html` (2,664 ch) vs `/a/lukkab.html` (2,266 ch).
 *
 * The highest overlap anywhere in the 46-article set is **47.1%**, between
 * `/a/mida.html` ("Kas Jeesus on Jumal…", 6,168 ch) and `/a/pakub.html` ("KKK:
 * Mida Jeesus meile pakub?", 3,520 ch). Read side by side, these are distinct
 * documents — one an article, one a FAQ answer — that happen to quote the **same
 * block of John passages** (John 6:37-40, 12:44-46, 8:58 …). The shared text is
 * scripture, not duplicated authored prose, so both are kept. Flagged here so a
 * later de-duplication pass does not mistake it for a genuine twin.
 *
 * ## Extraction — this host does NOT use the shared EveryStudent template
 *
 * The single most important finding on this domain. Verified 2026-07-29 by
 * running the repo's own `extractContent` algorithm (node-html-parser, same
 * `tidy`, same first-match scoping) against **all 77 live pages** — the only
 * check that proves anything, because a grep for these tokens hits the inline
 * `<style>` block on every page and false-positives every time:
 *
 *   - `.content4`        — **NO ELEMENT on all 77 pages.**
 *   - `.content4b`       — **NO ELEMENT on all 77 pages.**
 *   - `.contentpadding`  — **NO ELEMENT on all 77 pages.**
 *   - `.articletitle`    — **NO ELEMENT on all 77 pages.**
 *   - `.contentleft`     — 1 instance on 77/77 pages; extracts the full article.
 *   - `.contentleftpadding` — 1 instance on 77/77 pages; **identical character
 *     count to `.contentleft` on 77 of 77 pages**, because it is that element's
 *     only child and nothing sits between them.
 *
 * tudengielu.net runs an older, hand-rolled EveryStudent layout
 * (`#bigback > #container > .contentleft | .contentright`), not the
 * `.content4`/`.contentpadding` template of the #111/#112 estate. **Every
 * selector inherited from a sibling entry would have missed**, `extractContent`
 * would have fallen back to `<body>`, and all 46 articles would have ingested
 * with the full nav, sidebar and footer attached.
 *
 * `contentSelectors` is therefore the **one measured container and nothing
 * else**. It is NOT a fallback chain: `extractContent` scopes to the FIRST
 * selector that MATCHES AN ELEMENT, not the first that yields text, so any
 * additional entry could only shadow this one. `.contentleft` is deliberately
 * omitted despite extracting identically — it is the parent, so it can never win
 * a race this selector loses, and listing it would only obscure which one was
 * measured. Scoping to `.contentleftpadding` excludes the `.contentright`
 * sidebar, `#datecrumbs`, `.navmenu2`, `#footer` and `#cookie-notice`, all of
 * which are siblings of `.contentleft`, not descendants.
 *
 * Measured yield on the 46 kept articles: **1,114-27,503 chars after stripping**,
 * every one clearing `minContentLength: 250`; the shortest is `/a/sattusime.html`
 * at 1,114. `<title>` resolves on all 46.
 *
 * ## Chrome stripped — measured INSIDE `.contentleftpadding`, not inherited
 *
 * Counts below are element instances and characters actually removed, measured
 * one selector at a time across all 77 pages (46 articles where noted):
 *
 *   - **`.a2a_dd` — 136 instances across 46/46 articles, 1,080 chars.** The
 *     AddToAny share link "Saada lehekülg sõbrale" ("send this page to a
 *     friend"), appended below every article body. This is the one selector this
 *     host genuinely needs: it is the functional equivalent of the siblings'
 *     `.shareiconsmenupg`, under a completely different class name.
 *   - **`.a2a_kit` — 91 instances across 46/46 articles, 0 chars.** The AddToAny
 *     icon-button rows (Facebook/X/WhatsApp/email). Image-only, so they remove no
 *     text, but all 91 **contain** an `.a2a_dd`, so the pair is listed
 *     outer-then-inner to take the whole widget rather than leave a shell.
 *   - **`.addthis_toolbox` — 1 instance on 1 page, 24 chars.** A legacy AddThis
 *     widget left on a single article. Cheap to name, so it is named.
 *   Combined, the site-specific strip removes **1,104 chars, 24.0 per article**.
 *
 * The sibling strip list was measured and found **entirely inapplicable** — every
 * one of these is at **0 element instances on all 77 pages**, and none is
 * carried over, because retaining them would falsely imply this host shares the
 * estate template:
 *   `sitelevel_noindex` 0 · `.shareiconsmenupg` 0 · `.fccell` 0 · `.fctable` 0 ·
 *   `.articledivider` 0 · `.relatedbottom` 0.
 * Also present but not worth naming: `.hr2` (11 instances, 1 page, **0 chars**)
 * and `.hr1` (57 instances, 23 pages, **0 chars**) — empty decorative rules.
 *
 * ⓘ The standard `form` strip does real work on exactly one page:
 * `/a/seks2.html` carries the site's only `<form>`, a 731-char "Jah/Ei"
 * self-assessment quiz. Stripped as chrome by the shared base list; the article
 * still yields 4,321 chars.
 *
 * ⚠️ `.contentleftpadding` binds on `/m/`, `/kontakt.html`, `/johannese/` and the
 * homepage too — it does **not** discriminate content from nav. The URL filters
 * above are what keep the corpus clean; the selector must not be relied on for it.
 *
 * ## Language: `["et"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. These pages serve
 * genuine Estonian prose, not untranslated English and not Finnish.
 * `/a/olemas.html` opens "Kas Jumal on olemas? Kas on tõendeid Jumala olemasolu
 * kohta?" ("Does God exist? Is there evidence for God's existence?") and presses
 * the reader "Kas sa ei tahaks, et keegi kasvõi ükskord näitaks sulle tõendeid
 * Jumala olemasolu kohta?"; `/a/hingerahu.html` is "Hingerahu ebastabiilses
 * maailmas" ("Peace of mind in an unstable world"); `/a/seks1.html` asks "Kas
 * abielu-eelne seks on vale?"; `/a/kolmainsust.html` answers "Kas oskate
 * selgitada kolmainsust?". Every article closes on the site's own CTA line
 * "Kuidas alustada suhet Jumalaga" ("How to begin a relationship with God").
 *
 * **Estonian, not Finnish**, on two independent grounds. Orthographic: the letter
 * **`õ` exists in Estonian and not in Finnish**, and it is everywhere here —
 * "tõendeid", "Sõna", "põhjuseid", "lõpp", "mõtle" — appearing on 76 of the 77
 * pages (the sole exception is `/m/kogemus.html`, all of 28 words long).
 * Grammatical: the case endings are Estonian, not Finnish — "ebastabiilses
 * maailmas" (Finnish would be *epävakaassa maailmassa*), "Jumalaga" and
 * "kellegagi" using the Estonian comitative *-ga* (Finnish uses the separate
 * postposition *kanssa*), and "Kas … on olemas" where Finnish would form
 * *Onko … olemassa*.
 *
 * **Not untranslated English**, checked rather than assumed: across all 46
 * articles the median English-stopword density is **0%**, and the worst page in
 * the set is `/a/sattusime.html` at **0.6%** (1 token in 181). The only English
 * on these pages is bibliographic — footnotes citing English-language books
 * (e.g. "R.E.D. Clark, Creation (London: Tyndale Press, 1946)", "The Wonders of
 * God's Creation, Moody Institute of Science") — which is normal citation
 * apparatus in a translated article, not an untranslated body. Bylines are the
 * English originals' ("Autor: Marilyn Adamson"), as expected for translations of
 * everystudent.com material; the article text itself is fully Estonian.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * ## No signup / email-series landing page exists on this host
 *
 * The walled siblings each carry one (`/jean.html`, `/john.html`, `/pack.html`,
 * `/aventure.html`) and `everystudent-de` blocks `/abenteuerreise.html`. Verified
 * 2026-07-29 that tudengielu.net has no equivalent: 17 candidate paths were
 * probed — `/john.html`, `/pack.html`, `/aventure.html`, `/seiklus.html`,
 * `/pakett.html`, `/pakk.html`, `/jaan.html`, `/johannes.html`,
 * `/johannese.html`, `/sitemap.html`, `/plan.html`, `/kaart.html`,
 * `/m/intl.html`, `/m/keeled.html`, `/m/johannese.html`, `/a/jolka.php`,
 * `/sisu.html` — and **all 17 returned HTTP 404**. The `/johannese/` chapters
 * blocked above are this host's only Gospel-of-John material, and there is no
 * "adventure/pack" email series to exclude. There is likewise no
 * other-languages page (the sibling-domain link list the English entry drops as
 * `/menus/intl.html`) — this host does not publish one.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: ~110 sequential plain-HTTP requests drew no 429 and no throttling,
 * and at 46 pages the whole crawl is under a minute of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentEt: SourceEntry = {
  key: "everystudent-et",
  name: "EveryStudent — Estonian (TudengiElu)",
  domain: "www.tudengielu.net",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["et"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:et"],
  defaultCategory: "article",
  rights:
    "© TudengiElu.net (Agape Eesti / Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.tudengielu.net",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (plain Apache, no Cloudflare at all). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.tudengielu\\.net/"],
    // The whole article corpus and nothing else: 46 of the 77 sitemap URLs.
    // Estonian slugs are plain ASCII on this host, but `[^/]+` stays
    // diacritic-safe for ä/ö/ü/õ if a slug is ever added carrying them.
    articleHints: ["^https://www\\.tudengielu\\.net/a/[^/]+\\.html$"],
    block: [
      // Gospel of John, chapters 1-21: VERBATIM Bible text, "© Eesti
      // Piibliselts" (Estonian Bible Society) — a third-party rights holder, so
      // this entry's `rights` line would misattribute them. 2,834-7,691 chars
      // each, so minContentLength can NOT catch them. Estonian analogue of the
      // Gospel-of-John page the walled siblings block.
      "^https://www\\.tudengielu\\.net/johannese/",
      // The 8 section indexes (eksistents, elust, jeesus, kaart, kkk, kogemus,
      // moistatused, veebilehest) — headline+teaser link lists, 77-2,635 chars.
      // FIVE of the eight clear the 250 floor, so the floor can NOT catch them.
      // /m/kaart.html is the site-plan page; /m/veebilehest.html about+privacy.
      "^https://www\\.tudengielu\\.net/m/",
      // The contact page: 285 chars, so it clears the floor by 35. URL-blocked.
      "^https://www\\.tudengielu\\.net/kontakt\\.html$",
      // The homepage: 653 chars of welcome copy + teaser pairs. Clears the floor.
      "^https://www\\.tudengielu\\.net/?$",
    ],
    // ONLY `.contentleftpadding` — measured 2026-07-29 on all 77 live pages as
    // the container that extracts the article. This host runs an OLDER,
    // hand-rolled layout: `.content4`, `.content4b`, `.contentpadding` and
    // `.articletitle` have NO ELEMENT on any of the 77 pages, so every selector
    // inherited from a sibling would have missed and fallen back to <body>.
    // Not a fallback chain: extractContent scopes to the first selector that
    // MATCHES rather than the first that yields text, so a second entry could
    // only shadow this one. `.contentleft` (the identical-extracting parent) is
    // omitted for exactly that reason.
    contentSelectors: [".contentleftpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form", // also takes /a/seks2.html's 731-char "Jah/Ei" quiz
      // Site-specific chrome — all counted in this host's markup (see header).
      // The sibling selectors (sitelevel_noindex, .shareiconsmenupg, .fccell,
      // .fctable, .articledivider, .relatedbottom) are ABSENT on purpose: each
      // was measured at 0 element instances on all 77 pages.
      ".a2a_kit", // AddToAny icon rows (91 el, 0 ch) — listed first: each CONTAINS an .a2a_dd
      ".a2a_dd", // the "Saada lehekülg sõbrale" share link (136 el, 1,080 ch)
      ".addthis_toolbox", // legacy AddThis widget on one article (1 el, 24 ch)
    ],
    requestDelayMs: 1000,
    maxPages: 120, // 77 sitemap entries (46 articles) + headroom
    minContentLength: 250,
  },
};
