/**
 * EveryStudent — Japanese (studentinjapan.com). The Japanese banner of Cru's
 * seeker-facing Q&A ministry: short apologetics/life-issue articles aimed at
 * Japanese-speaking students who are not believers.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). studentinjapan.com is its own domain, so it gets its
 * own key, the same way `everystudent-ar` / `everystudent-fr` are separate from
 * `everystudent`, and `thelife-fr` / `thelife-zh` are separate from `thelife`.
 *
 * **NOT WALLED — plain HTTP throughout, so `fetchStrategy` is omitted.**
 * Verified 2026-07-28: `robots.txt`, `/sitemap.xml`, the homepage and all 20
 * content pages probed (15 `/a/` articles + 5 non-article pages) returned
 * **HTTP/2 200** to a plain `curl` with a browser UA — no `403`, no "Attention
 * Required", no "Just a moment" interstitial. The only non-200 seen anywhere was
 * the intentional apex→`www` 301. The host does sit behind Cloudflare
 * (`server: cloudflare` on
 * every response), but it serves rather than challenges. This is the decisive
 * difference from the three walled banners (everystudent.com,
 * everyarabstudent.com, questions2vie.com) which all 403 to plain HTTP and must
 * pay Firecrawl per page. Nothing here is billed.
 *
 * **Discovery mode, not hand-listed seeds** — the opposite call from the three
 * walled siblings, and for the opposite reason. Their `/sitemap.xml` is
 * unreachable to plain HTTP, so their inventory had to be bought once through
 * Firecrawl's `/v2/map` and frozen into `seedPaths`. Here the sitemap is free
 * and reachable, so there is nothing to freeze and no reason to hand-list: the
 * `sitemaps` + `allow` + `articleHints` + `block` shape keeps this entry small
 * and lets the article set track the site. Precedent: `thelife-fr`.
 *
 * **Sitemap — verified 2026-07-28.** `https://www.studentinjapan.com/sitemap.xml`
 * is a single flat `<urlset>` (no `<sitemapindex>`, so no recursion),
 * `last-modified: 2026-06-02`, generated by xml-sitemaps.com, carrying exactly
 * **94 `<loc>` entries**, all on `www.studentinjapan.com`. The bare apex
 * `https://studentinjapan.com/sitemap.xml` **301s to the `www` host**, which is
 * why `baseUrl`, `domain` and every regex below are pinned to `www.` — the
 * sitemap emits `www` absolute URLs and the filters match the full absolute URL.
 *
 * The 94 break down as:
 *   - **81 `/a/<slug>.html`** — the article corpus. This is the whole target set.
 *   - **9 `/m/<slug>.html`** — section/menu indexes (`about`, `eni`, `exi`,
 *     `exp`, `for`, `iss`, `map`, `per`, `testimonies`). Navigation, not
 *     articles; `/m/map.html` is the site-plan page (a bare list of links) and
 *     `/m/about.html` is the site's privacy/about blurb. The sibling entries
 *     drop the equivalent `/menus/*` and `/m/*` pages for the same reason.
 *   - **the bare homepage `/`** — an index. Notably it binds **none** of the
 *     four content selectors (measured), so it would fall through to `<body>`
 *     and extract the whole page chrome. Blocked.
 *   - **`/john.html`, `/pack.html`, `/unsubscribe.html`** — email-funnel pages,
 *     see below.
 * Verified by simulating `allow ∧ articleHints ∧ ¬block` against all 94 URLs:
 * **exactly the 81 `/a/` articles survive**, 13 dropped.
 *
 * **`/john.html` and `/pack.html` are the SAME two email-signup landing pages
 * the French entry dropped** — `/john.html` (1,099 ch) is the sign-up for a
 * 42-part Gospel-of-John email study and `/pack.html` (952 ch) the
 * 7-message「アドベンチャー・パック」series, the exact twins of questions2vie's
 * `/jean.html` and `/aventure.html`. Both are funnel copy wrapped around a
 * subscribe form, not a seeker question being answered, so both are blocked —
 * following slice #10's evidence-based drop rather than slice #9's provisional
 * keep. `/unsubscribe.html` is mailing-list plumbing ("メール配信中止・再開の手続き").
 *
 * ⚠️ **`minContentLength` cannot be relied on to catch those three.** Measured
 * 2026-07-28: `/unsubscribe.html` extracts to **356 chars** — comfortably ABOVE
 * the 250 floor — and the other two are four times that. Length is not
 * aboutness, so the `block` list is doing real work here, not decoration.
 *
 * **The 250 floor is safe for real articles, in the other direction.** The
 * shortest article in a 15-article sample was `/a/plates.html` at **826 chars**
 * (a 3:59 video narration transcript); the range ran 826 → 15,860 chars
 * (`/a/Bible215.html`). Japanese packs far more meaning per character than a
 * Latin script, so 250 chars of Japanese is already a substantial passage —
 * the floor is kept at 250 for cross-source consistency, and no sampled article
 * came close to it.
 *
 * **robots.txt — fetched live 2026-07-28.** `User-agent: *` with exactly two
 * Disallow rules: **`/a/fol.html`** and **`/m/intl.html`**. Neither appears in
 * the sitemap, so today the article set is untouched by robots. The
 * `/a/fol.html` block below is nonetheless load-bearing: it is the ONLY
 * disallowed path that would match `articleHints` if it ever entered the
 * sitemap, and it is link-targeted from the "FEATURE CLOSE" block of every
 * single article ("イエスを信じました。成長の助けになる情報はこちらから"). `/m/intl.html`
 * — the page linking out to the sibling language domains — is blocked for
 * parity with the siblings and to record the robots rule explicitly.
 *
 * **Extraction — measured on THIS host, not inherited on trust.** All four
 * shared-template selectors bind on every article probed: `.content4`,
 * `.content4b`, `.articletitle`, `.contentpadding`. `.content4` is the widest
 * container and is tried first.
 *
 * The strip list needed **two corrections** against the sibling entries:
 *   - **`sitelevel_noindex` does NOT exist on this host.** The siblings strip it
 *     as a custom TAG; here the string "noindex" appears **zero times** in the
 *     markup. The site's own do-not-index marker is an HTML *comment*
 *     (`<!-- FreeFind Begin No Index -->`), which no selector can target and
 *     which the parser discards anyway. Retained in the list purely as a
 *     harmless no-op for cross-banner parity — it strips nothing here.
 *   - **`.shareiconsmenupg` is new and REQUIRED.** It wraps the「他の人にシェアする」
 *     label plus the AddToAny (`a2a_*`) share buttons, and it sits *inside*
 *     `.content4` but *outside* `.content4b`/`.contentpadding`. Because
 *     `.content4` is tried first it WOULD be captured, leaving every article
 *     ending on the words "share with others". The siblings never needed this
 *     because their English/French template puts the widget inside the
 *     `sitelevel_noindex` element that does not exist here.
 * `.fccell` is the "FEATURE CLOSE" call-to-action table appended to every
 * article, and `.fctable` is its wrapping `<table>` — stripping the wrapper too
 * removes the row scaffolding the cell-level selector leaves behind (68 vs 63
 * chars on `/a/atheist.html`). `.relatedbottom` is **declared in the page's CSS
 * but never used in the markup** on this host — a measured no-op, kept for
 * parity. `.hr2` and `.articledivider` bind but are empty presentational rules.
 * Net effect measured: **47–84 chars of pure chrome removed per page**, leaving
 * articles ending cleanly on their own last line (the footnote list).
 *
 * ⓘ One residual: a few articles carry an inline related-article promo
 * ("こちらの記事もあわせてご覧ください" + one link, ~20 chars) in a **bare `<p>` with no
 * class or id** — unreachable by any selector. Too small and too rare to chase;
 * noted so a future reader does not hunt for the selector that removes it.
 *
 * **Character encoding: UTF-8.** Worth stating because Japanese legacy sites
 * often serve Shift_JIS or EUC-JP. Verified 2026-07-28 three ways: the page
 * declares `<meta http-equiv="content-type" content="text/html; charset=utf-8" />`,
 * a byte-level sniff reports `text/html; charset=utf-8`, and the Japanese text
 * decodes cleanly as UTF-8 with no replacement characters. ⚠️ The HTTP response
 * header is a bare `content-type: text/html` with **no `charset` parameter**, so
 * a client that trusts the header alone and defaults to ISO-8859-1 would mojibake
 * every page; the fetcher must honour the `<meta>` declaration (or default to
 * UTF-8) rather than the header.
 *
 * **Language: `["ja"]` — read, not assumed.** The pages genuinely serve
 * Japanese, not untranslated English: across the 15 articles sampled, **86.8%–
 * 100% of alphabetic characters are kana/kanji**, and the residue is romanized
 * citations (English book titles in footnotes, e.g. "Paul E. Little, Know Why
 * You Believe, IVP Books, 1988"). The 86.8% floor is `/a/dna.html`, whose title
 * embeds the Latin string "DNA" and which cites Western science sources; no
 * sampled page was untranslated English. Sample titles read「復活はあったのか？」("Did the
 * resurrection happen?"),「孤独とどう向き合うか」("How to face loneliness"),
 * 「宗教嫌いの私が…！？」("Me, who hated religion…!?"). The stored per-document label
 * still comes from content detection at ingest (invariant 6), never from this
 * field.
 *
 * ⚠️ **Japanese is a NEW language for this corpus** — no `ja` documents exist
 * today, so unlike the French slice there are no pre-existing golden cases this
 * source becomes eligible for by construction. Stage-4 will need `ja` cases
 * written from scratch, and `ja` starts as a SINGLE-source language for gating.
 *
 * `requestDelayMs: 1000` — we are paying this host's bandwidth directly rather
 * than proxying through Firecrawl, so the politeness is real. No rate-limiting
 * was observed across ~25 sequential probes at ~1s spacing (zero 429s), so the
 * sibling default is kept rather than raised.
 */
import type { SourceEntry } from "./types.js";

export const everystudentJa: SourceEntry = {
  key: "everystudent-ja",
  name: "EveryStudent — Japanese (Student in Japan)",
  domain: "www.studentinjapan.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ja"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ja"],
  defaultCategory: "article",
  rights:
    "© StudentInJapan.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.studentinjapan.com",
    // No `fetchStrategy`: this host is NOT walled (verified 2026-07-28, every
    // probe 200 to plain HTTP), so the plain-http default applies and nothing
    // is billed. See the header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.studentinjapan\\.com/"],
    // The article corpus is exactly /a/<slug>.html — 81 of the sitemap's 94.
    articleHints: ["^https://www\\.studentinjapan\\.com/a/[^/]+\\.html$"],
    block: [
      // robots.txt Disallow, fetched live 2026-07-28. /a/fol.html is the only
      // disallowed path that would match articleHints, and it is linked from
      // every article's FEATURE CLOSE block — this is the load-bearing entry.
      "^https://www\\.studentinjapan\\.com/a/fol\\.html$",
      "^https://www\\.studentinjapan\\.com/m/intl\\.html$",
      // Section/menu indexes (9 in the sitemap: about, eni, exi, exp, for, iss,
      // map, per, testimonies) — navigation, not articles.
      "^https://www\\.studentinjapan\\.com/m/",
      // Email-funnel pages. All three clear minContentLength (356–1,099 chars),
      // so the floor cannot catch them — see the header.
      "^https://www\\.studentinjapan\\.com/(john|pack|unsubscribe)\\.html$",
      // The homepage binds none of the four content selectors (measured), so it
      // would fall through to <body> and extract page chrome.
      "^https://www\\.studentinjapan\\.com/?$",
    ],
    contentSelectors: [
      ".content4",
      ".content4b",
      ".articletitle",
      ".contentpadding",
    ],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome, all measured on this host 2026-07-28 (see header):
      "sitelevel_noindex", // NO-OP here — the element does not exist; kept for parity
      ".relatedbottom", // NO-OP here — declared in CSS, never used in markup
      ".fccell", // "FEATURE CLOSE" call-to-action cells appended to every article
      ".fctable", // …and the <table> wrapping them
      ".shareiconsmenupg", // 「他の人にシェアする」+ AddToAny buttons — INSIDE .content4
      ".hr2",
      ".articledivider",
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 120, // 81 discovered articles + headroom
    minContentLength: 250,
  },
};
