/**
 * EveryStudent — Hindi (everystudent.in, "EveryStudent.in"). The Hindi banner of
 * Cru's seeker-facing Q&A ministry: short apologetics and life-issue articles,
 * first-person testimonies and video transcripts written for Hindi-speaking
 * students who are not believers. A sibling of `everystudent` (en) and of the
 * non-walled `-pl` / `-sq` / `-ru` / `-de` / `-ko` entries.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everystudent.in is its own domain, so it gets its own
 * key, the same way `everystudent-pl` (kazdystudent.pl), `everystudent-sq`
 * (pyetjetejetes.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * `hi` is a **NEW language for this corpus** — verified 2026-07-30: no other
 * registry entry declares `hi`. Nothing below depends on that, and the stored
 * per-document label still comes from content detection at ingest (invariant 6),
 * never from `languages`.
 *
 * ## NOT walled — plain HTTP, Cloudflare notwithstanding
 *
 * Verified 2026-07-30: **~100 plain-HTTP GETs** with a full desktop-Chrome UA
 * (the sitemap, all 40 sitemap URLs twice, 7 more URLs found by link harvest,
 * plus robots probes). **Every content request returned HTTP/2 200 with real
 * HTML**, and grepping all 47 fetched documents for a block-page signature
 * (`Attention Required`, `Just a moment`, `Checking your browser`, `Enable
 * JavaScript and cookies`) found **zero hits**.
 *
 * ⚠️ Every response does carry `server: cloudflare` with `cf-ray` and NEL
 * headers. That is the CDN, not a wall — the classification here is made on the
 * absence of a block-page body, exactly as #114 established, because keying off
 * the Cloudflare header alone false-positives on hosts that pass traffic fine.
 * `fetchStrategy` is therefore intentionally OMITTED (plain HTTP is the default,
 * ADR-0012), so discovery is free and this is a **discovery crawl** rather than
 * the hand-listed seed set the three walled banners were forced into. Precedent
 * for the shape: `thelife-fr`, `everystudent-pl`.
 *
 * **Canonical host: `www.everystudent.in`, checked BOTH ways.** Verified
 * 2026-07-30: `http://everystudent.in/` **301 → `https://www.everystudent.in/`**
 * and `http://www.everystudent.in/` **301 → `https://www.everystudent.in/`**.
 * The apex does NOT serve (unlike `everystudent.sk`, which redirects the other
 * way), and all 40 sitemap `<loc>` values already use `https://www.` — so
 * `domain`, `baseUrl` and every regex below are pinned to `www.`.
 *
 * ## robots.txt — there isn't one
 *
 * Verified 2026-07-30: `https://www.everystudent.in/robots.txt` returns **HTTP
 * 404**, and the body is the site's own Hindi error page (37,032 bytes of HTML,
 * `<title>क्षमा कीजिए!</title>` — "Sorry!"), not a rules file. It contains
 * **0 occurrences of `Disallow` and 0 of `User-agent`** (both grepped), so
 * there is no rule to honour and **no URL is blocked below on robots grounds**.
 * Every exclusion in `block` is a content-quality call. Same probe on the bare
 * apex follows the 301 to the same 404.
 *
 * ## Sitemap — 40 entries, no delta from recon, and `https://` locs
 *
 * Verified 2026-07-30: `https://www.everystudent.in/sitemap.xml` → HTTP 200,
 * **3,169 bytes**, `content-type: application/xml`, **Last-Modified
 * 2025-12-22** — seven months old, not the 2014 fossil `everystudent.sk` was
 * catalogued from. A single flat `<urlset>` (no `<sitemapindex>`, so no
 * recursion), generated by xml-sitemaps.com, carrying no `lastmod`,
 * `changefreq` or `priority`. It holds **40 `<loc>` elements and 40 distinct
 * URLs** — no duplicates. That matches this slice's recon figure of ~40
 * **exactly: zero delta**.
 *
 * `/sitemap_index.xml` was tried as well and returns **404** (the same 37 KB
 * Hindi error page), so there is no Yoast-style index hiding a larger set.
 *
 * ⚠️ **All 40 `<loc>` values use the `https://` scheme** (counted: 40 of 40,
 * `http://` 0 of 40). `discover.ts` filters the RAW `<loc>` string without
 * normalising, so the `^https://` pin below is correct here — unlike
 * `everystudent.gr`, where an `^https://` pin would have discovered nothing.
 *
 * The 40 break down as:
 *   - **30 `/a/<slug>.html`** — the article corpus discovery keeps.
 *   - **6 `/m/<slug>.html`** — section indexes (`existence`, `questions`,
 *     `relationships`, `knowing`) plus `/m/map.html` (site plan) and
 *     `/m/about.html`. BLOCKED, below.
 *   - **`/contact.html`**, **`/john.html`**, **`/john_thanks.html`** and **`/`**.
 *     All BLOCKED, below.
 *
 * **All 40 URLs are live.** A full sweep returned **40 × HTTP 200 with no
 * redirect at all** — there is no dead-URL cohort of the kind `everystudent-ro`
 * shipped 25 of, and nothing redirects to the homepage.
 *
 * ⚠️ **The slugs are pure ASCII English even though the content is Devanagari.**
 * This was checked, not assumed: all 40 `<loc>` values were scanned for
 * non-ASCII bytes and for `%XX` percent-encoding and returned **zero hits** —
 * the site publishes Hindi articles at the English slugs its parent
 * everystudent.com uses (`/a/isthere.html`, `/a/trinity.html`). So an
 * ASCII-only hint regex loses nothing here. One slug IS mixed-case,
 * **`/a/Godreal.html`**, so the hint uses `[^/]+` rather than `[a-z0-9-]+`; a
 * lowercase-only class would have silently dropped that article.
 *
 * ## HTML-map cross-check — the site's own map is the SUPERSET, 4 articles pinned
 *
 * These generated sitemaps are known to be stale, so `/m/map.html` ("साइट का
 * नक्शा" — "site map") was fetched and diffed. Verified 2026-07-30: it links
 * **34 `/a/` URLs — the XML sitemap's 30 plus 4 the XML omits**, and there are
 * **0 `/a/` URLs in the XML that the map lacks**. The four extras were fetched
 * and are genuine articles, so they are pinned in `seedPaths` (acquire.ts unions
 * seeds with discovered URLs):
 *   - **`/a/sawyer.html` — 21,431 ch.** "आशा के साथ जीवन" ("Life with hope"),
 *     Steve's testimony after an HIV diagnosis.
 *   - **`/a/source.html` — 15,366 ch.** "एक परिवर्तित जीवन का उद्गम" ("The
 *     source of a changed life").
 *   - **`/a/nickv.html` — 3,442 ch.** Nick Vujicic's video transcript,
 *     "ईश्वर को जानना".
 *   - **`/a/plates.html` — 1,732 ch.** "गिरती तश्तरियाँ" ("Falling Plates"),
 *     the film's transcript. ⓘ KEPT, unlike the Polish sibling's `/wideo.html`,
 *     which was dropped because it extracted as ~60 one-line blocks that chunk
 *     badly. Measured here it is **9 paragraph blocks, median 116 chars** —
 *     ordinary prose that respects paragraph boundaries (invariant 4). The
 *     sitemap already carries two comparable transcript articles
 *     (`/a/gods-help-video.html`, `/a/personally-video.html`), so keeping this
 *     one is consistent rather than exceptional.
 *
 * As a wider net, every internal `href` across all 47 fetched pages was
 * harvested: **46 distinct URLs**, adding exactly three more beyond the map —
 * `/a/fol.html`, `/bible.html` and `/m/intl.html`, all blocked below on measured
 * evidence. `/john_thanks.html` is the reverse case: it sits in the XML sitemap
 * but **no page links to it** (it is the post-signup thank-you), and it is
 * blocked too.
 *
 * ## Extraction — `.contentpadding`, measured on THIS host
 *
 * Verified 2026-07-30 by running the repo's own `extractContent`
 * (node-html-parser, exactly as `src/acquisition/extract.ts` uses it) over all
 * 47 fetched pages — not grepped, because `.content4`, `.content4b`,
 * `.contentpadding`, `.fccell`, `.fctable`, `.hr2`, `.articledivider` and
 * `.relatedbottom` are **all declared in the page's inline `<style>` block**, so
 * a grep false-positives on every one of them. Every candidate the campaign has
 * seen across the estate was measured, zeros included:
 *
 *   - **`.contentpadding` — 1 instance, and the whole article.** Matches on
 *     **34 of 34 kept pages** and extracts **2,021 – 25,039 chars** (raw
 *     pre-strip 2,333 – 25,280). **It is never a matched-but-empty element: 0
 *     of 34 extract zero characters.** This is the shipped selector.
 *   - **`.content4` — matches, and extracts 0 chars on every article page.**
 *     An empty float wrapper: 34 of 34 kept pages match it at **0 chars**.
 *     Listing it first would bind the wrapper, extract nothing, and skip every
 *     article as `too-thin` on an HTTP 200 — the silent batch-1 failure (#128).
 *     It is deliberately absent from `contentSelectors`.
 *   - **`#content4` (the ID form) — 0 instances.**
 *   - **`.content4b` — 0 instances.** ⓘ The raw HTML *does* contain
 *     `<div class="content4b">`, but a stray `</sitelevel_noindex>` pops the
 *     open-element stack before it, so the parser never forms that element (nor
 *     `.container2`, nor `<body>`). Grepping the markup would have "found" it;
 *     the parser does not.
 *   - **`.contentleftpadding`, `.cb-entry-content`, `.entry-content`,
 *     `.post-content`, `.article-content`, `.content`, `article`, `main` — 0
 *     instances each.** Absent from this host.
 *   - **`.articletitle` — 1 instance, 11–74 chars.** A title, not a body.
 *   - **`<body>` — 0 instances on all 34 article pages** (present only on the
 *     homepage and 4 `/m/` indexes), so `extractContent`'s implicit
 *     `body ?? root` fallback would land on the document root and leak the
 *     literal `<!DOCTYPE html>` text node.
 *   - **`html` — always matches, 19,677 – 45,187 chars unstripped.**
 *
 * **`"html"` is appended as the LAST entry, and it is safe precisely because
 * `.contentpadding` has ZERO matched-but-empty pages.** It cannot shadow
 * anything (nothing follows it), it fires only if `.contentpadding` is missing,
 * and it beats the implicit `root` fallback because `<html>` is a real element
 * carrying no doctype text node. Today it never fires on a kept page: measured
 * across all 34, **0 pages fall back**. It exists so that a future article whose
 * container collapses on broken markup degrades to a whole-page document rather
 * than to the `<!DOCTYPE html>` blob that cost `everystudent-pl` an article.
 * `"head"` is paired with it in `stripSelectors` for the same reason.
 *
 * **Measured end to end with the shipped selectors and strip list across all 34
 * kept articles: 1,732 – 25,039 chars, median 11,985, total 392,266, and 0
 * pages below the 250-char floor.** Re-scanned afterwards for chrome leftovers
 * ("दूसरों केसाथ बाँटिए" = "share with others", "साइट का नक्शा", "►",
 * `<!DOCTYPE`): **none survive**.
 *
 * ⚠️ `.contentpadding` also binds on `/contact.html`, `/john.html`,
 * `/john_thanks.html`, `/m/about.html`, `/m/map.html` and `/m/intl.html` — it
 * does NOT discriminate article from chrome. The URL filters do that.
 *
 * ## Chrome stripped — each selector's own contribution, measured
 *
 * Figures are the characters each selector removes **on its own** (baseline
 * strip list plus that one selector), inside the `.contentpadding` scope:
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`, so the missing leading dot
 *     is correct. **2 instances, exactly 170 chars, on all 34 articles** — the
 *     "परमेश्वर के वचन को स्वयं पढ़ें / दूसरों केसाथ बाँटिए" ("Read God's Word
 *     yourself / Share with others") header row and the "प्रश्न कीजिए ? … ►
 *     साइट का नक्शा" footer block. ⓘ Its 4 open tags are matched by 4 close
 *     tags on every page checked — **this host's wrapper is well-formed**, so
 *     do not repeat the `-de`/`-ru` "malformed markup" note here.
 *   - **`.fctable` — 1–2 instances, 71–388 chars**: the "FEATURE CLOSE"
 *     call-to-action table ("► मैंने यीशु को अपने जीवन में आने के लिए कहा … ►
 *     मेरा एक सवाल है"). **`.fccell` — 4–8 instances, the same 71–388 chars**,
 *     because the cells nest inside the table. Both are listed: with the table
 *     stripped first `.fccell` then matches 0, but stripping only the cells
 *     would leave the table shell.
 *   - **`.a2a_kit` — 2 instances, 0 chars.** The AddToAny share row; its
 *     buttons are images and `structuredText` does not read `alt`. Kept as a
 *     drift guard against text labels appearing later.
 *   - **`.shareiconsmenupg` — 1 instance, 21 chars in isolation**
 *     ("दूसरों केसाथ बाँटिए"). ⓘ On THIS host `sitelevel_noindex` is well-formed
 *     and already contains it, so **in list order this selector matches 0
 *     elements and removes 0 chars** — a documented no-op kept as a guard, the
 *     same finding as `everystudent-pl`.
 *   - **`.hr2` (2–6 instances) and `.articledivider` (0–1)** — bind, but are
 *     empty presentational divs drawing the rules around the CTA. **0 chars.**
 *   - **`head` — 0 instances inside `.contentpadding`, 0 chars** on all 34
 *     articles. It matters only on the `"html"` fallback path, where it drops
 *     the duplicated `<title>`. Safe because `extract.ts` reads the title from
 *     `root` at line 43, BEFORE the strip loop at line 52 — an edit that
 *     reorders those two steps would lose every title.
 *   - **`.relatedbottom` — 0 instances, and OMITTED** rather than carried as a
 *     parity no-op. It has been dead config on every host measured in this
 *     campaign; its presence in a sibling list is not evidence it binds.
 *
 * ## What is blocked, and the measured evidence for each
 *
 * `articleHints` already excludes everything outside `/a/`. The list below is
 * deliberately redundant for those, recording *why* each group is out so a later
 * widening of the hints cannot silently readmit them. **One entry is NOT
 * redundant** — `/a/fol.html` sits under `/a/` and matches `articleHints`, so
 * `block` is the only thing keeping it out.
 *
 * All char counts are post-strip, measured with the repo's own `extractContent`.
 * **Never argue "minContentLength will drop it":** when no content selector
 * matches, `extract.ts` falls back to `<body> ?? root`, and `<body>` is absent
 * from the parsed tree on this host's article pages — so the real fallback is
 * the whole document. A sibling staged 25 byte-identical homepage copies on that
 * reasoning. If a page is not wanted, it is blocked by URL.
 *
 *   - **`/a/fol.html` — 612 ch.** "परमेश्वर के साथ आरम्भ करना" ("Starting with
 *     God"): the post-decision referral page, whose body is an invitation to
 *     leave for the partner site EkNayaJeevan.com and sign up for a free
 *     "आत्मिक जीवन आरम्भ करने वाले की किट" ("spiritual starter kit"). The Hindi
 *     twin of the Polish `/a/nowezycie.html` (619 ch) and the German
 *     `/abenteuerreise.html` — the estate's "adventure/pack email series" page.
 *     It clears the 250 floor, it is absent from today's XML sitemap (so
 *     discovery cannot reach it), and it is linked from the CTA of 16 pages —
 *     the block is what makes its exclusion deliberate rather than lucky.
 *   - **`/bible.html` — SCRIPTURE, blocked under the estate-wide policy
 *     (2026-07-29).** Titled "परमेश्वर के वचन को स्वयं पढ़ें" ("Read God's Word
 *     yourself"), it is the Bible-reading landing page linked from the header of
 *     every single article — the Hindi analogue of the Albanian
 *     `/a/gjoni.html`. Public-domain Scripture text rather than ministry
 *     writing, so outside what this corpus answers from. Note the anchors: this
 *     pattern is pinned to the ROOT path and must never be loosened to a bare
 *     `bible\.html`, which would also kill the article below.
 *   - **`/a/bible.html` is KEPT — it is an essay ABOUT the Bible, not the
 *     Bible.** 24,712 ch, "बाइबल का इतिहास – बाइबल किसने लिखी है – यह
 *     विश्वसनीय क्यों है ?" ("History of the Bible – who wrote it – why is it
 *     reliable?"). Told apart from Scripture by structure, not by title: it is
 *     argumentative prose that opens "बाइबल 40 लेखकों के द्वारा, 1500 साल की
 *     अवधि के दौरान लिखी गई" ("the Bible was written by 40 authors over 1,500
 *     years") and closes on a numbered bibliography of SECONDARY sources
 *     (मैक्डोवेल / McDowell, टेसिटस / Tacitus, Zondervan), with no chapter-and-
 *     verse run anywhere. No third-party Bible-society copyright appears on it,
 *     so the `rights` line below does not misattribute.
 *   - **The 6 `/m/` indexes plus `/m/intl.html`.** The 4 section indexes have no
 *     `.contentpadding` at all (`html` binds instead) and yield **386–1,226 ch**
 *     of headline+teaser link list. `/m/map.html` (1,422 ch) is the site plan;
 *     `/m/about.html` (864 ch) is the about page; `/m/intl.html` (11 ch) is the
 *     other-languages index, absent from the sitemap and found only by link
 *     harvest. All navigation, none of it content.
 *   - **`/contact.html` — 338 ch.** "हमसे संपर्क करें", the contact form plus a
 *     privacy statement. It CLEARS the 250 floor.
 *   - **`/john.html` — 1,807 ch.** "यूहन्ना के सुसमाचार में एक अध्ययन" — the
 *     localized Gospel-of-John email-study signup, the Hindi twin of the French
 *     `/jean.html`, Romanian `/ioan.html` and Arabic `/john.html`.
 *   - **`/john_thanks.html` — 315 ch.** Its post-signup thank-you page ("पहली
 *     ईमेल आपके मेलबॉक्स में अगले ही कुछ मिन्टों में होगी!"). In the sitemap,
 *     linked from nowhere, and over the floor.
 *   - **`/` — 961 ch.** The homepage. It has no `.contentpadding`, so `"html"`
 *     binds and it yields its full teaser list rather than nothing.
 *
 * ## Language: `["hi"]` — read and counted, not inferred from the script
 *
 * Verified 2026-07-30 by reading the extracted text. `/a/trinity.html` asks
 * **"क्या आप त्रिएकत्व की व्याख्या कर सकते हैं?"** ("Can you explain the
 * Trinity?"); `/a/isthere.html` is "क्या परमेश्वर का अस्तित्व है – छः ऐसे कारण
 * हैं जो विश्वास दिलाते हैं" ("Does God exist — six reasons that persuade");
 * `/a/why.html` is "जीवन इतना कठिन क्यों है?" ("Why is life so hard?");
 * `/a/plates.html` narrates "मैं ही रास्ता और सच्चाई और जीवन हूँ, मैं जीसस हूँ"
 * ("I am the way, the truth and the life — I am Jesus"). Genuine Hindi prose,
 * not the untranslated-English failure mode cru.org's Spanish path showed.
 *
 * ⚠️ **Devanagari alone does NOT decide this** — Nepali (`ne`,
 * nepalistudent.net) uses the same script and is being registered in the same
 * batch, so the two were separated on counted grammar across all 30 sitemap
 * articles (350,295 extracted chars):
 *
 * | marker | language | occurrences |
 * |---|---|---|
 * | `है` / `हैं` (copula) | Hindi | **2,788 / 1,187** |
 * | `का` / `की` / `के` (genitive) | Hindi | **905 / 1,130 / 2,065** |
 * | `में` (locative) | Hindi | **1,515** |
 * | `छ` / `छन्` (copula) | Nepali | **2 / 0** |
 * | `मा` (locative) | Nepali | **0** |
 * | `गर्न` / `हुन्` / `थियो` | Nepali | **0 / 0 / 0** |
 *
 * The two `छ` hits are both `छ:` — the Hindi numeral "six" in
 * `/a/jesusislam.html`, not the Nepali copula. Nepali-exclusive markers are
 * therefore effectively **zero**, against ~4,000 Hindi copulas.
 *
 * ⚠️ **The word boundaries had to include `\p{M}`, not just `\p{L}`.** Devanagari
 * vowel signs (ा ो ं ्) are combining marks, so a `(?<!\p{L})…(?!\p{L})` guard
 * matches `छ` inside `छोटा` and `है` inside `हैं`. The first pass with the
 * Latin-shaped guard reported 594 false `छ` hits and inflated `है` by 1,193; the
 * corrected `(?<![\p{L}\p{M}\p{N}])…(?![\p{L}\p{M}\p{N}])` guard produced the
 * table above. `को` and `हो` are deliberately excluded from the verdict — both
 * are ordinary Hindi words as well as Nepali ones, so they discriminate nothing.
 *
 * **Encoding.** ⚠️ Responses carry a bare **`content-type: text/html` with NO
 * charset parameter**; the charset is declared only in-document
 * (`<meta charset=utf-8>`). Checked rather than trusted: all 40 pages
 * **strict-decode as UTF-8 with 0 replacement characters (U+FFFD)** and 0
 * mojibake markers, and the extracted corpus is **99.9% Devanagari** (265,078
 * Devanagari characters against 238 Latin). The 238 Latin characters are 26
 * short bibliographic runs — book titles ("The Dead Sea Scrolls", "Know Why You
 * Believe"), cited domains (www.reasons.org, biblegateway.com), "COVID-19", the
 * DNA bases "A, T, G, C" — normal citation apparatus in a translated article,
 * not an untranslated body. `<html lang="hi">` is declared and agrees, but the
 * verdict rests on the counts above, not on that attribute
 * (persoalanhidup.com declares `lang="id"` and serves Malay).
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly. Roughly 100
 * sequential requests at ~0.4–0.5s spacing drew **zero 429s** and no throttling,
 * so the sibling default is kept rather than raised.
 *
 * **Expected yield: 34 documents** — the 30 `/a/` URLs discovery finds in the
 * sitemap, plus the 4 pinned seeds.
 */
import type { SourceEntry } from "./types.js";

export const everystudentHi: SourceEntry = {
  key: "everystudent-hi",
  name: "EveryStudent — Hindi (EveryStudent.in)",
  domain: "www.everystudent.in",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["hi"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:hi"],
  defaultCategory: "article",
  rights:
    "© EveryStudent.in (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everystudent.in",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // here. Cloudflare fronts the host but serves no block page. See header.
    sitemaps: ["/sitemap.xml"],
    // Pinned because the XML sitemap omits them while the site's own
    // /m/map.html lists them. All four fetched and confirmed genuine articles
    // (1,732-21,431 ch). acquire.ts unions seeds with discovered URLs.
    seedPaths: [
      "/a/nickv.html",
      "/a/plates.html",
      "/a/sawyer.html",
      "/a/source.html",
    ],
    allow: ["^https://www\\.everystudent\\.in/"],
    // All 40 sitemap <loc> values use https:// (counted 40/40), so ^https:// is
    // right here. `[^/]+` rather than a lowercase class: /a/Godreal.html carries
    // an uppercase G. Slugs are pure ASCII English despite the Devanagari body
    // (verified: 0 non-ASCII bytes, 0 %XX escapes across all 40 locs).
    articleHints: ["^https://www\\.everystudent\\.in/a/[^/]+\\.html$"],
    block: [
      // The estate's "Who was Jesus?" page (21,724 chars) — curated highlights
      // from the Gospel of John carrying the family's own formula: excerpts
      // taken straight from the Bible with NO COMMENTARY ADDED. Verbatim
      // Scripture, not ministry writing, so it is excluded 2026-08-06 under the
      // same estate-wide policy that blocked the FULL Gospel of John
      // (`sq /a/gjoni.html` 98.9k, `es /articulos/biblia_juan.html` 100.4k) and
      // `everystudent-ar`'s /bible/**.pdf: "outside what this corpus answers
      // from". This is the ~20-26k curated version of the same thing; all 13
      // instances across the estate go together (campaign #111 §0.13).
      // NOT inert — sibling copies took ranks 7 and 8 on a cross question,
      // consuming top-10 slots a real answer would hold.
      // It matches the article shape, so only a URL block catches it.
      "^https://www\\.everystudent\\.in/a/whowas\\.html$",
      // ── NOT redundant: this matches articleHints, so `block` is the only
      // thing excluding it. "परमेश्वर के साथ आरम्भ करना" (612 ch) — the
      // post-decision referral/starter-kit signup pointing at EkNayaJeevan.com.
      // Hindi twin of the Polish /a/nowezycie.html. Clears the 250 floor;
      // absent from the sitemap but linked from 16 pages' CTA.
      "^https://www\\.everystudent\\.in/a/fol\\.html$",
      // SCRIPTURE — "परमेश्वर के वचन को स्वयं पढ़ें" ("Read God's Word
      // yourself"), the Bible-reading page linked from every article header.
      // Blocked under the estate-wide policy set 2026-07-29. ⚠️ Anchored to the
      // ROOT path on purpose: a bare `bible\.html` would also kill
      // /a/bible.html, which is an apologetics ESSAY about the Bible (24,712 ch,
      // secondary-source bibliography, no verse runs) and is deliberately kept.
      "^https://www\\.everystudent\\.in/bible\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 6 section/nav indexes plus /m/intl.html (the other-languages page,
      // 11 ch, sitemap-absent). The 4 section indexes have no .contentpadding,
      // so `html` binds and returns 386-1,226 ch of teaser link list;
      // /m/map.html is the site plan (1,422 ch), /m/about.html the about page
      // (864 ch). All clear the 250 floor.
      "^https://www\\.everystudent\\.in/m/",
      // contact = the contact form (338 ch); john = the Gospel-of-John email
      // study signup (1,807 ch, Hindi twin of the French /jean.html);
      // john_thanks = its post-signup thank-you (315 ch). All over the floor.
      "^https://www\\.everystudent\\.in/(contact|john|john_thanks)\\.html$",
      // The homepage — no .contentpadding, so `html` binds and it yields 961 ch
      // of teaser headlines rather than nothing.
      "^https://www\\.everystudent\\.in/?$",
    ],
    // `.contentpadding` measured 2026-07-30 as the sole element extracting the
    // article: 34/34 kept pages match it, NONE at 0 chars, 1,732-25,039 ch
    // post-strip. `.content4` is deliberately ABSENT — it matches on all 34 and
    // extracts 0 chars, and extractContent binds the first selector that
    // MATCHES rather than the first that yields text, so listing it would skip
    // every article as `too-thin` on an HTTP 200 (#128).
    // "html" is a LAST-position fallback only: it cannot shadow anything, and
    // because .contentpadding is never matched-but-empty it fires on 0 of 34
    // pages today. It exists so a future collapsed container degrades to a whole
    // page instead of extractContent's implicit root (which leaks "<!DOCTYPE
    // html>" — <body> is absent from this host's article pages).
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Pairs with the "html" fallback: 0 instances / 0 chars inside
      // .contentpadding, but on the fallback path it drops the duplicated
      // <title>. Safe because extract.ts reads the title from `root` (line 43)
      // BEFORE this strip loop (line 52) — keep that order.
      "head",
      // Site-specific chrome, each counted on this host 2026-07-30 (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 inst / 170 ch on all 34: the "read God's Word / share" header + footer blocks. Well-formed here.
      ".fctable", // the "FEATURE CLOSE" CTA table, 1-2 inst / 71-388 ch
      ".fccell", // its cells — same text; listed so the shell cannot survive alone
      ".a2a_kit", // AddToAny share row, 2 inst / 0 chars (image-only buttons today)
      ".shareiconsmenupg", // 21 ch in isolation, but 0 in list order — sitelevel_noindex already contains it here. Drift guard.
      ".hr2", // empty divs drawing the rules around the CTA block, 0 chars
      ".articledivider",
      // `.relatedbottom` is deliberately NOT listed: 0 instances on this host.
    ],
    requestDelayMs: 1000, // direct fetches, no proxy; 0 × 429 over ~100 requests
    maxPages: 80, // 40 sitemap URLs + 4 pinned seeds + headroom
    minContentLength: 250,
  },
};
