/**
 * EveryStudent — Greek (everystudent.gr, "Αναζητήσεις για τη ζωή και τον Θεό" /
 * "Searches for life and God"). The Greek banner of Cru's seeker-facing Q&A
 * ministry, run by Agape (Cru's Greek arm, named on /m/about.shtml): short
 * apologetics and life-issue articles, FAQ answers and first-person testimonies
 * written for Greek-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-pl`, `everystudent-sq`, `everystudent-cs`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everystudent.gr is its own domain, so it gets its own
 * key, the same way `everystudent-pl` (kazdystudent.pl), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-29: robots.txt, /sitemap.xml, all 43 sitemap URLs, /a/fol.shtml
 * and ~25 probe URLs were fetched with plain `curl` carrying a desktop-Chrome UA.
 * **Every live page returned HTTP/2 200 with real HTML**; responses are `server:
 * nginx` + `x-powered-by: PleskLin` with no Cloudflare layer and no block page.
 * So `fetchStrategy` is intentionally OMITTED — plain HTTP is the default and
 * nothing here needs Firecrawl (ADR-0012). Discovery is therefore free, making
 * this a **discovery crawl** rather than the hand-listed seed set the three
 * walled banners were forced into. Precedent: `thelife-fr`, `everystudent-pl`.
 *
 * ## ⚠️ The sitemap publishes `http://` URLs — an estate first
 *
 * Verified 2026-07-29: every one of the 43 `<loc>` values is
 * `http://www.everystudent.gr/…`, **not https**. `discoverUrls` filters and
 * returns the raw `<loc>` string verbatim (it never rewrites the scheme), so the
 * `allow` / `articleHints` / `block` regexes below **must** admit `http` or
 * discovery keeps nothing at all. Every sibling to date pins `^https://`; this is
 * the first host where that would have yielded an empty crawl. They use
 * `^https?://` for that reason, and the `s?` is load-bearing, not defensive.
 *
 * Fetching is unaffected: all 43 http URLs **301 to the identical path on https**
 * (measured one by one — the redirect is a pure scheme upgrade, no path or host
 * change), and `HttpFetcher` sets `redirect: "follow"`. ⓘ Consequence to know:
 * because `normalizeUrl` preserves the scheme, these documents will be stored
 * under their `http://` URLs. Deterministic and stable across runs, just
 * cosmetically unlike the siblings.
 *
 * Both apex and `www` serve the site (apex does NOT redirect to www), but every
 * `<loc>` uses `www`, so `www.everystudent.gr` is the canonical host here.
 *
 * ## robots.txt — one rule, and it names an article
 *
 * Verified 2026-07-29: HTTP 200, 36 bytes, Last-Modified 2022-05-02. The file is
 * exactly two lines:
 *
 *     User-agent: *
 *     Disallow: /a/fol.shtml
 *
 * Like the Albanian sibling and unlike the Polish one, the single rule **points
 * into the `/a/` article namespace**, so it had to be honoured rather than noted.
 * `/a/fol.shtml` returns 200 and extracts **3,422 chars** ("Ξεκινώντας με το Θεό"
 * — "Starting with God", the post-decision follow-up page), so neither the 250
 * floor nor the article-hint regex would have excluded it. It is **absent from
 * /sitemap.xml and from the site's own HTML map**, so discovery cannot reach it
 * today — but it IS linked from every article, and it matches `articleHints`
 * exactly, so it is blocked below explicitly. The acquire path does not enforce
 * robots.txt (known gap), which is precisely why this block is by hand: the day
 * the generated sitemap picks the page up, the block is the only thing stopping
 * it. Note this page is a 33rd article, NOT one of the 32 counted below.
 *
 * ## Sitemap — 43 entries, all distinct, 32 articles
 *
 * Verified 2026-07-29: `https://www.everystudent.gr/sitemap.xml` → HTTP 200,
 * 3,337 bytes, a single flat `<urlset>` (no `<sitemapindex>`, so no recursion),
 * generated by xml-sitemaps.com. 43 `<loc>` elements, **43 distinct URLs** — no
 * duplicates. Matches the "~43" from prior recon exactly. The breakdown:
 *   - **32 `/a/<slug>.shtml`** — the article corpus. This is the keep set.
 *   - **9 `/m/<slug>.shtml`** — section indexes (`existence`, `jesus`,
 *     `experience`, `issues`, `enigmas`, `forum`, `sitemap`, `about`, `intl`).
 *     BLOCKED.
 *   - **`/index.shtml`** and **`/`** — the homepage under two URLs. BLOCKED.
 * Note the extension is `.shtml`, not the `.html` every sibling uses — the hint
 * regex is pinned to it.
 *
 * **All 32 articles are live and not one redirects.** A no-follow sweep of all 43
 * https URLs returned **42 × 200 and 1 × 404**, and the 404 is `/m/jesus.shtml` —
 * a section index that is blocked anyway. **No sitemap URL redirects to the
 * homepage** and no article URL redirects at all, so there is no dead-seed cohort
 * of the kind a sibling shipped 25 of.
 *
 * ⓘ The only redirect anywhere on this host is the scheme upgrade described
 * above: each of the 43 `http://` sitemap URLs 301s to the same path on https.
 *
 * ⚠️ **Slugs are pure lowercase ASCII — checked, not assumed.** All 43 `<loc>`
 * values were scanned for non-ASCII bytes, for `%XX` percent-encoding and for
 * uppercase letters: **zero hits on all three**. Despite being a Greek-script
 * site the slugs are English words (`/a/isthere.shtml`, `/a/loveorlust.shtml`),
 * so no Greek-script or percent-encoded URL hazard exists here. `[^/]+` is used
 * anyway so a future mixed-case slug cannot be silently dropped.
 *
 * ## Cross-checked against the site's own HTML map — no delta, so no seeds
 *
 * These generated sitemaps are known to be stale, so `/m/sitemap.shtml`
 * ("Διάγραμμα του δικτυακού τόπου") was fetched and diffed. Verified 2026-07-29:
 * it links **32 `/a/` URLs, and the two sets are identical** — 0 in the HTML map
 * that the XML lacks, 0 the other way. Then, as a wider net, every `href` on all
 * 43 pages was harvested. That union adds exactly **two** internal paths beyond
 * the sitemap, and neither is a missing article:
 *   - **`/a/fol.shtml`** — the robots.txt-disallowed follow-up page (above).
 *   - **`/en/word/john11.shtml`** — a **dead 404**, linked from `/a/faith.shtml`.
 *     Its shape (`/en/word/john…`) suggests a retired Gospel-of-John reader.
 * So **no article is missing from discovery** and `seedPaths` is deliberately
 * absent: there is nothing to pin.
 *
 * ⓘ **This host has no email-signup funnel to block.** The Gospel-of-John study
 * page and the "spiritual adventure" email series that every sibling carries
 * (`/jean.html`, `/jan.html`, `/gjonit.html`, `/pack.html`, `/aventure.html`, …)
 * **do not exist here** — 22 candidate slugs were probed on 2026-07-29
 * (`/ioannis`, `/ioanni`, `/john`, `/a/john`, `/pack`, `/adventure`,
 * `/peripeteia`, … in both `.shtml` and `.html`) and **all 22 returned 404**.
 * The site's calls to action link out to the ENGLISH everystudent.com
 * (`/question.html`, 224 occurrences), which `allow` excludes by host. Nothing to
 * block, so nothing is blocked for it — this is an absence that was measured.
 *
 * ⓘ **No full Scripture on this host, so the estate-wide scripture block does not
 * apply.** The longest article, `/a/bible.shtml` (30,923 chars), was read: it is
 * "Γιατί μπορείς να Εμπιστεύεσαι τη Βίβλο;" ("Why you can trust the Bible"), a
 * manuscript-and-archaeology apologetics piece, NOT a Bible book. There is no
 * twin of the Albanian `/a/gjoni.html` or Spanish `/articulos/biblia_juan.html`.
 *
 * ## ⚠️ EXTRACTION: the shared EveryStudent template DOES NOT BIND here
 *
 * This is the one decision that would silently destroy the source if undone, so
 * it was measured rather than inherited. Every candidate was run through the
 * repo's own parser (`node-html-parser`, exactly as `src/acquisition/extract.ts`
 * uses it) over all 43 sitemap pages plus /a/fol.shtml on 2026-07-29 — not
 * grepped, since these tokens also appear in the pages' inline `<style>` blocks.
 * Across the 32 article pages:
 *
 *   - **`.contentpadding` — 0 matches. ABSENT.**
 *   - **`.content4` — 0 matches. ABSENT** (as a CLASS — see the trap below).
 *   - **`.content4b`, `.contentleftpadding`, `.content`, `.article-content`,
 *     `.entry-content`, `.cb-entry-content`, `.articletitle`, `.articlebody`,
 *     `<article>`, `<main>` — 0 matches each. ABSENT.**
 *   - **`#content4` — 1 match on 31/32, extracting 2,099–30,998 chars raw.** The
 *     article, and nothing above it. **Zero-char matches: none.**
 *   - `#content_box` — matches 32/32 but is `#content4` plus 162 chars of
 *     wrapper on every page, and is the **0-char trap** on the one broken page.
 *   - `#container` — `#content4` plus ~4,540 chars of header/sidebar chrome.
 *   - `<body>` — 31/32 (absent on the broken page); whole-page, 5,386–36,927 ch.
 *   - `<html>` — 32/32, whole document, 6,938–38,498 ch.
 *
 * ⚠️ **`content4` is an ID on this host, not a class.** The markup is
 * `<div id="content4">`; there is no `class="content4"` anywhere. So the sibling
 * selector `.content4` silently matches nothing here, and `#content4` — one
 * character different — is the answer. This is the third distinct generator in
 * the `everystudent.<cc>` naming shape (`.cz` = bespoke Yii `.content`, `.hu`/`.ro`
 * = `.contentpadding`, `.bg` = Angular `.article-content`, `.gr` = `#content4`).
 * The domain name predicts nothing.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text —
 * so listing `#content_box` after `#content4` "as a fallback" would bind an empty
 * div on /a/personally.shtml, extract 0 chars, and skip it as `too-thin` on an
 * HTTP 200: silent, and invisible to the unit tests. That is how five of the
 * eight pilot entries first shipped. `contentSelectors` here is therefore the
 * single measured container and nothing else.
 *
 * **Measured with `["#content4"]` plus the strip list below, across the 31
 * healthy articles: 2,021 – 30,923 chars, median 11,232, and 0 pages below the
 * 250 floor.** Output opens on the article `<h1>` and closes on the article's own
 * numbered scripture-footnote line, with no cookie bar, nav, breadcrumb, share
 * row, CTA or footer left.
 *
 * ## ⚠️ `/a/personally.shtml` — one page whose container collapses
 *
 * Verified 2026-07-29: on this ONE article the parsed tree loses `#content4`,
 * `#content_box` (matches but holds **0 chars**), `#container` **and `<body>`** —
 * the article ends up as flat direct children of `<html>`. Cause: two `<p>`
 * blocks wrap block-level children (`<p>…<ul>…</ul></p>` at line 208 and
 * `<p>…<table>…</table></p>` at line 219). node-html-parser auto-closes `<p>` on
 * the block opener, so each trailing `</p>` arrives as a stray end tag and pops
 * the open-element stack one level further than it should. Raw `<div>` nesting is
 * perfectly balanced (49/49) and structurally identical to a healthy page, so
 * this is invisible to any tag-counting check. Confirmed by bisection: no single
 * line removal restores the tree — the pops are cumulative.
 *
 * **It is NOT blocked**, unlike the Polish sibling's equivalent
 * (`/a/biblia.html`), because here the damage is fully repairable from the strip
 * list. With no selector matching, `extractContent` falls through to `<body> ??
 * root`; `<body>` is also gone, so the container is the document root. Adding the
 * four page-chrome IDs (`#cookie-notice`, `#head_container`, `#sidebar`,
 * `#footer`) plus `head` to `stripSelectors` turns that root fallback from 6,804
 * chars of nav-polluted text into **6,072 chars of clean article** — the four
 * spiritual laws presentation, opening on its title and closing on the prayer.
 * Those five selectors were measured across all 32 articles: on the 31 healthy
 * ones they live OUTSIDE `#content4` and change the output by **exactly 0 chars**
 * (delta measured page by page), so they cost nothing and rescue a page that
 * would otherwise have to be dropped. This is why they are in the list.
 *
 * ⓘ **The one residue is a literal `<!DOCTYPE html>` at the head of that single
 * document** (17 chars) — the doctype node the root container carries and the
 * `-sq` entry documents. A `contentSelectors: ["#content4", "html"]` chain would
 * remove it (`<html>` is a real element, so no doctype node), and it is safe here
 * because `#content4` never matches with 0 chars on any article. It is left OUT
 * anyway: the brief for this entry is one measured selector, and a 17-char wart
 * on 1 of 31 documents does not justify the fallback-chain footgun. **Flagged for
 * the orchestrator** — adding `"html"` as a second entry is a one-line change.
 *
 * ## Chrome stripped — every selector measured on THIS host, 2026-07-29
 *
 * Marginal contribution, measured by re-running the full extraction with each
 * selector withheld, over all 32 articles:
 *
 *   - **`.sectionlink` — 75 instances on 31/32 pages, removing 54–213 chars per
 *     page (3,741 total).** This host's equivalent of the siblings' "FEATURE
 *     CLOSE" CTA block: the trailing action links "Πώς να αρχίσω μια σχέση με τον
 *     Θεό" ("How do I start a relationship with God"), "Έχω μια ερώτηση…" ("I have
 *     a question…"), "Ζήτησα από τον Ιησού να έρθει…". The single largest real
 *     removal. It carries no `.fccell`/`.fctable` class — see below.
 *   - **`.navtree1` — 31 instances on 31/32 pages, 9–24 chars each (518 total).**
 *     The section breadcrumb above the headline ("Γνωρίζοντας τον Θεό").
 *   - **`head`, `#cookie-notice`, `#head_container`, `#sidebar`, `#footer` — 0
 *     chars on all 31 healthy articles** (they sit outside `#content4`), and
 *     **732 chars on /a/personally.shtml**, where the container falls back to the
 *     document root. Present solely for that page. See the section above.
 *   - **`.a2a_kit` — 62 instances on 31/32 pages, 0 chars.** The AddToAny share
 *     row; the buttons are empty anchors and `structuredText` reads no `alt`.
 *     Stripped so a markup change that adds text labels cannot leak them.
 *   - **`.fblike` (31 inst), `.hr1` (105 inst), `.articledividerforum` (21 inst),
 *     `.articledivider` (9 inst) — 0 chars each**, confirmed. Empty presentational
 *     divs drawing the rules that bracket sections and the CTA block.
 *
 * ⚠️ **Every selector on the standard EveryStudent chrome list is a
 * 0-INSTANCE no-op here and is therefore NOT in the list below.** Measured, not
 * assumed — `sitelevel_noindex` **0 instances**, `.fccell` **0**, `.fctable`
 * **0**, `.hr2` **0**, `.relatedbottom` **0**, `.shareiconsmenupg` **0**. This
 * host carries no FreeFind `sitelevel_noindex` markers at all, which is also why
 * it shows none of the malformed-wrapper damage that `-de`/`-ru` have: its one
 * broken page breaks for an unrelated reason (stray `</p>`, above). Do not add
 * them back expecting them to bind; `.sectionlink` is what `.fccell` would have
 * been here.
 *
 * ⓘ **`.pullquoteNEW` is deliberately NOT stripped.** 9 instances across 4
 * articles, 1,241 chars. Checked individually: **7 of the 9 are unique text**
 * (testimony callouts that appear nowhere else in the article) and only 2, both
 * on `/a/quench.shtml`, duplicate a body paragraph. Stripping would delete far
 * more real content than duplicate, so it stays. Revisit only if the chunker
 * shows the 2 duplicates hurting.
 *
 * ## ⚠️ minContentLength cannot be relied on to catch the non-articles
 *
 * Every page blocked below was fetched and extracted under the shipped config.
 * Verified 2026-07-29 — the homepage and 7 of the 9 indexes **clear the 250-char
 * floor**, so the floor could not have excluded them and the `block` list is
 * doing real work:
 *   - **`/` and `/index.shtml` — 559 chars each**, byte-identical teaser lists
 *     ("ΥΠΑΡΧΕΙ ΘΕΟΣ; Έξι ξεκάθαροι λόγοι…"). The homepage does NOT extract to 0:
 *     `#content4` is absent, so the fallback yields its full teaser page. Two URLs
 *     for one page, so leaving them would stage two identical documents.
 *   - **the 9 `/m/` indexes — 94 to 1,281 chars** of headline+teaser link lists.
 *     `/m/sitemap.shtml` (1,281 ch) is the site plan; `/m/about.shtml` (1,101 ch)
 *     is about + privacy; `/m/intl.shtml` (189 ch) is the other-languages page and
 *     the only one carrying English; `/m/jesus.shtml` is the 404 (94 ch).
 *   - **`/a/fol.shtml` — 3,422 chars.** robots-disallowed; see above.
 *
 * ## Language: `["el"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Greek prose, not untranslated English. `/a/isthere.shtml` is "Υπάρχει
 * Θεός;" ("Does God exist?") and opens "Δε θα σου άρεσε να σου δείξει κάποιος
 * στοιχεία της παρουσίας του Θεού…" ("Wouldn't you like someone to show you
 * evidence of God's presence…"); `/a/prayers.shtml` is "Απαντάει ο Θεός στις
 * προσευχές μας;" and narrates "Τον καιρό που ήμουν άθεη είχα κάποια καλή φίλη
 * που προσευχόταν συχνά" ("When I was an atheist I had a good friend who prayed
 * often"); `/a/trinity.shtml` is "Μπορείς να εξηγήσεις την Τριαδικότητα;";
 * `/a/personally.shtml` quotes John 3:16 in Greek ("Τόσο πολύ αγάπησε ο Θεός τον
 * κόσμο…"). Scripture citations use Greek book names throughout (Κατά Ιωάννην,
 * Α΄ Πέτρου, Ησαΐας, Ψαλμός, Ρωμαίους, Φιλιππησίους, Ιερεμίας, Αποκάλυψη).
 *
 * Counted by hand across all 32 articles (codepoint tally, no library): **Greek
 * letters are 94.7%–100.0% of all letters**, the floor being `/a/bible.shtml`
 * (22,873 Greek vs 1,292 Latin) where the Latin is bibliographic — English book
 * and author names in the footnotes. That is normal citation apparatus in a
 * translated article, not an untranslated body. **No page showed the cru.org
 * `/mx/es/` failure mode of a localized URL serving an English body.** The only
 * English page on the domain is `/m/intl.shtml`, which is blocked.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * ## Encoding — clean UTF-8, declared twice
 *
 * Verified 2026-07-29 because a Greek-script host makes this load-bearing, and
 * two siblings (`studentinjapan.com`, `everykoreanstudent.com`) send a bare
 * `content-type` with no charset. This host does not have that problem: every
 * live page returns **`content-type: text/html; charset=utf-8`** in the HTTP
 * header AND declares `<meta http-equiv="content-type" content="text/html;
 * charset=utf-8"/>` in the document, with `<html lang="el">`. All 32 articles
 * were scanned for U+FFFD replacement characters and for the `Î`/`Ã` byte-pair
 * artefacts that UTF-8-read-as-ISO-8859-7 would produce: **0 pages affected**.
 * The Greek reads clean.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~110 sequential requests
 * across the recon drew **zero 429s and no throttling**, so the sibling default is
 * kept rather than raised.
 *
 * **Expected yield: 32 documents** — all 32 `/a/` articles in the sitemap. The
 * robots-disallowed `/a/fol.shtml` is a 33rd article that the sitemap does not
 * list, so blocking it costs nothing today and guards against a regenerated
 * sitemap tomorrow. Running the entry's own `allow`/`articleHints`/`block`
 * regexes over the real 43-URL sitemap keeps exactly those 32 and drops the
 * other 11 (verified 2026-07-29).
 */
import type { SourceEntry } from "./types.js";

export const everystudentEl: SourceEntry = {
  key: "everystudent-el",
  name: "EveryStudent — Greek (EveryStudent.gr)",
  domain: "www.everystudent.gr",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["el"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:el"],
  defaultCategory: "article",
  rights:
    "© EveryStudent.gr (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (nginx/Plesk, no Cloudflare). See header.
    baseUrl: "https://www.everystudent.gr",
    sitemaps: ["/sitemap.xml"],
    // ⚠️ `https?` is REQUIRED, not defensive: every <loc> in this sitemap is
    // `http://www.everystudent.gr/…`, and discoverUrls filters the raw <loc>
    // string without rewriting the scheme. An `^https://` pin — what every
    // sibling uses — would discover ZERO urls here. All 43 http URLs 301 to the
    // same path on https and HttpFetcher follows redirects. See header.
    allow: ["^https?://www\\.everystudent\\.gr/"],
    // The whole article corpus: 32 of the 43 sitemap URLs. Note `.shtml`, not
    // the `.html` every sibling uses. `[^/]+` rather than a lowercase class:
    // today's 43 slugs are verified all-lowercase pure ASCII (zero non-ASCII
    // bytes, zero %XX escapes, zero uppercase), but this keeps a future
    // mixed-case slug from being silently dropped.
    articleHints: ["^https?://www\\.everystudent\\.gr/a/[^/]+\\.shtml$"],
    block: [
      // ── This one matches articleHints; `block` is the ONLY thing excluding it.
      // robots.txt Disallow, fetched live 2026-07-29 — the single rule on this
      // host, and it names an /a/ path. "Ξεκινώντας με το Θεό" returns 200 and
      // extracts 3,422 chars, so nothing else would have excluded it. Absent
      // from the sitemap but linked from every article. The acquire path does
      // not enforce robots.txt, so this block is the enforcement.
      "^https?://www\\.everystudent\\.gr/a/fol\\.shtml$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 9 section indexes (existence, jesus, experience, issues, enigmas,
      // forum, sitemap, about, intl) — headline+teaser link lists extracting
      // 94-1,281 chars, so 7 of the 9 CLEAR minContentLength and the floor can
      // NOT catch them. /m/sitemap.shtml is the site plan; /m/about.shtml is
      // about + privacy; /m/intl.shtml is the other-languages page and the only
      // English page on the domain; /m/jesus.shtml is a 404.
      "^https?://www\\.everystudent\\.gr/m/",
      // The homepage, published under BOTH URLs — 559 chars of identical teaser
      // list each, so leaving them would stage two byte-identical documents.
      // It does NOT extract to 0: #content4 is absent, so the fallback returns
      // the whole teaser page.
      "^https?://www\\.everystudent\\.gr/index\\.shtml$",
      "^https?://www\\.everystudent\\.gr/?$",
      // /en/word/john11.shtml is linked from /a/faith.shtml and is a dead 404.
      // Not in the sitemap, so discovery cannot reach it today. Blocked as a
      // forward guard: the path shape is a retired Gospel-of-John reader, and
      // the estate-wide scripture policy (set by everystudent-ar, applied by
      // -sq/-et/-mn/-fa) keeps verbatim Bible text out of this corpus.
      "^https?://www\\.everystudent\\.gr/en/",
    ],
    // ⚠️ `content4` is an ID here, NOT a class — `<div id="content4">`, with no
    // class="content4" anywhere on the host. The sibling `.content4` matches
    // NOTHING, and so do .contentpadding, .content4b, .articletitle, article and
    // main (all measured 0 matches across 32 articles). #content4 matches on
    // 31/32 with 2,099-30,998 raw chars and never yields 0 chars.
    // Do NOT add #content_box as a "fallback": extractContent binds the first
    // selector that MATCHES, and on /a/personally.shtml #content_box matches
    // while holding 0 chars — it would turn that page into a silent too-thin
    // skip. That page is instead rescued by the page-chrome strips below.
    contentSelectors: ["#content4", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // ── Page chrome that lives OUTSIDE #content4: measured 0-char no-ops on
      // all 31 healthy articles, and the 732 chars that make the root fallback
      // on /a/personally.shtml (whose container collapses to the document root
      // via stray </p> tags) a clean 6,072-char article instead of a nav dump.
      "head",
      "#cookie-notice",
      "#head_container",
      "#sidebar",
      "#footer",
      // ── Chrome inside #content4, all counted on this host 2026-07-29:
      ".sectionlink", // the CTA action links — 75 inst, 54-213 ch/page. This host's .fccell.
      ".navtree1", // section breadcrumb above the headline — 31 inst, 9-24 ch
      ".a2a_kit", // AddToAny share row — 62 inst, 0 ch today (empty anchors)
      ".fblike", // 31 inst, 0 ch
      ".hr1", // empty divs drawing the section rules — 105 inst, 0 ch
      ".articledividerforum", // 21 inst, 0 ch
      ".articledivider", // 9 inst, 0 ch
      // NB: sitelevel_noindex, .fccell, .fctable, .hr2, .relatedbottom and
      // .shareiconsmenupg are all 0 INSTANCES on this host (measured) and are
      // deliberately omitted rather than carried as parity no-ops. See header.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 60, // 43 sitemap URLs (32 articles, all 32 kept) + headroom
    minContentLength: 250,
  },
};
