/**
 * EveryStudent — Romanian (everystudent.ro). The Romanian banner of Cru's
 * seeker-facing Q&A ministry: short apologetics/life-issue articles aimed at
 * Romanian-speaking students who are not believers.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everystudent.ro is its own domain, so it gets its own
 * key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate from their
 * English parents.
 *
 * **NOT walled — plain HTTP, so no `fetchStrategy`.** Verified 2026-07-28:
 * `robots.txt`, `/sitemap.xml`, the homepage and every article page probed
 * returned **200** to a plain `curl` with a browser UA. No Cloudflare block-page
 * signature anywhere (no "Attention Required", no "Just a moment"). This is the
 * first EveryStudent banner in the estate that does NOT need Firecrawl — the
 * three walled ones (`everystudent`, `everystudent-ar`, `everystudent-fr`) are
 * the exception here, not the rule. Omitting `fetchStrategy` leaves it at the
 * `plain-http` default, so this source costs nothing per page.
 *
 * **Discovery mode, not hand-listed seeds** — the opposite call from the three
 * walled siblings, and for exactly the reason their headers give: they hand-list
 * because their `/sitemap.xml` is 403 and re-enumeration costs Firecrawl credits.
 * Neither applies here. `/sitemap.xml` is public and free, so `sitemaps` +
 * `allow`/`articleHints`/`block` is strictly better — it picks up new articles
 * without an entry edit. Precedent: `thelife-fr`.
 *
 * **`robots.txt` is `User-agent: * Allow: /`** — fetched live 2026-07-28, 22
 * bytes, the entire file. No Disallow rules at all, so nothing in the article
 * set is disallowed. Same as everyarabstudent.com and questions2vie.com, and
 * UNLIKE everystudent.com, which carries a real disallow list. Note the bare
 * apex `everystudent.ro` 301s to `www.everystudent.ro`; `domain`/`baseUrl` use
 * the `www.` form the sitemap's own `<loc>` entries use, so no redirect hop is
 * paid per page.
 *
 * **Sitemap: 102 URLs, all unique** (verified 2026-07-28, `<urlset>` not a
 * `<sitemapindex>`; generated by xml-sitemaps.com with a 2019 `lastmod`):
 *   - **85 `/a/*.html`** — the article corpus.
 *   - **5 `/v/*.html`** — video pages. **Kept, not dropped**: 4 of the 5 carry a
 *     real Romanian transcript under a "Transcriere video:" heading (measured
 *     1,619–6,644 chars of body text), which is substantive seeker content in
 *     the same voice as the articles. The English sibling makes the same call —
 *     it seeds `/videos/*`, including `/videos/collins.html`, the very same
 *     Francis Collins piece that lives here at `/v/collins.html`.
 *   - **8 `/m/*.html`** — the mobile/menu section indexes (`acord`, `credinta`,
 *     `despre`, `existenta`, `intl`, `intrebari`, `relatii`, `viata`).
 *     Navigation, not articles: `/m/intrebari.html` extracts to 906 chars that
 *     are purely a list of other pages' titles. `/m/intl.html` is the page
 *     linking out to the sibling language domains. Blocked, matching the `/m/`
 *     drop in `everystudent-fr` and `/menus/` in `everystudent`.
 *   - **`/sitemap.html`** — the "Harta site-ului" link index (2,575 chars of
 *     nothing but other pages' titles). The Romanian twin of the `/sitemap.html`
 *     the English entry drops. Blocked.
 *   - **`/contact.html`** — the "Întreabă-ne" contact form + privacy notice
 *     (886 chars). Blocked.
 *   - **`/ioan.html`** — an email-signup landing page for a Gospel-of-John email
 *     series (1,550 chars: "Înregistrare", "o serie de mesaje trimise prin
 *     email", an unsubscribe explanation, signed by the site director). Blocked.
 *     This is the exact Romanian twin of `/jean.html` on the French banner,
 *     which slice #10 seeded provisionally, fetched, and then dropped on
 *     evidence. It clears `minContentLength` comfortably — length is not
 *     aboutness — so the floor could never have caught it and the URL block is
 *     doing real work.
 *   - **the bare homepage.** Blocked (and see below — it is also inert).
 *
 * ⚠️ **The sitemap is STALE: 25 of the 85 `/a/` URLs are dead.** HEAD-checked all
 * 90 `/a/` + `/v/` URLs on 2026-07-28: 65 returned 200 and **25 returned 301 to
 * the homepage** (`/a/adam`, `/a/apostolii`, `/a/asemanare`, `/a/astazi`,
 * `/a/cale`, `/a/care`, `/a/ceva`, `/a/cine`, `/a/cine2`, `/a/coronavirus`,
 * `/a/fericire`, `/a/iad`, `/a/inchinare`, `/a/inspirata`, `/a/intamplare`,
 * `/a/iubitor`, `/a/miracole`, `/a/nimic`, `/a/ofera`, `/a/raul2`,
 * `/a/religiile`, `/a/rezultat`, `/a/sex`, `/a/sex2`, `/a/suferinta`). The
 * filters below keep 90 of the sitemap's 102 URLs (85 `/a/` + 5 `/v/`), but only
 * **65 of those are live**, and one live `/v/` page is a transcript-less embed
 * (below), so expect **~64 ingested documents**, not 102. Do not read a
 * shortfall against the sitemap count as a crawl failure.
 *
 * ⚠️ **All 25 are HARD-BLOCKED below, and must stay that way.** This entry
 * originally left them unblocked on the theory that they were "self-policing" —
 * the homepage carries none of the template selectors, so extraction would yield
 * 0 chars and `minContentLength` would drop them. **That reasoning was wrong,
 * and a real acquire run on 2026-07-28 proved it.** It overlooked
 * `extractContent`'s fallback (`src/acquisition/extract.ts:50`):
 *
 *     const container = scope ?? root.querySelector("body") ?? root;
 *
 * When NO `contentSelector` matches, extraction does not return nothing — it
 * falls back to `<body>` and returns the whole page. On the homepage that is the
 * 842-char teaser list ("Care este scopul meu în viaţă?… Există Dumnezeu?…"),
 * comfortably above the 250 floor. The unblocked run staged **89 documents, 25
 * of them byte-identical copies of that nav page** (verified by `md5(raw_content)`
 * — a single hash with `count = 25`). They are not deduped away either: the
 * ingest dedup gate keys on `(sourceKey, canonicalUrl)`, so 25 distinct URLs
 * mean 25 separate documents chunked and embedded.
 *
 * So the floor does NOT handle it, and a 25-branch block regex is the cheap
 * option. If the site restores any of these pages, drop it from the alternation.
 * The expected yield is unchanged at **~64 documents** — that number was always
 * right; only the mechanism was wrong.
 *
 * **Extraction — `.contentpadding` is the container, and `.content4` is an
 * EMPTY SPACER that must never precede it.** Re-verified 2026-07-28 by running
 * the repo's own `extractContent` against live pages, which is the only check
 * that proves anything here:
 *   - `.contentpadding` — **1 instance, the whole article**. `/a/exista.html` →
 *     20,511 chars raw, **20,214 after stripping**, ending on its own last
 *     footnote; `/a/scop.html` → 3,782 raw / 3,628 stripped.
 *   - `.content4` — **1 instance, an empty spacer div: 0 characters.**
 *   - `.content4b` — **0 instances.** Absent from this host entirely.
 *   - `.articletitle` — an `<h1>`, 16–30 chars. A title, not a body.
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not the
 * first that yields text, so listing `.content4` ahead of `.contentpadding`
 * bound the empty spacer and extracted **0 chars on every page** — every article
 * skipped as `too-thin` on a 200 status, with no error anywhere. That is how
 * this entry first shipped.
 *
 * **Strip list — re-counted 2026-07-28 inside `.contentpadding`.** The earlier
 * figures were taken against a container that extracted nothing and are
 * superseded. `sitelevel_noindex` (a custom element) removes **102 chars** on
 * both sampled pages; `.fccell` — the call-to-action table — removes **195** on
 * `/a/exista.html` and **52** on `/a/scop.html`; `.hr2` (2 instances) and
 * `.articledivider` (1) are rule divs at **0 chars**. `.relatedbottom` has **no
 * element instance** on this host — retained for parity with the siblings, but
 * it strips nothing and that is not a mistake to "fix".
 *
 * The addition: **`.shareiconsmenupg` is site-specific and load-bearing** (1
 * instance, 8 chars). `sitelevel_noindex` alone does not contain the share
 * widget, because this host's markup overlaps: the `<sitelevel_noindex>` that
 * nominally wraps it opens inside `.contentpadding` and closes only after
 * `.contentpadding` has closed, so any conforming parser pops it at the first
 * `</div>` and the widget survives as a direct child of the container (#128).
 * Without this selector every extracted body ended in a dangling "SHARE:". Do
 * not remove it on the grounds that `sitelevel_noindex` "already covers" the
 * share links — on this host it does not.
 *
 * `/v/filmuliisus.html` is likewise left unblocked and left to the floor: it is a
 * bare 2-hour JESUS film embed with no transcript, extracting to **53 chars**,
 * so `minContentLength` drops it. The other four `/v/` pages survive.
 *
 * **Language: `["ro"]` — read, not assumed.** The probed pages serve genuine
 * Romanian prose with correct diacritics (ș/ț/ă/î/â), not untranslated English:
 * `/a/exista.html` opens "Există dovezi ale existenţei lui Dumnezeu?" ("Is there
 * evidence of God's existence?") and `/a/depresie.html` is titled "Sfârşitul
 * depresiei" ("The end of depression"). The stored per-document label still
 * comes from content detection at ingest (invariant 6), never from this field.
 *
 * ⓘ **Romanian is a NEW language for this corpus** — unlike French at slice #10,
 * no `ro` documents exist yet, so no existing golden case becomes eligible by
 * construction and Stage-4 Part A re-review has nothing to re-rank. `ro` starts
 * as a single-source language for gating purposes.
 *
 * `requestDelayMs: 1000` — plain HTTP against a small static Apache site. The
 * 100+ probe requests made during recon (including a 90-URL HEAD sweep at 400ms)
 * drew no 429 and no throttling, so 1s is comfortably polite.
 */
import type { SourceEntry } from "./types.js";

export const everystudentRo: SourceEntry = {
  key: "everystudent-ro",
  name: "EveryStudent — Romanian (everystudent.ro)",
  domain: "www.everystudent.ro",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ro"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ro"],
  defaultCategory: "article",
  rights:
    "© EveryStudent.ro (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everystudent.ro",
    // No `fetchStrategy`: this banner is NOT walled (verified 2026-07-28, all
    // 200s to plain curl), so it stays on the plain-http default. See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.everystudent\\.ro/"],
    articleHints: [
      // The article corpus (85 in the sitemap, 60 of them live).
      "^https://www\\.everystudent\\.ro/a/[^/]+\\.html$",
      // Video pages — 4 of 5 carry a real Romanian transcript. See header.
      "^https://www\\.everystudent\\.ro/v/[^/]+\\.html$",
    ],
    block: [
      // The estate's "Who was Jesus?" page (22,539 chars) — curated highlights
      // from the Gospel of John carrying the family's own formula: excerpts
      // taken straight from the Bible with NO COMMENTARY ADDED. Verbatim
      // Scripture, not ministry writing, so it is excluded 2026-08-06 under the
      // same estate-wide policy that blocked the FULL Gospel of John
      // (`sq /a/gjoni.html` 98.9k, `es /articulos/biblia_juan.html` 100.4k) and
      // `everystudent-ar`'s /bible/**.pdf: "outside what this corpus answers
      // from". This is the ~20-26k curated version of the same thing; all 13
      // instances across the estate go together (campaign #111 §0.13).
      // NOT inert — sibling copies took ranks 7 and 8 on a cross question,
      // consuming top-10 slots a real answer would hold.
      // It matches the article shape, so only a URL block catches it.
      "^https://www\\.everystudent\\.ro/a/cineafostiisus\\.html$",
      // /m/* are the mobile/menu section indexes — navigation, not articles.
      // /m/intl.html is also the page linking to the sibling language domains.
      "^https://www\\.everystudent\\.ro/m/",
      // Link indexes, contact chrome, and the Gospel-of-John email-signup
      // landing page (the Romanian twin of the French /jean.html, dropped at
      // slice #10 — it clears minContentLength, so only a URL block catches it).
      "^https://www\\.everystudent\\.ro/(sitemap|contact|ioan)\\.html$",
      // The homepage. NOTE: it does NOT extract to 0 chars — no contentSelector
      // matches, so extractContent falls back to <body> and yields the 842-char
      // teaser list. It must be blocked by URL, not left to minContentLength.
      "^https://www\\.everystudent\\.ro/?$",
      // The 25 dead /a/ URLs that 301 to the homepage (see header). Each one
      // therefore extracts that same 842-char nav page via the <body> fallback,
      // and the ingest dedup gate keys on (sourceKey, canonicalUrl) so they do
      // NOT collapse — an unblocked run staged 25 byte-identical copies.
      // Verified dead 2026-07-28 (301) and again by the 2026-07-28 acquire run.
      // If the site restores a page, remove it from this alternation.
      "^https://www\\.everystudent\\.ro/a/(adam|apostolii|asemanare|astazi|cale|care|ceva|cine|cine2|coronavirus|fericire|iad|inchinare|inspirata|intamplare|iubitor|miracole|nimic|ofera|raul2|religiile|rezultat|sex|sex2|suferinta)\\.html$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-28 as the sole element on this
    // host that extracts the article. `.content4` is deliberately ABSENT: it is
    // an empty spacer div (0 chars) and, because extractContent scopes to the
    // first selector that MATCHES rather than the first that yields text,
    // listing it here made every page skip as `too-thin`. `.content4b` does not
    // exist on this host.
    // Rule 1e (added 2026-07-30, retrofitted): trailing "html" rescues pages
    // whose .contentpadding container collapses. Without it extract.ts falls
    // through to `?? root`, which returns the whole document INCLUDING a
    // literal `<!DOCTYPE html>` text node. Proven inert on healthy pages —
    // 21 of 21 sampled extractions were byte-identical before and after.
    // It can shadow nothing, because nothing follows it.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "head", // 0 ch inside .contentpadding; strips the duplicated
      // <title> on the "html" fallback path only. Safe because extract.ts
      // reads the title from `root` BEFORE the strip loop runs.
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome, measured on this host 2026-07-28 (see header):
      "sitelevel_noindex", // custom element: cookie notice, sidebar, nav
      ".relatedbottom", // CSS-only on this host; kept for sibling parity
      ".fccell", // the "FEATURE CLOSE" call-to-action table
      ".hr2",
      ".articledivider",
      // NOT covered by sitelevel_noindex here: the site's markup overlaps, so
      // the share widget resolves to a direct child of .content4 and every body
      // otherwise ends in a dangling "SHARE:". See header.
      ".shareiconsmenupg",
    ],
    requestDelayMs: 1000, // plain HTTP, small static site; no 429s seen in recon
    maxPages: 150, // 102 sitemap URLs + headroom
    minContentLength: 250,
  },
};
