/**
 * EveryStudent — Telugu (everytelugustudent.com). The Telugu banner of Cru's
 * seeker-facing Q&A ministry: short apologetics and life-issue articles, FAQ
 * answers and first-person testimonies written for Telugu-speaking students who
 * are not believers. A sibling of `everystudent` (en), `everystudent-bn`,
 * `everystudent-sq`, `everystudent-pl`, `everystudent-ko`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everytelugustudent.com is its own domain, so it gets
 * its own key, the same way `everystudent-bn` (everybengalistudent.com),
 * `everystudent-fr` (questions2vie.com), `thelife-fr` (laviejenparle.com) and
 * `thelife-zh` (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP throughout
 *
 * Verified 2026-07-30: robots.txt, /sitemap.xml, **all 39 sitemap URLs**,
 * /a/fol.html, /m/intl.html and ~19 probe URLs were fetched with plain `curl`
 * carrying a full desktop-Chrome UA. Every live page returned **HTTP/2 200 with
 * real HTML**; responses are `server: Apache` with **no Cloudflare layer at
 * all** and no block-page signature anywhere. So `fetchStrategy` is
 * intentionally OMITTED: plain HTTP is the default and nothing here needs
 * Firecrawl (ADR-0012). Discovery is therefore free, making this a **discovery
 * crawl** rather than the hand-listed seed set the three walled banners
 * (everystudent.com, everyarabstudent.com, questions2vie.com) were forced into.
 * Precedent for the shape: `thelife-fr`, `everystudent-bn`.
 *
 * **Canonical host is `www.`, checked BOTH ways.** Verified 2026-07-30: the bare
 * apex `http://everytelugustudent.com/` returns **301 → https://www.everytelugu
 * student.com/**, and `https://www.…` returns 200. That is the normal direction
 * for this estate but the OPPOSITE of `everystudent.sk`, so it was measured
 * rather than assumed. `domain`, `baseUrl` and every regex below are pinned to
 * `www.` — the sitemap emits `www` absolute URLs and the filters match the full
 * absolute URL, so an apex-pinned regex would match nothing.
 *
 * ## robots.txt — nothing is disallowed
 *
 * Verified 2026-07-30: HTTP 200. The entire file is a single line,
 * `User-agent: * Allow: /` (the same one-line form as everyarabstudent.com and
 * questions2vie.com). There is **no `Disallow` rule of any kind**, so no URL is
 * blocked below on robots grounds — every exclusion here is a content-quality
 * call. Note the contrast with `everystudent-sq`, whose single Disallow named an
 * `/a/` article and had to be honoured by hand; nothing of that sort exists here.
 *
 * ## Sitemap — 39 entries, matching the brief's recon exactly
 *
 * Verified 2026-07-30: `https://www.everytelugustudent.com/sitemap.xml` → HTTP
 * 200, **3,342 bytes**, `application/xml`, a single flat `<urlset>` (no
 * `<sitemapindex>`, so no recursion), generated by xml-sitemaps.com. It holds
 * **39 `<loc>` elements, all distinct** — no delta from the "~39" prior recon.
 * `/sitemap_index.xml` is a **404** (there is no Yoast index hiding a larger
 * inventory, the way `everystudent.sk`'s 2014 fossil did).
 *
 * ⓘ Its `Last-Modified` is **2017-10-26**, which is old enough to warrant the
 * fossil check — but it is NOT stale: all 39 URLs were swept and returned
 * **39 × 200 with zero redirects**, and the site's own HTML map lists exactly the
 * same 30 articles (below). The host is simply a static site that has not
 * changed since 2017.
 *
 * **Scheme is `https://` on every `<loc>`** (checked, because `everystudent.gr`
 * publishes `http://` and `discover.ts` filters the RAW `<loc>` string without
 * normalising). So the `^https://` pin below is correct here; no `^https?://`
 * widening is needed.
 *
 * The 39 break down as:
 *   - **30 `/a/<slug>.html`** — the article corpus. This is the keep set (29
 *     after the scripture block below).
 *   - **7 `/m/<slug>.html`** — section indexes (`existence`, `questions`,
 *     `relationships`, `knowing`, `forum`, `map`, `about`). BLOCKED.
 *   - **`/contact.html`** — the question form. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 *
 * ⚠️ **Slugs are pure ASCII — checked, not assumed.** All 39 `<loc>` values were
 * scanned for non-ASCII bytes and for `%XX` percent-encoding: **zero hits**. The
 * Telugu banner reuses the English slugs verbatim (`/a/isthere.html`,
 * `/a/gaylesbian.html`, `/a/whowas.html`) while every body is Telugu, so an
 * ASCII hint is safe HERE. It is still written `[^/]+` rather than `[a-z0-9-]+`
 * because **one slug is mixed-case — `/a/Godreal.html`** — and a lowercase-only
 * class would have silently dropped it.
 *
 * ## Cross-checked against the site's own HTML sitemap — no delta
 *
 * These generated sitemaps are known to run short, so `/m/map.html` ("వెబ్ సైట్
 * ఆకారం", "website map") was fetched and diffed against the XML. Verified
 * 2026-07-30: it links **30 `/a/` URLs**, and the two sets are **identical** —
 * 0 in the HTML map that the XML lacks, 0 the other way.
 *
 * As a wider net, every internal `href` across all 39 fetched pages was
 * harvested: **48 distinct on-site URLs**, i.e. 9 beyond the sitemap. Seven of
 * those (`/faith.html`, `/nothing.html`, `/personally.html`, `/reallife.html`,
 * `/something.html`, `/who.html`, `/who2.html`) are **404s** — root-level
 * artefacts of resolving the articles' own relative hrefs against the site root;
 * they are dead and unreachable by discovery, so they are not blocked. The other
 * two are real: `/m/intl.html` (11 chars, "మిగతా బాషలు" / "other languages" — the
 * page linking out to the sibling language domains; excluded by `articleHints`
 * and by the `/m/` block) and **`/a/fol.html`, which is pinned in `seedPaths`**.
 *
 * ## The ONE pinned seed — `/a/fol.html`
 *
 * Verified 2026-07-30: HTTP 200, and a **genuine 2,834-char article** —
 * "దేవునితో ఆరంభించుట" ("Beginning with God"), answering "నేను నా జీవితంలోనికి
 * యేసును ఆహ్వానించినప్పుడు, ఆయన నాలో నిజముగా ఉన్నాడని నేను ఎలా తెలుసుకోగలను?"
 * ("When I invited Jesus into my life, how can I know He is really in me?"). It
 * is continuous prose built on quoted scripture (1 యోహాను 5:14, ప్రకటన 3:20,
 * యోహాను 6:37, 1 పేతురు 3:18), not a signup form: the only CTA is a closing
 * "మాకు ఈమెయిలు చెయ్యండి" ("email us") line. It is **absent from BOTH maps** and
 * reachable only from each article's FEATURE CLOSE cell, so discovery cannot
 * find it — hence the pin. Same call as `everystudent-ms`, which seeds its own
 * `/a/fol.html`; the OPPOSITE of `-th` (944 ch) and `-am` (713 ch), whose
 * same-named pages really are short signup stubs. The difference was read, not
 * inferred from the filename.
 *
 * ## ⚠️ EXTRACTION: the shared EveryStudent template DOES NOT BIND on this host
 *
 * This is the one decision that would silently destroy the source if undone, so
 * every candidate was run through the repo's own parser (`node-html-parser`,
 * exactly as `src/acquisition/extract.ts` uses it) over **all 30 article pages**
 * on 2026-07-30 — measured by extracted TEXT LENGTH, never by grepping for a
 * class name, because these tokens are also declared in each page's inline
 * `<style>` block and a grep false-positives on all of them:
 *
 *   - **`.content4` — matches on 30/30 pages and extracts 0 characters on every
 *     one.** Two empty spacer divs per page. THE SHADOW SELECTOR.
 *   - **`.contentpadding` — 0 matches.** Present once in the raw source but never
 *     as a parsed element.
 *   - **`#content4` (the ID form) — 0 matches on articles.** It does bind on 5 of
 *     the `/m/` indexes (292–674 chars), which are blocked anyway.
 *   - **`.content4b` — 0 matches.** Absent from this host.
 *   - **`.contentleftpadding`, `.entry-content`, `.post-content`,
 *     `.article-content`, `.cb-entry-content`, `.content`, `article`, `main` —
 *     0 matches each.** This is not a WordPress/Yii/Angular generator.
 *   - **`.articletitle` — 27/30 matches, 4–78 chars.** A title, not a body.
 *   - **`<body>` — 0 matches on all 30 articles**, even though `<body>` appears
 *     once in the raw source; the parser loses it.
 *   - **`<html>` — 30/30, and the ONLY element that contains the article**
 *     (6,873–28,377 chars unstripped, mean 15,473).
 *
 * Root cause, same shape as `everystudent-sq` and `-ko`: the FreeFind markers
 * **interleave with** rather than nest inside the content divs. In
 * `/a/isthere.html`, `<sitelevel_noindex>` opens at line 177 and the content
 * stack opens inside it — `<div id="content4">` at 183, `<div class="content4">`
 * at 189, `<div class="contentpadding">` at 190 — but the
 * `</sitelevel_noindex>` at line 204 closes that whole div stack early, and the
 * unmatched close tags also dispose of `<body>` (opened at line 32). Walking the
 * parse tree confirms it: `<html>`'s direct children are `<head>`,
 * `<sitelevel_noindex>`, two empty divs, then `<h1 class="articletitle">` and
 * ~100 bare `<p>` elements — **the article is flat under `<html>`, with no
 * wrapper element left to select.**
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text — so
 * listing `.content4` "outermost first as a fallback" would bind an empty spacer
 * div, extract 0 chars, and skip all 30 articles as `too-thin` on an HTTP 200:
 * silent, and invisible to the unit tests. That is how five of the eight pilot
 * entries first shipped. **And appending `"html"` after `.content4` would not
 * rescue it** — `.content4` MATCHES, so the fallback would never be consulted.
 * `contentSelectors` here is therefore `["html"]` outright.
 *
 * `["html"]` is also deliberately explicit rather than left to
 * `extractContent`'s `body ?? root` fallback: `<body>` is absent, so the implicit
 * fallback would land on `root`, whose doctype node leaks the literal string
 * `<!DOCTYPE html>` into the head of every document. Verified 2026-07-30: with
 * `["html"]`, **0 of 31 extractions begin with `<!DOCTYPE`**.
 *
 * **Measured with `["html"]` plus the strip list below, across all 30 sitemap
 * articles + the pinned seed: 1,911 – 23,429 chars, median 9,112, and 0 pages
 * below the 250 floor.** Output opens on the article title and closes on the
 * article's own last line (usually its numbered footnote list, e.g.
 * "(1) మత్తయి 7:29 (2) మత్తయి 16:15-16 …"), with no nav, share widget, CTA or
 * footer left. Re-scanned for leftovers on 8 articles: no "పంచుకోండి" ("share")
 * label and no "►" CTA bullet survives on any of them.
 *
 * ## ⚠️ SCRIPTURE: `/a/whowas.html` is the abridged Gospel of John — BLOCKED
 *
 * Verified 2026-07-30. Titled "యేసు ఎవరు?" ("Who was Jesus?"), it extracts
 * **23,429 chars** — the single longest page on the domain — and its own
 * standfirst says it plainly: "ఇవి బైబిల్ లోని యోహాను సువార్త నుండి
 * సేకరించబడినవి. ఎలాంటి వ్యాఖ్యలు జోడించబడలేదు" ("These are gathered from the
 * Gospel of John in the Bible. No commentary whatsoever has been added").
 * Walking the extracted text confirms it: 129 blocks running chapter by chapter
 * through **John 1, 3, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 and 20**,
 * each under its own "యోహాను N" heading.
 *
 * Blocked under the **estate-wide scripture policy (2026-07-29)** set by
 * `everystudent-ar` for its `/bible/**.pdf` and applied by `-es`, `-sq`, `-et`,
 * `-mn`, `-fa` and `-bn`: public-domain Scripture text rather than ministry
 * writing — outside what this corpus answers from. `-bn` blocks the byte-for-byte
 * equivalent page at the same slug.
 *
 * **It is also the only third-party-copyright page on the domain.** All 30
 * articles were scanned for "Tyndale", "New Living", "copyright ©", "All rights
 * reserved" and Bible-society markers. Two pages hit, and they are different in
 * kind:
 *   - `/a/whowas.html` closes with "…the Holy Bible, New Living Translation,
 *     copyright © 1996, 2004, 2007 by Tyndale House Foundation. … All rights
 *     reserved." That is a Bible-society licence on text Cru redistributes by
 *     permission, not one this corpus holds, and the `rights` line below would
 *     misattribute it. Two independent reasons to block.
 *   - `/a/isthere.html` matches only on a **bibliographic footnote** —
 *     "(3) R.E.D. Clark, Creation (London: Tyndale Press, 1946), p. 20" — which
 *     is ordinary citation apparatus. KEPT.
 *
 * ⓘ **An apologetics essay ABOUT the Bible is not scripture, and is kept.**
 * `/a/bible.html` ("మీరు బైబిల్ ను ఎందుకు నమ్మవచ్చు" — "Why you can trust the
 * Bible", 15,081 ch) argues *from* history and archaeology *about* the text
 * ("బైబిల్ ను 1500 సంవత్సరాల వ్యవధిలో, 40 రచయితలు వ్రాశారు" — "the Bible was
 * written by 40 authors over 1,500 years"). The test applied was whether the body
 * is quoted scripture under chapter headings with the author's commentary
 * removed — true only of `/a/whowas.html`.
 *
 * ## ⚠️ minContentLength cannot be relied on to catch the non-articles
 *
 * Every page blocked below was fetched and extracted with the real selector +
 * strip list, and **all but one clear the 250-char floor** — so the floor could
 * not have excluded them and `block` is doing real work. Verified 2026-07-30:
 *   - the **7 `/m/` section indexes in the sitemap: 274 – 1,047 chars** of
 *     headline+teaser link list — every one of them ABOVE the floor.
 *     `/m/map.html` (1,047 ch) is the site plan; `/m/about.html` (905 ch) is the
 *     about page. The off-sitemap 8th, `/m/intl.html` (11 ch), is the only page
 *     on the domain the floor would have caught unaided.
 *   - **`/contact.html` — 299 chars.** "ప్రశ్న అడగవచ్చు" ("you may ask a
 *     question"), the email question form plus its privacy note. It clears 250 by
 *     49 chars: exactly the near-miss case where guessing is not good enough.
 *   - **`/` — 1,089 chars.** The homepage. It does NOT extract to 0: `html`
 *     matches on it as readily as on an article, so it yields its full teaser
 *     list. It must be blocked by URL.
 *
 * **There is NO Gospel-of-John signup page and NO "adventure/pack" email series
 * on this host — an absence that was MEASURED, not assumed.** `/john.html`,
 * `/jean.html`, `/pack.html`, `/adventure.html`, `/gospel.html`, `/a/john.html`
 * and `/a/gospel.html` were all probed on 2026-07-30 and **every one is a 404**.
 * `/sitemap.html`, `/m/sitemap.html` and `/plan.html` are 404s too — this host's
 * site plan lives at `/m/map.html`, already covered by the `/m/` block. So the
 * blocks the sibling entries carry for those pages are deliberately absent here
 * rather than copied forward as regexes that can never bind.
 *
 * ## Chrome stripped — measured across all 30 articles, 2026-07-30
 *
 * Instance counts are totals over the 30 articles; char figures are the marginal
 * characters each selector removes, measured by re-running the full extraction
 * with that one selector withheld, on 5 pages (`isthere`, `why`, `bible`,
 * `personally`, `source`):
 *
 *   - **`script` — 181 instances, 1,271–1,418 chars.** `structuredText` reads
 *     inline script bodies, so this is the second-largest contributor and is
 *     load-bearing, not boilerplate.
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **60 instances (2/page),
 *     removing exactly 2,100 chars on every single page** — the largest
 *     contributor by far, carrying the top nav and the bottom related-links +
 *     footer block. Hence the bare tag name with **no leading dot**; the
 *     siblings' form is correct rather than a typo.
 *   - **`head` — 30 instances, 17–33 chars.** Needed **only because the container
 *     is `<html>`**: without it every document opens with a duplicate of its own
 *     `<title>`. Safe because `extract.ts` reads the title from `root` at line 43,
 *     BEFORE the strip loop at line 52 — a future edit that reorders those two
 *     steps would lose every title, so keep them in that order.
 *   - **`.likesharediv` — 60 instances, 12 chars/page.** The share row, and the
 *     one piece of chrome that survives `sitelevel_noindex` on THIS host: the
 *     label "పంచుకోండిి" ("share") sits in a `.likethis` span inside it, OUTSIDE
 *     the well-formed noindex wrapper. Without this selector that word prefixes
 *     all 30 extractions. (`.likethis` and `.floatleft` remove the same 12 chars
 *     because they nest inside; `.likesharediv` is the correct outer level, and
 *     the same selector `everystudent-ko` uses.)
 *   - **`.fccell` — 144 instances, 68–195 chars.** The "FEATURE CLOSE"
 *     call-to-action cells appended to every article.
 *     ⓘ **`.fctable` is 0 instances on this host** — the CTA `<table>` carries no
 *     class here, only its cells do — so it is deliberately NOT in the list. Do
 *     not add it expecting it to bind.
 *   - **`.a2a_kit` — 60 instances, 0 chars.** The AddToAny share-button row; the
 *     buttons are images and `structuredText` does not read `alt`. It nests
 *     inside `.likesharediv`, so in list order it is already gone by the time
 *     this fires — a true no-op today, kept only so a future markup change that
 *     moves the buttons out of that wrapper cannot leak labels into every article.
 *   - **`.hr2` (85 instances) and `.articledivider` (25, on 25/30 pages)** —
 *     empty presentational divs drawing the rules bracketing the CTA. **0 chars**,
 *     confirmed.
 *   - **`style`, `noscript`, `svg`, `nav`, `header`, `footer`, `form`** — the
 *     shared boilerplate prefix. Measured honestly: `noscript`/`svg`/`nav`/
 *     `header`/`footer` are **0 instances** on this host; `style` (181) and
 *     `form` (90) bind but remove **0 chars**.
 *   - **`.shareiconsmenupg` and `.relatedbottom` — 0 instances each**, checked
 *     because siblings carry them. They are **omitted**, not kept as parity
 *     no-ops: nothing on this host can ever bind them, and `.likesharediv` is the
 *     selector that actually does this job here.
 *
 * ## Language: `["te"]` — read, not inferred
 *
 * Verified 2026-07-30 by reading the extracted text myself. The pages serve
 * genuine Telugu prose, not untranslated English. `/a/isthere.html` opens
 * "దేవుడు ఉన్నాడా? దేవుడు ఉన్నాడని నమ్ముటకు ఆరు సూటైన కారణాలు ఇవి" ("Does God
 * exist? Here are six straightforward reasons to believe God exists");
 * `/a/why.html` is "జీవితం – ఎందుకింత కష్టం?" ("Life — why is it so hard?") and
 * asks "లోకంలో మనం చూస్తున్న వాటిని ఎలా వివరించగలం?" ("How can we explain what we
 * see in the world?"); `/a/prayers.html` narrates "నేను దేవుడుని తెలియని
 * వ్యక్తిగా వున్నపుడు (నాస్తికుడు), నా కోసం పదే పదే ప్రార్ధన చేసే
 * స్నేహితురాలుండేది" ("When I was someone who did not know God (an atheist), I
 * had a friend who prayed for me again and again"). Scripture citations use
 * Telugu book names throughout (యోహాను, మత్తయి, మార్కు, రోమా, ప్రకటన, యిర్మీయా,
 * 1 పేతురు, ఫిలిప్పీ).
 *
 * ⚠️ **Script confirmed as TELUGU, U+0C00–U+0C7F — codepoint-counted, not eyeballed,
 * because a sibling agent was writing Tamil (U+0B80–U+0BFF) concurrently.** Across
 * six sampled articles the extracted text is **7,522–19,723 Telugu codepoints per
 * page and ZERO Tamil, ZERO Devanagari**. Sample glyphs read: దేవుడు, యేసు,
 * బైబిల్, ప్రార్ధన — Telugu forms, not Tamil.
 *
 * ⚠️ **Encoding: the header omits the charset, and the bytes are still clean
 * UTF-8.** Responses carry a bare `content-type: text/html` with **no charset
 * parameter** (the apex 301 even advertises `iso-8859-1`), but the documents
 * declare `<meta charset=utf-8>` and decode as valid UTF-8 with no replacement
 * characters and no mojibake — verified by reading the rendered Telugu above.
 * `<html lang="te">` agrees with what was read, but the reading is what decided
 * it (`persoalanhidup.com` declares `lang="id"` and serves Malay).
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~60 sequential
 * plain-HTTP requests drew **zero 429s** and no throttling, so the sibling
 * default is kept rather than raised.
 *
 * **Expected yield: 30 documents** — 30 sitemap articles, minus the blocked
 * `/a/whowas.html`, plus the pinned `/a/fol.html` seed.
 */
import type { SourceEntry } from "./types.js";

export const everystudentTe: SourceEntry = {
  key: "everystudent-te",
  name: "EveryStudent — Telugu (everytelugustudent.com)",
  domain: "www.everytelugustudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["te"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:te"],
  defaultCategory: "article",
  rights:
    "© EveryTeluguStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everytelugustudent.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare at all). See header.
    sitemaps: ["/sitemap.xml"],
    // ONE pinned seed: /a/fol.html is a genuine 2,834-ch article
    // ("దేవునితో ఆరంభించుట") that BOTH the XML sitemap and /m/map.html omit, so
    // discovery cannot reach it. Same call as everystudent-ms.
    seedPaths: ["/a/fol.html"],
    // `^https://` — verified 2026-07-30 that every <loc> is https (unlike
    // everystudent.gr, whose http:// locs need `^https?://`).
    allow: ["^https://www\\.everytelugustudent\\.com/"],
    // The whole article corpus: 30 of the 39 sitemap URLs. `[^/]+` rather than a
    // lowercase class — /a/Godreal.html carries an uppercase G, and a
    // [a-z0-9-]+ hint would silently drop it. Slugs are pure ASCII (verified:
    // zero non-ASCII bytes, zero %XX escapes across all 39 <loc> values), even
    // though every body is Telugu.
    articleHints: ["^https://www\\.everytelugustudent\\.com/a/[^/]+\\.html$"],
    block: [
      // ── This matches articleHints; `block` is the ONLY thing excluding it.
      // "యేసు ఎవరు?" — 23,429 chars of verbatim John (chapters 1,3,5,6,7,10-20
      // under their own headings), whose standfirst says "no commentary
      // whatsoever has been added". Estate-wide scripture policy (2026-07-29),
      // and the ONE page on the domain carrying a third-party licence: "New
      // Living Translation, copyright © … Tyndale House Foundation", which the
      // `rights` line above would misattribute. Contrast /a/bible.html, an
      // apologetics essay ABOUT the Bible, which is kept.
      "^https://www\\.everytelugustudent\\.com/a/whowas\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 7 section indexes (existence, questions, relationships, knowing,
      // forum, map, about) — headline+teaser link lists, 274-1,047 chars, so
      // they CLEAR the 250 floor and the floor cannot catch them. /m/map.html is
      // this host's site plan; /m/intl.html (11 ch, off-sitemap) links out to
      // the sibling language domains.
      "^https://www\\.everytelugustudent\\.com/m/",
      // The email question form, "ప్రశ్న అడగవచ్చు" — 299 chars, clearing the
      // 250 floor by only 49. A near miss, not a safe one.
      "^https://www\\.everytelugustudent\\.com/contact\\.html$",
      // The homepage. It does NOT extract to 0 — `html` matches on it too, so it
      // yields its 1,089-char teaser list. Only a URL block excludes it.
      "^https://www\\.everytelugustudent\\.com/?$",
    ],
    // ⚠️ NOT the shared EveryStudent template. Measured 2026-07-30 over all 30
    // articles: `.content4` MATCHES on 30/30 and extracts 0 chars,
    // `.contentpadding` / `#content4` / `.content4b` / `.entry-content` /
    // `.post-content` / `.article-content` / `.content` match 0/30, and even
    // <body> is lost — a stray </sitelevel_noindex> closes the content divs
    // early and flattens the article into <html>'s direct children. `<html>` is
    // the only element that still contains it.
    // Do NOT prepend `.content4`: extractContent binds the first selector that
    // MATCHES, so it would win on every page and yield "" — and because it
    // matches, appending "html" after it would never fire either.
    contentSelectors: ["html"],
    stripSelectors: [
      "script", // 1,271-1,418 chars: structuredText reads inline script bodies
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Required because the container is <html>: drops the duplicate <title>.
      // extract.ts reads the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-30 (see header):
      "sitelevel_noindex", // custom TAG (2/page): nav + related links + footer — 2,100 chars on all 30
      ".likesharediv", // the share row; its "పంచుకోండిి" label sits OUTSIDE the noindex wrapper — 12 chars
      ".fccell", // "FEATURE CLOSE" CTA cells — 68-195 chars. `.fctable` is 0 instances here.
      ".a2a_kit", // AddToAny buttons — 0 chars, and nested inside .likesharediv; a drift guard only
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      // `.shareiconsmenupg` and `.relatedbottom` are deliberately ABSENT:
      // 0 instances each on this host, so they could never bind.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 60, // 39 sitemap URLs + 1 pinned seed + headroom
    minContentLength: 250,
  },
};
