/**
 * EveryStudent — Slovenian (vsakstudent.com, "VsakStudent.com" / "Every
 * student"). The Slovenian banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, Q&A answers and first-person testimonies
 * written for Slovenian-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-pl`, `everystudent-sq`, `everystudent-hr`
 * and the rest of the estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). vsakstudent.com is its own domain, so it gets its own
 * key, the same way `everystudent-sq` (pyetjetejetes.com), `everystudent-fr`
 * (questions2vie.com), `thelife-fr` (laviejenparle.com) and `thelife-zh`
 * (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-30: robots.txt, /sitemap.xml, all 23 `/a/` articles, all 6
 * `/m/` indexes, the homepage, /janez.html and /pisite.html were fetched with
 * plain `curl` carrying a full desktop-Chrome UA — **every one returned HTTP/2
 * 200 with real HTML**. Response headers are bare `server: Apache` with **no
 * Cloudflare layer at all** and no block-page signature anywhere, so
 * `fetchStrategy` is intentionally OMITTED: plain HTTP is the default
 * (ADR-0012). Discovery is therefore free, making this a **discovery crawl**
 * rather than the hand-listed seed set the three walled banners were forced
 * into. Precedent for the shape: `thelife-fr`, `everystudent-sq`.
 *
 * The bare apex **301-redirects to `www`** (measured on both / and
 * /robots.txt: `https://vsakstudent.com/` → `https://www.vsakstudent.com/`),
 * so `www.vsakstudent.com` is the canonical host and the one every sitemap
 * `<loc>` uses. `domain`, `baseUrl` and every regex below are pinned to `www.`
 * — this host runs the COMMON direction, not the `everystudent.sk` reverse.
 *
 * ## robots.txt — allows everything
 *
 * Verified 2026-07-30: HTTP 200, **22 bytes**, Last-Modified 2018-04-25. The
 * entire file is a single line, `User-agent: * Allow: /`. There is **no
 * Disallow rule at all**, so nothing below is dropped on robots grounds and no
 * path needed blocking by hand to honour it — every exclusion in `block` is a
 * content-quality call.
 *
 * ## Sitemap — 30 entries, https scheme, and it is NOT a fossil
 *
 * Verified 2026-07-30: `https://www.vsakstudent.com/sitemap.xml` → HTTP 200,
 * **2,575 bytes**, `application/xml`, a single flat `<urlset>` (no
 * `<sitemapindex>`, so no recursion), generated by xml-sitemaps.com. It holds
 * **30 `<loc>` elements and 30 distinct URLs** — no duplicates. That matches
 * the "~30" from prior recon exactly, so there is no delta to report.
 *
 * `/sitemap_index.xml`, `/sitemap.xml.gz`, `/sitemap.html`, `/mapa.html`,
 * `/kazalo.html`, `/peta.html` and `/m/sitemap.html` were all probed and all
 * returned **404** — `/sitemap.xml` is the only machine map this host has, so
 * there is no live Yoast index hiding a larger inventory the way
 * `everystudent.sk` had.
 *
 * ⚠️ Its `Last-Modified` is **2017-10-06**, which is exactly the
 * `everystudent.sk` fossil signature — so it was cross-checked rather than
 * trusted. It is NOT a fossil: the site's own live HTML map lists precisely the
 * same 22 `/a/` URLs (below). The file is old because the site is small and
 * static, not because it is stale.
 *
 * ⚠️ **Scheme: the `<loc>` values are `https://`**, so the regexes below pin
 * `^https://`. (`discover.ts` filters the RAW `<loc>` string without
 * normalising, so the `^https?://` widening `everystudent.gr` needed is not
 * required here — and was checked, not assumed.)
 *
 * The 30 break down as:
 *   - **22 `/a/<slug>.html`** — the article corpus, all kept.
 *   - **6 `/m/<slug>.html`** — section indexes (`obstoj`, `odgovori`,
 *     `ostrani`, `spoznati`, `vprasanja`, `zemljevid`). BLOCKED, below.
 *   - **`/janez.html`** — verbatim Scripture. BLOCKED, below.
 *   - **`/`** — the homepage. BLOCKED, below.
 *
 * **All 22 `/a/` URLs are live.** A sweep of the full article set returned
 * **22/22 HTTP 200 with an empty `redirect_url`** — zero 301s, zero 302s.
 * There is **no dead-URL cohort** of the kind `everystudent-ro` shipped 25 of,
 * and no `.php` extension twins of the kind the French entry dropped. Slugs are
 * **pure lowercase ASCII**: all 30 `<loc>` values were scanned for non-ASCII
 * bytes, for `%XX` percent-escapes and for uppercase letters — **zero hits on
 * all three**. The site de-diacriticises its own slugs
 * (`/a/soocanjezneizbeznostjo.html` for "soočanje z neizbežnostjo"). `[^/]+` is
 * used anyway rather than a lowercase class, so a future mixed-case slug cannot
 * silently vanish.
 *
 * ## Cross-checks — the XML map missed one real article, pinned as a seed
 *
 * Two nets were run past the XML sitemap.
 *
 * **Net 1 — the site's own HTML map.** `/m/zemljevid.html` ("Zemljevid strani")
 * links **22 `/a/` URLs, and the two sets are identical**: 0 in the HTML map
 * that the XML lacks, 0 the other way. So the 2017 timestamp cost nothing.
 *
 * **Net 2 — every internal href on all 32 fetched pages.** This is the net that
 * paid, exactly as it did in batch 3. The union adds **one** `/a/` URL that is
 * in **NEITHER map**: **`/a/spoznatiboga2.html`**. It is linked from the body of
 * **11 of the 22 articles**, returns HTTP 200, and is a genuine article —
 * "Kako začeti življenje z Bogom?" ("How to begin life with God?"), 2,907
 * extracted chars of post-decision Q&A prose answering "Pravkar sem Jezusa
 * povabil v svoje srce, sedaj pa nisem prepričan, če je resnično v meni ali ne."
 *
 * It was checked for near-duplication against `/a/spoznatiboga.html`, whose
 * `<title>` is identical: they share **7 of 490 twelve-word shingles = 1.4%**,
 * far below the 87.9% band that got the French `/jeanFR.html` dropped. Two
 * distinct articles under a shared title, not one page at two URLs.
 *
 * Discovery cannot reach it, so it is **pinned in `seedPaths`** — acquire.ts
 * unions seeds with discovered URLs. This is the only seed; everything else
 * comes from the sitemap.
 *
 * **Expected yield: 23 documents** — the 22 sitemap articles plus the seeded
 * one. Measured end-to-end with the exact selector and strip list below:
 * **2,907 – 29,741 chars, median 10,716, and 0 pages below the 250 floor.**
 *
 * ## ⚠️ EXTRACTION: this is a DIFFERENT GENERATOR — no FreeFind class exists
 *
 * This is the decision that would silently destroy the source if undone, so
 * every candidate was run through the repo's own parser (`node-html-parser`,
 * exactly as `src/acquisition/extract.ts` uses it) over all 22 article pages on
 * 2026-07-30 — measured by EXTRACTED TEXT LENGTH, never by grepping for a class
 * name, which false-positives on the inline style block.
 *
 * This host was redesigned onto its own template (`/css/lessframework2022.css`,
 * `/css/menu2022.css`) and **carries none of the FreeFind markup the estate is
 * built around.** Measured, on 22/22 article pages:
 *
 *   - **`.contentpadding` — 0 matches.** The class does not exist here. This is
 *     the "no safe default" case: assuming the sibling default would have bound
 *     nothing.
 *   - **`.content4` — matched, 0 chars** — because it does not match at all: **0
 *     matches** on 22/22.
 *   - **`#content4` — 0 matches.** `.content4b`, `.cb-entry-content`,
 *     `.entry-content`, `.post-content`, `.contentleftpadding`,
 *     `.article-content`, `.content`, `.articletitle`, `.articlebody`,
 *     `<article>`, `<main>` — **0 matches each.** All ten of the previously
 *     measured generators miss on this host.
 *   - **`#contentpadding` — an ID, not a class: 22/22 matches, 4,023 – 30,414
 *     chars raw, and ZERO matched-but-empty pages.** ✅ SHIPPED FIRST.
 *   - **`#content` — 22/22, identical text** (4,023 – 30,414). It is the parent
 *     of `#contentpadding` and holds nothing extra, so the tighter inner
 *     container is preferred.
 *   - **`#container` — 22/22, 4,421 – 30,812 chars**: `#content` plus ~398 chars
 *     of breadcrumb/nav. Strictly worse.
 *   - **`<body>` — 22/22, 5,821 – 32,212 chars.** Unlike `everystudent-sq` and
 *     `everystudent-pl`, this host DOES emit a parseable `<body>` — but it is
 *     the whole page including nav, menus, sidebar and footer.
 *   - **`<html>` — 22/22, 7,337 – 33,768 chars.** Whole document.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain**. `extractContent` scopes to
 * the FIRST selector that MATCHES AN ELEMENT, not the first that yields text, so
 * a zero-text match SHADOWS every working selector after it. That is how five of
 * the eight pilot entries first shipped. Nothing that extracts 0 chars is listed
 * here, and the measured container is listed FIRST.
 *
 * ✅ **`"html"` is appended as the LAST entry.** It is safe precisely because
 * `#contentpadding` has **zero matched-but-empty pages** — a selector that can
 * match at 0 chars would make the fallback unreachable, and this one cannot. It
 * shadows nothing (nothing follows it), fires only if `#contentpadding` is ever
 * absent, and beats `extractContent`'s implicit `body ?? root` because `<html>`
 * is a real element carrying no literal `<!DOCTYPE html>` text node. It exists
 * for the batch-3 failure mode: three genuine articles were nearly lost when a
 * single unclosed tag collapsed their container. **On the 32 pages fetched here
 * it never fires** — `#contentpadding` binds on every single one, articles and
 * chrome pages alike.
 *
 * ⚠️ `#contentpadding` therefore does **not** discriminate article from chrome:
 * it binds on the homepage, all 6 `/m/` indexes, /pisite.html and /janez.html
 * too. The URL filters below are what keep the corpus clean; the selector must
 * not be relied on to do it.
 *
 * ## ⚠️ `.hidden` is CONTENT on this host — it must NOT be stripped
 *
 * The class name reads like chrome and it is not. Measured 2026-07-30: inside
 * `#contentpadding`, `.hidden` holds **7,328 chars on `/a/zakajlahkozaupamo.html`
 * across 3 divs** (`#question1`, `#question2`, `#question3`) — collapsible
 * "read more" panels holding a table of archaeological finds, a manuscript-count
 * comparison of the New Testament against Homer and Herodotus, and worked gospel
 * examples. That is 25% of the site's longest article and genuine apologetics
 * prose. At document level `.hidden` is dual-purpose — 47 instances, of which
 * the other 44 are the collapsed mobile menu at 140 chars a page. Stripping it
 * would trade 140 chars of menu for 7,328 chars of real content. It is
 * deliberately absent from `stripSelectors`.
 *
 * ## Chrome stripped — per-selector, measured inside `#contentpadding`
 *
 * Marginal chars each selector removes, measured by running the extraction with
 * that one selector applied alone, across all 22 articles:
 *
 *   - **`script` — 44 instances, 652 chars on EVERY page (14,344 total).** The
 *     single largest real contributor: two inline `document.write` blocks
 *     building the Facebook like-button iframe. Without this, that JavaScript
 *     source text lands in every document.
 *   - **`.navtree` (22 inst, 425 ch) and `.navtree1` (22 inst, 449 ch)** — the
 *     breadcrumb section label, printed twice per page (e.g. "Obstoj Boga" —
 *     "Existence of God"), 13–46 chars each. Small but real, and it would open
 *     every extracted document with a stray nav word.
 *   - **`.a2a_kit` (44 inst) and `.a2a_dd` (44 inst) — 0 chars.** The AddToAny
 *     share row this host uses. Zero today because the buttons are images and
 *     `structuredText` does not read `alt`. Stripped anyway so a markup change
 *     that adds text labels cannot leak them into every article.
 *   - **`.articledivider` (18 inst) and `.hr1` (73 inst) — 0 chars.** Empty
 *     presentational divs drawing the rules between sections. Honest no-ops that
 *     nevertheless BIND, kept as drift guards.
 *   - **`head` — 0 instances inside `#contentpadding`, so 0 chars on the healthy
 *     path.** It is here only to serve the `"html"` fallback, where it removes
 *     **1,484 – 1,607 chars per page** of duplicated `<title>` and meta. Safe
 *     because `extract.ts` reads the title from `root` at line 43, BEFORE the
 *     strip loop at line 52 — a future edit that reorders those two steps would
 *     lose the title, so keep them in that order.
 *   - **`style` — 0 instances in scope, 1,133 chars per page under the `"html"`
 *     fallback.** Same rationale as `head`.
 *   - `noscript`, `svg`, `nav`, `header`, `footer`, `form` — **0 instances
 *     anywhere on this host**; it emits no HTML5 sectioning tags at all (its
 *     header/footer/menu are `<div id=…>`). Retained as the estate-wide generic
 *     base only.
 *
 * ⓘ **The FreeFind chrome selectors are deliberately OMITTED, not carried for
 * parity.** Measured on this host: `sitelevel_noindex`, `.fccell`, `.fctable`,
 * `.hr2`, `.relatedbottom` and `.shareiconsmenupg` are **0 instances each** —
 * they are not merely 0-char, they cannot bind, because this generator never
 * emits them. Listing them would be pure noise. Do not add them back expecting
 * them to do anything.
 *
 * ⓘ This host's document-level nav chrome (`.navmenu2` 157 ch, `.nav2link` 140,
 * `.centeredmenu` 80, `.otherhomelink` 66, `.bottomnav` 24, `.copyright` 18,
 * `.hiddenmenu` 17, per page) all sits **outside `#contentpadding` — 0 instances
 * in scope**. It is not listed because the only path that would need it is the
 * `"html"` fallback, which never fires on any known page. The numbers are
 * recorded here so that call is a one-line reversal if it ever does.
 *
 * ## What is blocked, and the measured evidence for each
 *
 * `articleHints` already excludes everything outside `/a/`. The `block` list is
 * deliberately redundant for those, recording *why* each group is out so a later
 * widening of the hints cannot silently readmit them — the same defensive
 * posture as `thelife-fr` / `everystudent-pl` / `everystudent-sq`.
 *
 * Every page below was fetched and extracted. **Six of the eight clear the
 * 250-char floor**, so the floor could not have excluded them and these blocks
 * are doing real work. And when no `contentSelector` matches, `extractContent`
 * does NOT return empty — it falls back to `<body> ?? root`, i.e. the whole
 * document — so "minContentLength will drop it" is never the argument.
 *
 *   - **`/janez.html` — BLOCKED as FULL SCRIPTURE, and for a third-party
 *     copyright.** Titled "Evangelij po Janezu" ("The Gospel According to
 *     John"), it is the verbatim Slovenian standard-translation text of John,
 *     with numbered verses and an in-page chapter index anchoring `#1` through
 *     `#21`. Extracts 4,951 chars, well clear of the floor. Blocked 2026-07-30
 *     under the estate-wide scripture policy (2026-07-29) that `everystudent-ar`
 *     and `everystudent-sq` set: public-domain Scripture text rather than
 *     ministry writing — outside what this corpus answers from. ⚠️ It also
 *     closes with **"© 1996, 2003 Društvo Svetopisemska družba Slovenije"** (the
 *     Slovenian Bible Society), so this entry's `rights` line would actively
 *     MISATTRIBUTE it to Cru. It is in the XML sitemap, so only a URL block
 *     catches it.
 *   - ⓘ **How scripture was told apart from writing ABOUT scripture.**
 *     `/a/zakajlahkozaupamo.html` is the longest page on the site (29,741 chars)
 *     and is titled "Zakaj lahko zaupamo Svetemu pismu" ("Why we can trust the
 *     Bible") — it is KEPT. It is argument prose in an author's voice
 *     ("Odgovor je: da. Sveto pismo ni le zbirka izmišljenih zgodbic…") with
 *     manuscript and archaeology evidence tables. `/janez.html` is numbered
 *     verses under a Bible-society copyright with a 21-chapter index. Voice,
 *     verse numbering and the copyright line are what separate them — not
 *     length, and not the presence of Bible words.
 *   - **`/m/*` — the 6 section indexes.** 214 – 2,696 chars of headline+teaser
 *     link lists. `/m/zemljevid.html` ("Zemljevid strani", 755 ch) is the site
 *     plan, the Slovenian twin of the French `/plan.html`; `/m/ostrani.html` ("O
 *     strani", 2,696 ch) is the about + cookie/privacy page. Five of the six
 *     clear the 250 floor; only `/m/odgovori.html` (214 ch) would have been
 *     caught by it.
 *   - **`/pisite.html` — the contact form.** **380 chars** — "Pišite nam" ("Write
 *     to us"), plus a privacy statement and the note "Če je le mogoče,
 *     e-sporočila napišite v angleščini." It CLEARS the floor, so only a URL
 *     block excludes it. Slovenian twin of the Polish `/pytanie.html`.
 *   - **`/` — the homepage.** **569 chars.** It does NOT extract to 0:
 *     `#contentpadding` binds on it as readily as on an article, so it yields its
 *     full teaser list ("Ali Bog resnično obstaja? … » več"). Only a URL block
 *     excludes it.
 *
 * ⓘ **There is NO "adventure/pack" email-series page on this host — a measured
 * absence, not an omission.** The siblings' `/aventure.html` /
 * `/abenteuerreise.html` / `/pack.html` / `/czybogjest.html` has no counterpart
 * here: the union of every internal href across all 32 fetched pages contains
 * exactly 23 `/a/` articles, 6 `/m/` indexes, `/janez.html`, `/pisite.html` and
 * `/`, and ten plausible Slovenian slugs were probed directly
 * (`/pustolovscina.html`, `/paket.html`, `/prijava.html`,
 * `/duhovnapustolovscina.html`, `/svetopismo.html`, `/biblija.html`,
 * `/sedem.html`, `/novozivljenje.html`, `/zacetek.html`, `/alibogobstaja2.html`)
 * — **all ten returned 404**. The Gospel-of-John page exists but is Scripture
 * rather than a signup form, and is blocked above on that ground.
 *
 * ⓘ **No parallel-script tree.** Slovenian is written in Latin only, and the
 * corpus confirms it: **0 Cyrillic characters** across all 22 articles. There is
 * no Latin/Cyrillic twin of any article, so no duplicate-content concern of the
 * kind a Serbian host would raise.
 *
 * ## Language: `["sl"]` — read and counted, not inferred
 *
 * ⚠️ Slovenian is a South Slavic neighbour of Croatian (`hr`, vrlovazno.com) and
 * Serbian (`sr`), both already in or adjacent to this estate, so it was
 * confirmed on evidence rather than on the `<html lang="sl">` declaration (which
 * all 31 pages carry, and which `persoalanhidup.com` proved is not
 * trustworthy). Counts below are over the 22-article extracted corpus —
 * **277,447 chars / 46,064 word tokens** — using **word boundaries**,
 * `(?<!\p{L})…(?!\p{L})`, never naive substring matching.
 *
 * **Slovenian markers, all present:** `ki` 532 (the Slovenian relative pronoun),
 * `lahko` 438, `so` 304, `tudi` 212, `nekaj` 196, `kaj` 128, `zelo` 87, `ker`
 * 68, `kdo` 55, `vprašanje` 40 + `vprašanja` 11, `samo` 25.
 *
 * **The dual number — the decisive Slovenian feature, and it is there:** the
 * three-way copula `je` 1,692 / `sta` 44 / `so` 304 is complete, and the dual
 * forms `sta` 44, `dva` 11, `dve` 9, `njiju` 4, `oba` 1 all occur. Neither
 * Croatian nor Serbian has a productive dual.
 *
 * **Croatian markers — every one is ZERO:** `što` 0, `vrlo` 0, `pitanje` 0,
 * `tko` 0, `nije` 0, `jer` 0, `gdje` 0, `uvijek` 0, `svijet` 0, `vrijeme` 0,
 * `mogu` 0, `kuća` 0, `tjedan` 0. The ije-reflex forms are absent outright.
 *
 * **Serbian markers — zero:** `šta` 0, `gde` 0, `uvek` 0, `vreme` 0, `posle` 0,
 * `hoću` 0, `opšte` 0, `hleb` 0. And **0 Cyrillic characters**.
 *
 * ⚠️ **Two counts look like Serbian and are not — this is exactly the batch-3
 * trap.** `ko` scores 164 and `svet` 74. But `ko` in Slovenian is the
 * conjunction "when", not the Serbian interrogative "who" — and the Slovenian
 * "who", `kdo`, scores 55 while its Croatian (`tko`) and Serbian (`ko`-as-who,
 * paired with `šta`) partners score 0. `svet` is Slovenian for "world"
 * (Slovenian has no ije-reflex), and its Croatian counterpart `svijet` is 0.
 *
 * ⚠️ **Word boundaries changed the answer, as they did on Croatian vs Serbian in
 * batch 3.** Naive substring counts on this same corpus: `ko` **2,202** naive vs
 * **164** bounded (inside "kako", "nekoliko", "toliko"), `je` 5,132 vs 1,692,
 * `sta` 618 vs 44, `kaj` 426 vs 128, `što` 5 vs **0**. An unbounded count would
 * have read `ko`=2,202 and misfiled this host.
 *
 * **Orthography confirms it independently:** 7,013 occurrences of the Slovenian
 * letters `č`/`š`/`ž`, and **0 occurrences of `ć` or `đ`** — two letters that
 * exist in the Croatian and Serbian-Latin alphabets and NOT in the Slovenian
 * one.
 *
 * **Read directly, not just counted.** `/a/svetatrojica.html` asks "Ali lahko
 * pojasnite Sveto Trojico?" and answers "Imena »Trojica« v Svetem Pismu ne
 * moremo zaslediti, saj je nastalo šele kasneje"; `/a/alibogobstaja.html` opens
 * "Si tudi vi kdaj želite, da bi vam vsaj enkrat v življenju nekdo predstavil
 * dokaze, da Bog resnično obstaja?"; `/a/alibogodgovarja.html` narrates "Ko sem
 * bila sama še ateistka, sem imela zelo dobro prijateljico, ki je veliko
 * molila"; `/a/zivetizupanjem.html` is a hemophiliac student's HIV testimony.
 * The Q&A pages use the native "V:" / "O:" (vprašanje / odgovor) pair.
 *
 * **Not untranslated English** — the cru.org `/mx/es/` failure mode was checked
 * for explicitly. Across 46,064 word tokens the English function words score
 * `the` 15, `and` 2, `God` 3, and `because` / `question` / `answer` **0 each**.
 * The handful present is bibliographic citation apparatus, not body text.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~45 sequential
 * plain-HTTP requests at ~1s spacing drew **zero 429s** and no throttling, and
 * at 23 pages the whole crawl is under a minute of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentSl: SourceEntry = {
  key: "everystudent-sl",
  name: "EveryStudent — Slovenian (VsakStudent.com)",
  domain: "www.vsakstudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["sl"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:sl"],
  defaultCategory: "article",
  rights:
    "© VsakStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.vsakstudent.com",
    // No `fetchStrategy`: verified 2026-07-30 that plain HTTP serves every page
    // on this host (bare Apache, no Cloudflare header, no block page). See header.
    sitemaps: ["/sitemap.xml"],
    // The sitemap emits `https://` absolute URLs and discover.ts filters the RAW
    // <loc>, so `^https://` is correct here (checked, not assumed).
    allow: ["^https://www\\.vsakstudent\\.com/"],
    // The whole article corpus: 22 of the 30 sitemap URLs. `[^/]+` rather than a
    // lowercase class — today every slug is lowercase ASCII (verified: zero
    // non-ASCII bytes, zero %XX escapes, zero uppercase across all 30 <loc>
    // values), but a future mixed-case slug must not silently vanish.
    articleHints: ["^https://www\\.vsakstudent\\.com/a/[^/]+\\.html$"],
    // The ONE article in neither the XML sitemap nor /m/zemljevid.html, found by
    // harvesting hrefs: linked from 11 of the 22 articles, HTTP 200, 2,907 ch of
    // genuine post-decision Q&A prose, and only 1.4% shingle overlap with the
    // same-titled /a/spoznatiboga.html. Discovery cannot reach it; acquire.ts
    // unions seeds with discovered URLs.
    seedPaths: ["/a/spoznatiboga2.html"],
    block: [
      // FULL SCRIPTURE — "Evangelij po Janezu", the verbatim Gospel of John with
      // numbered verses and a 21-chapter index (4,951 ch, well over the floor).
      // Blocked under the estate-wide scripture policy (2026-07-29). It also
      // carries a THIRD-PARTY copyright, "© 1996, 2003 Društvo Svetopisemska
      // družba Slovenije", which this entry's `rights` line would misattribute
      // to Cru. In the sitemap, so only a URL block catches it. Contrast
      // /a/zakajlahkozaupamo.html, an essay ABOUT the Bible — kept.
      "^https://www\\.vsakstudent\\.com/janez\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 6 section indexes (obstoj, odgovori, ostrani, spoznati, vprasanja,
      // zemljevid) — headline+teaser link lists, 214-2,696 ch. Five of the six
      // CLEAR minContentLength. /m/zemljevid.html is the site plan;
      // /m/ostrani.html is the about + cookie/privacy page.
      "^https://www\\.vsakstudent\\.com/m/",
      // The contact form: 380 ch ("Pišite nam" + privacy statement), so it
      // clears the 250 floor and the floor could NOT catch it.
      "^https://www\\.vsakstudent\\.com/pisite\\.html$",
      // The homepage. It does NOT extract to 0 — #contentpadding binds on it as
      // readily as on an article, yielding 569 ch of teaser headlines.
      "^https://www\\.vsakstudent\\.com/?$",
    ],
    // ⚠️ NOT the shared EveryStudent template — this host was redesigned onto
    // its own (lessframework2022.css) and emits NONE of the FreeFind markup.
    // Measured 2026-07-30 over all 22 articles with node-html-parser:
    // `.contentpadding` 0 matches, `.content4` 0 matches, `#content4` 0 matches,
    // `.content4b` / `.entry-content` / `.post-content` / `.cb-entry-content` /
    // `.contentleftpadding` / `.article-content` / `.content` / `article` /
    // `main` 0 matches each. `#contentpadding` is an ID here, not a class:
    // 22/22 matches, 4,023-30,414 ch, and ZERO matched-but-empty pages.
    // Do NOT prepend anything: extractContent binds the first selector that
    // MATCHES, so a 0-char match would shadow this one and skip every article.
    // "html" is a safe LAST resort precisely because #contentpadding never
    // matches empty — it fires only if a broken page collapses the container
    // (the batch-3 failure mode) and shadows nothing.
    contentSelectors: ["#contentpadding", "html"],
    stripSelectors: [
      "script", // 44 inst, 652 ch on EVERY page: inline document.write FB-iframe blocks
      "style", // 0 inst in scope; 1,133 ch/page on the "html" fallback path
      "noscript",
      "svg",
      "nav", // this host emits no HTML5 sectioning tags at all — generic base only
      "header",
      "footer",
      "form",
      // Required by the "html" fallback: drops the duplicated <title> (1,484-1,607
      // ch there, 0 ch in scope). extract.ts reads the title from `root` BEFORE
      // stripping — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-30 (see header):
      ".navtree", // breadcrumb section label, 22 inst / 425 ch total
      ".navtree1", // the same label printed a second time, 22 inst / 449 ch
      ".a2a_kit", // AddToAny share row — 0 chars today (image-only buttons)
      ".a2a_dd", // its dropdown — 0 chars; both stripped as drift guards
      ".articledivider", // empty presentational rule divs, 18 inst, 0 chars
      ".hr1", // ditto, 73 inst, 0 chars
      // ⚠️ `.hidden` is deliberately NOT here: on this host it holds 7,328 ch of
      // real article content (the collapsible evidence tables on
      // /a/zakajlahkozaupamo.html), not chrome. See the header.
      // ⓘ sitelevel_noindex / .fccell / .fctable / .hr2 / .relatedbottom /
      // .shareiconsmenupg are OMITTED, not forgotten: 0 instances each on this
      // host. They cannot bind. Do not add them back.
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 60, // 30 sitemap URLs + 1 seed (23 kept after filtering) + headroom
    minContentLength: 250,
  },
};
