/**
 * EveryStudent — Macedonian (studentskiodgovori.com, "Студентски одговори" /
 * "Student Answers"). The Macedonian banner of Cru's seeker-facing Q&A ministry:
 * short apologetics and life-issue articles, FAQ answers and first-person
 * testimonies written for Macedonian-speaking students who are not believers. A
 * sibling of `everystudent` (en), `everystudent-pl`, `everystudent-sq`,
 * `everystudent-ru`, `everystudent-de` and the rest of the estate.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). studentskiodgovori.com is its own domain, so it gets
 * its own key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: ~230 plain-HTTP GETs with a full desktop-Chrome UA
 * (/robots.txt, /sitemap.xml, a HEAD sweep of all 65 sitemap URLs, a full body
 * fetch of all 65, plus /a/zapoznaj402.html, /duhovna-avantura.html,
 * /m/jazici.html and ~20 negative probes). Not one carried a Cloudflare
 * block-page signature and not one 429'd. So `fetchStrategy` is intentionally
 * OMITTED: plain HTTP is the default and nothing here needs Firecrawl
 * (ADR-0012), unlike everystudent.com / everyarabstudent.com /
 * questions2vie.com which all 403.
 *
 * Consequence: discovery is free, so this is a **discovery crawl** rather than
 * the hand-listed seed set the walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-pl`, `everystudent-sq`.
 *
 * The bare host **301-redirects to `www`** (measured on /robots.txt and
 * /sitemap.xml), so `www.studentskiodgovori.com` is canonical and the host every
 * `<loc>` uses. Every regex below is pinned to it.
 *
 * ## robots.txt — THERE IS NONE
 *
 * Verified 2026-07-29: `https://www.studentskiodgovori.com/robots.txt` returns
 * **HTTP 404**, serving the site's own Macedonian "Се извинуваме" error page
 * (which is why a naive `curl` looks like it got a file — it got HTML). There is
 * no robots.txt on this host at all, so **nothing is disallowed** and no URL
 * below is blocked on robots grounds; every exclusion here is a content-quality
 * call. The pages do carry `<meta name="robots" content="all" />`.
 *
 * ## Sitemap — 65 entries, all distinct, 49 under /a/ and one of those is dead
 *
 * Verified 2026-07-29: `/sitemap.xml` → HTTP 200, **5,568 bytes**, a single flat
 * `<urlset>` (no `<sitemapindex>`, so no recursion), generated by
 * xml-sitemaps.com. 65 `<loc>` elements, **65 distinct URLs**, matching the "~65"
 * from prior recon exactly. Breakdown:
 *   - **49 `/a/<slug>.html`** — the article namespace. 48 live, 1 dead.
 *   - **7 `/m/<slug>.html`** — section indexes (`postoenjeto100`,
 *     `iskustvoto300`, `zazivotot500`, `enigmi600`, `forum700`, `mapa`,
 *     `stranicata803`). BLOCKED.
 *   - **7 `/avantura/<n>.html`** — the seven instalments of the "Духовна
 *     авантура" e-mail series. BLOCKED.
 *   - **`/kontakti.html`** — the contact page. BLOCKED.
 *   - **`/`** — the homepage. BLOCKED.
 *
 * **A HEAD sweep of all 65 returned 64 × 200 and 1 × 404, with ZERO redirects.**
 * There is no dead-redirect cohort of the kind `everystudent-ro` shipped 25 of.
 * The single 404 is **`/a/duhovna-avantura.html`** — the sitemap's own typo: the
 * page it means lives at root as `/duhovna-avantura.html`. `acquire.ts` drops
 * `status >= 400` as `fetch-failed`, so it would not stage today, but it is
 * blocked anyway because its 404 body extracts **418 chars** — comfortably over
 * the 250 floor — so the day the site "fixes" that URL we would stage either an
 * error page or an e-mail-signup page, not an article.
 *
 * ⓘ **Slugs are lowercase Latin ASCII transliterations of Macedonian words**
 * (`/a/dalipostoi101.html` for "дали постои", `/a/chinii-koi-pagjaat.html` for
 * "чинии што паѓаат"), NOT Cyrillic and NOT percent-encoded — checked, not
 * assumed: all 65 `<loc>` values were scanned for non-ASCII bytes and for `%XX`
 * escapes, **zero hits**, and for uppercase letters, **zero hits**. So the
 * Cyrillic/percent-encoding hazard that would break a `[a-z]`-only hint regex
 * does not exist on this host. `[^/]+` is used regardless, so a future
 * mixed-case or Cyrillic slug cannot be silently dropped.
 *
 * ## HTML-map cross-check — one orphan article, pinned as the only seed
 *
 * These sitemaps are known to be stale, so the site's own map was fetched and
 * diffed, then every `href` on all 65 pages was harvested as a wider net.
 * Verified 2026-07-29:
 *   - **`/m/mapa.html` ("Мапа на сајтот") lists 48 `/a/` links.** Nothing in the
 *     HTML map is missing from the XML sitemap. The delta runs the other way:
 *     the XML has exactly one `/a/` URL the HTML map omits, and it is the dead
 *     `/a/duhovna-avantura.html`. **The HTML map is the more accurate of the two.**
 *   - The full href harvest surfaced **3 paths absent from the XML sitemap**:
 *     - **`/a/zapoznaj402.html` — a genuine article, live, 2,866 chars**
 *       ("Запознај го Бог лично (следуваат некои информации што ќе ти бидат од
 *       помош)" — the follow-up to the gospel presentation). It is linked from
 *       **16 different articles** yet is in **neither** map. Discovery is
 *       sitemap-only, so nothing would ever reach it — hence the single
 *       `seedPaths` entry. `acquire.ts` unions seeds with discovered URLs and
 *       does NOT apply `block` to seeds, so the pin is safe.
 *     - **`/duhovna-avantura.html`** — the e-mail-series signup page. BLOCKED.
 *     - **`/m/jazici.html` ("Останати јазици")** — a stub extracting **15 chars**
 *       with **zero outbound links**. Covered by the `/m/` block.
 *
 * **Expected yield: 49 documents** — the 48 live sitemap articles plus the one
 * pinned seed.
 *
 * ## Extraction — measured on this host, never inherited on trust
 *
 * Verified 2026-07-29 by running the repo's own `extractContent`
 * (node-html-parser, exactly as `src/acquisition/extract.ts` uses it) over all
 * **68 fetched pages**. Grepping proves nothing here: every one of these class
 * names is also declared in the page's inline `<style>` block, so a grep
 * false-positives on all of them. Counts are post-base-strip:
 *
 *   - **`.contentpadding` — the article, on every page that has one.** Matched
 *     61/68, **and not one of those 61 extracted 0 characters** (101–23,515 ch).
 *     Per-page: `/a/dalipostoi101.html` 18,915 ch, `/a/biblijata215.html`
 *     20,751 ch, `/a/koronavirus.html` 14,453 ch, `/a/molitvi306.html` 9,928 ch.
 *   - **`.content4` — matched on 66/68 pages and extracted 0 chars on 61 of
 *     them.** An empty spacer div, exactly as on `-pl`. The only 5 that yield
 *     text (408–1,063 ch) are `/m/` indexes, which are blocked. Listing it ahead
 *     of `.contentpadding` would bind the spacer on every article and skip the
 *     whole source as `too-thin` on an HTTP 200 — the batch-1 failure (#128).
 *     `contentSelectors` is NOT a fallback chain: `extractContent` scopes to the
 *     first selector that MATCHES AN ELEMENT, not the first that yields text.
 *   - **`.content4b` — 1 match, 0 chars** (present only on the malformed page
 *     below). **`.content4c`, `.contentpadding2`, `.contentleftpadding`,
 *     `.cb-entry-content`, `.entry-content`, `.article-content`, `.content`,
 *     `<article>`, `<main>` — 0 matches each**, absent from this host.
 *   - **`.articletitle` — 61 matches, 3–71 chars.** A title, not a body.
 *   - **`<body>` — absent from the parsed tree on all 49 article pages** (an
 *     unmatched `</sitelevel_noindex>` disposes of it), present only on the
 *     homepage and 5 `/m/` indexes. So the fallback container on an article is
 *     the document ROOT, whose doctype node leaks the literal string
 *     `<!DOCTYPE html>` into the text.
 *   - **`html` — 68/68, 829–24,291 chars.** Works, but is strictly worse than
 *     `.contentpadding` on the 61 pages that have one, so it is not shipped.
 *
 * Final measured yield with `[".contentpadding"]` + the strip list below, across
 * the 49 kept articles: **1,326 – 23,349 chars, median 8,600, and 0 pages below
 * the 250 floor.**
 *
 * ## ⚠️ `/a/zapoznaj401.html` — malformed, and deliberately NOT blocked
 *
 * "Запознај го Бог лично" ("Know God personally") is the core gospel-presentation
 * article of the whole site, and it is the **one page where `.contentpadding`
 * does not form**. Root cause, isolated by single-line deletion and then
 * reproduced minimally: line 195 opens `<p><span style="line-height: 200%;">`
 * and **never closes the `<span>`** (29 `<span>` openers vs 28 closers on the
 * page). node-html-parser pops the open-element stack when the `</p>` arrives,
 * taking `.container2`, `.content4` and `.contentpadding` with it; the article
 * survives as bare `<p>` siblings directly under `<html>`. Re-inserting a single
 * `</span>` restores `.contentpadding`, and the minimal case
 * `<div class="contentpadding"><p><span>x</p>…</div>` reproduces it in isolation.
 *
 * **It is kept anyway, because the fallback output here is clean.** Measured:
 * `.contentpadding` misses → `<body>` is absent → the container is the document
 * root → **6,066 chars**, which is the entire article and nothing else. That
 * works only because `sitelevel_noindex` on this host wraps *every* piece of
 * chrome (cookie bar, both navs, sidebar, share row, footer), so stripping it
 * cleans the root fallback as thoroughly as it cleans `.contentpadding`. The only
 * contamination is the literal string `<!DOCTYPE html>` at the head of the text.
 *
 * ⚠️ This is the OPPOSITE call to `everystudent-pl`, which blocks its equivalent
 * `/a/biblia.html` — and the difference is measured, not stylistic: on `-pl` the
 * same fallback produces a **31,117-char blob** carrying the cookie bar, top nav,
 * both menus, the sidebar and the footer, because that host's chrome is not
 * wrapped. Here it produces 6,066 clean chars. Blocking would cost the single
 * most important article on the domain to remove one doctype token.
 *
 * ⓘ **A call for the orchestrator, not taken here.** Adding `"html"` as a second
 * `contentSelectors` entry would remove even the `<!DOCTYPE html>` token, because
 * `<html>` is an element while `root` is not. It is measured safe — `.contentpadding`
 * has **zero** matched-but-empty pages on this host, so it can never be shadowed —
 * but the entry ships the SINGLE measured selector by policy and leaves the
 * one-word addition to review.
 *
 * ## Chrome stripped — every selector counted on this host, 2026-07-29
 *
 * Isolated removal (base strip + that one selector), scope `.contentpadding`,
 * over the 49 kept articles. Zeros are reported as zeros:
 *   - **`sitelevel_noindex`** is a custom ELEMENT tag, not a class — the missing
 *     leading `.` is correct, not a typo. **100 instances on 49/49 pages,
 *     removing 5,933 chars (86–818 per page)** — the largest contributor. It
 *     carries "СПОДЕЛИ ГО ТЕКСТОТ:" ("SHARE THE TEXT:"), the related-article
 *     block and the rules bracketing the CTA.
 *   - **`.fctable` — 50 instances on 47/49 pages, 5,335 chars (59–218 per
 *     page)**: the "FEATURE CLOSE" call-to-action table ("► Како да започнеш
 *     лична врска со Бог? ► Имам прашање…").
 *   - **`.fccell` — 234 instances on 48/49 pages, 5,454 chars in isolation**;
 *     its marginal contribution *given* `.fctable` is **119 chars**, because the
 *     cells nest inside the table. Both are listed: stripping only the cells
 *     leaves the table shell, and 2 pages carry cells outside a classed table.
 *   - **`.shareiconsmenupg` — 48 instances on 48/49 pages, 1,008 chars in
 *     isolation but a 0-CHAR NO-OP in list order.** On THIS host the enclosing
 *     `<sitelevel_noindex>` is **well-formed and already contains it**, so once
 *     that is stripped first this selector matches nothing. It is kept as a cheap
 *     drift guard, NOT because it strips anything today. (Do not repeat the
 *     `-de`/`-ru` "required because the markup is malformed" claim here — that
 *     was measured false on this host.)
 *   - **`.a2a_kit` — 96 instances on 48/49 pages, 0 chars.** The AddToAny share
 *     row; its buttons are images and `structuredText` does not read `alt`.
 *     Stripped so a future markup change that adds text labels cannot leak
 *     "WhatsApp Share / Facebook Share / …" into every article.
 *   - **`.hr2` (108 instances, 49/49 pages) and `.articledivider` (45 instances,
 *     45/49) — 0 chars each.** Empty presentational divs.
 *   - **`.relatedbottom` — 0 instances.** Dead config on this host, as on every
 *     host measured so far. Retained only as a parity no-op; do not read its
 *     presence as evidence it binds.
 *   - **`head` — 22 chars, on exactly ONE page** (`/a/zapoznaj401.html`, the
 *     root-fallback case above), where it removes the duplicated `<title>`.
 *     0 chars on the other 48, where the container is `.contentpadding` and no
 *     `<head>` is inside it. Safe because `extract.ts` captures the title from
 *     `root` BEFORE the strip loop runs — a future edit that reorders those two
 *     steps would lose the title, so keep them in that order.
 *
 * ## No full Bible book on this host — the scripture policy has nothing to bind
 *
 * Checked because five siblings carry complete Bible books on article URLs
 * (`es` `/articulos/biblia_juan.html` 100,409 ch; `sq` `/a/gjoni.html` 98,887 ch).
 * Verified 2026-07-29: the longest page on this domain is **23,349 chars**
 * (`/a/sindrom508.html`, an eating-disorder testimony), only ~2.7× the median,
 * and the four longest are ordinary long-form articles with normal footnote
 * density. `/a/biblijata215.html` (20,585 ch) is "Како може да веруваме во
 * Библијата?" — an apologetics article *about* the Bible, not Bible text.
 * `/jovan.html`, `/a/jovan.html`, `/jovanovo.html`, `/evangelie.html`,
 * `/biblija.html`, `/a/biblija.html` and `/pdf/` all return 404. **There is no
 * Gospel-of-John page and no `/pdf/` tree on this banner**, so no scripture block
 * is needed and none is written. There is also no third-party Bible-society
 * copyright notice anywhere in the fetched HTML.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` already excludes everything outside `/a/`. The `block` list is
 * deliberately redundant for those, recording *why* each group is out so a later
 * widening of the hints cannot silently readmit them. One entry is **not**
 * redundant: `/a/duhovna-avantura.html` sits under `/a/` and matches
 * `articleHints`, so `block` is the only filter keeping it out.
 *
 * All char counts are post-strip. ⚠️ **Every single one clears
 * `minContentLength: 250`**, so the floor could not have excluded any of them —
 * the URL blocks are doing real work, not decorating:
 *   - **`/` — 1,002 chars.** The homepage. It does NOT extract to 0: it has no
 *     `.contentpadding`, so `extractContent` falls back to `<body>` and returns
 *     the full teaser list. Only a URL block excludes it.
 *   - **`/m/*` — 386–1,649 chars.** The 7 section indexes; 5 of them have no
 *     `.contentpadding` and fall back to `<body>` for a headline+teaser link
 *     list. `/m/mapa.html` (1,649 ch) is the site plan; `/m/stranicata803.html`
 *     (754 ch) is the privacy policy; `/m/jazici.html` (15 ch) is the
 *     other-languages stub. Navigation, not content.
 *   - **`/kontakti.html` — 338 chars.** "Имаш прашање? Пиши ни" — the contact
 *     page plus a privacy statement. Clears the floor; only a block catches it.
 *   - **`/duhovna-avantura.html` — 904 chars.** "Духовна авантура", the signup
 *     landing page for a free 7-e-mail series, signed by Marilyn Adamson,
 *     "Директор на EveryStudent.com". The Macedonian twin of the French
 *     `/aventure.html`, German `/abenteuerreise.html`, Arabic `/pack.html`,
 *     Polish `/czybogjest.html` and Albanian `/aventures.html`. Absent from the
 *     XML sitemap but linked from **all 68** fetched pages, so it is blocked in
 *     case a regenerated sitemap ever picks it up.
 *   - **`/avantura/1.html` … `/avantura/7.html` — 2,397–4,281 chars each.** The
 *     seven instalments of that series themselves ("Духовна авантура, пакет -
 *     # 1"), which the sitemap DOES list. E-mail-course copy addressed to a
 *     subscriber ("Добредојдовте! Ви благодарам што се регистриравте"), not
 *     seeker Q&A articles.
 *   - **`/a/duhovna-avantura.html` — a 404 whose error body extracts 418 chars.**
 *     See the sitemap section. The one block that `articleHints` cannot express.
 *
 * ⓘ **Three video-transcript articles are KEPT, diverging from `-pl`.** This is
 * a judgement call worth flagging: `/a/chinii-koi-pagjaat.html` (1,326 ch,
 * "Чинии што паѓаат" — the *Falling Plates* film), `/a/video-dali-bog-e-dobar.html`
 * (1,477 ch) and `/a/video-naucen-dokaz.html` (2,098 ch) are Macedonian
 * transcripts of short films. `everystudent-pl` blocks its equivalent
 * `/wideo.html` on the grounds that a transcript "extracts as ~60 one-line blocks
 * that chunk poorly against paragraph boundaries" (invariant 4). **That reason
 * was measured and does NOT hold here**: all three extract as normal multi-line
 * paragraphs, they sit under `/a/`, and the site's own `/m/mapa.html` lists them
 * as articles. They are substantive seeker content, so they are kept.
 *
 * ## Language: `["mk"]` and CYRILLIC script — read and counted, not assumed
 *
 * ⚠️ Checked explicitly because the neighbouring `sr` banner (studentskikutak.com)
 * turned out to be **Latin**-script Serbian with no Cyrillic tree. **This host is
 * the opposite: it is Cyrillic, with no Latin tree.** Verified 2026-07-29 by
 * reading the extracted text and then counting characters across all 49 articles:
 * **355,089 Cyrillic characters against 3,417 Latin — 99.05% Cyrillic.** The
 * Latin residue is bibliographic: footnotes citing foreign-language books
 * ("Dinesh D'Souza, What's So Great about Christianity, Regnery Publishing",
 * "Eugene Wigner, The Unreasonable Effectiveness of Mathematics…"), which is
 * normal citation apparatus in a translated article, not an untranslated body.
 * No sampled page was untranslated English.
 *
 * It is **Macedonian**, not Serbian or Bulgarian, on the alphabet's own evidence:
 * the Macedonian-only letters are present in quantity across the corpus —
 * **ќ ×1,433, њ ×745, ѓ ×422, љ ×273, џ ×43, ѕ ×17** — while the Serbian-only
 * **ђ and ћ appear 0 times** and the Bulgarian-only **ъ, щ, ю, я appear 0 times**.
 * The site declares `<html lang="mk">` and `a2a_config.locale = "mk"`.
 *
 * What I read: `/a/objasnuvate709.html` asks „Што можете да кажете за доктрината
 * на Светото Тројство?" and answers „Зборот 'Тројство' го нема никаде во
 * Библијата, туку човекот го употребува за да го опише она што го научил за Бог
 * од Библијата"; `/a/molitvi306.html` is "Дали Бог одговара на нашите молитви?";
 * the site's own tagline is "Сигурно место за истражување на прашања поврзани со
 * Бог и Животот" ("A safe place to explore questions about God and Life").
 * Scripture citations use Macedonian book names throughout (Јован, Исаија,
 * Римјаните, 1 Петрово, Ефесјаните, Откровение).
 *
 * **No parallel Latin/Cyrillic trees exist**, so there is no duplicate-content
 * decision to make: the only path prefixes on the entire host are `/a/` and
 * `/m/` (harvested from every internal href on all 68 pages), `/lat/` returns
 * 404, and `/m/jazici.html` — the "Останати јазици" ("Other languages") page —
 * is a 15-char stub with **zero outbound links**, not a language switcher. The
 * URL *slugs* are Latin ASCII transliterations, but that is spelling of
 * filenames, not a second edition of the content.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. ~230 sequential
 * requests drew **zero 429s and no throttling**, so the sibling default is kept
 * rather than raised; at 49 pages the whole crawl is under a minute.
 */
import type { SourceEntry } from "./types.js";

export const everystudentMk: SourceEntry = {
  key: "everystudent-mk",
  name: "EveryStudent — Macedonian (StudentskiOdgovori.com)",
  domain: "www.studentskiodgovori.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["mk"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:mk"],
  defaultCategory: "article",
  rights:
    "© StudentskiOdgovori.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.studentskiodgovori.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (no Cloudflare block page on ~230 requests). See header.
    sitemaps: ["/sitemap.xml"],
    // The ONE article in neither the XML sitemap nor /m/mapa.html, yet linked
    // from 16 articles: "Запознај го Бог лично (следуваат некои информации…)",
    // 2,866 ch. Discovery is sitemap-only, so nothing would ever reach it.
    // acquire.ts unions seeds with discovered URLs and does not `block` seeds.
    seedPaths: ["/a/zapoznaj402.html"],
    allow: ["^https://www\\.studentskiodgovori\\.com/"],
    // The article namespace: 49 of the 65 sitemap URLs (48 live). `[^/]+` rather
    // than a lowercase class — slugs are all-lowercase Latin ASCII today (zero
    // non-ASCII bytes, zero %XX escapes, zero uppercase across all 65 <loc>),
    // but a Cyrillic or mixed-case slug added later must not be silently dropped.
    articleHints: ["^https://www\\.studentskiodgovori\\.com/a/[^/]+\\.html$"],
    block: [
      // ── This one matches articleHints; `block` is the ONLY thing excluding it.
      // The sitemap's own typo for the root-level /duhovna-avantura.html: it
      // returns HTTP 404, and the 404 body extracts 418 chars — over the 250
      // floor — so if the URL is ever "fixed" we would stage an error page or a
      // signup page rather than an article.
      "^https://www\\.studentskiodgovori\\.com/a/duhovna-avantura\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 7 section indexes, 386-1,649 ch. Five have no .contentpadding, so
      // extractContent falls back to <body> and returns the whole nav page.
      // /m/mapa.html is the site plan; /m/stranicata803.html is the privacy
      // policy; /m/jazici.html is the 15-char other-languages stub.
      "^https://www\\.studentskiodgovori\\.com/m/",
      // "Духовна авантура" — the free 7-e-mail series signup, 904 ch. Macedonian
      // twin of the French /aventure.html and Arabic /pack.html. Absent from the
      // sitemap but linked from all 68 pages; blocked in case that changes.
      "^https://www\\.studentskiodgovori\\.com/duhovna-avantura\\.html$",
      // The seven instalments of that series, 2,397-4,281 ch each, which the
      // sitemap DOES list. Subscriber e-mail copy, not seeker Q&A articles.
      "^https://www\\.studentskiodgovori\\.com/avantura/",
      // "Имаш прашање? Пиши ни" — the contact page, 338 ch. Clears the floor.
      "^https://www\\.studentskiodgovori\\.com/kontakti\\.html$",
      // The homepage — no .contentpadding, so the <body> fallback returns
      // 1,002 ch of teaser headlines rather than nothing.
      "^https://www\\.studentskiodgovori\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article, on 61 of 68 fetched pages with ZERO
    // matched-but-empty cases (101-23,515 ch). `.content4` is deliberately
    // ABSENT: it matches on 66/68 pages and extracts 0 chars on 61 of them, and
    // because extractContent binds the first selector that MATCHES rather than
    // the first that yields text, listing it would make every article skip as
    // `too-thin` on an HTTP 200. Not a fallback chain: exactly one selector.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // 22 ch on exactly ONE page (/a/zapoznaj401.html, where .contentpadding is
      // lost to an unclosed <span> and the container falls back to the document
      // root): removes the duplicated <title>. extract.ts reads the title from
      // `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome, all counted on this host 2026-07-29 (see header):
      "sitelevel_noindex", // custom ELEMENT tag: 100 inst on 49/49 pages, 5,933 ch — "СПОДЕЛИ ГО ТЕКСТОТ:" + related + CTA rules
      ".fctable", // the "FEATURE CLOSE" CTA table: 50 inst, 5,335 ch
      ".fccell", // its cells: 234 inst, 5,454 ch isolated / 119 ch marginal over .fctable — both needed
      ".shareiconsmenupg", // 0-CHAR NO-OP in list order: sitelevel_noindex is well-formed here and already contains it. Kept as a drift guard only.
      ".a2a_kit", // AddToAny share row: 96 inst, 0 chars today (image-only buttons)
      ".hr2", // 108 inst, 0 chars — empty presentational divs
      ".articledivider", // 45 inst, 0 chars
      ".relatedbottom", // 0 instances on this host; parity no-op, does not bind
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 over ~230 requests
    maxPages: 100, // 65 sitemap URLs + 1 pinned seed + headroom
    minContentLength: 250,
  },
};
