/**
 * EveryStudent — Slovak (everystudent.sk). The Slovak banner of Cru's
 * seeker-facing Q&A ministry: short apologetics and life-issue articles plus
 * first-person student testimonies, written for Slovak-speaking students who
 * are not believers. The site describes itself as "bezpečné miesto, kde nájdeš
 * odpovede na otázky, ktoré ťa zaujímajú o Bohu" ("a safe place to find answers
 * to the questions about God that interest you", /o-nas/).
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source = one crawl job (ADR-0006 §Decision 1). everystudent.sk is its own
 * domain, so it gets its own key, exactly as `everystudent-cs`
 * (everystudent.cz), `everystudent-fr` (questions2vie.com) and `everystudent-pl`
 * (kazdystudent.pl) are separate.
 *
 * ============================================================
 * ⚠️ NOT the same application as its neighbour `everystudent-cz`.
 * This is a THIRD generator again — WordPress + Elementor.
 * ============================================================
 * `everystudent-cs` is a bespoke **Yii PHP app** whose article body is
 * `.content`; the English/Arabic/French banners are a legacy hand-rolled site
 * whose body is `.content4`/`.contentpadding`. **everystudent.sk is neither.**
 * Verified 2026-07-29: `robots.txt` names `/wp-admin/`, `/wp-login.php` and
 * `/xmlrpc.php`; `/sitemap_index.xml` is generated by **Yoast SEO**; every page
 * carries Elementor's `.elementor-*` widget classes and the theme's
 * `.entry-content` wrapper. `server: openresty`.
 *
 * Consequence: **`.content` — the Czech host's selector — matches 0 of 100
 * pages here**, as do `.content4`, `.content4b` and `.contentpadding`. Nothing
 * from `everystudent-cs` transfers except the estate-level policy decisions.
 *
 * ## ⚠️ Cross-estate overlap with everystudent.cz: ONE page, already excluded there
 *
 * Measured 2026-07-29 with 8-word-shingle Jaccard similarity between the Czech
 * host's extracted bodies and all 94 Slovak bodies ≥250 ch:
 *   - `everystudent.cz` `/in/163/koronavirus_jak_prekonat_strach` — the single
 *     **Slovak-bodied page on the Czech host** that `everystudent-cs`'s header
 *     documents — matches this host's **`/uzkost-a-strach/` at 60.1%**. It was
 *     indeed lifted from everystudent.sk. **No duplicate-content risk exists
 *     today**: `everystudent-cs` neither discovers it (absent from that host's
 *     sitemap) nor pins it as a seed, deliberately. If a future agent ever adds
 *     it there, it would become a near-duplicate of this source's
 *     `/uzkost-a-strach/`. Leaving it out of `everystudent-cs` remains correct.
 *   - Genuinely Czech articles vs this host: `/in/13/existuje_buh` and
 *     `/in/36/proc_je_zivot_tak_tezky` both score **0.00% against every one of
 *     the 94 Slovak pages**. Czech and Slovak translations of the same English
 *     source article share no 8-gram at all. **The two estates do not overlap**
 *     and can be ingested side by side.
 *
 * ## NOT walled — plain HTTP, so `fetchStrategy` is omitted (the default)
 *
 * Verified 2026-07-29: ~140 plain-HTTP GETs (robots.txt, all four sitemaps, all
 * 103 live sitemap URLs, 7 off-sitemap probes, plus HEAD/GET sweeps of the 2014
 * sitemap's 27 orphan slugs) — **100 × 200, 3 × 301, zero 403s and no
 * Cloudflare block page**. Unlike the English/Arabic/French banners (ADR-0012).
 *
 * ⚠️ **The canonical host is the BARE apex, not `www.`** — the reverse of every
 * sibling. Measured: `https://www.everystudent.sk/` **301 → `https://everystudent.sk/`**,
 * and `http://everystudent.sk/` 301 → `https://everystudent.sk/`. Every `<loc>`
 * in the Yoast sitemaps is emitted bare, so `domain`, `baseUrl` and every regex
 * below are pinned bare. Adding `www.` would make every filter miss.
 *
 * ## robots.txt — 5 Disallow rules, none of which touch an article
 *
 * Verified 2026-07-29, HTTP 200. The whole file:
 *
 *     User-agent: *
 *     Disallow: /wp-admin/
 *     Allow: /wp-admin/admin-ajax.php
 *     Disallow: /wp-login.php
 *     Disallow: /prihl/
 *     Disallow: /xmlrpc.php
 *     Disallow: /?s=
 *     Sitemap: https://everystudent.sk/sitemap_index.xml
 *
 * These are WordPress plumbing and the site-search query, not content. **No
 * article URL is disallowed.** The acquire path does not enforce robots.txt
 * (known gap), so all five are mirrored into `block` BY HAND below rather than
 * merely noted — `/wp-login.php` is in fact linked twice from live pages, so
 * this is not theoretical.
 *
 * ## Two sitemaps exist, and the one at /sitemap.xml is a 2014 fossil
 *
 * Verified 2026-07-29:
 *   - **`/sitemap_index.xml` (654 B) — LIVE, and the one used.** A Yoast
 *     `<sitemapindex>` with three children, `lastmod` 2026-05-28/06-03:
 *     `post-sitemap.xml` (**90 URLs**), `page-sitemap.xml` (**7**),
 *     `category-sitemap.xml` (**6**) = **103 distinct URLs**. `CrawlPolicy`
 *     auto-recurses a `<sitemapindex>`, so listing the index is enough.
 *   - **`/sitemap.xml` (11,966 B) — a fossil, DELIBERATELY NOT LISTED.** Emitted
 *     by google-sitemap-generator 3.4, stamped `generated-on="July 21, 2014"`,
 *     `http://www.everystudent.sk/` throughout, **44 URLs**. (This is the "~44"
 *     of prior recon — it was reading the dead file.) All 27 of its slugs that
 *     the Yoast set lacks were swept: **23 × 301 into URLs already in the live
 *     set, 4 × 404** (`/jarka/`, `/zuzka/`, `/vitaj/`, `/stranke/`). It
 *     contributes **zero new articles**, and listing it would fetch 23 old
 *     permalinks that redirect onto documents we already hold — staging
 *     duplicates at URLs no content hash can collapse. Omitted on that evidence.
 *
 * ⚠️ **3 live sitemap URLs 301-REDIRECT TO THE HOMEPAGE and are blocked by URL.**
 * `/dusickova-sutaz/` (All Souls' contest), `/predvianocna-skupinka/`
 * (pre-Christmas group) and `/velkonocna-sutaz/` (Easter contest) — expired
 * event/campaign stubs Yoast still lists. This host's analogue of the Czech
 * host's 26 dead event stubs, but it must be handled DIFFERENTLY: the Czech
 * stubs return 200 with `.content` bound to a 25-char "no records found" body,
 * so `minContentLength` genuinely caught them. These three return **301 to `/`**,
 * and the homepage extracts **581 chars** — comfortably over the floor. Left
 * unblocked they would stage three byte-identical copies of the homepage. There
 * is no URL pattern uniting them, so all three are named explicitly.
 *
 * ## HTML-map cross-check — the sitemap is missing 3 articles, pinned as seeds
 *
 * The site's own `/mapa-stranky/` extracts only 35 chars (a JS-rendered plugin
 * listing), so it was useless as a cross-check and a full `href` harvest across
 * all 100 fetched pages was used instead: **106 distinct on-host page URLs, 10
 * of them absent from the Yoast sitemap.** Resolved 2026-07-29:
 *   - **`/vznik-vesmiru-2/`, `/vznik-vesmiru-3/`, `/vznik-vesmiru-4/` — 200, real
 *     articles, PINNED in `seedPaths`.** They are parts II–IV of the four-part
 *     "Vznik vesmíru" ("Origin of the universe") series — "Niečo" (8,587 ch),
 *     "Niekto" (6,802 ch), "Kto?" (7,393 ch) — and Yoast lists only part I
 *     (`/vznik-vesmiru-1/`, 5,646 ch). Each binds `.entry-content` once, is
 *     Slovak, and duplicates nothing. Without these seeds the series would land
 *     in the corpus with three of its four parts missing.
 *   - `/ako-vieme-ze-jezis-skutocne-zil/` → 301 to `/skutocne-zil-jezis/`, and
 *     `/kto-bol-jezis/` → 301 to `/citaty-o-jezisovi/`; `/osobne/` → 301 to
 *     `/spoznaj-boha/`. Old permalinks for documents already kept — no new text.
 *   - `/uncathegorized/` (13 inbound links) — the misspelt WordPress
 *     "Nezaradené" category index. Blocked; see the zero-char note below.
 *   - `/jazykylasky/` + `/jazykylasky/quiz.html` — a quiz shell with **no
 *     `.entry-content` at all**, so `extractContent` would fall through to the
 *     whole document. Blocked.
 *   - `/wp-login.php` — robots-disallowed. Blocked.
 *
 * ## Extraction — `.entry-content`, ONE selector, measured on 100 pages
 *
 * Every candidate below was run through the repo's own `extractContent`
 * (node-html-parser) over all 100 successfully-fetched pages on 2026-07-29 — not
 * grepped, because a class name in an inline `<style>` block false-positives.
 * Char counts are post-base-strip; `(n)` is the element count:
 *   - **`.contentpadding` — NO MATCH, 0 chars, on 0 of 100 pages.**
 *   - **`.content4` — NO MATCH, 0 chars, on 0 of 100 pages.**
 *   - **`.content4b` / `.articletitle` / `.contentleftpadding` /
 *     `.article-content` / `.cb-entry-content` — NO MATCH, 0 chars, 0 of 100.**
 *   - **`.content` (the everystudent.cz selector) — NO MATCH, 0 chars, 0 of 100.**
 *   - **`.entry-content` — matches 100/100; 478 – 31,789 ch, median 3,038.
 *     ✅ SHIPPED.** Exactly **1 instance on all 94 article pages**.
 *   - `article` — identical text to `.entry-content` on articles, but **9–22
 *     instances on the 6 category pages** (first = 143 ch, one teaser card).
 *     Rejected: a superset-shaped trap.
 *   - `main` — matches 100/100 and is a strict superset (3,198 vs 3,038 median):
 *     it folds in the post header/meta. Rejected.
 *   - `body` — 202 – 31,967 ch (whole page). `html` — 244 – 32,024 ch, and leaks
 *     the literal `<!DOCTYPE html>` node. Both rejected.
 *   - `.post-content` — 6/100 (the category pages only), 143–201 ch. Rejected.
 *   - `.elementor-widget-container` — 94/100 but **2 pages extract 0 chars**, and
 *     it is an inner widget wrapper that truncates articles built from several
 *     widgets (1,237 ch vs 11,723 on `/existuje-boh/`). Rejected.
 *
 * ⚠️ `contentSelectors` is **NOT a fallback chain** — `extractContent` binds the
 * FIRST selector that matches an ELEMENT and stops, even at 0 chars, so a
 * zero-text match SHADOWS every working selector after it. Exactly one selector
 * is declared, and no fallback is added on purpose: `.entry-content` was present
 * on 100/100 pages fetched, so there is no page a fallback could rescue.
 *
 * ⚠️ **`.entry-content` extracts 0 chars on the 6 category indexes** (9–22
 * instances each, first empty). Those are blocked by URL anyway; the note is
 * here so nobody reads "matches 100/100" as "yields text 100/100".
 *
 * ## Chrome stripped — one selector, and it is the only one that binds
 *
 * Measured inside `.entry-content` across the 94 pages over 250 ch, 2026-07-29:
 *   - **`.elementor-widget-button` — 78/94 pages, 4,341 ch total (avg 46).** The
 *     Elementor CTA buttons: "Otestuj sa" ("Take the test"), "Odoberať"
 *     ("Subscribe"), "Online kurz «5 jazykov lásky»". Real chrome, real removal.
 *   - **`sitelevel_noindex`, `.fccell`, `.fctable`, `.hr2`, `.articledivider`,
 *     `.relatedbottom`, `.shareiconsmenupg` — ALL 0 instances / 0 chars, and
 *     absent from the raw HTML of all 100 pages.** They belong to the legacy
 *     FreeFind template this host does not use. Every one is **omitted** rather
 *     than carried as sibling-parity dead config: on this generator they could
 *     never bind, so their presence would be misleading rather than defensive.
 *     `.sharedaddy`, `.addtoany_share_save_container`, `.wp-block-buttons` and
 *     `.elementor-share-buttons` were checked too — also 0 instances.
 *
 * ⓘ **Deliberately NOT stripped, though it looked strippable:**
 *   - `.elementor-widget-heading` — 415 ch on 12/94 pages, and it does remove
 *     the "POZRI SI ĎALŠIE JAZYKY LÁSKY:" related-links heading on the five
 *     love-language articles. But on `/zavislost-od-pornografie/` it wraps a
 *     **genuine article section heading** ("Ako sa oslobodiť od pornografie?").
 *     Stripping it would silently delete real content to save ~4 chars/page.
 *   - `.elementor-widget-text-editor` and `.e-con` — these CONTAIN the article
 *     body (493,669 ch and 479,774 ch respectively across the corpus). Named
 *     here because "strip the Elementor wrappers" is the obvious wrong move.
 *
 * ## What is blocked, and the measured evidence for each
 *
 * Article URLs on this host are bare single-segment slugs (`/<slug>/`), the
 * SAME shape as the category and page URLs — so `articleHints` cannot separate
 * them by path prefix the way the `/a/` siblings do. **The `block` list is doing
 * all of the discrimination here and is not redundant decoration.** All figures
 * are post-strip, measured 2026-07-29:
 *   - **`/` — 581 ch.** The homepage; `.entry-content` binds and yields its
 *     teaser list. Over the floor.
 *   - **The 6 category indexes** (`existencia`, `otazky-odpovede`, `poznanie`,
 *     `vztahy`, `zivot`, `zmenene`) **+ `/uncathegorized/` — 0 ch each.** These
 *     are the zero-char shadow: `.entry-content` matches 9–22 times and the
 *     first is empty. The floor would drop them, but blocking spares 7 fetches
 *     and states the intent.
 *   - **The 6 non-article WordPress pages** — `/mapa-stranky/` (35 ch, site
 *     map), `/kontakt/` (63 ch), `/posli-modlitebnu-prosbu/` (**393 ch**, prayer
 *     request form), `/otazky-a-odpovede/` (**1,224 ch**, a pure question-link
 *     index), `/podpor-nas/` (**1,066 ch**, donate), `/o-nas/` (**1,125 ch**,
 *     about). Four of the six clear the 250 floor — length is not aboutness.
 *   - **The email-series signup pages, all well over the floor.** This host's
 *     twins of the French `/jean.html` + `/aventure.html`:
 *       · `/studium-janovho-evanjelia/` (**2,600 ch**) — "Štúdium Jánovho
 *         evanjelia", the Gospel-of-John study signup ("Naša e-koučka Eva ťa
 *         pozýva na biblické štúdium Evanjelia podľa Jána"). It also carries the
 *         only Czech-language text on the host, in subscriber testimonials.
 *       · `/emailove-balicky/` (**1,806 ch**) — "Emailové balíčky", the hub
 *         offering the e-mail series ("Ponúkame ti emailové série («balíčky»)").
 *         The literal Slovak "packages" page — twin of the Arabic `/pack.html`.
 *       · `/hladanie-pravdy/` (**1,737 ch**) — "Veda vs. viera: Hľadanie pravdy",
 *         a 5-email series signup ("Pripravili sme pre teba krátku sériu
 *         emailov"). Twin of the Polish `/czybogjest.html`.
 *       · `/startovaci-balicek/` (**2,431 ch**) — "Štartovací balíček", the
 *         post-decision starter kit. Twin of the Polish `/a/nowezycie.html`.
 *   - **`/ekoucing/` (1,921 ch)** — "Kto je e-kouč?", a description of the
 *     e-coaching service ("Na správy našich čitateľov odpovedajú desiatky našich
 *     e-koučov"). Service chrome, not a seeker Q&A article.
 *   - **The quiz trio** — `/test-5-jazykov-lasky/` (**24 ch**: the string "By
 *     WordPress Quiz plugin" and nothing else), `/5-jazykov-lasky-test/` (**546
 *     ch**, a teaser whose whole payload is "urob si tento bezplatný
 *     2-minútový test", fully contained in the real 4,054-ch article
 *     `/5-jazykov-lasky/` which IS kept), and `/jazykylasky/` (**no
 *     `.entry-content` at all** → whole-document fallback).
 *   - **The 3 homepage-redirect stubs** and the **5 robots.txt paths**, above.
 *
 * ⓘ **NO full-Scripture page on this host — nothing to block under the
 * estate-wide scripture policy** (which `everystudent-sq` applies to its 98,887-ch
 * Gospel of John and `everystudent-es` to `/articulos/biblia_juan.html`).
 * Verified 2026-07-29 by scanning every kept body for Slovak verse references:
 * the highest density is **3.5 refs per 1,000 chars** (`/povedal-jezis-niekedy-ze-je-boh/`,
 * 5,191 ch), i.e. ordinary citation apparatus. The longest document,
 * `/je-biblia-pravdiva/` at **31,734 ch**, is "Dá sa veriť Biblii? Čo hovoria
 * dôkazy?" — a long-form apologetics essay ABOUT the Bible's historical and
 * archaeological reliability, not Bible text. It is KEPT.
 *
 * ⓘ **The 11 person-named slugs are testimonies and are KEPT** — `/eva/`,
 * `/gabika/`, `/milan/`, `/tomas/`, `/peter/`, `/miska/`, `/peta/`, `/biba/`,
 * `/gabi/`, `/regina/`, `/viktor/` (1,942–4,079 ch). Read 2026-07-29: each is a
 * first-person student narrative ("Dlhé roky som zápasila so svojou identitou",
 * "Boh neexistuje a basta!"), the same genre as `everystudent-sq`'s
 * `/a/heather.html`. Not author pages.
 *
 * ⓘ **The 5 love-language articles overlap each other 47.1–51.6%** (8-gram
 * Jaccard): `/fyzicke-dotyky/`, `/kvalitny-cas/`, `/prijimanie-darov/`,
 * `/skutky-sluzby/`, `/slova-uistenia/`, each 1,536–1,646 ch. They share a
 * ~700-char closing passage but each opens on its own distinct love language
 * ("Tvojím jazykom lásky sú SKUTKY SLUŽBY…"). That is far below the 87.9–93.8%
 * band at which the French and English entries dropped near-duplicates, so all
 * five are kept. Flagged so the similarity is not read later as a bug.
 *
 * ## Language: `["sk"]` — read, and confirmed SLOVAK not Czech
 *
 * Verified 2026-07-29 by reading the extracted text myself. `/spoznaj-boha/`
 * opens "Kto je Boh? Ako ho nájsť či spoznať? Máme čakať na blesk z jasného
 * neba?" ("Who is God? How to find or know him? Should we wait for a bolt from
 * the blue?"); `/vznik-vesmiru-2/` runs "Ak teda niekedy existovalo Absolútne
 * Nič, bolo by tu toto Absolútne Nič až dodnes"; `/gabi/` is "Cítil si sa už
 * niekedy ako pokrytec? Ja áno."
 *
 * The distinguishing evidence against Czech is orthographic and decisive. Across
 * all 94 extracted bodies ≥250 ch:
 *   - **Slovak-only letters `ľ ĺ ŕ ô ä` — 3,424 occurrences, on 94 of 94 pages.**
 *     No page lacks them. E.g. "spoľahlivý spôsob" (Slovak) where Czech would
 *     write "spolehlivý způsob"; "ľudia", "vzťah", "päť".
 *   - **Czech-only letters `ř ě ů` — 9 occurrences, on 3 of 94 pages**, and every
 *     one is accounted for: two are Czech-language book citations in footnotes
 *     ("Philip Yancey, *Ježíš, jak jsem ho neznal*, Návrat domů, Praha 2002"),
 *     and the rest are Czech subscriber testimonials on
 *     `/studium-janovho-evanjelia/` — which is blocked. **No article body is
 *     Czech.**
 * This is the exact mirror of `everystudent-cs`'s finding (ř/ě/ů on 73/73 pages
 * there, ľ/ĺ/ŕ/ô/ä concentrated on its one imported Slovak page). The two
 * sources are cleanly separated by language as well as by domain.
 *
 * `requestDelayMs: 1000` — the sibling default, and NOT the Czech host's 2000.
 * That 2000 was set because everystudent.cz timed out 3 times in a 97-URL sweep.
 * **This is a different host on different infrastructure and it never timed
 * out**: ~140 sequential requests produced 0 timeouts, 0 × 429 and no
 * throttling. Pages are large (~450 KB of Elementor markup, ~2.5 s each), so the
 * transfer already paces the crawl; 83 pages is ~5 minutes of wall clock.
 *
 * ⚠️ **Slovak is a NEW language for this corpus** as far as this entry knows —
 * `everystudent-cs` declares `cs`, which is a different ISO 639-1 code. Stage-4
 * needs fresh Slovak golden cases rather than a Part A re-review. Per ADR-0007's
 * 500-char detection floor, the shortest kept document (478 ch) sits just BELOW
 * it and may not receive a stored `sk` label; every other kept document clears
 * it. The stored per-document label always comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * **Expected yield: 83 documents** — 80 of the 103 sitemap URLs survive
 * `allow ∧ articleHints ∧ ¬block` (simulated against the live file), plus the 3
 * pinned seeds. Measured extracted length across all 83: **478 – 31,734 ch,
 * median 3,689**, every one binding `.entry-content` and clearing the floor.
 */
import type { SourceEntry } from "./types.js";

export const everystudentSk: SourceEntry = {
  key: "everystudent-sk",
  name: "EveryStudent — Slovak (EveryStudent.sk)",
  // The BARE apex is canonical: www.everystudent.sk 301s here, and every Yoast
  // <loc> is emitted bare. Adding "www." would make every regex below miss.
  domain: "everystudent.sk",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["sk"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:sk"],
  defaultCategory: "article",
  rights:
    "© EveryStudent.sk (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    // No `fetchStrategy`: verified unwalled 2026-07-29 (~140 GETs, zero 403s,
    // `server: openresty` with no Cloudflare layer).
    baseUrl: "https://everystudent.sk",
    // The LIVE Yoast index; CrawlPolicy auto-recurses its 3 children
    // (post/page/category = 103 URLs). /sitemap.xml is deliberately NOT listed:
    // it is a 2014 google-sitemap-generator fossil whose 27 unique slugs are 23
    // redirects onto documents we already hold plus 4 hard 404s. See header.
    sitemaps: ["/sitemap_index.xml"],
    allow: ["^https://everystudent\\.sk/"],
    // Articles are bare single-segment slugs. `[^/]+` rather than a
    // lowercase-only class: all 103 <loc> values were scanned and carry no
    // uppercase, no non-ASCII byte and no %XX escape today, but Slovak
    // diacritics in a future slug would arrive percent-encoded and a
    // `[a-z0-9-]+` hint would silently drop them.
    articleHints: ["^https://everystudent\\.sk/[^/]+/$"],
    // ⚠️ Category and page URLs share the article URL shape, so articleHints
    // CANNOT separate them — every rule below is load-bearing, not redundant.
    block: [
      // The homepage: .entry-content binds and yields 581 ch of teasers.
      "^https://everystudent\\.sk/?$",
      // The 6 category indexes + the misspelt "uncathegorized" one. They are
      // the zero-char shadow: .entry-content matches 9-22x and the first is
      // empty, so they extract 0 ch. Blocked to state intent and save fetches.
      "^https://everystudent\\.sk/(existencia|otazky-odpovede|poznanie|vztahy|zivot|zmenene|uncathegorized)/$",
      // The 6 non-article WordPress pages. Four of the six CLEAR the 250 floor:
      // /otazky-a-odpovede/ 1,224 ch (a pure question-link index), /o-nas/
      // 1,125, /podpor-nas/ 1,066 (donate), /posli-modlitebnu-prosbu/ 393
      // (prayer form); /mapa-stranky/ 35 and /kontakt/ 63 fall below it.
      "^https://everystudent\\.sk/(mapa-stranky|kontakt|o-nas|podpor-nas|posli-modlitebnu-prosbu|otazky-a-odpovede)/$",
      // The email-series signup pages, 1,737-2,600 ch — all far above the floor,
      // so ONLY a URL block catches them. studium-janovho-evanjelia = the
      // Gospel-of-John study (twin of the French /jean.html); emailove-balicky =
      // the "packages" hub and hladanie-pravdy = its 5-email series (twins of
      // the Arabic /pack.html); startovaci-balicek = the post-decision starter
      // kit (twin of the Polish /a/nowezycie.html). See header.
      "^https://everystudent\\.sk/(studium-janovho-evanjelia|emailove-balicky|hladanie-pravdy|startovaci-balicek)/$",
      // "Kto je e-kouč?" — 1,921 ch describing the e-coaching service itself.
      "^https://everystudent\\.sk/ekoucing/$",
      // ⚠️ 3 LIVE SITEMAP URLS THAT 301 TO THE HOMEPAGE — expired event stubs
      // Yoast still lists. Unlike the Czech host's dead stubs (which return 200
      // with a 25-char body the floor catches), these resolve to the homepage's
      // 581 ch, so leaving them unblocked stages 3 identical homepage copies.
      // No pattern unites them; all three are named. See header.
      "^https://everystudent\\.sk/(dusickova-sutaz|predvianocna-skupinka|velkonocna-sutaz)/$",
      // The quiz trio: /test-5-jazykov-lasky/ is a 24-ch plugin shell,
      // /5-jazykov-lasky-test/ a 546-ch teaser wholly contained in the real
      // article /5-jazykov-lasky/ (4,054 ch, KEPT), and /jazykylasky/ has NO
      // .entry-content at all so extractContent would return the whole document.
      "^https://everystudent\\.sk/(test-5-jazykov-lasky|5-jazykov-lasky-test|jazykylasky)(/|$)",
      // Old permalink that 301s to /spoznaj-boha/ (already kept). Absent from
      // the live sitemap but still linked from a live page.
      "^https://everystudent\\.sk/osobne/$",
      // robots.txt Disallow rules, mirrored BY HAND because the acquire path
      // does not enforce robots.txt. /wp-login.php is genuinely linked twice
      // from live pages, so this is not a theoretical guard.
      "^https://everystudent\\.sk/(wp-admin|wp-login\\.php|xmlrpc\\.php|prihl)(/|$)",
      "^https://everystudent\\.sk/\\?s=",
    ],
    // Parts II-IV of the 4-part "Vznik vesmíru" series. Yoast lists only part I.
    // Fetched and measured 2026-07-29: 8,587 / 6,802 / 7,393 ch, Slovak, each
    // binding .entry-content once, duplicating nothing. acquire.ts unions these
    // with discovered URLs. See header.
    seedPaths: ["/vznik-vesmiru-2/", "/vznik-vesmiru-3/", "/vznik-vesmiru-4/"],
    // ⚠️ WordPress + Elementor — NOT the .content4/.contentpadding family and
    // NOT everystudent.cz's Yii `.content`. Measured 2026-07-29 over all 100
    // fetched pages: .contentpadding, .content4, .content4b, .content,
    // .articletitle, .contentleftpadding, .article-content and .cb-entry-content
    // ALL match 0 of 100. .entry-content matches 100/100 (1 instance on every
    // article, 478-31,789 ch). ONE selector: extractContent binds the first
    // selector that MATCHES rather than the first that yields text, so any
    // addition here risks shadowing this one at 0 chars.
    contentSelectors: [".entry-content"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // The ONLY site-specific chrome that binds on this host: Elementor's CTA
      // buttons ("Otestuj sa", "Odoberať", "Online kurz …") — 78/94 pages,
      // 4,341 ch total. The legacy FreeFind selectors the siblings strip
      // (sitelevel_noindex, .fccell, .fctable, .hr2, .articledivider,
      // .relatedbottom, .shareiconsmenupg) are 0 instances / 0 chars here and
      // are omitted rather than carried as dead config. NB do NOT add
      // .elementor-widget-text-editor or .e-con — they CONTAIN the article body
      // — nor .elementor-widget-heading, which wraps a real section heading on
      // /zavislost-od-pornografie/. See header.
      ".elementor-widget-button",
    ],
    requestDelayMs: 1000, // 0 timeouts / 0 × 429 in ~140 requests; not the .cz host
    maxPages: 140, // 103 sitemap URLs (80 kept) + 3 seeds + headroom
    minContentLength: 250,
  },
};
