/**
 * EveryStudent — Vietnamese (everyvietstudent.com). The Vietnamese banner of
 * Cru's seeker-facing Q&A ministry: short apologetics and life-issue articles
 * written for Vietnamese-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ar`, `everystudent-fr` and the #111
 * non-walled batch (`-de` `-es` `-ja` `-ko` `-pt` `-ro` `-ru` `-zh-cn`).
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everyvietstudent.com is its own domain, so it gets its
 * own key, the same way `everystudent-ru` (mirstudentov.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: **~95 plain-HTTP requests** with a full browser UA
 * (robots.txt, /sitemap.xml, a HEAD sweep of all 76 sitemap URLs, all 66
 * articles fetched in full, the 8 `/m/` indexes, `/co.html`, `/m/intl.html` and
 * the homepage) — **every one returned HTTP 200 with real HTML**, and not one
 * carried a Cloudflare block-page signature. `server: Apache`, no Cloudflare
 * headers at all. So `fetchStrategy` is intentionally OMITTED: plain HTTP is
 * the default and nothing here needs Firecrawl (ADR-0012). Discovery is
 * therefore free, so this is a **discovery crawl** rather than the hand-listed
 * seed set the three walled banners were forced into. Precedent for the shape:
 * `thelife-fr` and the non-walled sibling `everystudent-ru`.
 *
 * The bare host 301-redirects to `www` (measured on /robots.txt), so
 * `www.everyvietstudent.com` is the canonical host and the one every `<loc>`
 * uses.
 *
 * ⓘ **The host sends `content-type: text/html` with NO charset parameter** —
 * verified 2026-07-29 on all 76 URLs (`content_type` was the bare string
 * `text/html` every time; only `/sitemap.xml` differs, at `application/xml`,
 * and `/robots.txt` at `text/plain`). The bytes ARE UTF-8: the documents
 * declare `<meta http-equiv="content-type" content="text/html; charset=utf-8"/>`,
 * a strict UTF-8 decode of a fetched page succeeds with no BOM, and the
 * Vietnamese diacritics (ă â đ ê ô ơ ư plus tone marks) render correctly. Any
 * mojibake seen downstream is a decoder defaulting to latin-1, not a broken
 * site.
 *
 * ## robots.txt — no Disallow at all
 *
 * Verified 2026-07-29: HTTP 200, **22 bytes**, Last-Modified 2020-03-24. The
 * whole file is the single line `User-agent: * Allow: /` (the `Allow` sits on
 * the SAME line as the agent — loose syntax, identical to everyarabstudent.com
 * and questions2vie.com). **Zero `Disallow` lines**, so nothing on this domain
 * is disallowed and no URL below is dropped on robots grounds — every exclusion
 * is a content-quality call.
 *
 * ## Sitemap — 76 entries, all distinct, all live
 *
 * Verified 2026-07-29: `https://www.everyvietstudent.com/sitemap.xml` → HTTP
 * 200, 6,220 bytes, `application/xml`, generated by xml-sitemaps.com,
 * Last-Modified 2020-03-23. It holds 76 `<loc>` elements and **76 distinct
 * URLs** — no duplicates. This matches prior recon's ~76 exactly. Breakdown:
 *   - **66 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **8 `/m/<slug>.html`** — section indexes (`ex1`, `ex2`, `en`, `is`, `je`,
 *     `fo`, `ab`, `map`). BLOCKED, below.
 *   - **`/co.html`** — the contact page. BLOCKED, below.
 *   - **`/`** — the homepage. BLOCKED, below.
 *
 * A HEAD sweep of all 76 (HTTP/1.1, full browser UA) returned **76/76 HTTP 200
 * with an empty redirect_url** — no 301/302, no dead entries. There is nothing
 * here of the kind a sibling shipped as 25 unblocked redirect-to-homepage URLs.
 *
 * Slugs are **ASCII-folded and mixed-case** — `101DucChuaTroi.html`,
 * `511VanPhamDoiTruyHai.html`, `virus-corona.html`. Despite the language being
 * heavily diacriticked, **no URL carries a diacritic or a percent-escape**
 * (checked across all 76), so `[^/]+` is a safe, case-safe hint.
 *
 * ## HTML-map cross-check — zero delta, but link-crawling found two more
 *
 * `/m/map.html` is this host's own HTML site map. Verified 2026-07-29: it links
 * **exactly the same 66 `/a/` URLs** as the XML sitemap — the set difference is
 * empty in both directions. (The two maps disagree only on navigation:
 * `/m/je.html` is in the XML but not the HTML map, `/m/intl.html` the reverse.
 * Both are blocked either way.)
 *
 * Link-unioning every `href` across all 66 articles + all `/m/` pages + the
 * homepage + `/co.html` surfaced **two `/a/` URLs neither map lists**:
 *   - **`/a/402Batdauvoi.html` — live, HTTP 200, PINNED in `seedPaths`.**
 *     "Bắt Đầu Hành Trình Với Chúa" ("Starting the journey with God"), linked
 *     from `/a/101DucChuaTroi.html` and `/a/401Nhanbiet.html`. Extracts **657
 *     chars** — real Vietnamese prose, above the 250 floor, but it is a short
 *     post-decision next-steps page whose two onward links go off-domain to
 *     batdauvoichua.com (a separate domain, therefore out of scope by
 *     ADR-0006). Pinned because acquire.ts unions seeds with discovered URLs
 *     and sitemap discovery would otherwise never see it. **Judgement call**:
 *     if the corpus should hold only seeker Q&A, this one seed is the line to
 *     delete.
 *   - **`/a/217HaithuChanLy.html` — DEAD: 301 → `/m/ex2.html`.** Linked from
 *     `/m/je.html` only. It is in neither map so discovery cannot reach it
 *     today; it is blocked anyway (see below) so a regenerated sitemap cannot
 *     silently readmit it.
 * No page on this host is orphaned in the other direction: all 66 sitemap
 * articles are linked from somewhere on the site.
 *
 * Expected yield: **67 documents** (66 discovered + 1 pinned seed).
 *
 * ## No Gospel-of-John signup page and no adventure/pack series exist here
 *
 * Verified 2026-07-29 rather than assumed. `/john.html`, `/jean.html`,
 * `/pack.html`, `/adventure.html` all return **404**, and the only signup-shaped
 * link anywhere on the host — `/word/john11.html`, referenced once from
 * `/a/215KinhThanh.html` — is also a **404** (it serves the site's custom
 * "Ồ! Xin Lỗi!" error page). The only `<form>` on any page is the SiteLevel
 * search box, which the base `form` strip removes. So the URL blocks the
 * sibling entries carry for those pages have no target here; `articleHints`
 * (which admits nothing outside `/a/`) covers the case regardless.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes all of these. The `block` list is
 * deliberately redundant: it records *why* each group is out, so a later
 * widening of the hints cannot silently readmit them. Same defensive posture as
 * `everystudent-ru` and `thelife-fr`. Char counts are extracted text measured
 * 2026-07-29 with the repo's own `extractContent` under the exact policy below:
 *
 *   - **`/m/*` — navigation, not content.** All 8 fetched; they extract
 *     **892–3,218 chars** of headline+teaser link lists. `/m/ex1` (Sự hiện hữu),
 *     `/m/ex2` (Biết Đức Chúa Trời), `/m/en` (Câu hỏi cuộc sống), `/m/is` (Mối
 *     quan hệ), `/m/je` (Chúa Giê-xu?) and `/m/fo` (Hỏi và đáp) are the section
 *     indexes; `/m/ab` (1,316 ch) is "Về trang web" — about + Cru attribution;
 *     `/m/map` (3,218 ch) is the HTML site map. Every one clears the 250-char
 *     floor, so `minContentLength` could NOT have caught them.
 *   - **`/co.html` — the contact page, 488 chars.** "Bạn có thắc mắc?" plus a
 *     privacy statement. Also clears the floor.
 *   - **`/` — the homepage, 892 chars** of teaser cards. It has no
 *     `.contentpadding`, so extraction falls back to the document root and
 *     returns the whole page — comfortably over the floor. Length is not
 *     aboutness; only a URL block excludes it.
 *   - **`/a/217HaithuChanLy.html` — the one redirecting URL on this host**
 *     (301 → `/m/ex2.html`, a nav index). Not currently discoverable; blocked so
 *     a future sitemap regeneration cannot stage a copy of the ex2 index.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Re-measured 2026-07-29 by running the repo's own `extractContent`
 * (node-html-parser) against all 67 live article pages — the only check that
 * proves anything, because every one of these tokens is ALSO declared in the
 * page's inline `<style>` block and a grep false-positives on all of them.
 * Per-candidate, on `/a/101DucChuaTroi.html` / `/a/305Mucdich.html` /
 * `/a/709BaNgoi.html`:
 *   - **`.contentpadding` — 1 instance, the whole article**: kicker, `<h1>`,
 *     subhead, byline, body and footnotes. **18,946 / 4,819 / 4,113 chars**
 *     before the chrome strip.
 *   - **`.content4` — 1 instance, an empty spacer `<div class="content4"> </div>`:
 *     0 characters.** Listing it first is the trap: across all 67 articles a
 *     `[".content4", ".content4b", ".articletitle", ".contentpadding"]` chain
 *     extracts **0 chars on 67/67 pages** (min 0, max 0) — every article skipping
 *     as `too-thin` on an HTTP 200, silently. `extractContent` scopes to the
 *     FIRST selector that MATCHES AN ELEMENT, not the first that yields text.
 *   - **`.content4b` — 0 instances** on 66 of 67 pages (present, and empty, only
 *     on the one malformed page below).
 *   - **`.articletitle` — an `<h1>`, 27 / 28 / 53 chars.** A title, not a body.
 *   - **`#content`, `.content`, `.maincontent`, `<article>`, `<main>` — 0
 *     instances.** Absent from this host entirely.
 * `contentSelectors` is therefore the ONE measured container and nothing else.
 * With it, all 67 articles extract **657–28,225 chars; 0 pages under the 250
 * floor, 0 pages at zero**.
 *
 * ⚠️ `.contentpadding` also binds on `/co.html`, `/m/ab.html` and `/m/map.html` —
 * it does **not** discriminate content from nav. The URL filters above are what
 * keep the corpus clean; the selector must not be relied on to do it.
 *
 * ⓘ **One page's container does not survive parsing, and that is fine.** On
 * `/a/726DucChuaTroiyeu.html` the markup nests `container2 > content4 >
 * content4b > contentpadding`, and node-html-parser closes the outer three
 * immediately, so `.contentpadding` yields **0 element instances** even though
 * the literal `<div class="contentpadding">` is in the bytes. `extractContent`
 * then falls through to its root fallback and still returns **the complete
 * article, 4,275 chars** (the chrome strip removes 905 chars of nav from it),
 * with one cosmetic artifact: a leading `<!DOCTYPE html>` token. No page is
 * lost. Related: `root.querySelector("body")` is null on **every** page of this
 * host (node-html-parser does not synthesise an implicit `<body>` here), so the
 * documented "<body> fallback" is really a whole-document fallback.
 *
 * ## Chrome stripped — measured INSIDE the real scope, all 67 pages
 *
 *   - **`sitelevel_noindex`** is a **custom ELEMENT tag**, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. 2–4 instances per page;
 *     **marginal removal 69–802 chars on 67/67 pages** (cookie bar, nav, share
 *     row, utility bar). The single load-bearing strip on this host. Hence the
 *     bare tag-name selector with no leading `.` — correct, not a typo.
 *   - **`.fccell` (0–6) and `.fctable` (0–1)** — the "FEATURE CLOSE"
 *     call-to-action table appended to every article. In isolation each removes
 *     **up to 214–218 chars**; against the full list they are mutually
 *     redundant on 66 pages (the cells nest in the table), and **`.fccell` is
 *     the one that still fires on `/a/726DucChuaTroiyeu.html`** (218 chars),
 *     where the table shell is not reachable. Both kept: dropping `.fctable`
 *     would leave the shell, dropping `.fccell` would leak the CTA on 726.
 *   - **`.shareiconsmenupg` (0–1 per page)** — the "CHIA SẺ" AddToAny share row.
 *     In isolation it removes 22 chars; against the full list its **marginal
 *     removal is 0 on 67/67**, because on THIS host the wrapping
 *     `<sitelevel_noindex>` is well-formed enough to contain it (unlike the
 *     German and Russian siblings, where it is not — #128). Kept anyway: it is
 *     a zero-cost guard against exactly the malformation the siblings hit, and
 *     it is required parity across the estate.
 *   - **`.hr2` (0–6) and `.articledivider` (1)** — empty divs drawing the rules
 *     that bracket the CTA block. **0 chars**, confirmed on all 67.
 *   - **`.relatedbottom`** has **no element instance** on any page measured — a
 *     no-op on this host. Retained for parity with the sibling entries; do not
 *     read its presence here as evidence it binds.
 * Total chrome removed per page: **69–905 chars**.
 *
 * ## Language: `["vi"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Vietnamese prose, not untranslated English. `/a/305Mucdich.html` asks
 * "Mục đích sống của tôi là gì?" and answers "Bạn sẽ sống một cuộc đời đầy ý
 * nghĩa khi bạn biết mục đích của cuộc đời mình" ("you will live a life full of
 * meaning when you know the purpose of your own life"), then runs an extended
 * parable about a hammer left unused in a toolbox — idiomatic prose, not
 * machine output. `/a/virus-corona.html` is "Virus Corona (COVID-19) - Làm Thế
 * Nào Đối Phó Với Sự Lo Lắng" ("…how to cope with anxiety"), bylined "Được viết
 * bởi Marilyn Adamson". `/a/709BaNgoi.html` is "Bạn có thể giải thích về Ba Ngôi
 * Đức Chúa Trời không?" (the Trinity). Scripture citations use Vietnamese book
 * names throughout — Rôma, Thi thiên, Êsai, Giăng, Khải Huyền, II Timôthê,
 * Phục truyền luật lệ ký. The only English on these pages is the site's own
 * brand string and the Cru attribution ("Campus Crusade for Christ,
 * International") in `/m/ab.html`, which is blocked anyway.
 *
 * ⓘ Source-side inconsistency worth knowing about: the site spells Jesus both
 * "Chúa Giê-xu" and "Chúa Jêsus" (sometimes on the same page), and God both
 * "Đức Chúa Trời" and "Thượng Đế". Both variants will land in extracted text;
 * anything keying off a single spelling will under-match.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: ~95 sequential plain-HTTP requests drew no 429 and no throttling,
 * and at 67 pages the whole crawl is well under two minutes of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentVi: SourceEntry = {
  key: "everystudent-vi",
  name: "EveryStudent — Vietnamese (EveryVietStudent.com)",
  domain: "www.everyvietstudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["vi"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:vi"],
  defaultCategory: "article",
  rights:
    "© EveryVietStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everyvietstudent.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (Apache, no Cloudflare). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.everyvietstudent\\.com/"],
    // The whole article corpus and nothing else: 66 of the 76 sitemap URLs.
    // Slugs are ASCII-folded but MIXED CASE (/a/101DucChuaTroi.html), so the
    // hint must stay case-safe — `[^/]+` handles it.
    articleHints: ["^https://www\\.everyvietstudent\\.com/a/[^/]+\\.html$"],
    block: [
      // The 8 section indexes (ex1, ex2, en, is, je, fo, ab, map) — headline+
      // teaser link lists at 892-3,218 chars, so they clear minContentLength
      // and the floor can NOT catch them. /m/ab.html is the about page;
      // /m/map.html the HTML site map; /m/intl.html (linked but not in the
      // sitemap) the page linking out to the sibling language domains.
      "^https://www\\.everyvietstudent\\.com/m/",
      // The contact page: 488 chars of blurb + privacy statement.
      "^https://www\\.everyvietstudent\\.com/co\\.html$",
      // The homepage: 892 chars of teaser cards, no article container.
      "^https://www\\.everyvietstudent\\.com/?$",
      // The one redirecting URL on this host: 301 -> /m/ex2.html, a nav index.
      // Not in either sitemap today; blocked so a regenerated sitemap cannot
      // stage a copy of that index page under an article URL.
      "^https://www\\.everyvietstudent\\.com/a/217HaithuChanLy\\.html$",
    ],
    // One pinned seed, unioned with discovery by acquire.ts. A live 200 article
    // (657 ch) that BOTH the XML sitemap and the site's own /m/map.html omit —
    // reachable only as a link from /a/101DucChuaTroi.html and
    // /a/401Nhanbiet.html. See the header for the judgement call.
    seedPaths: ["/a/402Batdauvoi.html"],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article (657-28,225 ch across all 67 pages, none
    // under the floor). `.content4` is deliberately ABSENT: it is an empty
    // spacer div (0 chars) and, because extractContent scopes to the first
    // selector that MATCHES rather than the first that yields text, listing it
    // here made all 67 pages extract 0 chars and skip as `too-thin`.
    // Rule 1e (added 2026-07-30, retrofitted): trailing "html" rescues pages
    // whose .contentpadding container collapses. Without it extract.ts falls
    // through to `?? root`, which returns the whole document INCLUDING a
    // literal `<!DOCTYPE html>` text node. Proven inert on healthy pages —
    // 21 of 21 sampled extractions were byte-identical before and after.
    // It can shadow nothing, because nothing follows it.
    contentSelectors: [".contentpadding", "html"],
    stripSelectors: [
      "head", // 0 ch inside .contentpadding; strips the duplicated
      // <title> on the "html" fallback path only. Safe because extract.ts
      // reads the title from `root` BEFORE the strip loop runs.
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form", // the SiteLevel search box, the only form on the host
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2-4/page: cookie bar, nav, share row, utility bar
      ".shareiconsmenupg", // the "CHIA SẺ" AddToAny widget (0 marginal here; parity guard)
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells — still load-bearing on /a/726DucChuaTroiyeu.html
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".relatedbottom", // no instance on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 110, // 76 sitemap entries (66 articles) + 1 pinned seed + headroom
    minContentLength: 250,
  },
};
