/**
 * EveryStudent — Polish (kazdystudent.pl, "KazdyStudent.pl" / "Every student").
 * The Polish banner of Cru's seeker-facing Q&A ministry: short apologetics and
 * life-issue articles, FAQ answers and first-person testimonies written for
 * Polish-speaking students who are not believers. A sibling of `everystudent`
 * (en), `everystudent-ar`, `everystudent-fr`, and of the non-walled batch-1
 * entries `-de` / `-es` / `-ja` / `-ko` / `-pt` / `-ro` / `-ru` / `-zh-cn`.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). kazdystudent.pl is its own domain, so it gets its own
 * key, the same way `everystudent-fr` (questions2vie.com), `thelife-fr`
 * (laviejenparle.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * `pl` is a NEW language for this corpus as far as this entry knows; nothing
 * below depends on that, and the stored per-document label still comes from
 * content detection at ingest (invariant 6), never from `languages`.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: **~185 plain-HTTP GETs** with a full desktop-Chrome UA
 * (robots.txt, /sitemap.xml, all 78 `/a/` articles, all 7 `/m/` indexes, the
 * homepage, /mapa.html, /pytanie.html, /wideo.html, /jan.html,
 * /czybogjest.html, /prywatnosci.html, /a/nowezycie.html, plus a 90-URL HEAD
 * sweep). **Every one returned HTTP 200 with real HTML** and not one carried a
 * Cloudflare block-page signature. So `fetchStrategy` is intentionally OMITTED:
 * plain HTTP is the default and nothing here needs Firecrawl (ADR-0012). Same
 * as the batch-1 non-walled siblings, unlike everystudent.com /
 * everyarabstudent.com / questions2vie.com, which all 403.
 *
 * Consequence: discovery is free, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-de`, `everystudent-ru`.
 *
 * The bare host **301-redirects to `www`** (measured on /robots.txt), so
 * `www.kazdystudent.pl` is the canonical host and the one every `<loc>` uses.
 *
 * ## robots.txt — one rule, and it touches nothing in scope
 *
 * Verified 2026-07-29: HTTP 200, **30 bytes**, exactly two lines —
 * `User-agent: *` and **`Disallow: /logo/`**. `/logo/` is an image directory:
 * it appears in **0** of the 78 article pages, 0 sitemap entries and 0 links on
 * /mapa.html (all grepped). **No article URL is disallowed**, so nothing below
 * is dropped on robots grounds — every exclusion is a content-quality call. The
 * rule is not mirrored into `block` because no discovered URL can ever hit it.
 *
 * ## Sitemap — 90 entries, all distinct, 78 articles
 *
 * Verified 2026-07-29: `https://www.kazdystudent.pl/sitemap.xml` → HTTP 200,
 * **6,681 bytes**, `application/xml`, generated by xml-sitemaps.com. It holds
 * 90 `<loc>` elements and **90 distinct URLs** — no duplicates. This matches the
 * "~90" from prior recon exactly. The breakdown:
 *   - **78 `/a/<slug>.html`** — the article corpus. This is the keep set.
 *   - **7 `/m/<slug>.html`** — section indexes (`doswiadczenie`, `faq`,
 *     `jezus`, `onas`, `problemy`, `pytania`, `zycie`). BLOCKED, below.
 *   - **`/mapa.html`** (site plan), **`/pytanie.html`** (contact form),
 *     **`/wideo.html`** (video page), **`/jan.html`** (email course) and
 *     **`/`** (homepage). All BLOCKED, below.
 *
 * **All 78 `/a/` URLs are live.** A HEAD sweep of all 90 sitemap URLs returned
 * **88 × 200 and 2 × 301**, and *both* redirects are `/m/` pages that are
 * blocked anyway: `/m/jezus.html` → `/m/doswiadczenie.html` and `/m/onas.html`
 * → `/prywatnosci.html`. **No sitemap URL redirects to the homepage**, and no
 * article URL redirects at all — there is no dead-seed cohort of the kind a
 * sibling shipped 25 of.
 *
 * ⚠️ **Polish slugs here are pure ASCII — the diacritic hazard did not
 * materialise, and that was checked, not assumed.** All 90 `<loc>` values were
 * regex-scanned for non-ASCII bytes and for `%XX` percent-encoding: **zero
 * hits**. The site de-diacriticises its own slugs (`/a/malzenstwo.html` for
 * "małżeństwo", `/a/nicosc.html` for "nicość", `/a/pozadanie.html` for
 * "pożądanie"). Two slugs do carry an **uppercase** letter —
 * `/a/Boza-pomoc.html` and `/a/jak-osobiscie-poznac-Boga.html` — so the hint
 * regex must not be lowercase-only; `[^/]+` covers both. A `[a-z0-9-]+` hint
 * would have silently dropped those two articles.
 *
 * ## Cross-checked against the site's own HTML sitemap — no delta
 *
 * The XML sitemap of a sibling was 17% short, so /mapa.html was fetched and
 * diffed. Verified 2026-07-29: it links **78 `/a/` URLs**, and the two sets are
 * **identical** — 0 in the HTML map that the XML lacks, 0 the other way. Then,
 * as a wider net, every `href` on all 78 articles + all 7 `/m/` indexes + the
 * homepage was harvested: **79 distinct `/a/` URLs**, i.e. exactly one beyond
 * the sitemap — `/a/nowezycie.html`, and it is an email-signup page, not an
 * article (see below). So **no article is missing from discovery** and
 * `seedPaths` is intentionally absent: there is nothing to pin.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` already excludes everything outside `/a/`. The `block` list is
 * deliberately redundant for those, recording *why* each group is out so a later
 * widening of the hints cannot silently readmit them — same defensive posture as
 * `thelife-fr` / `everystudent-de` / `everystudent-ru`. Two entries are **not**
 * redundant: `/a/nowezycie.html` and `/a/biblia.html` sit under `/a/` and match
 * `articleHints`, so `block` is the only thing keeping them out.
 *
 * All char counts below are post-strip, measured with the repo's own
 * `extractContent` (see "Extraction"). Every one clears `minContentLength: 250`,
 * so **the floor could not catch a single one of them** — they need URL blocks.
 *
 *   - **`/` — the homepage.** Verified 2026-07-29: it has **no
 *     `.contentpadding` at all**, so `extractContent` falls back to `<body>` and
 *     returns **1,138 chars** of teaser headlines and CTA copy. This is exactly
 *     the failure the "minContentLength will drop it" argument gets wrong: a
 *     missing content selector yields the whole nav page, not nothing.
 *   - **`/m/*` — the 7 section indexes.** Verified 2026-07-29: they too have no
 *     `.contentpadding`; the `<body>` fallback gives **~958 chars** of
 *     headline + teaser pairs linking to `/a/` pages (e.g. /m/zycie.html =
 *     "Istnienie Boga"). Navigation, not content.
 *   - **`/mapa.html` — the site plan.** **2,920 chars** of pure link list
 *     ("Mapa witryny / Strona Główna / …"). It clears the floor by an order of
 *     magnitude — length is not aboutness. Polish twin of the French
 *     `/plan.html` and the Russian `/sitemap.html`.
 *   - **`/prywatnosci.html` — "O nas / Polityka Prywatności".** **2,529 chars**
 *     of about-page and privacy boilerplate. It is absent from the XML sitemap
 *     but IS the 301 target of `/m/onas.html`, so it is blocked explicitly.
 *   - **`/pytanie.html` — the contact form.** **401 chars**: "Masz pytanie?"
 *     plus a privacy statement. Note the contrast with the Russian sibling's
 *     `/vopros.html` (85 chars, which the floor would have caught) — this one
 *     clears 250 and would be staged.
 *   - **`/jan.html` — the Gospel-of-John email course.** **837 chars**: "Darmowy
 *     kurs: Miesiąc z Janem" ("Free course: A month with John"), a signup form
 *     for 31 emails run with partner site STARTzBOGIEM.pl. The Polish twin of
 *     the French `/jean.html` and Arabic `/john.html`.
 *   - **`/czybogjest.html` — the 7-email series.** **856 chars**: "Darmowy kurs:
 *     Czy jest Bóg?" — "Zapraszam cię do zapisania się na serię siedmiu
 *     e-maili". The Polish twin of the German `/abenteuerreise.html`, French
 *     `/aventure.html` and Arabic `/pack.html`. Absent from the XML sitemap;
 *     linked from /mapa.html, the homepage and every article's CTA, so blocked
 *     in case the generated sitemap ever picks it up.
 *   - **`/a/nowezycie.html` — the 8-email "Duchowy Zestaw Startowy".** **619
 *     chars**: "bezpłatna seria ośmiu e-maili" — the post-decision starter-kit
 *     signup, linked from the FEATURE CLOSE cell of every article. **It lives
 *     under `/a/` and therefore MATCHES `articleHints`.** It is not in the XML
 *     sitemap today, so discovery would not reach it; the block is what makes
 *     that safe rather than lucky.
 *   - **`/wideo.html` — the "Spadające Talerze" ("Falling Plates") film page.**
 *     **1,490 chars**, and unlike the pages above it is genuine gospel content:
 *     the extracted body is the film's transcript. It is excluded because it is
 *     a *video landing page*, not a seeker Q&A article, and the transcript
 *     extracts as ~60 one-line blocks ("Ty. / Spójrz w swoje oczy. / …") that
 *     chunk poorly against paragraph boundaries (invariant 4). Same call as the
 *     Russian entry's `/m/vid.html`. ⓘ This is the one block a reviewer might
 *     reasonably reverse; it costs one document either way.
 *   - **`/a/biblia.html` — blocked for a SOURCE-SIDE MARKUP BUG, not for
 *     content.** See the next section; this is the one block that loses a real
 *     article.
 *
 * ## ⚠️ `/a/biblia.html` — one article lost to malformed HTML
 *
 * "Historia Biblii — Kto napisał Biblię" is a genuine, substantial article, and
 * it is blocked anyway. Verified 2026-07-29: its source carries **66 `<p>`
 * openers against 67 `</p>` closers** — one unmatched close tag. node-html-parser
 * pops the open-element stack on it, so the whole `<div>` tree collapses: on
 * every other page `.contentpadding` is a proper element, but here
 * `querySelector(".contentpadding")` returns **null**, `.content4` returns null,
 * `.content4b` matches an element holding **0 chars**, and the article text ends
 * up as bare `<p>` siblings directly under `<html>`. Walking every element on
 * the page, **no container holds the article**.
 *
 * With `.contentpadding` unmatched, `extractContent` falls through to
 * `<body>` — which this host also does not emit — and finally to the document
 * root, producing a **31,117-char blob that opens with the literal string
 * "<!DOCTYPE html>"** and folds in the cookie bar, top nav, both menus, the
 * sidebar and the footer. That clears `minContentLength` ~124× over, so nothing
 * downstream would flag it. Blocking is the containment.
 *
 * A fallback selector was tried and **rejected**: `[".contentpadding",
 * ".content4b"]` binds `.content4b` here and extracts **0 chars**, which turns a
 * visibly-bad document into an invisible `too-thin` skip — strictly worse. The
 * `-ko` remedy (`contentSelectors: ["html"]`) is wrong here too, because it
 * would apply to the 77 pages that parse correctly. Recoverable later either by
 * a source-side fix or by sanitising HTML before `parse()`; out of scope now.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Verified 2026-07-29 by running the repo's own `extractContent`
 * (node-html-parser) over the fetched HTML — the only check that proves
 * anything, because **every one of these tokens is also declared in the page's
 * inline `<style>` block**, so grepping for a class name false-positives on all
 * of them. Char counts are raw (pre-strip) on `/a/istnienieboga.html`:
 *   - **`.contentpadding` — 1 instance, the whole article: 18,722 chars.**
 *     Kicker, title, subhead, byline, body and footnote list. Present and
 *     non-empty on **77 of 78** articles (the exception is `/a/biblia.html`,
 *     above).
 *   - **`.content4` — 1 instance, an empty spacer div: 0 chars.** Swept across
 *     **all 78 articles: 0 of them extract a single character from it.** Listing
 *     it ahead of `.contentpadding` would bind the spacer and skip every page as
 *     `too-thin` on an HTTP 200 — the batch-1 failure (#128).
 *   - **`.content4b` — 0 instances on 77 of 78 pages** (present only on the
 *     broken `/a/biblia.html`, where it extracts 0 chars).
 *   - **`.articletitle` — 1 instance, 3–44 chars.** A title, not a body.
 *   - `.content`, `article`, `main` — **0 instances**, absent from this host.
 *   - `<body>` — **0 instances on `/a/` pages**; this host emits no `<body>`
 *     element that the parser recognises, so the fallback container is the
 *     document root (24,892–39,180 chars of whole page). One more reason the
 *     content selector must be the measured one.
 * So `contentSelectors` is the single measured container and nothing else. Over
 * the 77 kept articles it yields **1,785 – 22,911 chars** (median 6,823), each
 * opening on the section kicker + title and closing on its own "Przypisy:"
 * scripture-footnote line.
 *
 * ⚠️ `.contentpadding` also binds on `/mapa.html`, `/pytanie.html`,
 * `/wideo.html`, `/jan.html`, `/czybogjest.html` and `/prywatnosci.html` — it
 * does **not** discriminate article from chrome. The URL filters above are what
 * keep the corpus clean; the selector list must not be relied on to do it.
 *
 * ## Chrome stripped — per-selector contribution, measured inside the scope
 *
 * Removals measured cumulatively in list order inside `.contentpadding`:
 *   - **`sitelevel_noindex`** is a **custom ELEMENT tag**, not a class:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **2 instances, 144 chars**,
 *     identical on all five articles measured — the "UDOSTĘPNIJ INNYM:"
 *     ("SHARE WITH OTHERS:") row and the "Masz pytanie? / Darmowy kurs…"
 *     related-links block. Hence the bare tag name with no leading `.`.
 *   - **`.shareiconsmenupg` — 1 instance, 19 chars ("UDOSTĘPNIJ INNYM:")** when
 *     measured on its own. ⓘ On THIS host the enclosing `<sitelevel_noindex>` is
 *     **well-formed** and already contains it, so once that is stripped first
 *     this selector matches 0 elements — a no-op in list order. That is the
 *     opposite of the `-de`/`-ru` finding (#128), where the same wrapper is
 *     malformed and the share row survives. Kept as an explicit guard: it costs
 *     nothing and the day the markup drifts, "UDOSTĘPNIJ INNYM:" would otherwise
 *     trail every extraction.
 *   - **`.fctable` (1 instance) — 52–180 chars**, the "FEATURE CLOSE"
 *     call-to-action table appended to every article ("► Jak nawiązać przyjaźń z
 *     Bogiem ► Mam pytanie…"). **`.fccell` (4–6 instances)** removes the same
 *     block; measured on its own it is also 52–180 chars, because the cells nest
 *     inside the table. Both are listed: stripping only the cells would leave
 *     the table shell.
 *   - **`.hr2` (2) and `.articledivider` (1)** — bind, but are empty
 *     presentational divs drawing the rules bracketing the CTA. **0 chars.**
 *   - **`.relatedbottom` — 0 instances**, absent from this host. Retained as a
 *     harmless parity no-op with the sibling entries; do not read its presence
 *     here as evidence it binds.
 * After the full list, five articles were re-scanned for leftovers: no
 * "UDOSTĘPNIJ", no "Darmowy kurs", no "Masz pytanie", no "►" survives.
 *
 * ## Language: `["pl"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text myself. The pages serve
 * genuine Polish prose, not untranslated English. `/a/istnienieboga.html` opens
 * "Czy Bóg istnieje? Czy można to udowodnić?" and asks the reader "Czy
 * chciałabyś lub chciałbyś, aby ktoś po prostu wykazał istnienie Boga?";
 * `/a/modlitwy.html` is "Czy Bóg odpowiada na nasze modlitwy?" and narrates
 * "Kiedy byłam ateistką, miałam dobrą przyjaciółkę, która często się modliła";
 * `/a/cierpienie.html` is "Wierzyć w Boga, który pozwala na cierpienie?";
 * `/a/trojca.html` explains "«Trójca» to termin, którego nie ma w Biblii, ale
 * używamy go do opisania tego, co wyraźnie wynika z nauczania Pisma Świętego".
 * The FAQ pages use the native "Pytanie:" / "Odpowiedź:" pair throughout, and
 * scripture citations use Polish book abbreviations (Rz, Jer, J, Mt, Łk, Ap,
 * Pwt, Iz, 1 Kor) with the Polish "Przypisy:" ("Footnotes:") heading.
 *
 * The only English on these pages is bibliographic — footnotes citing
 * English-language books (e.g. "R.E.D. Clark, Creation (London: Tyndale Press,
 * 1946)") — which is normal citation apparatus in a translated article, not an
 * untranslated body. No page showed the cru.org `/mx/es/` failure mode of a
 * localized URL serving an English body.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: ~185 sequential plain-HTTP requests drew no 429 and no throttling,
 * and at 78 pages the whole crawl is ~90 seconds of wall clock.
 *
 * **Expected yield: 77 documents** — 78 sitemap articles minus the blocked
 * `/a/biblia.html`.
 */
import type { SourceEntry } from "./types.js";

export const everystudentPl: SourceEntry = {
  key: "everystudent-pl",
  name: "EveryStudent — Polish (KazdyStudent.pl)",
  domain: "www.kazdystudent.pl",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["pl"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:pl"],
  defaultCategory: "article",
  rights:
    "© KazdyStudent.pl (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.kazdystudent.pl",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (unlike the three walled EveryStudent banners). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.kazdystudent\\.pl/"],
    // The whole article corpus: 78 of the 90 sitemap URLs. `[^/]+` rather than
    // a lowercase class — /a/Boza-pomoc.html and /a/jak-osobiscie-poznac-Boga.html
    // carry uppercase letters. Slugs are de-diacriticised ASCII (verified: zero
    // non-ASCII bytes and zero %XX escapes across all 90 <loc> values).
    articleHints: ["^https://www\\.kazdystudent\\.pl/a/[^/]+\\.html$"],
    block: [
      // ── These two match articleHints; `block` is the ONLY thing excluding them.
      // The 8-email "Duchowy Zestaw Startowy" signup ("bezpłatna seria ośmiu
      // e-maili"), 619 ch — the Polish twin of the German /abenteuerreise.html.
      // Absent from today's sitemap but linked from every article's CTA cell.
      "^https://www\\.kazdystudent\\.pl/a/nowezycie\\.html$",
      // A real article, blocked for a SOURCE-SIDE MARKUP BUG: 66 <p> openers vs
      // 67 </p> closers collapses the div tree, so .contentpadding never forms
      // and extractContent falls back to the document root — a 31,117-char blob
      // of the entire page. A .content4b fallback extracts 0 ch, which is worse
      // (silent). See the header. Costs one genuine document.
      "^https://www\\.kazdystudent\\.pl/a/biblia\\.html$",
      // ── Below here articleHints already excludes them; these record WHY.
      // The 7 section indexes (doswiadczenie, faq, jezus, onas, problemy,
      // pytania, zycie) — no .contentpadding, so the <body> fallback returns
      // ~958 ch of headline+teaser link list, well clear of the 250 floor.
      "^https://www\\.kazdystudent\\.pl/m/",
      // The site plan: 2,920 ch of pure link list. Polish twin of the French
      // /plan.html and the Russian /sitemap.html.
      "^https://www\\.kazdystudent\\.pl/mapa\\.html$",
      // "O nas / Polityka Prywatności" — 2,529 ch of about + privacy
      // boilerplate. Not in the sitemap, but it IS the 301 target of /m/onas.html.
      "^https://www\\.kazdystudent\\.pl/prywatnosci\\.html$",
      // The contact form: 401 ch, so unlike the Russian /vopros.html (85 ch)
      // this one CLEARS minContentLength and the floor cannot catch it.
      "^https://www\\.kazdystudent\\.pl/pytanie\\.html$",
      // "Darmowy kurs: Miesiąc z Janem" — the 31-email Gospel-of-John course
      // signup, 837 ch. Polish twin of the French /jean.html.
      "^https://www\\.kazdystudent\\.pl/jan\\.html$",
      // "Darmowy kurs: Czy jest Bóg?" — the 7-email series signup, 856 ch.
      // Polish twin of the Arabic /pack.html. Not in the sitemap; blocked so a
      // regenerated sitemap cannot quietly admit it.
      "^https://www\\.kazdystudent\\.pl/czybogjest\\.html$",
      // The "Spadające Talerze" film page: 1,490 ch of line-broken transcript,
      // not a seeker Q&A article. Same call as the Russian /m/vid.html.
      "^https://www\\.kazdystudent\\.pl/wideo\\.html$",
      // The homepage — no .contentpadding, so the <body> fallback returns
      // 1,138 ch of teaser headlines rather than nothing.
      "^https://www\\.kazdystudent\\.pl/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article (1,785-22,911 ch across the 77 kept pages).
    // `.content4` is deliberately ABSENT: it is an empty spacer div extracting
    // 0 chars on all 78 articles and, because extractContent scopes to the first
    // selector that MATCHES rather than the first that yields text, listing it
    // here would make every page skip as `too-thin`. `.content4b` does not exist
    // on this host except on the one broken page, where it is also empty.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 inst / 144 ch: share row + related links
      ".shareiconsmenupg", // "UDOSTĘPNIJ INNYM:" AddToAny widget, 19 ch — already inside
      // sitelevel_noindex on THIS host (well-formed here, unlike -de/-ru), so a
      // no-op in list order. Kept as a guard against that markup drifting.
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells: "► Jak nawiązać przyjaźń z Bogiem…" — 52-180 ch
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".relatedbottom", // 0 instances on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 130, // 90 sitemap entries (78 articles, 77 kept) + headroom
    minContentLength: 250,
  },
};
