/**
 * EveryStudent — Korean (everykoreanstudent.com). The Korean banner of Cru's
 * seeker-facing Q&A ministry: short apologetics/life-issue articles aimed at
 * Korean-speaking students who are not believers.
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). everykoreanstudent.com is its own domain, so it gets
 * its own key, the same way `everystudent-ar` / `everystudent-fr` /
 * `everystudent-ja` are separate from `everystudent`, and `thelife-fr` /
 * `thelife-zh` are separate from `thelife`.
 *
 * **NOT WALLED — plain HTTP throughout, so `fetchStrategy` is omitted.**
 * Verified 2026-07-28: `robots.txt`, `/sitemap.xml`, the homepage, 13 `/a/`
 * articles and 4 `/m/` menu pages all returned **HTTP/2 200** to a plain `curl`
 * with a browser UA — no `403`, no "Attention Required", no "Just a moment".
 * Responses are `server: Apache` with no Cloudflare layer at all, so this host
 * is even further from the three walled banners (everystudent.com,
 * everyarabstudent.com, questions2vie.com) than the Japanese one is. The only
 * non-200 seen anywhere was the intentional apex→`www` 301. Nothing is billed.
 *
 * **Discovery mode, not hand-listed seeds** — the sitemap is free and reachable,
 * so there is nothing to freeze into `seedPaths` and no reason to hand-list.
 * Precedent: `thelife-fr`, and the `everystudent-ja` sibling.
 *
 * **Sitemap — verified 2026-07-28.** `https://www.everykoreanstudent.com/sitemap.xml`
 * is a single flat `<urlset>` (no `<sitemapindex>`, so no recursion),
 * `content-type: application/xml`, `last-modified: 2017-09-25`, 4,131 bytes,
 * generated by xml-sitemaps.com, carrying exactly **48 `<loc>` entries**, all on
 * `www.everykoreanstudent.com`. The bare apex 301s to the `www` host, which is
 * why `baseUrl`, `domain` and every regex below are pinned to `www.` — the
 * sitemap emits `www` absolute URLs and the filters match the full absolute URL.
 *
 * The 48 break down as:
 *   - **38 `/a/<slug>.html`** — the article corpus. This is the target set.
 *   - **9 `/m/<slug>.html`** — section/menu indexes (`about`, `enigmas`,
 *     `existence`, `experience`, `forum`, `issues`, `jesus`, `map`, `personal`).
 *     Navigation, not articles; `/m/map.html` is the site-plan page and
 *     `/m/about.html` the about blurb. The siblings drop `/m/*` for the same reason.
 *   - **the bare homepage `/`** — an index.
 * Verified by simulating `allow ∧ articleHints ∧ ¬block` against all 48 URLs:
 * **exactly 37 survive** (the 38 `/a/` pages less the Flash stub below), 11 dropped.
 *
 * ⚠️ **EXTRACTION: the shared EveryStudent template DOES NOT BIND on this host.**
 * This is the one decision on this entry that would silently destroy the source
 * if undone, so it is measured rather than inherited. Running the repo's own
 * parser (`node-html-parser`, exactly as `src/acquisition/extract.ts` uses it)
 * over 13 article pages on 2026-07-28:
 *   - **`.content4` matches 2 divs on every article page, and the first one
 *     extracts 0 characters.** `extractContent` takes the FIRST `querySelector`
 *     hit, so it would scope to an empty element and return `""` for every
 *     article — the entire source would ingest nothing while looking configured.
 *   - **`.contentpadding` → 0 matches**, although the raw HTML plainly contains
 *     `<div class="contentpadding">`. It does not survive parsing.
 *   - **`.content4b` → 0 matches** — absent from the markup entirely.
 *   - `.articletitle` → 1 match, but it holds only the 11–25-char headline.
 *   - **`<body>` is itself absent from the parsed tree** on all 13 article pages.
 *
 * Root cause: this banner's FreeFind markers **interleave with** rather than
 * nest inside the content divs. In `/a/isthere101.html`, `<sitelevel_noindex>`
 * opens at line 211, `<div id="content4">` at 217, `<div class="content4">` at
 * 223, `<div class="contentpadding">` at 224 — and then `</sitelevel_noindex>`
 * at line 244 closes that whole div stack early. The article body (title at
 * line 252, prose through 424) is left as **flat direct children of `<html>`**,
 * 152 of them. No wrapper element survives to select. Simplified Chinese and
 * Georgian were already known to diverge from the template; Korean is a third
 * divergence, and a quieter one — the selectors *match*, they just match nothing.
 *
 * So `contentSelectors` is **`["html"]`**: the only element that actually
 * contains the article. `.content4` deliberately does NOT appear in the list —
 * it would match, win, and yield empty text. Measured with `["html"]` plus the
 * strip list below across 12 real articles: **1,086 – 14,965 chars**, 55–70%
 * Hangul, opening on the article title and closing on its own scripture-footnote
 * list, with no nav, cookie bar, share widget, related-articles list or CTA left.
 *
 * **Strip list — per-selector contribution measured on `/a/isthere101.html`:**
 *   - `sitelevel_noindex` (a custom TAG, not a class; 2 elements) → **1,311
 *     chars**, by far the largest: the cookie-consent bar, the top nav, and the
 *     bottom share + 「가장 인기 있는 글」 ("most popular articles") block.
 *   - `.fccell` (6 elements) → 94 chars, the "FEATURE CLOSE" call-to-action cells.
 *   - `head` (1 element) → 13 chars. Needed **only because the container is
 *     `<html>`**: without it every document would open with a duplicate of its
 *     own `<title>`. Safe because `extract.ts` captures the title from `root`
 *     BEFORE the strip loop runs — a future edit that reorders those two steps
 *     would lose the title, so keep them in that order.
 *   - `.likesharediv` (2 elements) → 6 chars, the AddToAny share wrapper.
 *   - `.hr2` (3) and `.articledivider` (1) bind but are empty presentational rules.
 *   - `.relatedbottom` → **0 elements, absent on this host**; kept as a
 *     harmless parity no-op with the sibling entries.
 *
 * **robots.txt — fetched live 2026-07-28.** `User-agent: *` with exactly two
 * Disallow rules: **`/features/fol.html`** and **`/features/folfl.html`**. Both
 * are legacy aliases that 301 to `/a/fol.html` and `/a/folfl.html`; neither the
 * aliases nor their targets appear in the sitemap, so **the article set is
 * entirely untouched by robots** and nothing needed dropping on robots grounds.
 * They are blocked below anyway to record the rule explicitly.
 * ⓘ Note the contrast with `everystudent-ja`, where `/a/fol.html` IS disallowed:
 * here it is **not**, and it returns 200 and is link-targeted from every
 * article's FEATURE CLOSE block. It stays out of scope only because it is absent
 * from the sitemap — if it is ever added, it becomes fair game, not a violation.
 *
 * **`/a/knowing401FLASH.html` is blocked** — measured 2026-07-28, it extracts to
 * **47 chars**: a Flash-era stub twin of `/a/knowing401.html` reading
 * 「플래시로 보시려면 여기를 클릭」 ("click here to view in Flash"). The 250 floor would
 * drop it anyway; blocking it avoids a pointless fetch and records the reason.
 *
 * ⚠️ **`minContentLength` cannot be relied on to catch the nav pages.** Measured
 * 2026-07-28, the `/m/` menu pages extract to **147–735 chars** and the homepage
 * to **845** — 3 of the 4 sampled menu pages and the homepage clear the 250
 * floor. The `block` list is doing real work here, not decoration.
 *
 * **The 250 floor is safe for real articles, in the other direction.** The
 * shortest of 12 sampled articles was `/a/heaven725.html` at **1,086 chars**,
 * 4.3× the floor; the range ran 1,086 → 14,965 (`/a/bible215.html`). Korean
 * packs more meaning per character than a Latin script, so 250 chars of Hangul
 * is already a substantial passage — the floor is kept at 250 for cross-source
 * consistency, and no sampled article came near it.
 *
 * **Character encoding: UTF-8** — worth stating because Korean legacy sites of
 * this vintage often serve EUC-KR. Verified 2026-07-28 three ways: the pages
 * declare `<meta http-equiv="content-type" content="text/html; charset=utf-8" />`
 * and `<html lang="ko">`; the bytes decode as **strict UTF-8 with zero
 * replacement characters**; and the same bytes **fail** to decode as EUC-KR, so
 * the declaration is not a mislabel. ⚠️ Same caveat as the Japanese banner: the
 * HTTP response header is a bare `content-type: text/html` with **no `charset`
 * parameter**, so a client trusting the header alone and defaulting to
 * ISO-8859-1 would mojibake every page — the fetcher must honour the `<meta>`
 * declaration (or default to UTF-8) rather than the header.
 *
 * **Language: `["ko"]` — read, not assumed.** The pages genuinely serve Korean,
 * not untranslated English. `/a/isthere101.html` opens 「하나님은 존재하는가?」 ("Does
 * God exist?") and argues from design; `/a/knowing401.html` is 「하나님을 개인적으로
 * 알아가기: CCC 사영리」 (the Four Spiritual Laws), running from 「제 1원리: 하나님은 당신을
 * 사랑하시며, 당신을 위한 놀라운 계획을 가지고 계십니다」 to a written prayer of response;
 * `/a/heaven725.html` asks 「천국은 어떤 곳입니까? 천국이 정말로 존재합니까?」 and answers from
 * 요한계시록 (Revelation) 21. Hangul runs 55–70% of extracted characters; the 55%
 * floor is `/a/Godreal.html`, whose residue is romanized science citations ("Dr.
 * Antony Flew", "DNA", the A/T/G/C bases) inside Korean prose. No sampled page
 * was untranslated English. The stored per-document label still comes from
 * content detection at ingest (invariant 6), never from this field.
 *
 * ⚠️ **Korean is a NEW language for this corpus.** Checked 2026-07-28: no other
 * registry entry declares `ko`, and `eval/qa-golden.yaml` contains no `ko`
 * cases. So — as with Japanese, and unlike French — there are no pre-existing
 * golden cases this source becomes eligible for by construction. Stage-4 will
 * need `ko` cases written from scratch, and `ko` starts as a SINGLE-source
 * language for gating purposes.
 *
 * `requestDelayMs: 1000` — we pay this host's bandwidth directly rather than
 * proxying through Firecrawl, so the politeness is real. No rate-limiting was
 * observed across ~25 sequential probes at ~1s spacing (zero 429s), so the
 * sibling default is kept rather than raised.
 */
import type { SourceEntry } from "./types.js";

export const everystudentKo: SourceEntry = {
  key: "everystudent-ko",
  name: "EveryStudent — Korean (everykoreanstudent.com)",
  domain: "www.everykoreanstudent.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["ko"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:ko"],
  defaultCategory: "article",
  rights:
    "© EveryKoreanStudent.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.everykoreanstudent.com",
    // No `fetchStrategy`: this host is NOT walled (verified 2026-07-28, every
    // probe 200 to plain HTTP against bare Apache), so the plain-http default
    // applies and nothing is billed. See the header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.everykoreanstudent\\.com/"],
    // The article corpus is exactly /a/<slug>.html — 38 of the sitemap's 48.
    articleHints: ["^https://www\\.everykoreanstudent\\.com/a/[^/]+\\.html$"],
    block: [
      // robots.txt Disallow, fetched live 2026-07-28. Both are legacy aliases
      // that 301 to /a/fol.html and /a/folfl.html; neither they nor their
      // targets are in the sitemap, so this records the rule rather than
      // enforcing it. NOTE: /a/fol.html is NOT disallowed on this host.
      "^https://www\\.everykoreanstudent\\.com/features/fol(?:fl)?\\.html$",
      // Section/menu indexes (9 in the sitemap: about, enigmas, existence,
      // experience, forum, issues, jesus, map, personal) — navigation, not
      // articles. They extract to 147–735 chars, so the 250 floor cannot be
      // relied on to drop them; this block is load-bearing.
      "^https://www\\.everykoreanstudent\\.com/m/",
      // Flash-era stub twin of /a/knowing401.html — extracts to 47 chars.
      "^https://www\\.everykoreanstudent\\.com/a/knowing401FLASH\\.html$",
      // The homepage is an index and extracts to 845 chars — above the floor.
      "^https://www\\.everykoreanstudent\\.com/?$",
    ],
    // ⚠️ NOT the shared EveryStudent template. Measured 2026-07-28: `.content4`
    // matches but extracts 0 chars, `.content4b`/`.contentpadding` do not match
    // at all, and even <body> is lost — stray </sitelevel_noindex> end tags
    // close the content divs early and flatten the article into <html>'s direct
    // children. `<html>` is the only element that still contains the article.
    // Do NOT add `.content4` here: it would match, win, and yield "".
    contentSelectors: ["html"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Required because the container is <html>: drops the duplicate <title>.
      // extract.ts reads the title from `root` BEFORE stripping — keep that order.
      "head",
      // Site-specific chrome, all measured on this host 2026-07-28 (see header):
      "sitelevel_noindex", // custom TAG: cookie bar + top nav + bottom share/popular — 1,311 chars
      ".fccell", // "FEATURE CLOSE" call-to-action cells — 94 chars
      ".likesharediv", // AddToAny share wrapper — 6 chars
      ".relatedbottom", // NO-OP here — 0 elements on this host; kept for parity
      ".hr2",
      ".articledivider",
    ],
    requestDelayMs: 1000, // direct fetches, no Firecrawl proxy; 0 × 429 observed
    maxPages: 80, // 48 sitemap URLs (37 kept after filtering) + headroom
    minContentLength: 250,
  },
};
