/**
 * EveryStudent — Turkish (tanriyitanimak.com, "Tanrı'yı Tanımak" / "Knowing
 * God"). The Turkish banner of Cru's seeker-facing Q&A ministry: short
 * apologetics and life-issue articles, plus first-person testimonies, written
 * for Turkish-speaking students who are not believers. A sibling of
 * `everystudent` (en), `everystudent-ar`, `everystudent-fr`, and the #111
 * non-walled batch (`-de`, `-ru`, `-es`, …).
 *
 * **A separate SOURCE KEY, not a language of `everystudent`** — one domain =
 * one source (ADR-0006). tanriyitanimak.com is its own domain, so it gets its
 * own key, the same way `everystudent-ru` (mirstudentov.com), `everystudent-fr`
 * (questions2vie.com) and `thelife-zh` (uwota.com) are separate entries.
 *
 * ## NOT walled — plain HTTP
 *
 * Verified 2026-07-29: **187 plain-HTTP requests** with a full browser UA —
 * /robots.txt, /sitemap.xml, all 74 `/makaleler/` articles, all 11 `/ses/`
 * pages, all 9 `/konular/` pages plus the unlisted `/konular/kabul.html`, the
 * homepage, /videolar.html, /sitemap.html, /yolculuk/, /yuhanna/, /iletisim/,
 * /kirilantabaklar/, /ses/, /kk/sec.html, and a HEAD sweep of all 101 sitemap
 * URLs. **Every one returned HTTP 200**, none carried a Cloudflare block-page
 * signature (no `Attention Required`, no `Just a moment`), and the HEAD sweep
 * was 101/101 200 with **zero redirects**. The `server: cloudflare` header is
 * present, but this host serves rather than challenges. So `fetchStrategy` is
 * intentionally OMITTED: plain HTTP is the default and nothing here needs
 * Firecrawl (ADR-0012).
 *
 * Consequence: discovery is free, so this is a **discovery crawl**, not the
 * hand-listed seed set the three walled banners were forced into. Precedent for
 * the shape: `thelife-fr`, `everystudent-ru`, `everystudent-de`.
 *
 * The bare host 301-redirects to `www` (measured on /robots.txt), so
 * `www.tanriyitanimak.com` is canonical and the host every `<loc>` uses.
 *
 * ## robots.txt — there isn't one
 *
 * Verified 2026-07-29: `https://www.tanriyitanimak.com/robots.txt` returns
 * **HTTP 404**, serving the site's own Turkish 404 page (`<title>Ay,
 * pardon!</title>`, 44,060 bytes of HTML) rather than any rule file. There is
 * no `User-agent` line, no `Allow`, no `Disallow`. **Nothing on this domain is
 * disallowed**, so no URL is dropped on robots grounds — every exclusion below
 * is a content-quality call, not a policy one. This is barer still than
 * `everystudent-ru` (a 13-byte `User-agent: *`) and unlike everystudent.com,
 * which carries a real disallow list.
 *
 * ## Sitemap — 101 usable entries, and one malformed `<loc>`
 *
 * Verified 2026-07-29: `/sitemap.xml` → HTTP 200, 16,548 bytes,
 * `application/xml`, Last-Modified 2026-07-14, generated by xml-sitemaps.com.
 * It contains **102 literal `<loc>` opening tags but only 101 well-formed
 * entries**: at line 471 the generator truncated one mid-write —
 * `  <loc>https://www.tanriyitanimak.com/ses/` with no closing `</loc>` and no
 * `</url>`, immediately followed by the next `<url>`. All 101 well-formed URLs
 * are distinct. (Prior recon said "~102"; the 102nd is that fragment.)
 *
 * Harmless, and checked rather than assumed: running discover.ts's own parse
 * (`parse(xml).querySelectorAll("url loc")`, node-html-parser) over the live
 * file yields **exactly 101 loc nodes, none merged or whitespace-mangled**, and
 * the filters below keep **71**. The truncated fragment produces no extra
 * candidate, and `/ses/` is blocked anyway.
 *
 * The 101 URLs break down as:
 *   - **74 `/makaleler/<slug>.html`** — the article corpus. 71 kept, 3 blocked.
 *   - **11 `/ses/<slug>.html`** — audio pages. BLOCKED (near-duplicates).
 *   - **9 `/konular/<slug>.html`** — section indexes + legal pages. BLOCKED.
 *   - **6 single-purpose pages** — `/`, `/videolar.html`, `/sitemap.html`,
 *     `/yolculuk/`, `/yuhanna/`, `/iletisim/`, `/kirilantabaklar/`. BLOCKED.
 *
 * So `articleHints` is exactly `/makaleler/<slug>.html`, and the **expected
 * yield is 71 documents**.
 *
 * Slugs are pure ASCII despite the Turkish content — charset across all 74 is
 * `[-.2A-Za-z]`, with **three mixed-case slugs** (`KutsalRuh.html`,
 * `Rabiyimidir.html`, `Tanriyi-tanimak-video.html`) and no percent-encoding
 * anywhere on the host (0 of the 106 distinct internal hrefs harvested carry a
 * `%XX` escape or a non-ASCII byte). A lowercase-only hint would have dropped
 * two live articles, so the hint uses `[^/]+` and stays case-agnostic.
 *
 * ## HTML-sitemap cross-check — the XML sitemap is NOT stale here
 *
 * The sibling sitemaps in this estate lie (one missed 17% of its articles,
 * another listed 25 dead URLs), so this one was cross-checked rather than
 * trusted. Verified 2026-07-29 against the site's own `/sitemap.html` (103
 * internal links) plus every section index, the homepage, /videolar.html,
 * /ses/ and all 74 article pages — **106 distinct internal URLs harvested in
 * total**, of which exactly **74 are `/makaleler/` links, matching the XML
 * sitemap's 74 with zero delta**. No article is missing from the sitemap, so
 * **no `seedPaths` are needed** and the field is omitted.
 *
 * The harvest found only two host URLs the XML sitemap lacks, neither an
 * article: `/ses/` (the audio index — this is the truncated `<loc>` above) and
 * `/kk/sec.html` (a Bible-edition chooser, **35 chars**). A third,
 * `/konular/kabul.html` ("Tanrı'yla Yürümeye Başlamak", a post-decision
 * follow-up, 900 chars), is linked but unlisted; the `/konular/` block covers
 * it if it is ever added to the sitemap. `/kk/` gets no rule because discovery
 * reads the sitemap only and can never reach it.
 *
 * ## What is blocked, and the evidence for each
 *
 * `articleHints` alone already excludes everything outside `/makaleler/`. The
 * `block` list is deliberately redundant: it records *why* each group is out,
 * so a later widening of the hints cannot silently readmit them. Same
 * defensive posture as `everystudent-ru` / `everystudent-de` / `thelife-fr`.
 *
 *   - **`/ses/*` — audio pages that reprint their article.** Verified
 *     2026-07-29 across all 11: every slug has a twin (10 under `/makaleler/`,
 *     `ulasmak` under `/konular/`), and **76.3%–98.8% of each audio page's
 *     12-word shingles appear verbatim in its twin** (Jaccard 57.0%–98.2%;
 *     `/ses/isakimdi.html` is 98.8% / 98.2% against `/makaleler/isakimdi.html`,
 *     22,168 ch vs 22,020 ch). That is a harder overlap than the German
 *     sibling's `/audio/*` (73.3%), which was blocked on the same reasoning.
 *     The document-level content hash cannot collapse duplicates sitting at
 *     different URLs, so ingesting both would double-count 10 articles. The
 *     `/ses/` index itself (679 ch) is caught by the same prefix.
 *   - **`/konular/*` — section indexes and legal chrome, none of them
 *     articles.** Verified 2026-07-29, all 9 fetched. The six section indexes
 *     (`varlik`, `isa`, `yasamadair`, `sorunlar`, `tanimak`, `sorucevap`) are
 *     headline+teaser link lists and have **no `.contentpadding` element at
 *     all**, so they fall back to `<body>` and extract **455–1,467 chars** of
 *     nav — well clear of the 250 floor. The rest are
 *     `/konular/gizlilik.html` (KVKK privacy policy, 9,737 ch),
 *     `/konular/cerez.html` (cookie policy, 6,026 ch) and
 *     `/konular/ulasmak.html` (6,387 ch). Turkish twins of the `/m/*` indexes
 *     the French and Russian entries drop.
 *     ⓘ `/konular/ulasmak.html` is the judgement call in this list: unlike the
 *     others it is real prose — the "Tanrı'ya Ulaşmak" gospel presentation,
 *     i.e. this host's Four-Spiritual-Laws page. It is excluded for consistency
 *     with the estate (everystudent.com's robots.txt disallows `/4laws.html`,
 *     and no sibling entry ingests its equivalent), not because it is thin.
 *     Flagged for the orchestrator: readmitting it means one extra document and
 *     one extra `block` line, nothing more.
 *   - **`/yolculuk/` — the email-series signup.** Verified 2026-07-29: the
 *     sign-up landing page for the free "Ruhsal Yolculuk Serisi" ("Spiritual
 *     Journey Series", "Lütfen bana Ruhsal Yolculuk Serisi'ni gönderin!"), the
 *     Turkish twin of the French `/aventure.html`, German `/abenteuerreise.html`
 *     and Arabic `/pack.html`. It extracts **1,266 chars**, so it CLEARS the
 *     250-char floor comfortably — length is not aboutness, which slice #10
 *     paid to learn. Only a URL block excludes it.
 *   - **`/yuhanna/` — the Gospel-of-John signup.** Verified 2026-07-29: the
 *     sign-up page for "Rabbi Daha İyi Tanımak – Yuhanna'nın Müjdesine Dair Bir
 *     Çalışma" (a John email study), twin of the French `/jean.html` and Arabic
 *     `/john.html`. **1,761 chars** — also over the floor.
 *   - **`/makaleler/*-video.html` — the two pages with no working container.**
 *     Verified 2026-07-29: `/makaleler/Tanriyi-tanimak-video.html` and
 *     `/makaleler/yardimini-video.html` are the only two pages on the host with
 *     **no `.contentpadding` element**. They carry a `.content4b` div instead —
 *     which is *also* an empty spacer, **0 chars** — so no selector binds and
 *     extraction falls back to `<body>`, yielding **5,518 / 5,681 chars** of
 *     nav + sidebar + a genuine "Video transkripti". They match the article
 *     hint, so only a URL block stops them. See the extraction section for the
 *     one call the orchestrator may want to revisit.
 *   - **`/makaleler/isafilmi.html` — a 126-char teaser** for the JESUS Film
 *     ("Pek çok kişiye yaşam veren İsa Mesih'in gerçek sözlerini şimdi sizde
 *     görün."). Below `minContentLength`, so it would be dropped anyway;
 *     blocking skips the fetch and makes the expected yield exact.
 *   - **`/videolar.html` (609 ch) and `/sitemap.html` (3,440 ch)** — the video
 *     index and the site plan. `/videolar.html` has no `.contentpadding` and
 *     body-falls-back; `/sitemap.html` extracts a pure link list. Both clear
 *     the floor. Turkish twins of the French `/plan.html`.
 *   - **`/iletisim/` — the contact page, 652 chars** ("Bizimle Paylaşın" plus a
 *     Telegram link and the JS fallback line). Over the floor.
 *   - **`/kirilantabaklar/` — a 53-char video stub** (`#kırılantabaklar`).
 *   - **`/`** — the homepage. It has **no `.contentpadding` and no `.content4`
 *     at all**, so it body-falls-back to **889 chars** of teaser headlines. It
 *     would NOT be caught by `minContentLength`; blocked so it is never fetched.
 *
 * ## Extraction — measured on this host, not inherited on trust
 *
 * Verified 2026-07-29 by running extract.ts's own logic (node-html-parser,
 * same tidy/strip order) over the live HTML of all 74 articles. Measuring by
 * extracted TEXT LENGTH is the only check that proves anything here: every one
 * of these tokens is *also* declared in the page's inline `<style>` block, so a
 * grep for the class name false-positives on all of them.
 *
 * Every candidate probed, with its char count on `/makaleler/varmi.html`:
 *   - **`.contentpadding` — 1 instance, the whole article: 18,724 ch raw,
 *     18,378 after stripping.** THIS IS THE ONE SHIPPED.
 *   - `.content4` — **1 instance, an empty spacer div: 0 characters.** Measured
 *     0 chars on **all 85** article + audio pages fetched; present as an element
 *     on 83 of them, absent only on the two `-video.html` pages.
 *   - `.content4b` — **0 instances on 83 of 85 pages**; present on the two
 *     `-video.html` pages only, where it also extracts **0 characters**.
 *   - `.articletitle` — 1 instance, **14–53 ch**. An `<h1>`; a title, not a body.
 *   - `.articlebody`, `#content`, `.content`, `main`, `article` — **0 instances**.
 *   - `.container2` / `.video-container` — 0 ch (video pages only);
 *     `.tagwrap` 18 ch; `.subhead` 25–89 ch; `.sidebar` 92 ch.
 *   - `<body>` fallback (what runs when nothing matches) — 18,433 ch on this
 *     page, i.e. it does NOT return empty and cannot be relied on to self-filter.
 * Across the whole corpus `.contentpadding` extracts min 126 / median 6,766 /
 * max 23,811 chars, and only one article (`isafilmi`, blocked) is under 250.
 *
 * `contentSelectors` is therefore the ONE measured container and nothing else.
 * `extractContent` scopes to the FIRST selector that MATCHES AN ELEMENT, not
 * the first that yields text, so listing `.content4` (or `.content4b`) ahead of
 * `.contentpadding` would bind an empty spacer and extract **0 chars on every
 * page** — every article skipped as `too-thin` on an HTTP 200, silently. That
 * is how five of the eight #111 pilot entries first shipped.
 *
 * ⓘ **One deliberate omission, for the orchestrator to rule on.** Appending
 * `.content4b` *after* `.contentpadding` would be safe in isolation — it exists
 * on exactly the two `-video.html` pages, so it could never shadow the real
 * container — but it would extract 0 chars there too, so it recovers nothing.
 * There is **no element on those two pages that wraps the transcript**; the only
 * way to ingest them is the `<body>` fallback, which drags in ~1,400 chars of
 * nav. They are blocked instead. If those two transcripts are wanted later, the
 * fix is a page-specific container upstream, not a selector here.
 *
 * ⚠️ `.contentpadding` also binds on `/sitemap.html`, `/konular/gizlilik.html`,
 * `/ses/*`, `/yolculuk/` and `/yuhanna/` — it does **not** discriminate content
 * from nav or from signup pages. The URL filters above are what keep the corpus
 * clean; the selector must not be relied on to do it.
 *
 * ## Chrome stripped — counted INSIDE `.contentpadding`
 *
 * Measured 2026-07-29 on `/makaleler/varmi.html`, `/makaleler/KutsalRuh.html`
 * and `/makaleler/Rabiyimidir.html`; totals **346 / 241 / 328 chars removed**.
 * Each figure below is that selector applied alone to the base-stripped scope:
 *
 *   - **`sitelevel_noindex`** is a **custom ELEMENT tag, not a class**:
 *     `<sitelevel_noindex> … </sitelevel_noindex>`. **2 instances inside
 *     `.contentpadding`, 154 chars** on all three pages — the "BU MAKALEYİ
 *     PAYLAŞIN:" share row and the bottom utility nav ("Bizimle Paylaşın /
 *     Videolar / Makaleleri Dinle / ► Site haritası"). The missing leading `.`
 *     is correct, not a typo.
 *   - **`.fctable` (1–2) and `.fccell` (4–8)** — the "FEATURE CLOSE"
 *     call-to-action table appended to every article ("► İsa Mesih'i az önce
 *     yaşamıma davet ettim… ► Tanrı'yla arkadaşça bir ilişki başlatmaya ne
 *     dersiniz? ► Bize e-mail ile ulaşın…"). Measured removal **192 / 87 / 174
 *     chars**; the two selectors remove the same block (the cells nest in the
 *     table), and `.fctable` is kept because stripping only the cells would
 *     leave the table shell.
 *   - **`.hr2` (2–4) and `.articledivider` (0–1)** — empty divs drawing the
 *     rules that bracket that CTA block. **0 chars**, confirmed.
 *   - **`.shareiconsmenupg` (1 per article, "BU MAKALEYİ PAYLAŞIN:", 23 ch) —
 *     kept, but on THIS host it is redundant.** Measured drop-one-out: removing
 *     it from the strip list changes the output by **0 chars**, because here the
 *     enclosing `<sitelevel_noindex>` is **well-formed** and already contains it
 *     (unlike the German and Russian siblings, where the tag opens inside
 *     `.contentpadding` and closes after it, so the parser pops it early and the
 *     share row survives — #128). Retained for sibling parity and as insurance
 *     if this host's markup regresses to the malformed form; do not read its
 *     presence here as evidence it currently removes anything.
 *   - **`.relatedbottom`** has **no element instance** on any page measured — a
 *     no-op here. Retained for parity; same caveat.
 *
 * Articles end on their own last line after stripping (e.g. `varmi` closes on
 * its footnote list, "Dipnotlar: (1) Romalılar 1:19-21 …").
 *
 * ## Language: `["tr"]` — read, not inferred
 *
 * Verified 2026-07-29 by reading the extracted text. The pages serve genuine
 * Turkish prose, not untranslated English: `/makaleler/varmi.html` is titled
 * "Tanrı Var mı? - İnanmak İçin Sebepler" and opens "Birisinin çıkıp Tanrı'nın
 * varlığını basitçe ispatlayan bir delil göstermesi herkesin hoşuna giderdi,
 * değil mi?"; `/makaleler/ateist.html` ("Bir Ateist Rabbi Nasıl Buldu?")
 * narrates "İmanlı insanlara sorduğum, 'Rabbin var olduğunu nereden biliyorsun?'
 * sorularımla rahatsız olmuşa benziyorlardı."; `/makaleler/uclubirlik.html`
 * answers "Üçlübirlik'i açıklayabilir misiniz?" with "Bizler üç boyutlu bir
 * dünyada yaşıyoruz."; `/makaleler/dirilis.html` asks whether Christ's death and
 * resurrection mean anything for us. Scripture citations use Turkish book names
 * throughout (Yuhanna, Romalılar, Yeremya, Vahiy, 1. Korintliler, Galatyalılar,
 * Efesliler).
 *
 * Corroborating the reading across the whole corpus rather than the sample: the
 * Turkish-specific letters `ı İ ğ Ğ ş Ş ç Ç ö Ö ü Ü` make up **7.06%–14%** of
 * every one of the 74 articles' extracted characters (median 9.54%, lowest
 * `/makaleler/kadin.html` at 7.06%). An untranslated English body would sit near
 * 0%, as cru.org's `/mx/es/…/10-pasos-basicos/` did. None does.
 *
 * The stored per-document language label still comes from content detection at
 * ingest (invariant 6), never from this field. `tr` is a NEW language for this
 * corpus as far as this entry is concerned.
 *
 * `requestDelayMs: 1000` — the politeness default. Nothing in the probes argued
 * for more: 187 sequential plain-HTTP requests drew no 429 and no throttling,
 * and at 71 pages the whole crawl is ~1.5 minutes of wall clock.
 */
import type { SourceEntry } from "./types.js";

export const everystudentTr: SourceEntry = {
  key: "everystudent-tr",
  name: "EveryStudent — Turkish (Tanrı'yı Tanımak)",
  domain: "www.tanriyitanimak.com",
  trust: "partner",
  ingestionMode: "html-scrape",
  languages: ["tr"],
  defaultTags: ["everystudent", "cru", "topic:seeker", "lang:tr"],
  defaultCategory: "article",
  rights:
    "© TanriyiTanimak.com (Cru) — partner ministry content; used for retrieval/attribution.",
  crawl: {
    baseUrl: "https://www.tanriyitanimak.com",
    // No `fetchStrategy`: verified 2026-07-29 that plain HTTP serves every page
    // on this host (unlike the three walled EveryStudent siblings). See header.
    sitemaps: ["/sitemap.xml"],
    allow: ["^https://www\\.tanriyitanimak\\.com/"],
    // The article corpus: 74 of the 101 well-formed sitemap URLs. Case-agnostic
    // on purpose — /makaleler/KutsalRuh.html and /makaleler/Rabiyimidir.html
    // carry uppercase letters, and a lowercase-only hint would drop them.
    articleHints: [
      "^https://www\\.tanriyitanimak\\.com/makaleler/[^/]+\\.html$",
    ],
    // No `seedPaths`: cross-checked 2026-07-29 against /sitemap.html and every
    // section index — 74 /makaleler/ links harvested, 74 in the XML sitemap,
    // zero delta. Nothing needs pinning.
    block: [
      // The two pages with NO working container: .contentpadding is absent and
      // .content4b is an empty spacer (0 ch), so extraction body-falls-back to
      // 5,518 / 5,681 chars of nav + sidebar + transcript. They match the
      // article hint, so only a URL block stops them.
      "^https://www\\.tanriyitanimak\\.com/makaleler/[^/]*-video\\.html$",
      // A 126-char JESUS Film teaser — under minContentLength; blocking skips
      // the fetch and makes the expected yield exact (71).
      "^https://www\\.tanriyitanimak\\.com/makaleler/isafilmi\\.html$",
      // Audio pages reprinting their article: 76.3-98.8% 12-word shingle
      // containment against their /makaleler/ (or /konular/ulasmak) twin.
      // Ingesting both double-counts 10 articles. Also catches the /ses/ index.
      "^https://www\\.tanriyitanimak\\.com/ses/",
      // Section indexes (455-1,467 ch of nav via <body> fallback, no
      // .contentpadding), the KVKK privacy policy (9,737 ch), the cookie policy
      // (6,026 ch) and the "Tanrı'ya Ulaşmak" gospel presentation (6,387 ch).
      // Also covers the unlisted /konular/kabul.html. All clear the 250 floor.
      "^https://www\\.tanriyitanimak\\.com/konular/",
      // The video index: 609 ch, no .contentpadding, body fallback.
      "^https://www\\.tanriyitanimak\\.com/videolar\\.html$",
      // The site plan: 3,440 ch of pure link list. Turkish twin of /plan.html.
      "^https://www\\.tanriyitanimak\\.com/sitemap\\.html$",
      // "Ruhsal Yolculuk Serisi" — the free email-series signup, 1,266 ch, so
      // minContentLength can NOT catch it. Twin of the French /aventure.html.
      "^https://www\\.tanriyitanimak\\.com/yolculuk/",
      // The Gospel-of-John email study signup, 1,761 ch. Twin of /jean.html.
      "^https://www\\.tanriyitanimak\\.com/yuhanna/",
      // Contact page: 652 ch, over the floor.
      "^https://www\\.tanriyitanimak\\.com/iletisim/",
      // A 53-char video stub (#kırılantabaklar).
      "^https://www\\.tanriyitanimak\\.com/kirilantabaklar/",
      // The homepage — no article container, so it body-falls-back to 889 ch of
      // teaser headlines rather than extracting nothing.
      "^https://www\\.tanriyitanimak\\.com/?$",
    ],
    // ONLY `.contentpadding` — measured 2026-07-29 as the sole element on this
    // host that extracts the article (18,724 ch on /makaleler/varmi.html).
    // `.content4` is deliberately ABSENT: it is an empty spacer div (0 chars on
    // all 85 pages measured) and, because extractContent scopes to the first
    // selector that MATCHES rather than the first that yields text, listing it
    // here would make every page skip as `too-thin`. `.content4b` exists on two
    // pages only and is also 0 chars; both are blocked above.
    contentSelectors: [".contentpadding"],
    stripSelectors: [
      "script",
      "style",
      "noscript",
      "svg",
      "nav",
      "header",
      "footer",
      "form",
      // Site-specific chrome — all counted in this host's markup (see header):
      "sitelevel_noindex", // custom ELEMENT tag, 2 inst / 154 ch inside .contentpadding
      ".shareiconsmenupg", // "BU MAKALEYİ PAYLAŞIN:" — 0 marginal ch here (see header)
      ".fctable", // the "FEATURE CLOSE" CTA table shell
      ".fccell", // its cells: "► İsa Mesih'i az önce yaşamıma davet ettim…"
      ".hr2", // empty divs drawing the rules bracketing the CTA block
      ".articledivider",
      ".relatedbottom", // no instance on this host; kept for sibling parity
    ],
    requestDelayMs: 1000,
    maxPages: 150, // 101 well-formed sitemap entries (71 kept) + headroom
    minContentLength: 250,
  },
};
