/**
 * Starting With God (startingwithgod.com) — slice #1's source. Server-rendered
 * HTML, no anti-bot wall (docs/STATUS.md recon). Content lives in `#content`;
 * nav/sidebar/footer/share/comments are stripped before extraction. The seed
 * list is the site's own article set (from its sitemap), excluding category
 * index pages and cross-site (everystudent.com) links.
 */
import type { SourceEntry } from "./types.js";

export const startingWithGod: SourceEntry = {
  key: "starting-with-god",
  name: "Starting With God",
  domain: "www.startingwithgod.com",
  trust: "trusted",
  ingestionMode: "html-scrape",
  languages: ["en"],
  defaultTags: ["audience:seeker", "topic:gospel"],
  defaultCategory: "article",
  rights: "© Starting With God — used for retrieval/attribution; not redistributed.",
  crawl: {
    baseUrl: "https://www.startingwithgod.com",
    contentSelectors: ["#content"],
    stripSelectors: [
      "script",
      "style",
      "nav",
      "#sidebar",
      "#breadcrumbs",
      "#cookie-notice",
      ".footer",
      ".fb-comments",
      ".a2a_kit",
      ".navmenu2",
      ".nav1",
      ".topbar",
    ],
    requestDelayMs: 1500,
    maxPages: 60,
    minContentLength: 250,
    seedPaths: [
      "/bible-study/lesson-1.html",
      "/bible-study/lesson-2.html",
      "/bible-study/lesson-3.html",
      "/bible-study/lesson-4.html",
      "/bible-study/lesson-5.html",
      "/bible-study/what-is-the-gospel.html",
      "/bible-study/what-to-do-with-problems.html",
      "/directors-blog/is-god-willing-to-give-me-direction-in-my-life.html",
      "/knowing-god/bible.html",
      "/knowing-god/faith.html",
      "/knowing-god/gods-grace.html",
      "/knowing-god/half-day.html",
      "/knowing-god/holy-spirit.html",
      "/knowing-god/how-god-speaks.html",
      "/knowing-god/motivating.html",
      "/knowing-god/what-is-faith.html",
      "/new-life/am-i-christian.html",
      "/new-life/connect.html",
      "/new-life/gods-love.html",
      "/new-life/how-to-be-sure-of-heaven.html",
      "/new-life/jesus.html",
      "/new-life/new.html",
      "/new-life/spirit-filled.html",
      "/new-life/will-this-last.html",
      "/questions/baptism.html",
      "/questions/does-god-really-love-me.html",
      "/questions/every-student-app.html",
      "/questions/how-to-stop-worrying.html",
      "/questions/sin.html",
      "/questions/start-easy-conversations-about-god.html",
      "/questions/the-ripple-effect.html",
      "/struggles/changes.html",
      "/struggles/do-not-listen.html",
      "/struggles/expect.html",
      "/struggles/fall.html",
      "/struggles/forgiven.html",
      "/struggles/how-to-get-free-from-porn.html",
      "/struggles/how-to-live-the-christian-life.html",
      "/struggles/into-negative.html",
      "/struggles/preparing.html",
    ],
  },
};
